### ISSUE TITLE
Limit parallelism of worker since only one aqua session is available.

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#912] opened 2017-02-07 14:10 UTC
# Feature Request

## What challenge are you facing?

I am trying to run 2 mac minis as darwin workers for running the ios-simulator.
The mac minis only have one aqua session each, i.e. UI session. The ios-simulator occupies an aqua session. the ios-simulator can not run in parallell.

Note my pipe line has ~10 different app versions in parallell that needs testing.

If I run a default pipeline for running the ios tests using fastlane the simulator gets interrupted by parallell tasks that want to run their tests. even though the aqua session is buzy. Everything fails...

**Quick fix:**
I first added a serial group - this worked when I only had one worker.

Now I have two, so I set up 2 serial groups... and added tags to the workers...
serial groups: on-worker-1, on-worker-2
tags: worker-1, worker-2...

I think this currently is the only way to guarantee that a worker did not get more than 1 task at a time...

I spread these tags evenly over my apps to test, however one of the workers are much faster than the other. So it gets done quickly and then has nothing to do while the slow one keeps on churning the ios-simulator ui tests... Not very time effective.

**What would be better:** 

I need a way to signal:
  "worker A is ready to handle 1 task".
  "worker B is ready to handle 1 task".

Then the workers are locked until the task is completed.
Then they are unlocked again.

## A Modest Proposal

Either a way of setting number of parallell-tasks per worker or adding a mutex on worker.

* Concourse version: 2.6.0

**Comment by clarafu** [comment] 2017-06-07 14:26
This seems like a duplicate of #676 so I'm going to close this. Sounds like further validation for the other issue so we will take this into account. Thanks!

**Closed** 2017-06-23 13:54 UTC
Labels: area: ios, platform: macOS, type: enhancement
