### ISSUE TITLE
ci.concourse.org and more - generic 401 when logging into github oauth concourse with unauthorized account

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/concourse#3062] opened 2019-01-16 17:13 UTC
## Bug Report

Error when logging into a concourse ci server that uses github oauth and you are not a member of any approved teams.

## Steps to Reproduce

Log into a concourse ci server with a user that is not a member of any approved teams.

Example, if I log in to http://ci.concourse-ci.org using my current github account.

## Expected Results

A formatted error page or authentication error indicating I'm not allowed to access the server.

## Actual Results

Generic 401 error on a callback to `https://ci.concourse-ci.org/sky/callback?code=phxjrwk2gtfwmtvdfropcdagw&state=eyJyZWRpcmVjdF91cmkiOiIvIiwiZW50cm9weSI6IjAxYmNkOGY5NTBiYzRkNjlhODMzOTkzZmNkMjVkMzcyYzQyOTNlNzlkZjI1NmZiZjk1ZDBmOTllOGNjNjY2YmIifQ%3D%3D`

## Additional Context

I noticed this when testing if I could log into my org's concourse ci server with my personal github account, and, I could ??

What's strange is that the ci.concourse.org server always returns this error. My org's server returns this error but then if I browse to the root url again, shows me as logged in with that github user, but no pipelines.

Does this mean that if I enable github auth, anyone can log into my ci server with a github account, they just might not be able to see the pipelines?

Also if that's the case why can't I log into the ci.concourse.org one with a personal account like I can my org's one?

## Version Info

See ci.concourse.org !

**Comment by vito** [comment] 2019-01-16 19:09
Duplicate of https://github.com/concourse/concourse/issues/2670

**Comment by eedwards-sk** [comment] 2019-01-16 19:10
I spend most days googling and I still couldn't find that issue. Big fail on my part. Sorry @vito

**Closed by vito** 2019-01-16 19:09 UTC
Labels: bug, triage

**Comment by vito** [comment] 2019-01-16 19:11
No problem! :slightly_smiling_face:
