### ISSUE TITLE
Combination of `check-resource` and `version: every` does not behave as expected

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/concourse#1678] opened 2017-09-29 19:15 UTC
## What challenge are you facing?

Suppose we have a Concourse resource, called `product-resource`, which knows how to download software packages. It does this by interacting with an API which can tell it about software releases.

The `product-resource` resource definition might look like:

```
resources:
- name: example-product
  type: product-resource
  source:
    product_slug: example-product
    product_version: 1\.6\..*
```

And it might be in the plan like this:

```
jobs:
- name: get-and-do-something-with-product
  plan:
  - get: example-product
    version: every
  - task: do-something-with-the-software
    file: tasks/something-doer/task.yml
```

So far so good. If I create the pipeline, then anything in the 1.6.x series for example-product will be downloaded and acted on.

Looking at the resource view in the UI, I see that it starts with the latest version of example-product and _only_ that version:

```
product_version: "1.6.15"
```

But I have a problem: I want to do something to _all_ the versions in the 1.6.x line. I know that `version: every` will handle half of this. I expect the other half is `check-resource`.

So I run `fly -t exampleci check-resource --from "product_version:1.6.12"`. 

When I return to the web GUI, I can see that the resource has indeed found previous versions:

```
product_version: "1.6.15"
product_version: "1.6.14"
product_version: "1.6.13"
```

But that's all it's done. Builds don't trigger with the as-yet-untried versions.

This remains the case no matter whether I create the resource prior to creating the job, or if I create them together.

# Bug Report

What I expect to happen is that history is rewound to the first resource found and then progressively played forward.

Now, if I haven't set `version: every`, then the behaviour of only acting on version 1.6.15 is expected. But I specifically need to replay history from a known point in time.

* Concourse version: 3.3.4
* Deployment type: BOSH
* Infrastructure/IaaS: GCP

**Comment by jchesterpivotal** [comment] 2017-09-29 19:22
Possibly related: 
* #736: Still seeing resources with version: every getting skipped 
* #882: When a new pipeline gets a resource that has been pinned to a "very old" version, my pipeline won't run until I `fly check-resource --from foo` 
* #145: Support for purging version history of a resource.

**Comment by vito** [comment] 2017-09-29 20:08
This was an intentional decision from when we first designed `version: every` (it's the last note in the initial issue: https://github.com/concourse/concourse/issues/358#issue-146763653). I do not think it generally makes sense to start from the first version, as you may be just introducing a new job and pointing it to a resource which has a bunch of versions collected already.

I also don't really think it makes sense to add a flag for it. The way things are going now, we might start doing fancy data correlating such that detected versions for the same resource will be shared across pipelines and/or teams, which could result in a bunch of versions already being present upon first configuration, resulting in someone accidentally starting from e.g. a commit from years ago.

In that light, it sounds like what you're trying to do is more specific than "start from the beginning": it sounds like you're trying to run a batch process against a specific version or range of versions. Sounds partly related to #1167 but without a way to express the...batchiness.

In any case, I'm going to close this; the feature is working as intended, and this sounds like it should start from a more broad discussion around what you're trying to do.

**Closed by vito** 2017-09-29 20:08 UTC
