### ISSUE TITLE
Custom resource - reference other resources in `in`?

### ISSUE THREAD

**Issue by cjohansen** [concourse/concourse#1962] opened 2018-01-15 23:53 UTC
# Bug Report

I have two custom resources. The first one is only used with `put` to trigger deployments. With a `put` I am passing it files from other resources, which it then proceeds to read and process:

```yml
- name: deploy-staging
  plan:
  - get: repo
    passed: [build]
  - put: custom-deployment-resource
    params:
      version: repo/.git/HEAD
```

This works fine. However, I'm not having any luck doing the same on `get`:

```yml
- name: deploy
  plan:
  - get: repo
    passed: [build]
  - get: generate-config
    params:
      version: repo/.git/HEAD
```

This resolves in "No such file or directory repo/.git/HEAD". Is this a feature, or am I doing something wrong?

**Comment by jtarchie** [comment] 2018-01-16 00:27
The `get` doesn't get any inputs mounted into it.

**Comment by vito** [comment] 2019-01-03 16:06
Yeah, this doesn't work (by design). Right now `get` steps can't be dynamically parameterized because they're treated as the things that first feed into a job, so they can't have any dependencies of their own.

I think this is ultimately one of the cases covered by #684, so I'm gonna close it. Thanks!

**Closed by vito** 2019-01-03 16:06 UTC
