### ISSUE TITLE
Pipeline Team Migration Support

### ISSUE THREAD

**Issue by marknet15** [concourse/concourse#4246] opened 2019-08-09 12:28 UTC
## What challenge are you facing?

Currently we have a moderate number of pipelines that were all created in the default `main` team and since then we have moved to use dedicated Concourse teams for each of our developer teams, however what we are lacking is a straight forward mechanism (I.E the `fly` cli) to migrate a pipeline from one team to another.

## What would make this better?

I think something from the `fly` cli would be ideal as it it would make it straight forward for us to migrate a pipeline from one team to another.

## Are you interested in implementing this yourself?

Unfortunately I'm not very familiar with GoLang yet.

**Comment by clarafu** [comment] 2019-08-12 15:38
Hello! With this pipeline migration to a different team, is the goal of adding this new feature that you want to retain all the build history for all the jobs within that pipeline? Because this could be easily done by just setting the same pipeline in the new team and destroying the old one but this would lose all the build history.

**Comment by vito** [comment] 2019-08-13 16:24
Closing as a dupe of https://github.com/concourse/concourse/issues/1164 - we'd be happy to review a PR for it!

**Closed by vito** 2019-08-13 16:24 UTC
Labels: enhancement, fly
