### ISSUE TITLE
concourse freezes if a job has a dependency on itself

### ISSUE THREAD

**Issue by dsabeti** [concourse/concourse#511] opened 2016-07-05 18:31 UTC
Hey there. I made the mistake of putting the following in my pipeline:
```yaml
- name: my-job
  plan:
  - get: some-resource
    passed: [ my-job ]
```
Instead of getting an error during `fly set-pipeline`, the CLI just says "configuration updated". But the Concourse UI completely freezes without any indication to the error. Maybe this could be detected in the CLI and give a meaningful error?

**Comment by vito** [comment] 2016-07-14 18:01
dupe of https://github.com/concourse/concourse/issues/84

**Closed by vito** 2016-07-14 18:01 UTC
Labels: unscheduled
