### ISSUE TITLE
Concourse Web UI shows 404 when viewing a resource which name contains a slash

### ISSUE THREAD

**Issue by dadacafe** [concourse/concourse#2211] opened 2018-05-10 14:40 UTC
Concourse Web UI shows 404 when viewing a resource which has a slash in its name.

* Concourse version: 3.13.0
* Deployment type: binary

### Steps to reproduce:

See minimalistic example pipeline (attached).

1. $ fly -t ci set-pipeline -p concourse-test -c pipeline.yml
2. Open concourse web interface
3. Open concourse-test -pipeline
4. Click resource 'test/resource'
5. Observe 404

### Expected behavior:
Resource details would open normally similar to any other resource without slash mark in their names.

[pipeline.yml.txt](https://github.com/concourse/concourse/files/1992026/pipeline.yml.txt)

**Comment by xtremerui** [comment] 2018-05-18 14:52
Could you provide a screen shot including the browser address bar?

This issue should be fixed already. Using your yml I couldn't reproduce it.

<img width="1057" alt="screen shot 2018-05-18 at 10 50 50 am" src="https://user-images.githubusercontent.com/1585949/40241655-89a0676e-5a89-11e8-8781-3e62f5c0e7b4.png">

**Comment by dadacafe** [comment] 2018-05-18 15:01
There you go sir. In this screenshot the pipeline is paused but I also checked that it doesn't work if it isn't.

<img width="1424" alt="screen shot 2018-05-18 at 17 58 01" src="https://user-images.githubusercontent.com/8615566/40242120-6862f45e-5ac5-11e8-8ffb-287ab5f44aea.png">

**Comment by xtremerui** [comment] 2018-05-18 15:15
I could only see 404 if the pipeline is deleted. Will have to wait until others report the similar issue.

**Comment by dadacafe** [comment] 2018-05-18 16:48
Okay! Are there any logs I could look through to investigate possible cause for this issue?

**Comment by vito** [comment] 2019-06-05 21:09
I'm going to consolidate this into https://github.com/concourse/concourse/issues/3985 which has been a long time coming. Thanks!

**Closed by vito** 2019-06-05 21:09 UTC
Labels: needs-investigation
