### ISSUE TITLE
5.3.0: Couldn't successfully login through LDAP

### ISSUE THREAD

**Issue by SimonXming** [concourse/concourse#4116] opened 2019-07-11 09:04 UTC
## Bug Report

Couldn't successfully login through LDAP in Concourse 5.3.0

## Steps to Reproduce

No sure, it suddenly happened.

## Expected Results

After login with my LDAP account, top-right corner should be my LDAP username. Request for `http://concouse-instance/sky/userinfo` should return 200 with JSON body.

## Actual Results

After login with my LDAP account, top-right corner is still `login`. Request for `http://concouse-instance/sky/userinfo` should return 401 Unauthorized.

## Additional Context

After I click login, following request send:

1. `POST /sky/issuer/auth/ldap?req=xxxx`  `303 See Other` 
    * `ResponseHeader.Location: /sky/issuer/approval?req=xxxxxxx`
    * `RequestHeader.Cookie: ...... skymarshal_state(exists) ....`
2. `GET /sky/issuer/approval?req=xxxx` `303 See Other`
    * `ResponseHeader.Location: /sky/callback?code=xxxxxxx`
    * `RequestHeader.Cookie: ...... skymarshal_state(exists) ....`
3. `GET /sky/callback?code=xxxx` `307 Temporary Redirect`
    * `ResponseHeader.Location: /?csrf_token=xxxxxx`
    * `ResponseHeader.Set-Cookie: skymarshal_state=; Path=/; Max-Age=0; HttpOnly`
    * `ResponseHeader.Set-Cookie: skymarshal_auth=<4300+ char>`(**I think it's too long**)
    * `RequestHeader.Cookie: ...... skymarshal_state(exists) ....`
4. `GET /?csrf_token=xxxxxx` `200 OK`
    * `RequestHeader.Cookie: .......` (**skymarshal_auth NOT exists**)
5. `GET /sky/userinfo` `401 Unauthorized`
    * `RequestHeader.Cookie: .......` (**skymarshal_auth NOT exists**)

Also, delete/recreate k8s pod didn't fix this problem.

## Version Info

* Concourse version: 5.3.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: K8S
* Browser (if applicable): Chrome
* Did this used to work? Yes

**Comment by evanchaoli** [comment] 2019-07-15 08:11
@vito I think this is a serious bug. We tried to restart ATC but didn't help. This issue prevents us from upgrading to 5.3.0. The problem cluster is still there.  If you have somebody to work with us, we can even do live debug.

**Comment by evanchaoli** [comment] 2019-07-15 09:10
More info to add:
1. This problem suddenly happened after we had been using 5.3.0 for a while.
2. The problem is with all browsers.
3. From ATC log, we can see LDAP login success, no any error log. But UI will just jump back to the login page.

**Comment by jama22** [comment] 2019-07-15 17:51
@pivotal-jwinters any thoughts on why this might be happening?

**Comment by antonu17** [comment] 2019-07-16 00:09
From my experience, it might be related to 4>5 upgrade, where old teams were created with `--allow-all-users`. I remember seeing 401 after the upgrade. This problem was fixed by updating all existing teams, setting new-style users/groups.

**Comment by evanchaoli** [comment] 2019-07-16 01:08
@antonu17 How to do the update teams?

**Comment by evanchaoli** [comment] 2019-07-16 01:22
After I manually deleted some teams directly from db, the issue is resolved, I can login with my LDAP credential now. But I still don't understand the root cause. Concourse should at least log some error, otherwise it would be super hard to debugging this kind of issues.

**Comment by evanchaoli** [comment] 2019-07-16 03:52
Now I know the root cause. Because Concourse doesn't support an admin role, in order to better monitor the cluster, a few of our core team members are in all team, which is done by a set-team automation pipeline. Looks like a login token includes all teams the user is in, the more teams the longer token. Eventually causes login cookie to be longer than 4096 bytes.

What could be a solution?

**Comment by antonu17** [comment] 2019-07-16 10:37
> @antonu17 How to do the update teams?

I updated all existing teams via `fly set-team -n <team> --ldap-group=<group1> --ldap-group=<groupN>`

Team's look before update:

```
fly -t prod teams -d
name/role                         users           groups
<team>/owner                      all             none
```

After update:

```
fly -t prod teams -d
name/role                         users           groups
<team>/owner                      none            ldap:<group1>,ldap:<groupN>
```

**Comment by antonu17** [comment] 2019-07-16 10:40
> Now I know the root cause. Because Concourse doesn't support an admin role, in order to better monitor the cluster, a few of our core team members are in all team, which is done by a set-team automation pipeline. Looks like a login token includes all teams the user is in, the more teams the longer token. Eventually causes login cookie to be longer than 4096 bytes. That also explains why after I manually deleted some teams from DB, I could login.
> 
> What could be a solution?

Yes, keeping all the teams in a JWT token is really annoying too. Especially, when a new team is created, access granted, but users report "I have no access" and I have to make them logout/login in a browser.

**Comment by cirocosta** [comment] 2019-07-16 12:26
@evanchaoli thanks for taking the time to investigate!

That's indeed something that people have been asking for a while. I think these two issues capture what you'd like supported:

- [Super admin user](https://github.com/concourse/concourse/issues/3853)
- [Support large JWT token in web UI](https://github.com/concourse/concourse/issues/3141)

Do you think we should close this one then? It'd be great if you could add some comments to those issues to better capture your expectations and/or help out with some ideas too 😁  

Thank you!

**Comment by evanchaoli** [comment] 2019-07-16 12:36
Closing per @cirocosta 's comment.

**Closed by evanchaoli** 2019-07-16 12:36 UTC
Labels: auth, bug, web-ui
