### ISSUE TITLE
Flaky K8s topgun DNS proxy test

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6879] opened 2021-04-13 19:37 UTC
## Summary

https://github.com/concourse/concourse/blob/e870c6489235e0ad9bf1b722fac2e46848af499d/topgun/k8s/dns_proxy_test.go#L115-L120

This k8s topgun test has been particularly flaky recently, but I've seen failures as early as last October (e.g. https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-topgun/builds/367#L5f986e4f:934:941)

It doesn't seem to matter which backend is being used (guardian or containerd) - it flakes on both.

p.s. when it "flakes", it's actually because we expect the DNS resolution to fail, but it actually succeeds

## Steps to reproduce

Run k8s topgun

## Expected results

This test doesn't fail

## Actual results

It does pretty frequently - even when the suite passes, it's common that it flaked at least once.

## Additional context

@EstebanFS and I aren't too sure about the expected behaviour here. It seems to us that the DNS resolution should actually succeed. For both guardian and containerd, we set the nameservers to the provided nameserver AND our local DNS proxy when it's enabled:

https://github.com/concourse/concourse/blob/e870c6489235e0ad9bf1b722fac2e46848af499d/worker/workercmd/guardian.go#L104

https://github.com/concourse/concourse/blob/e870c6489235e0ad9bf1b722fac2e46848af499d/worker/workercmd/containerd.go#L168

Therefore, we'd expect resolving an address that is visible to the local DNS proxy to succeed (though the test says otherwise).

We opened #6878 to skip this test until we figure out whether the behaviour is actually what we want.

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?

**Comment by chenbh** [comment] 2021-04-20 19:42
So the expectation that having a DNS server and a proxy server should fail to resolve k8s addresses is correct. This is due to a quirk with DNS resolution: it only tries the next name server if the previous server times out. Even if the previous server fails to resolve, as long as it responds the search will terminate.

> The algorithm used is to try a name server, and if the query times out, try the next, until out of name servers, then repeat trying all the name servers until a maximum number of retries are made.

https://linux.die.net/man/5/resolv.conf

Since the proxy server's IP is added after all the passed in IPs, the query will go to `8.8.8.8` first and fail to resolve as expected.

**Comment by chenbh** [comment] 2021-04-20 19:44
Question is why did it start hitting the second DNS server (aka the proxy) consistently? This is hard to reproduce since the test clusters where this is occurring on is getting GC'd as soon as the tests complete.

**Comment by taylorsilva** [comment] 2021-05-06 16:30
Fixed by https://github.com/concourse/concourse/pull/6947

**Closed** 2021-05-06 16:30 UTC
Labels: bug
