### ISSUE TITLE
Paused jobs sometimes keep spawning

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#870] opened 2017-01-12 19:09 UTC
# Bug Report

* Concourse version: **2.5.1**
* Deployment type (BOSH/Docker/binary): **binary**
* Infrastructure/IaaS: **Centos7**
* Browser (if applicable): **Chrome, but I don't think it's related**
* Did this used to work? **Not sure, it seems to be intermittent**

## Observed Behavior
Pipeline configuration: Multiple jobs that are triggered from separate and non-overlapping resources.
The pipeline was paused along with each of the jobs within the pipeline.
We unpaused the pipeline and unpaused one of the jobs that we wanted to run. However, instead of just that one job running, all of the jobs tried to start running, even the paused ones. When we went into the paused jobs and aborted the build, a new build would start up almost immediately. We tried to then pause each of the resources of the paused jobs, and the jobs would still come back after aborting them.

This behavior seems to be flaky since I finished what I needed to do on that pipeline, paused it and started up another job on a similar but different pipeline without experiencing this bug. In the second pipeline's case, I paused all of the jobs and all of the resources before unpausing the pipeline and job/resource I cared about.

**Comment by vito** [comment] 2017-10-02 19:42
Duplicate of https://github.com/concourse/concourse/issues/482.

**Closed by vito** 2017-10-02 19:42 UTC
Labels: needs-investigation, type: bug
