### ISSUE TITLE
Garden server is not systemd aware

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#3613] opened 2019-03-28 14:57 UTC
Brought up by the Garden team:

> Hey - Garden team here (Tom and Giuseppe). We think we've found an issue in concourse 5.0.0. In earlier versions of concourse, you'd consume the garden bosh release to include garden in deployments and in 5.0.0 it looks like you switched to using the gdn binary directly. Xenial stemcells ship with systemd, which thinks it owns cgroups on the VMs and will mess with the cgroups for services not registered as systemd services and told explictly not to do that.

> We observe that the cgroup path for the garden server running in our concourse 5.0.0 deployment doesn't mention system.slice (telltale sign that it's systemd aware). Because of the issue, we register garden as a systemd service in our bosh ctl scripts and we fear that concourse isn't doing this in 5.0.0 which may cause unexpected behaviour related to container cgroups.

Affects Concourse v5.0.0

**Comment by BooleanCat** [comment] 2019-03-28 15:06
Relevant garden issue: https://github.com/cloudfoundry/garden-runc-release/issues/108 

We blogged about these problems after we discovered them here: https://github.com/georgethebeatle/systemdont

**Comment by chenbh** [comment] 2019-04-05 18:12
@BooleanCat 

@ddadlani and I investigated this a little and it looks like systemd is messing around with garden's cgroups but we managed to accidentally avoid this by running garden in runc mode

### Observations
- none of our users nor us noticed anything wrong and garden seems to Just Work™
- something **is** moving the container processes cgroups around:
```
$ tree /sys/fs/cgroups/memory
/sys/fs/cgroups/memory
├── 0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
├── ...
├── garden
└── ...

$ cat /var/vcap/data/worker/work/depot/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0/pidfile
3560719

$ cat /proc/3560719/cgroup
12:perf_event:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
11:hugetlb:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
10:net_cls,net_prio:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
9:cpuset:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
8:devices:/system.slice/runit.service/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
7:blkio:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
6:cpu,cpuacct:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
5:pids:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
4:freezer:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
3:rdma:/
2:memory:/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
1:name=systemd:/system.slice/runit.service/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0
```
- the `cgroups.procs` file for the garden cgroup is empty:
```
$ wc /sys/fs/cgroup/memory/garden/cgroup.procs
0 0 0 /sys/fs/cgroup/memory/garden/cgroup.procs
```
- however, the `state.json` for the bad containers **are** being updated properly
```
cat /run/runc/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0/state.json | jq .cgroup_paths
{
  "blkio": "/sys/fs/cgroup/blkio/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "cpu": "/sys/fs/cgroup/cpu,cpuacct/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "cpuacct": "/sys/fs/cgroup/cpu,cpuacct/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "cpuset": "/sys/fs/cgroup/cpuset/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "devices": "/sys/fs/cgroup/devices/system.slice/runit.service/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "freezer": "/sys/fs/cgroup/freezer/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "hugetlb": "/sys/fs/cgroup/hugetlb/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "memory": "/sys/fs/cgroup/memory/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "name=systemd": "/sys/fs/cgroup/systemd/system.slice/runit.service/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "net_cls": "/sys/fs/cgroup/net_cls,net_prio/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "net_prio": "/sys/fs/cgroup/net_cls,net_prio/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "perf_event": "/sys/fs/cgroup/perf_event/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0",
  "pids": "/sys/fs/cgroup/pids/0d233f08-00c2-43d8-5b57-2c2af4f5bfc0"
}
```
- `state.json` for good containers are behaving as expected
```
cat /run/runc/05cc300a-f464-4859-6230-9be9e18d0017/state.json | jq .cgroup_paths
{
  "blkio": "/sys/fs/cgroup/blkio/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "cpu": "/sys/fs/cgroup/cpu,cpuacct/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "cpuacct": "/sys/fs/cgroup/cpu,cpuacct/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "cpuset": "/sys/fs/cgroup/cpuset/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "devices": "/sys/fs/cgroup/devices/system.slice/runit.service/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "freezer": "/sys/fs/cgroup/freezer/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "hugetlb": "/sys/fs/cgroup/hugetlb/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "memory": "/sys/fs/cgroup/memory/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "name=systemd": "/sys/fs/cgroup/systemd/system.slice/runit.service/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "net_cls": "/sys/fs/cgroup/net_cls,net_prio/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "net_prio": "/sys/fs/cgroup/net_cls,net_prio/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "perf_event": "/sys/fs/cgroup/perf_event/garden/05cc300a-f464-4859-6230-9be9e18d0017",
  "pids": "/sys/fs/cgroup/pids/garden/05cc300a-f464-4859-6230-9be9e18d0017"
}
```
- the bad containers do go away after a while, a sign that garden was able to kill it successfully
- the number of `container-id`s in the garden depot (`/var/vcap/worker/work/depot`) matches with the number of containers in the runc state dir (`/run/runc/`), more signs there was no leaking containers

### Notes
So it looks like runc is (now) smart enough to figure out the actual cgroup paths for itself and is updating it's state appropriately.

Regarding the missing systemd service, is there anyway to tell the garden binary to add it on startup? One of the ways Concourse is distributed is as a binary so we can't rely on the BOSH release to add the service and it feels weird for us to be responsible for adding the service.

The containers we've seen were all run without resource limits, we're looking into seeing what would happen if we try to enforce container limits (i.e. actually use cgroup limits)

### Random details
```
$ runc -v
runc version 1.0.0-rc6+dev
commit: 2b18fe1d885ee5083ef9f0838fee39b62d653e30-dirty
spec: 1.0.1-dev
$ gdn -v
d694f9ae265ab2a01cb74604bae3a6a805777a73
```

**Comment by BooleanCat** [comment] 2019-04-09 18:26
> Regarding the missing systemd service, is there anyway to tell the garden binary to add it on startup? One of the ways Concourse is distributed is as a binary so we can't rely on the BOSH release to add the service and it feels weird for us to be responsible for adding the service.

Systemd is an opinionated service and will mess with cgroups unless instructed not to (actually container daemons are one of things the systemd docs call out as an appropriate circumstance in which systemd should be told to ignore cgroups).

There's a few ways in which I can armchair engineer where this might manifest:

1. pids from container memory cgroups are moved to another cgroup - effectively removing the memory limit for a container. We *think* we have observed this in Garden's CI. We see a test related to applying memory limits to containers fail periodically and we suspect its because systemd moved the process.
1. containers cannot be killed - runc uses the devices cgroup for a container as the source of truth for "which processare are 'in' a container", if systemd messes with that cgroup then some containerised processes would be "forgotten" by runc and won't ever be signalled.

**Comment by chenbh** [comment] 2019-04-09 21:16
we're considering registering the `concourse` cmd as a service and see if the `gdn` cgroups are respected by systemd.

**Comment by chenbh** [comment] 2019-04-11 16:35
Update: adding a `concourse.service` for the concourse binary (which spawns the garden server) allowed garden to create it's cgroups under our service:
```
$ cat /proc/24286/cgroup
12:pids:/system.slice/concourse.service/garden/ec388589-b3b4-47a8-444b-34be7872334c
11:cpu,cpuacct:/system.slice/concourse.service/garden/ec388589-b3b4-47a8-444b-34be7872334c
10:memory:/system.slice/concourse.service/garden/ec388589-b3b4-47a8-444b-34be7872334c
9:perf_event:/garden/ec388589-b3b4-47a8-444b-34be7872334c
8:rdma:/
7:freezer:/garden/ec388589-b3b4-47a8-444b-34be7872334c
6:devices:/system.slice/concourse.service/garden/ec388589-b3b4-47a8-444b-34be7872334c
5:cpuset:/garden/ec388589-b3b4-47a8-444b-34be7872334c
4:blkio:/system.slice/concourse.service/garden/ec388589-b3b4-47a8-444b-34be7872334c
3:hugetlb:/garden/ec388589-b3b4-47a8-444b-34be7872334c
2:net_cls,net_prio:/garden/ec388589-b3b4-47a8-444b-34be7872334c
1:name=systemd:/system.slice/concourse.service/garden/ec388589-b3b4-47a8-444b-34be7872334c
```

`perf_event`, `freezer`, `cpuset`, `hugetlb`, `net_cls,net_prio` does not have a `system.slice` directory so we're not sure if systemd will still mess around with the cgroups there.

Don't know what's going on with `rdma`, it has a `garden/` directory but there's no containers in there. Maybe it's not used by garden at all?

**Comment by BooleanCat** [comment] 2019-04-11 18:43
> so we're not sure if systemd will still mess around with the cgroups there

We observed systemd being fairly indiscriminate with the cgroups it messes with.

> Don't know what's going on with rdma, it has a garden/ directory but there's no containers in there. Maybe it's not used by garden at all?

Garden doesn't use the rdma cgroup at the moment..

**Comment by chenbh** [comment] 2019-04-11 22:02
> `perf_event`, `freezer`, `cpuset`, `hugetlb`, `net_cls,net_prio` does not have a `system.slice` directory so we're not sure if systemd will still mess around with the cgroups there.

Turns out systemd will straight up not manage those subsystems: https://github.com/systemd/systemd/blob/master/docs/CGROUP_DELEGATION.md#controller-support

That said, not sure why we saw it mess around with it in our prod workers. Maybe because all the hierarchies/controllers/subsystems are synchronized and if it messes around with a cgroup in something it manages (e.g. cpu), it will reflect the changes on the ones it doesn't manage (e.g. freezer) as well? Seems consistent with what we're seeing (it's always the same set of containers that are out of place in all the subsystems)

### So the steps for fixing this (issue only affects the concourse worker):
- BOSH release: use the same pattern the garden-release is doing and add a concourse.service to the worker job
- Binary: add documentation for root cause of issue and sample service for systemd
- Docker image: we use dumb-init so not affected

**Comment by ddadlani** [comment] 2019-04-15 14:08
IPM follow up: We should check if Docker will be affected by this issue as well (or other container runtimes e.g. rkt).

**Comment by cirocosta** [comment] 2019-04-15 16:40
Hey, regarding possibly `systemd` being invasive: https://docs.docker.com/engine/reference/commandline/dockerd/#options-for-the-runtime

which goes down to: https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/systemd/apply_systemd.go

**Comment by chenbh** [comment] 2019-04-16 17:56
Took a look at it with @cirocosta, Docker by default will manage it's own cgroups, it also has option to use systemd instead. 

Either way the official way of installing Docker will also create and install `docker.service` (along with a `containerd.service`) so systemd shouldn't be a problem there.

`rkt` doesn't appear to have a centralized daemon and has a [page](https://coreos.com/rkt/docs/latest/using-rkt-with-systemd.html) dedicated to working with systemd, I would say that there should be no issues there.

**Comment by cirocosta** [comment] 2019-05-01 21:55
Hey, a quick experience report - today @chenbh and I were looking at how the cgroups appear in GKE Ubuntu machine, at it seems like systemd might be playing some role there 🤔

**Comment by vito** [comment] 2019-05-13 15:59
merged https://github.com/concourse/concourse-bosh-release/pull/24

**Closed by vito** 2019-05-13 15:59 UTC
