### ISSUE TITLE
Fly hijack fails silently if /bin/bash not present on Image

### ISSUE THREAD

**Issue by tinygrasshopper** [concourse/concourse#758] opened 2016-11-09 14:04 UTC
If there is no /bin/bash executable in the container, fly fails silently and exits 0.

Error seen in atc log on stdout:
```
==> /var/vcap/sys/log/atc/atc.stdout.log <==
{"timestamp":"1478699521.179357529","source":"atc","message":"atc.hijack.hijack.failed-to-hijack","log_level":2,"data":{"error":"hijack: Backend error: Exit status: 500, message: {\"Type\":\"\",\"Message\":\"runc exec: exit status 1: exec failed: exec: \\\"bash\\\": executable file not found in $PATH\",\"Handle\":\"\"}\n","handle":"7d7b8972-a0f4-49b6-5b67-4d8b2384d93e","process":{"path":"bash","args":null,"env":["TERM=xterm"],"dir":"/tmp/build/0df9eea0","privileged":true,"user":"root","tty":{"window_size":{"columns":310,"rows":68}}},"session":"7968.1"}}
```

Expected behaviour: User should be notified of this error.

* Concourse version: v2.2.1
* Deployment type: BOSH

Thanks,
@APShirley and @tinygrasshopper

**Comment by chendrix** [comment] 2017-03-31 04:16
Is this still the behavior you see? Because I believe it's been changed to an (also bad) error message in fly now.

**Comment by chendrix** [comment] 2017-03-31 04:17
Nvm it's the same. Closing as dupe of concourse/concourse#833

**Closed by chendrix** 2017-03-31 04:17 UTC
Labels: troubleshooting, unscheduled
