### ISSUE TITLE
UI is very slow when log output is large

### ISSUE THREAD

**Issue by casparrolfe** [concourse/concourse#3689] opened 2019-04-04 15:44 UTC
## What challenge are you facing?

Task logs with a lot of output cause the UI to grind to a halt. I believe this is due to the browser struggling to render all of the DOM nodes for each line rendered.

## What would make this better?

Perhaps using some kind of virtual scroll (example of this implemented in React [here](https://bvaughn.github.io/react-virtualized))

## Are you interested in implementing this yourself?

Unfortunately I don't know any Elm!

**Comment by marco-m** [comment] 2019-04-05 12:50
Duplicate of #3521, please close.

**Closed** 2019-04-05 14:52 UTC
Labels: enhancement, triage
