### ISSUE TITLE
Git Resource check fails intermittently

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#2553] opened 2018-09-04 13:46 UTC
Multiple users have noted that their git check resource fails intermittently

Sample error message 1

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
fatal: unable to access 'https://github.com/cloudfoundry/php-buildpack.git/': Could not resolve host: github.com
```

Sample error message 2
```
Cloning into '/tmp/build/get'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

We verified on our private environment and were unable to reproduce the issue using a simple git resource.

When trying to curl github.com in a aggressive loop from a hijacked container, we noticed that most requests responded with a status 429 Too Many Requests ( possibly indicating a NAT related problem as all requests are routed through the NAT )

Also, Github was experiencing issues [Status](https://status.github.com/messages) from Aug 28 - Aug 31. This approximately corresponds with the git resource issues reported to us.

**Comment by matt-royal** [comment] 2018-09-18 17:54
The BAM team has experienced errors like the one shown in your second sample error message. We can provide a sampling of error messages and links to failed builds if that would be helpful.

**Comment by jama-pivotal** [comment] 2018-10-25 17:41
Closing this issue because the resolution was due to our NAT box dropping messages. Reproducing the snippet from our Wings incident log https://github.com/pivotal-cf/concourse-support/blob/42a3dbc9b00a66eba7afee190c5cb7c8fde4c162/incidents/Wings%2027-08-2018.md

## Issue
A bunch of folks seeing intermittent issues contacting external endpoints such as github.com


On further investigation, we discovered that the NAT box was overloaded

In `dmesg` we saw dropped packet messages such as `nf_conntrack: table full, dropping packet`

Used `netstat-nat` utility to determine the number of connections on the NAT box.

## Error Message
```
fatal: unable to access 'https://github.com/cloudfoundry/cli/': Could not resolve host: github.com
```

```
ERROR: Get https://network.pivotal.io/api/v2/products/p-windows-runtime/releases: dial tcp: lookup network.pivotal.io on 8.8.4.4:53: read udp 10.254.1.210:57649->8.8.4.4:53: i/o timeout
```

Different but potentially related error
```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
fatal: unable to access 'https://github.com/cloudfoundry/php-buildpack.git/': Could not resolve host: github.com
```

## Resolution
We increased the nf_conntrack table size by running `sysctl -w net.netfilter.nf_conntrack_max=131072`

This seemed to have resolved the problem of dropped packets.

**Closed by jama-pivotal** 2018-10-25 17:41 UTC
Labels: needs-investigation
