### ISSUE TITLE
Build UI never shows output - Hello world

### ISSUE THREAD

**Issue by sgbcoder** [concourse/concourse#5072] opened 2020-01-27 17:23 UTC
## Bug Report
The Build log shows loading forever and never prints the output.

## Steps to Reproduce

Followed the hello-world tutorial here: https://concoursetutorial.com/basics/task-hello-world/

## Expected Results

The build output shows "hello world"

## Actual Results

The loader keeps spinning indefinitely with no output even after build succeeds.
 
## Version Info

* Concourse version:5.6.0
* Deployment type (BOSH/Docker/binary):Docker
* Browser (if applicable):Chrome

I'm not using any anti-virus software, no reverse-proxy as well.Was able to see a running worker upon running fly -t <target> workers.

**Comment by sgbcoder** [comment] 2020-03-01 12:46
Still facing the issue....could anyone please help to triage this

**Comment by pivotal-jamie-klassen** [comment] 2020-03-03 15:53
@sgbcoder Out of curiosity, having seen the age of this issue, I just followed the tutorial on MacOS 10.12.6 and Chrome 80.0.3987.122 and everything worked.

With the level of detail you've provided, I can't help but suspect that this is not a bug, or if it is, it might be a problem with the Stark & Wayne tutorial. Overall, this issue appears to be a support request. It probably makes more sense to ask in the [support forums](https://discuss.concourse-ci.org/c/support) or in [Discord](https://discord.gg/MeRxXKW) instead of opening GitHub issues.

If I were you, I would be prepared to include more specific details about every single thing you did (from downloading the `docker-compose.yml` to installing/syncing fly, to cloning the tutorial repo, to executing the sample task, including the exact terminal commands and browser URLs, etc) and the feedback you saw. The docker-compose logs and browser logs might contain useful information, too.

I'm going to close the issue now to fight clutter in our tracker, but if you ask for help as I've suggested and measure the feedback signals I've outlined above and _still_ can't get things working, please open a new issue with the relevant details and the community will have a chance to investigate.

**Closed by pivotal-jamie-klassen** 2020-03-03 15:53 UTC
Labels: bug
