### ISSUE TITLE
[Bug] Check Resource UI returns to past error while checking is still happening

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#4119] opened 2019-07-12 15:27 UTC
Check resource button returns to previous error after it invokes its action. This  doesn't reflect the current state in the system as the check is occurring in the background.

**Setup**
We saw something confusing happening with the check resource button during out testing. We changed resource.Check to do `sleep 300` and have the scanner check context timeout in 60s. This mimics a resource check timeout occurring when a check script takes too long. 
The UI kinda tricks you. If you manually check resource by hitting the button. It'll kick off a check but won't block out for the duration of the check itself. This is ok but when the button transitions from currently checking. It goes back to checking failed and the error message but in reality the check is still happening in the background.

Heres a gif of what we're [describing.](https://imgur.com/e5a77H0)

**Comment by pivotal-jamie-klassen** [comment] 2019-07-12 15:56
i know that this has the same underlying cause as #3863 - maybe we should improve its description to include not just the case when a resource was successful and is currently checking, but also when it was failing before the check was initiated?

**Comment by pivotal-jamie-klassen** [comment] 2019-07-12 15:58
Duplicate of #3863, but I'm gonna link your excellent GIF on that issue.

**Closed by pivotal-jamie-klassen** 2019-07-12 15:58 UTC
Labels: bug, web-ui
