### ISSUE TITLE
Unhelpful message "error: resource not found" when illegal character "/" used in pipeline name

### ISSUE THREAD

**Issue by bendalby82** [concourse/concourse#986] opened 2017-03-28 13:47 UTC
# Bug Report

If you include a `/` in the name of your pipeline when you call `fly`, you will be prompted to `apply configuration? [yN]`, and then the command will fail with:  
`error: resource not found`  

Example failing call:  
`fly -t local set-pipeline -p ci/simple-deploy --config ci/simple_deploy.yml`  

It is currently very difficult to determine the problem from the error message.   

Suggestions to improve would be:   
a. Make the error message more helpful  
b. Enhance docs for `fly` CLI to mention illegal characters  
c. Enhance `fly` CLI to check for illegal characters

* Concourse version: 2.5.0 and 2.7.x
* Deployment type (BOSH/Docker/binary): Vagrant concourse/lite box
* Infrastructure/IaaS: Mac OSX 10.12.3
* Browser (if applicable): Not applicable

**Comment by chendrix** [comment] 2017-03-31 04:05
Closing as dupe of concourse/fly#139

**Closed by chendrix** 2017-03-31 04:05 UTC
Labels: unscheduled
