### ISSUE TITLE
download s3 resource returns runtime error

### ISSUE THREAD

**Issue by mandyozhao** [concourse/concourse#186] opened 2015-10-28 22:17 UTC
we(ops manager) have a resource in a public folder, when trying to download it as a task, it returns error as the following(it is a pretty long stack trace)

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x531305]

goroutine 6 [running]:
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).setTotalBytes(0xc8200a2380, 0xc8201480e0)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:206 +0x95
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).downloadPart(0xc8200a2380, 0xc820016720)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:175 +0x46a
created by github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).download
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:114 +0xbe

goroutine 1 [sleep]:
time.Sleep(0x989680)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).download(0xc8200a2380, 0xc8200a2380, 0x0, 0x0)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:128 +0x12b
github.com/aws/aws-sdk-go/service/s3/s3manager.(*Downloader).Download(0xc820117888, 0x7f9d2ef8fce0, 0xc8200300b0, 0xc8200a54a0, 0x0, 0x0, 0x0)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:70 +0xcf
github.com/concourse/s3-resource.(*s3client).DownloadFile(0xc820030090, 0xc820011950, 0x23, 0xc820011aa0, 0x25, 0x0, 0x0, 0xc8200548c0, 0x34, 0x0, ...)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/s3client.go:264 +0x316
github.com/concourse/s3-resource/in.(*InCommand).downloadFile(0xc820117eb0, 0xc820011950, 0x23, 0xc820011aa0, 0x25, 0x0, 0x0, 0x7ffc2590bf14, 0xe, 0xc820011aa0, ...)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/in/in_command.go:189 +0x18d
github.com/concourse/s3-resource/in.(*InCommand).inByRegex(0xc820117eb0, 0x7ffc2590bf14, 0xe, 0xc82000b260, 0x14, 0xc8200119b0, 0x28, 0xc820011950, 0x23, 0xc82000b280, ...)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/in/in_command.go:92 +0x2dc
github.com/concourse/s3-resource/in.(*InCommand).Run(0xc820117eb0, 0x7ffc2590bf14, 0xe, 0xc82000b260, 0x14, 0xc8200119b0, 0x28, 0xc820011950, 0x23, 0xc82000b280, ...)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/in/in_command.go:66 +0x2ee
main.main()
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/cmd/in/main.go:34 +0x2e2

goroutine 5 [chan receive]:
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).downloadPart(0xc8200a2380, 0xc820016720)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:157 +0xf2
created by github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).download
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:114 +0xbe

goroutine 7 [chan receive]:
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).downloadPart(0xc8200a2380, 0xc820016720)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:157 +0xf2
created by github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).download
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:114 +0xbe

goroutine 8 [chan receive]:
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).downloadPart(0xc8200a2380, 0xc820016720)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:157 +0xf2
created by github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).download
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:114 +0xbe

goroutine 9 [chan receive]:
github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).downloadPart(0xc8200a2380, 0xc820016720)
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:157 +0xf2
created by github.com/aws/aws-sdk-go/service/s3/s3manager.(*downloader).download
	/tmp/build/b6237934-9e2f-4838-56a4-73bd768b9a80/gopath/src/github.com/concourse/s3-resource/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go:114 +0xbe

goroutine 34 [IO wait]:
net.runtime_pollWait(0x7f9d2ef4c178, 0x72, 0xc82000e160)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201a40d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201a40d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201a4070, 0xc8201ba400, 0x400, 0x400, 0x0, 0x7f9d2ef8b050, 0xc82000e160)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201a6008, 0xc8201ba400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201a2870, 0x7f9d2ef0b230, 0xc8201a6008, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201b6000, 0x92c717, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201b6000, 0xc820228000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f9d2ef17dc0, 0xc8201b6000, 0xc82017a058, 0xc820228000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204e3120, 0xc820228000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8204651a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8204651a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82017a000)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 35 [select]:
net/http.(*persistConn).writeLoop(0xc82017a000)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 25 [select]:
net/http.(*persistConn).readLoop(0xc82017a0b0)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0xc82017a0b0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

**Comment by ctaymor** [comment] 2015-11-05 19:40
Looks to be a duplicate of https://github.com/concourse/s3-resource/issues/17

Feel free to close.

**Comment by xoebus** [comment] 2015-11-05 19:45
Thanks for letting us know!

**Closed** 2015-11-05 19:44 UTC
Labels: unscheduled
