### ISSUE TITLE
Should not specifying web-public-dir with concourse web automatically create the directory and files?

### ISSUE THREAD

**Issue by NorseGaud** [concourse/concourse#8910] opened 2024-02-08 15:16 UTC
## Summary

On macos running `concourse web` doesn't seem to work. I get a white page loading 8080 and an error like 

```
❯ concourse web
{"timestamp":"2024-02-08T14:54:27.847339000Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2024-02-08T14:54:28.036180000Z","level":"info","source":"atc","message":"atc.tracker-imb.start","data":{"session":"22"}}
{"timestamp":"2024-02-08T14:54:28.048894000Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":2098958,"session":"1"}}
{"timestamp":"2024-02-08T14:54:28.052577000Z","level":"info","source":"tsa","message":"tsa.listening","data":{}}
{"timestamp":"2024-02-08T14:54:28.052918000Z","level":"info","source":"atc","message":"atc.listening","data":{"debug":"127.0.0.1:8079","http":"0.0.0.0:8080"}}
{"timestamp":"2024-02-08T14:54:32.410139000Z","level":"error","source":"atc","message":"atc.index.failed-to-build-template","data":{"error":"template: index.html:8:63: executing \"index.html\" at \u003casset \"main.css\"\u003e: error calling asset: open main.css: file does not exist","session":"44"}}
2024/02/08 09:54:32 http: superfluous response.WriteHeader call from github.com/felixge/httpsnoop.(*Metrics).CaptureMetrics.func1.1 (capture_metrics.go:53)
{"timestamp":"2024-02-08T14:54:32.434224000Z","level":"error","source":"atc","message":"atc.index.failed-to-build-template","data":{"error":"template: index.html:8:63: executing \"index.html\" at \u003casset \"main.css\"\u003e: error calling asset: open main.css: file does not exist","session":"47"}}
2024/02/08 09:54:32 http: superfluous response.WriteHeader call from github.com/felixge/httpsnoop.(*Metrics).CaptureMetrics.func1.1 (capture_metrics.go:53)
{"timestamp":"2024-02-08T14:54:38.087693000Z","level":"info","source":"atc","message":"atc.scanner.tick.start","data":{"session":"23.2"}}
{"timestamp":"2024-02-08T14:54:38.094703000Z","level":"info","source":"atc","message":"atc.scanner.tick.end","data":{"session":"23.2"}}
```

Shouldn't this directory be created in the current directory if not specified with --web-public-dir= ?

Related: https://github.com/concourse/concourse/issues/7597

## Steps to reproduce

Get latest darwin binary, go through the getting started tutorial, and launch with `concourse web`

## Expected results

Web UI loads.

## Actual results

White UI and errors in logs.

## Triaging info

```
❯ concourse --version
7.11.2
```

* Browser (if applicable):  N/A

**Comment by NorseGaud** [comment] 2024-02-08 15:24
Even specifying the location with that flag doesn't work

```
❯ ll concourse-public
total 0

❯ concourse web --web-public-dir=/Users/m1mini/concourse-public
{"timestamp":"2024-02-08T15:23:40.898385000Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2024-02-08T15:23:41.082969000Z","level":"info","source":"atc","message":"atc.tracker-imb.start","data":{"session":"22"}}
{"timestamp":"2024-02-08T15:23:41.096816000Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":2038209,"session":"1"}}
{"timestamp":"2024-02-08T15:23:41.100758000Z","level":"info","source":"tsa","message":"tsa.listening","data":{}}
{"timestamp":"2024-02-08T15:23:41.101736000Z","level":"info","source":"atc","message":"atc.listening","data":{"debug":"127.0.0.1:8079","http":"0.0.0.0:8080"}}
{"timestamp":"2024-02-08T15:23:43.909570000Z","level":"error","source":"atc","message":"atc.index.failed-to-parse-templates","data":{"error":"template: pattern matches no files: `index.html`","session":"44"}}
```

**Comment by slimeandsoakem** [comment] 2024-02-26 13:09
I found that the docker build neglected the npm phases - 
Using the main concourse git repo, run these steps first to get the css's compiled
`npm install
npm install -g yarn
npm run build`

**Comment by taylorsilva** [comment] 2024-12-23 20:56
Duplicate of mentioned issue https://github.com/concourse/concourse/issues/7597

**Closed by taylorsilva** 2024-12-23 20:56 UTC
Labels: bug
