### ISSUE TITLE
Build scrolling broken

### ISSUE THREAD

**Issue by ostenbom** [concourse/concourse#5490] opened 2020-04-22 15:43 UTC
## Summary

Not able to scroll horizontally through build history in concourse 6. Is this just me?

## Steps to reproduce

Install concourse 6
Have more than 30 builds in a job
Try to scroll horizontally back in time

## Expected results

Able to go back in time

## Actual results

Not able to go back in time :( I get "pushed back" by the browser in some odd way. As if the rest of the data is there but it wont let me go there..

## Additional context

Tested on chrome, safari and firefox on MacOS Catalina

## Triaging info

* Concourse version: 6.0.0
* Browser (if applicable): Chrome 81, Safari 13, Firefox 75
* Did this used to work? Yep

**Comment by pivotal-jamie-klassen** [comment] 2020-04-22 16:55
Duplicate of #5383, which is fixed on master in #5392. Closing now - if you re-encounter the issue on an RC build/build from source on master, please open a new one!

**Closed by pivotal-jamie-klassen** 2020-04-22 16:55 UTC
Labels: bug
