### ISSUE TITLE
UI login page should not silently reject authentication

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#885] opened 2017-01-17 22:30 UTC
# Bug Report
* Concourse version: **2.6.0**
* Deployment type (BOSH/Docker/binary): **Binary**
* Infrastructure/IaaS: **Infrastructure - Ubuntu 16.04**
* Browser (if applicable): **Chrome**
* Did this used to work? **Not that I'm aware of**

Observed Behavior:
When logging in to the UI with a bad username/password, the login page does not show anything to the user indicating they failed to log in. Instead it just sits there as if nothing happened. So a user can't tell the difference between an authentication failure and a system failure.

Expected Behavior:
The login page should show something to the effect of "authentication failure" when a user's credentials are invalid. If possible, a separate error should be shown if there is a system failure.

**Comment by ClaraFuPivotal** [comment] 2017-05-08 16:09
I'm going to close this issue because it is a duplicate of https://github.com/concourse/concourse/issues/776. Thanks for submitting the bug report!

**Closed by ClaraFuPivotal** 2017-05-08 16:09 UTC
Labels: bug, unscheduled
