### ISSUE TITLE
Fly stdout writing appears to be slow (unbuffered?)

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1446] opened 2017-08-05 08:46 UTC
# Bug Report

I use fly to monitor our builds and the concourse cluster very often with commands that produce a lot of output, e.g. `fly -t ci containers` or watch...

Unfortunately the output sometimes scrolls past very slow in my terminals. Here's some stats on linux: 

```
root@DESKTOP-QHC4AFO:~# time fly -t ci containers 
... lots of output here
real    0m0.709s
user    0m0.078s
sys     0m0.047s
``` 

Compare that with piping the same output through `cat`
```
root@DESKTOP-QHC4AFO:~# time fly -t ci containers | cat

real    0m0.382s
user    0m0.047s
sys     0m0.063s
root@DESKTOP-QHC4AFO:~#
```

I see the same thing with Powershell, where it's even worse (measured using [Time](https://stackoverflow.com/a/19990623/125407)) : 

```
PS C:\dev\mc\meshfed-release> Time { fly -t ci containers }
Execution time: 2932 mS for  fly -t ci containers
```

Compare that to forcing buffered output through Out-Host (think: cat equivalent)

```
PS C:\dev\mc\meshfed-release> Time { fly -t ci containers | Out-Host }
Execution time: 280 mS for  fly -t ci containers | Out-Host
```

If there's such an option in the go libs that you use to write to stdout using a buffer, please enable it. Should be an easy win for performance. The cloud foundry cli appears to have the same issue as well, so it may be something systematic with go. 

* Concourse version: 3.3.2
* Deployment type (BOSH/Docker/binary): binary/docker-compose
* Infrastructure/IaaS: Meshcloud (OpenStack)

**Comment by JohannesRudolph** [comment] 2017-08-06 08:07
See also: https://stackoverflow.com/questions/13422381/idiomatically-buffer-os-stdout

**Comment by jtarchie** [comment] 2017-08-09 14:18
This seems more like a bug, rather than a feature request. Nothing seems to be broken here. It is just *slower*, correct?

**Comment by JohannesRudolph** [comment] 2017-08-09 17:00
Sorry, yes performance is a feature is a valid point

**Comment by jmelchio** [comment] 2018-02-20 15:46
@JohannesRudolph trying to recreate the issue locally in order to work on a possible fix. I'm running 3.9.0 here and I'm not seeing the difference between unbuffered and cat output when I'm timing it running on an OSX client.

Can you confirm this is still an issue for you and let us know which version you're running currently?
Can you tell me how long the list of containers is in your case?
Thx!

**Comment by JohannesRudolph** [comment] 2018-02-20 16:32
Hi, the issue seems to impact Windows much more than OS X (tried with
Powershell). I believe I traced this down to the go stdout library using
unbuffered io at the time.

**Comment by jmelchio** [comment] 2018-02-20 16:43
Hi, I can confirm that the output is unbuffered. I will try to replicate with a windows client. Thx.

**Comment by jmelchio** [comment] 2018-02-20 20:01
@JohannesRudolph I did my testing on Windows 10 Enterprise Eval (Build 1699.rs3_release.170928-1534) inside VirtualBox with two fly executables, one with, and one without buffering enabled:

Buffering does provide a minor improvement (~10-15%) when running in PowerShell but it remains slow compared to OSX and Linux performance. 
Running the fly executables in the Windows Bash shell improves things a lot; performance there is almost on par with what we see on OSX and Linux. If you are able to use this option it will give you a significant boost on Windows.

As the buffering implementation is straightforward and does not break any tests we will put the fix in and roll it out in a future release. We will be closing this item.

**Closed** 2018-02-21 16:20 UTC
Labels: fly
