### ISSUE TITLE
version: every does not always trigger every version.

### ISSUE THREAD

**Issue by jpalermo** [concourse/concourse#563] opened 2016-08-01 19:04 UTC
We have a resource fetch on a job:
```
- get: environment
  resource: building-pool
  trigger: true
  version: every
  passed: [check-pool-size-and-claim-environment]
```

We had 3 versions of this resource pass `check-pool-size-and-claim-environment`. The first one took ~50 to complete this job, and the next two resources were waiting when it was finished.

Rather than running the second version of the resource, it only ran the most recent version.

Possibly related to passed constraint.
https://concourseci.slack.com/archives/general/p1470077998003312

**Comment by vito** [comment] 2016-08-01 19:17
Do you have a way to reproduce this? Perhaps a pipeline.yml using nothing but the `time` resource so it's self-contained?

**Comment by halimacc** [comment] 2016-08-09 03:36
@vito , Hi, I have encountered the same problem, an example pipeline is [here](https://github.com/halimacc/pr-concourse-test/blob/master/pipeline.yml), just to test `version: every` with `get` from a git resource.

When adding a bunch of commits (more than 2),
job1(no `passes`) will be triggered by at most 2 commits, 
other jobs(with `passes`) will be triggered by most recent commit.

**Comment by ahelal** [comment] 2016-08-09 11:04
i have the same issue with github releases it skips some verision.

**Comment by mariash** [comment] 2016-08-23 01:14
@halimacc we could not reproduce the issue with provided pipeline. Make sure you ran at least one build. Since it will pull latest version if there is no build with that resource. If you could help us figure out what might be wrong that would be helpful. Thanks.

**Comment by halimacc** [comment] 2016-08-23 14:16
@mariash Hi, I just reproduce the issue. After the first build, I pushed 3 new commits, you can see the results at http://13.94.41.160:8080/pipelines/every-test, there're 4 versions in resource `git-concourse-test`, but there's only 3 builds triggered at `job1` and 2 builds triggered at `job2`. the pipeline file is at the [here](https://github.com/halimacc/pr-concourse-test/blob/master/pipeline.yml).

**Comment by mariash** [comment] 2016-08-23 14:25
Hi @halimac, when running a fresh pipeline `version: every` is not going to pull every commit, it will pull latest. Your job2 had builds scheduled when it did not have builds. Please try to reproduce the issue now on the same pipeline when you have some builds already. Thank you.

**Comment by mariash** [comment] 2016-08-23 17:09
@halimacc looking at this http://13.94.41.160:8080/pipelines/every-test/resources/git-concourse-test we are seeing that `46ab4` did not trigger the build which should have. Going to look into this. Thanks

**Comment by mariash** [comment] 2016-08-23 22:31
@halimacc thanks for your help, we believe we fixed this issue and fix will be in next release.

**Closed** 2016-08-24 18:03 UTC
Labels: bug
