### ISSUE TITLE
Refresh page with search does not encode spaces correctly after logout

### ISSUE THREAD

**Issue by jacky12** [concourse/concourse#5196] opened 2020-02-18 18:37 UTC
## Bug Report

Refresh page with search does not encode spaces correctly after logout

## Steps to Reproduce

In Chrome, open a tab in concourse and enter a search with spaces (i.e. "ship tile master") in order to find a pipeline. This tab's URL will now be something like `https://pks.releng.us/?search=ship%20tile%20master`.
From another tab, log out.
Go to the previous tab. By refreshing, the page will show no search results and be blank, as expected. The tab is still at `https://pks.releng.us/?search=ship%20tile%20master`.

Now log back in (using the github button) and the tab's URL will change from `https://pks.releng.us/?search=ship%20tile%20master` to `https://pks.releng.us/?search=ship+tile+master`.
The search page will refresh filling in the search box showing: "ship+tile+master", giving different search results.

## Expected Results

search box showing: "ship tile master", without the plus symbol.

## Actual Results

search box showing: "ship+tile+master" with plus symbols instead of spaces.

## Version Info

* Concourse version: 5.5.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome Version 78.0.3904.87 (Official Build) (64-bit)
* Did this used to work? no

**Comment by aoldershaw** [comment] 2020-02-21 18:03
Hi @jacky12, thanks for raising this issue. This has come up before (https://github.com/concourse/concourse/issues/4313) and is fixed in v5.7.0 by https://github.com/concourse/concourse/pull/4625.

The root cause of the issue seems to be a part of how `elm/url` (improperly) handles URLs containing a `+` - see https://github.com/concourse/concourse/issues/4313#issuecomment-544999952 if you're curious

**Closed by aoldershaw** 2020-02-21 18:03 UTC
Labels: bug
