### ISSUE TITLE
Create BOSH Smoke Tests for Containerd

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5985] opened 2020-08-13 14:43 UTC
Currently, we're seeing containerd fail on BOSH. Before deciding to remove the experimental flag from containerd, we will probably want to add some smoke tests around it to ensure it's working properly.

**Comment by muntac** [comment] 2020-08-31 15:06
When we try to deploy Concourse on BOSH with `containerd` we get a validation error stating that `CONCOURSE_GARDEN_` flags are in use as well.

This validation had been introduced recently, and it is complaining about these [three default values set](https://github.com/concourse/concourse-bosh-release/blob/d0322f2d8d646d4a7164144ee423e3fd840258fe/jobs/worker/spec#L206-L222) in the BOSH release.

`CONCOURSE_GARDEN_ALLOW_HOST_ACCESS` does not need a default value of false as the boolean will default to false when no value is provided.

`CONCOURSE_GARDEN_MAX_CONTAINERS` is set to default to 250. This is for two reasons.
1. One is historical as this is the default limit set by `garden-runc-release`. But as noted in this [blog](https://www.engineerbetter.com/blog/increasing-concourse-container-limits/) this does not apply to Concourse's usecase.

2. After 250 containers Concourse runs out of IP addresses to assign to containers. This is due to `CONCOURSE_GARDEN_NETWORK_POOL` defaulting to `10.254.0.0/22`.

This default for `CONCOURSE_GARDEN_NETWORK_POOL` is somewhat arbitrary and it would be best to update this to something higher to accommodate more containers. This should be done in the Concourse worker code instead of the BOSH release.

**Comment by scottietremendous** [comment] 2020-08-31 17:44
Some of this effort may have been completed already in this PR: https://github.com/concourse/concourse-bosh-release/pull/116

**Comment by andy-paine** [comment] 2020-09-02 13:51
You'll also need to address this FYI for `containerd` to work in BOSH https://github.com/concourse/concourse/issues/5984

**Comment by muntac** [comment] 2020-09-08 21:10
- [ ] Setting default values for network-pool and max-containers in the binary https://github.com/concourse/concourse/pull/6031
- [ ] Remove Guardian flag defaults from the BOSH release https://github.com/concourse/concourse-bosh-release/pull/121
- [ ] Fix https://github.com/concourse/concourse/issues/5984
- [ ] Create/enable smoke test with containerd for BOSH

**Comment by muntac** [comment] 2020-09-14 17:30
WIP - Rough Notes - to be updated

Setting default values for `network-pool` and `max-containers` in a way that is transparent involves exposing them in the Concourse binary's worker command.

This brings us to the common problem of making sure the check parameters job in CI for the [BOSH release](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-check-props/builds/537) and [Helm chart](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-check-helm-params/builds/352) still works.

Those jobs are trying to ensure that whatever is configurable through the binary should be configurable through the distribution (i.e. BOSH release and Helm chart). However, there are certain exceptions, which end up in two files called `ignored_in_distribution` and `ignored_in_concourse`.

Explanation of binary vs distribution vars
* The binary and distribution vars are both listed and compared to ensure they’re in sync. This ensures that features introduced in Concourse are modifiable by operators in the distribution - k8s or bosh - that they use.
* CI runs a check params job for helm and bosh to ensure this
* This check params lists the vars for the binary and corresponding distribution using the ci/tasks/scripts/check-distribution-env/diff script
* For the binary we list all the web and worker commands and filter out some commands based on a special file.
* This special file is called an “ignored_in_binary” file that exists in the corresponding distribution - concourse-chart or concourse-bosh-release
* This file is versioned i.e. is different for different versions of the chart and release
* For the distribution we get the relevant vars using a script called “list-actual” that’s different for k8s and for bosh
* For BOSH it goes through all files in the “jobs” directory and looks for items listed as “env: ENV_NAME” and lists all the ENV_NAME
* These are then filtered out using a similar special file called “ignored_in_distribution"
* For K8s the list_actual goes through everything in the “templates” directory, and lists any in the format “name: ENV_NAME”. In reality this only finds such items in the _helpers.tpl file
* It similarly filters out using an “ignored_in_distribution” in the chart repo


How K8s Tempalting works
* The “value.yml” values are used by the _helpers.tpl script to define some config lists e.g. concourse.worker.env
* These lists are then used by the template files in the templates directory e.g. worker-stateful-set and put in a specific part of the file using templating directives e.g. env:  {{- include "concourse.worker.env" . | indent 12 }}
* It’s all a bit convoluted. Maybe this is the simplest way. But my guess is that when the chart and this templating was created by community members the Concourse team adopted it and was happy that it worked.
* Over time folks have added to it to make it work but were afraid to get a holistic sense of the flow as its the last step of a issue that one might have been working on for a while.
* Those who got a sense may have thought it was best to leave it like it is.

How BOSH Templating works
* ___________
* The ignored_in_distribution of BOSH only lists Guardian variables.

Setting vs mentioning defaults in distribution:
* The README for bosh-release and chart says not to mirror the binary’s default values
* This was intended to prevent drift of behaviour between binary and distribution
* However, the README says instead to mention the default in the notes
* This documentation of the default runs into the same problem of being out of sync with the binary

Some history of max containers
* Concourse used to use the garden-runc-release instead of gdn binary directly
* The garden-runc-release defaults Guardian max-containers to 250
* After switching to gdn binary this did not default to 250 anymore and was unlimited
* The bosh-release got updated by Pivotal community members to mention the max-container limit which was set to 250 in the release
* The concourse chart never got updated to use 250 so all the folks deploying using that default to unlimited containers
* Sameer mentioned that not having a container limit can result in a “stampeding herd” problem
* This often happens during upgrading. It’s when the worker has a large number of containers coming up, is switching between the containers, but can never finish the work on any container (or finish it fast enough) to keep up with the incoming volume of workload. This causes the worker to stall and become unusable.
* Some companies have been pausing all the pipelines, spinning down the workers, upgrading, spinning back up, and unpausing pipelines to deal with this.

Principles
* Don’t use ignored_in_distribution for hacky purposes. Keep binary and distribution in sync - check-params/props will help you catch that.
* If it’s important enough to put in the distribution it’s important enough to put in the binary
* ignored_in_distribution - Unless it’s specific to the underlying technology of the distribution i.e. something that the binary can’t actually reason about
* What is the principle for including an env var in “ignored-in-concourse”?
* At the very least, `ignored-in-concourse` should look identical in BOSH release and Helm chart
* Rename "ignored-in" prefix of files to "ignore-from”. “Ignored-in” sounds like the source in question does not have these env vars whereas “ignore-from” sounds more like ignore these env vars that come from the source.


Next Steps
* Expose Guardian max-containers and network-pool in binary. Default to 250 and 10.80.0.0/16 using go-flags default parameter.
* Remove CONCOURSE_GARDEN_MAX_CONTAINERS and CONCOURSE_GARDEN_NETWORK_POOL from `ignored-in-distribution` in concourse-bosh-release
* Add maxContainers and networkPool to concourse-chart’s value.yml and _helpers.tpl

Further steps
* Remove all CONCOURSE_ variables from ignored-in-distribution of BOSH release
* Validate that ignored-in-concourse for Helm chart is as minimal as it can be
* Sync the ignored-in-concourse of the BOSH release and Helm chart. Have a new job that checks both are in sync.
* Put the principles of the ignored-in files in comments in the files. Update scripts if needed to ignore comments during comparison.

**Comment by muntac** [comment] 2020-09-15 18:02
Was the original purpose of check-params job to make sure whatever we include in the binary we add to the chart and release?

The question would then become "are the binary's flags (after filtering out ignored-in-concourse) a subset of the distribution's flags?". We would then no longer need an `ignored-in-distribution`.

**Comment by muntac** [comment] 2020-10-05 17:30
Necessary items have been covered. Waiting for CI to go green before closing issue.

**Comment by muntac** [comment] 2020-11-05 00:57
Closing as there have been successful builds - https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/bosh-smoke-containerd/builds/53

**Closed by muntac** 2020-11-05 00:57 UTC
