### ISSUE TITLE
Build step is taking few minutes to start

### ISSUE THREAD

**Issue by ezraroi** [concourse/concourse#2043] opened 2018-02-16 06:40 UTC
Hi,
we see very strange behavior, every new build step can be in the following state for few minutes before starting to run:

![image](https://user-images.githubusercontent.com/5808368/36296211-e3a39092-12f4-11e8-9ce3-b14a690e48b6.png)
 
This is making all our build very slow.. what can cause this? what is being done in this step that can take so much time?

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): 
* Infrastructure/IaaS: VM 6 cores and 16GB memory (worker)
* Browser (if applicable): Chrome
* Did this used to work?

**Comment by avanier** [comment] 2018-02-16 14:29
This is likely #1966 . This is potentially fixed by release `3.9.0`.

**Comment by vito** [comment] 2018-02-16 14:44
Also is the task `privileged`?

**Comment by ezraroi** [comment] 2018-02-16 16:10
Task is privileged... Server is binary and i have binary and docker workers.. Will upgrade to 3.9 and report

**Comment by pn-santos** [comment] 2018-02-16 16:56
We had this issue in 3.8.0 while using the `overlay` driver, in 3.9.0 switching to `btrfs` made the problem go away (and no instability recorded for the past 2 days)

**Comment by ezraroi** [comment] 2018-02-17 06:02
do you mean the `overlay` driver of the docker daemon? we use 'aufs'.

**Comment by pnsantos** [comment] 2018-02-19 21:48
no the driver you set when starting the worker (the env var `$CONCOURSE_BAGGAGECLAIM_DRIVER`)

**Comment by ezraroi** [comment] 2018-02-22 07:51
Cool, this worked!
thanks

**Comment by jama-pivotal** [comment] 2018-02-22 14:07
@ezraroi did @pn-santos tip help you? not sure if you meant to close the issue or leave it open 😕

**Comment by ezraroi** [comment] 2018-02-22 16:11
Yes it helped... Not sure if the issue needs to be closed as i think it should work fine also with other drivers... Otherwise it should be written in the docs or maybe be the default

**Comment by vito** [comment] 2018-03-19 14:07
Gonna close this as a dupe of https://github.com/concourse/concourse/issues/1404 which will be closed once we switch back to `btrfs` as the default driver.

**Closed by vito** 2018-03-19 14:07 UTC
Labels: bug, needs-investigation
