### ISSUE TITLE
concourse-worker - error - volume graph is disabled 

### ISSUE THREAD

**Issue by rabun788** [concourse/concourse#402] opened 2016-04-28 17:40 UTC
CMD:
`fly -t web watch --job hello-world/hello-world
targeting http://IP:PORT`

Response:
`initializing`
`volume graph is disabled`
`errored`

Cant find this issue anywhere..  

Dockerfile
FROM ubuntu:14.04
ENV CONCOURSE_DISTURL https://github.com/concourse/bin/releases/download
ENV CONCOURSE_VERSION 1.2.0-rc.9
RUN apt-get update && \
    apt-get install -y iptables ca-certificates aufs-tools wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    mkdir /opt/concourse && \
    mkdir /opt/concourse/bin && \
    cd /opt/concourse/bin/ && \
    wget -q https://github.com/vito/bin/releases/download/v1461709990/concourse_linux_amd64 && \
    apt-get remove wget -y && apt-get autoremove -y && \
    apt-get clean \
    mkdir /opt/concourse/conf && \
    chmod +x /opt/concourse/bin/*
WORKDIR /opt/concourse
COPY bin/concourse-worker.sh /opt/concourse/bin/
COPY sample/ ./
CMD /opt/concourse/bin/concourse-worker.sh

concourse-worker.sh

#!/bin/sh
set -e
ip=$(hostname --ip-address)
CONCOURSE_HOME=/opt/concourse
PATH=$PATH:$CONCOURSE_HOME/bin
concourse_linux_amd64 worker \
    --work-dir $CONCOURSE_HOME/worker \
    --tsa-host 172.20.232.190 \
    --tsa-port 10703 \
    --tsa-public-key host_key.pub \
    --tsa-worker-private-key worker_key

**Comment by RoboPhred** [comment] 2016-04-29 16:04
From my experiments, a concourse worker needs closer access to the server than docker is willing to give it.  The closest I have managed to get a worker running was with the "--privileged" flag, in which case I get an error generated by [overlay.go:126](https://github.com/docker/docker/blob/master/daemon/graphdriver/overlay/overlay.go#L126)

Can you share the options you are using to run that dockerfile?

**Comment by RoboPhred** [comment] 2016-04-29 17:30
The cause of this error is that guardian is not choosing a volume creator, and falls back on to the no-op method:

[noop_volume_creator.go:13](https://github.com/cloudfoundry-incubator/guardian/blob/master/gardener/noop_volume_creator.go#L13)

This happens when [GuardianCommand.wireVolumeCreator](https://github.com/cloudfoundry-incubator/guardian/blob/e24c4e280beceb1a7bcb1ec3a1209980bf47f4f7/guardiancmd/command.go#L407) has a graphRoot of "". 

Seems to be used by [GuardianCommand.Run](https://github.com/cloudfoundry-incubator/guardian/blob/e24c4e280beceb1a7bcb1ec3a1209980bf47f4f7/guardiancmd/command.go#L259), which pulls graphRoot from [GuardianCommand.Graph.Dir](https://github.com/cloudfoundry-incubator/guardian/blob/e24c4e280beceb1a7bcb1ec3a1209980bf47f4f7/guardiancmd/command.go#L164).
Interestingly this is not set as required, so perhaps guardian is failing to infer a default when concourse does not provide it?  Or is concourse failing to determine a directory and passing an empty string?

Time to dig into the concourse worker code next...

**Comment by RoboPhred** [comment] 2016-04-29 22:17
While researching this, I came across https://github.com/vito/lattice-concourse/tree/master/garden-linux-worker, which provides a functional worker inside of docker.  It is designed around using lattice, but I was able to use it for a custom docker-compose setup.

It does not use concourse/bin, but instead installs and runs a garden-linux env and announces it through the api.

https://github.com/vito/garden-linux-docker-image is also worth looking at, as it seems to be taking more care in setting up the 

Here is my docker-compose.yml
```
version: '2'
services:
  server:
    build: server/.
    ports:
      - "8080:8080"
      - "8022:2222"
    depends_on:
      - "database"
  worker:
    image: vito/garden-linux-worker
    privileged: true
    environment:
      - ATC_API_URL=http://server:8080
      - CF_INSTANCE_ADDR=worker:7777
  database:
    build: database/.
    volumes:
      - database_volume:/var/lib/postgresql/data

volumes:
  database_volume:
    driver: local
```

server/Dockerfile
```
FROM ubuntu:14.04

RUN useradd -m -s /bin/false concourse

WORKDIR /home/concourse

COPY concourse .

COPY session_signing_key .
COPY host_key .
COPY authorized_worker_keys .

RUN chown concourse * && \
    chmod a+r * && \
    chmod a+x concourse

USER concourse

ENTRYPOINT ["./concourse", "web", "--development-mode", "--session-signing-key", "/home/concourse/session_signing_key", "--tsa-host-key", "/home/concourse/host_key", "--tsa-authorized-keys", "/home/concourse/authorized_worker_keys", "--postgres-data-source", "postgres://concourse:concourse@database:5432/concourse?sslmode=disable", "--external-url", "http://YOURSITE:8080"]
```

It's worth noting that while I set up session, host, and worker keys, the worker does not have this key yet still works anyway.  I suspect this is a result of using the "--development-mode" option.
I do not know how to set up the keys in the worker, however.

**Comment by rabun788** [comment] 2016-05-02 18:19
Are you saying you were able to get the concourse-worker to work correctly using https://github.com/vito/garden-linux-docker-image ?

**Comment by RoboPhred** [comment] 2016-05-02 22:12
No, while I studied that repo I could not get it to talk to the server properly in the short time playing with it.


I am using the [lattice build](https://github.com/vito/lattice-concourse/tree/master/garden-linux-worker) by the same user, which corresponds to the docker image [vito/garden-linux-worker](https://hub.docker.com/r/vito/garden-linux-worker/).

Two env vars must be specified for this worker: ATC_API_URL (the external url), and CF_INSTANCE_ADDR (the address and port for the TTA server).

Also, "correctly" is rather strong for now.  It is running and communicating just fine when idle, but I am still working past json parse errors, which may be due to mismatched concourse versions, or just a bug in the concourse RC it is using.

**Comment by rabun788** [comment] 2016-05-10 16:52
Still doesn't work with suggested Dockerfile:

> root@124e25084107:~/scripts# ./start.sh worker {"timestamp":"1462898518.109760761","source":"worker","message":"worker.baggageclaim.fs.run-command.failed","log_level":2,"data":{"args":["bash","-e","-x","-c","\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"],"command":"/bin/bash","env":["PATH=/opt/concourse/worker/linux/btrfs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","MOUNT_PATH=/opt/concourse/worker/volumes","IMAGE_PATH=/opt/concourse/worker/volumes.img","SIZE_IN_BYTES=515141558272"],"error":"exit status 1","session":"2.1.1","stderr":"+ '[' '!' -e /opt/concourse/worker/volumes.img ']'\n+ touch /opt/concourse/worker/volumes.img\n+ truncate -s 515141558272 /opt/concourse/worker/volumes.img\n++ losetup -j /opt/concourse/worker/volumes.img\n++ cut -d: -f1\n+ lo=\n+ '[' -z '' ']'\n++ losetup -f --show /opt/concourse/worker/volumes.img\nlosetup: cannot find an unused loop device\n+ lo=\n","stdout":""}}
failed to set up volumes filesystem: exit status 1

**Comment by vito** [comment] 2016-05-10 18:54
@rabun788 That last error does not look related to the one in the title. Make sure you've got loopback devices available in your docker image; we'll need one for setting up the `btrfs` image used for volume management. Alternatively you could use `btrfs` as the host's graph driver.

The original issue reported is missing the critical information which is the configuration for the `hello-world` job.

**Comment by muv** [comment] 2016-05-14 23:12
I'm also trying to run the worker in Docker and getting similar (but a bit different) error also mentioning loopback device:

> {"timestamp":"1463137375.761673212","source":"worker","message":"worker.baggageclaim.fs.run-command.failed","log_level":2,"data":{"args":["bash","-e","-x","-c","\n\t\tif [ ! -e $IMAGE_PATH ] || [ \"$(stat --printf=\"%s\" $IMAGE_PATH)\" != \"$SIZE_IN_BYTES\" ]; then\n\t\t\ttouch $IMAGE_PATH\n\t\t\ttruncate -s ${SIZE_IN_BYTES} $IMAGE_PATH\n\t\tfi\n\n\t\tlo=\"$(losetup -j $IMAGE_PATH | cut -d':' -f1)\"\n\t\tif [ -z \"$lo\" ]; then\n\t\t\tlo=\"$(losetup -f --show $IMAGE_PATH)\"\n\t\tfi\n\n\t\tif ! file $IMAGE_PATH | grep BTRFS; then\n\t\t\tmkfs.btrfs --nodiscard $IMAGE_PATH\n\t\tfi\n\n\t\tmkdir -p $MOUNT_PATH\n\n\t\tif ! mountpoint -q $MOUNT_PATH; then\n\t\t\tmount -t btrfs $lo $MOUNT_PATH\n\t\tfi\n\t"],"command":"/bin/bash","env":["PATH=/var/lib/concourse/work/linux/btrfs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","MOUNT_PATH=/var/lib/concourse/work/volumes","IMAGE_PATH=/var/lib/concourse/work/volumes.img","SIZE_IN_BYTES=16035790848"],"error":"exit status 1","session":"2.1.1","stderr":"+ '[' '!' -e /var/lib/concourse/work/volumes.img ']'\n++ stat --printf=%s /var/lib/concourse/work/volumes.img\n+ '[' 16035790848 '!=' 16035790848 ']'\n++ cut -d: -f1\n++ losetup -j /var/lib/concourse/work/volumes.img\n+ lo=\n+ '[' -z '' ']'\n++ losetup -f --show /var/lib/concourse/work/volumes.img\nlosetup: /var/lib/concourse/work/volumes.img: **failed to set up loop device: No such file or directory**\n+ lo=\n","stdout":""}}

@vito I feel the answer is in your words

> Make sure you've got loopback devices available in your docker image; we'll need one for setting up the btrfs image used for volume management. Alternatively you could use btrfs as the host's graph driver.

Perhaps something is wrong with my Docker image or host system but I lack knowledge to figure out what. I'd be thankful for some links how I could "make some loopback devices available" in my image or "use btrfs as the host's graph driver".

**Comment by vito** [comment] 2016-05-16 14:11
@muv something like this: https://github.com/concourse/concourse/blob/9bb58ca099aab471521edd819584594778e38a5e/ci/scripts/baggageclaim#L20-L23

**Comment by muv** [comment] 2016-05-31 11:33
@vito thanks, turned out I used kernel < 3.19. The `failed to set up loop device: No such file or directory` is gone after running via `docker-machine`, which provides a VM with some 4.x kernel.

Now I'm investigating `insufficient subnets remaining in the pool` happening after every dozen builds.

**Comment by vito** [comment] 2016-06-03 15:59
Closing this for now since it's really just led into other issues which should be opened on their own.

The `volume graph is disabled` error means one of two things:

1. A task specified `image: docker:///` or `image: /foo/bar` (less likely)
2. A task did not specify an `image` at all.

Tasks should be using [`image_resource`](https://concourse.ci/running-tasks.html#image_resource) instead. This is an intentional change for the binary distribution; `image_resource` was introduced a while ago and `image` isn't worth supporting (it leads to disk usage, UX, and portability headaches).

**Closed by vito** 2016-06-03 15:59 UTC
Labels: unscheduled

**Comment by renier** [comment] 2016-11-08 14:52
@vito 

> The volume graph is disabled error means one of two things:
> A task specified image: docker:/// or image: /foo/bar (less likely)
> A task did not specify an image at all.
> Tasks should be using image_resource instead.

Why does the documentation [say that image_resource is optional](https://concourse.ci/running-tasks.html#image_resource) then? Is it?

**Comment by vito** [comment] 2016-11-08 18:27
@renier It is optional for platforms other than `linux`.

**Comment by JokerQyou** [comment] 2017-01-27 15:57
Sorry to bother you guys, but I'm still seeing this error when following the docker-compose tutorial [here](https://concourse.ci/docker-repository.html) with the hello-world pipeline guide [here](https://concourse.ci/hello-world.html). I've checked the docker images (as follows).

![image](https://cloud.githubusercontent.com/assets/1465267/22377292/44ce8c1a-e4ec-11e6-9756-6f931b3ffd95.png)

I'm using aufs for host system. And currently I don't have any clue on dealing with this issue. Can anyone give me some hints about where to start? Thanks.

**Comment by fbiville** [comment] 2017-09-21 08:03
@vito maybe the error message could be a bit more explicit
instead of "volume graph is disabled" what about:

> Error occurred because either:
> 1. A task specified image: docker:/// or image: /foo/bar
> 2. A task did not specify an image at all.

**Comment by EugenMayer** [comment] 2017-11-05 13:39
I ran into exact the same issue and as @fbiville mentioned i was totally miss guided first, then happened to notice that it is just the missing image_resource
