### ISSUE TITLE
Status in favicon

### ISSUE THREAD

**Issue by pronoiac** [concourse/concourse#599] opened 2016-08-22 17:48 UTC
Could we change the favicon based on the status (yellow, green, red) of a given job? It might help if we're trying to keep tabs (sorry for the pun) on a lot of jobs in a pipeline.

**Comment by vito** [comment] 2016-08-22 17:52
yep! dupe of https://github.com/concourse/concourse/issues/243 though - mind :+1:'ing it?

**Closed by vito** 2016-08-22 17:52 UTC
Labels: unscheduled
