### ISSUE TITLE
Lots of task output can freeze the UI

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#6884] opened 2021-04-14 18:33 UTC
## Summary

I accidentally added a trace level output to one task. The web ui froze and firefox suggested via overlay bar to terminate the tab that is slowing down the browser.

## Steps to reproduce

Create the simplest of all tasks and print ~50MB of log info to `stdio` from within a task.

## Expected results

Load the logs lazily at the viewable range level.

## Actual results

All the logs are loaded in one giant block, before displaying and slowing down the entire browser.

## Triaging info

* Concourse version: 7.1
* Browser (if applicable): firefox 87.0 
* Did this used to work? not sure :shrug:

**Comment by clarafu** [comment] 2021-04-15 17:49
@drahnr Did you see that the web UI freezing was after the build output loaded? Or did it freeze trying to load the build output? 

If it did freeze trying to load the build output, I think one thing that I noticed after 7.0.0 is that the query to fetch the build events from the database has gotten slower. This is because the `OR build_id_old = $1 ` was added to the query so it is not able to just use an index to fetch the rows.

https://github.com/concourse/concourse/blob/0ce9e3dd6fbdf2b5226c1927800d3ec2f45d701a/atc/db/build_event_source.go#L120-L125

That being said, I don't think this is the biggest reason behind the freezing of the UI and just something I wanted to note down. The freezing is probably mostly caused by trying to stream all those logs to the web UI.

**Comment by taylorsilva** [comment] 2021-04-15 19:55
Aidan is the real expert in this area, but the browser may also be chocking on trying to render the terminal output. Not sure how slow that part of rendering generally makes things. You could compare by streaming the output to fly using `fly watch`. If the browser hangs for longer than it takes fly to stream the output then that might be the cause; browser slow at rendering terminal output.

**Comment by drahnr** [comment] 2021-04-16 06:10
The output is _very_ snappy in the terminal with `fly trigger-job ... -w`

**Comment by drahnr** [comment] 2021-04-16 06:27
This is a bug in `cargo-spellcheck`, it does not handle glob patterns in workspaces just yet https://github.com/drahnr/cargo-spellcheck/issues/166

**Comment by drahnr** [comment] 2021-04-16 07:50
Try `0.8.0-beta.2` (does _not_ include a .aff or .dic yet) which contains a fix for https://github.com/drahnr/cargo-spellcheck/issues/166

**Comment by drahnr** [comment] 2021-04-16 14:42
It also causes `chromium`s tab to error with code `256`

I.e. https://ci.spearow.io/teams/spearow/pipelines/juice/jobs/pr-example-mnist-image-multiclass-classification-test-fedora-cuda/builds/8

**Comment by drahnr** [comment] 2021-04-18 08:45
`7.2.` emits the same behaviour.

**Comment by aoldershaw** [comment] 2021-04-19 21:39
It's unfortunate, but with the way we store build logs in the DB, this can't just be fixed with some changes to the UI - some discussion here: https://github.com/concourse/concourse/issues/3521#issuecomment-476856832. While #3521 isn't exactly around the UI freezing - just general slowness - I'm going to close this as a duplicate since its the same cause

**Closed by aoldershaw** 2021-04-19 21:39 UTC
Labels: bug
