### ISSUE TITLE
Automatically Setting Pipelines - From Mount Point / Directory

### ISSUE THREAD

**Issue by DandyDeveloper** [concourse/concourse#3971] opened 2019-06-04 04:48 UTC
# What challenge are you facing?
I'm deploying our Concourse server over Kubernetes using the helm chart, with this I'm also automatically generating all the pipeline files and writing them to a configmap. 

Right now, there is no way for me to set the pipeline without using Fly, outside of the container. 

## What would make this better?
Having some sort of option in the Concourse configuration like "pipeline-mount" would be ideal to just declare a mount point to apply all the pipelines.

It would save us having to manually call fly for every pipeline file, and allow us to automate pipeline updates through the Concourse helm chart, 

This is also harder to automate as the fly binary isn't available inside any docker images, or concourse container images. 

## Are you interested in implementing this yourself?
Yes, however I am not familiar with the pipeline registration outside of fly? If this is possible, I can do it myself with some direction.

**Comment by DandyDeveloper** [comment] 2019-06-04 04:54
Can https://github.com/concourse/concourse-pipeline-resource achieve what I'm trying to do?

**Comment by marco-m** [comment] 2019-06-04 18:25
Hello, this is a mix between a question and a duplicate of #1200. Yes, concourse-pipeline-resource can help you achieve what you are trying to do. For questions could you please use https://discuss.concourse-ci.org/ ?

Closing as a dup of #1200.

**Closed by marco-m** 2019-06-04 18:25 UTC
Labels: enhancement
