### ISSUE TITLE
Web UI times out when opening builds with large log outputs

### ISSUE THREAD

**Issue by Donnerbart** [concourse/concourse#6722] opened 2021-03-24 12:18 UTC
## Summary

When I try to open a build with a large log output in the Web UI, the page doesn't load or even crashes the browser tab.

The build itself was executed and I can download the logs via `fly`, e.g.
```bash
fly -t java watch -j java-tracer.nightly-it/build 44 > ~/java-tracer-its.log
```

## Steps to reproduce

I don't have the capacity to setup a demo reproducer right now, but the steps would be:

1) Create a pipeline job with a log output of ~200 MB.
2) Execute the build
3) Open the build in the Web UI like https://ci.example.com/teams/my-team/pipelines/my-pipeline/jobs/build/builds/1

## Expected results

Show at least a truncated version of the log output with the option to load the complete log (like Jenkins does).

## Actual results

![Screenshot from 2021-03-24 13-07-10](https://user-images.githubusercontent.com/4196298/112308919-fa7cb700-8ca2-11eb-813f-3c74d6e0b200.png)

![Screenshot from 2021-03-24 13-10-00](https://user-images.githubusercontent.com/4196298/112308923-fcdf1100-8ca2-11eb-90fb-0c81694f8a46.png)

## Triaging info

* Concourse version: v6.7.3
* Browser (if applicable): Google Chrome 89.0.4389.90 (Official Build) (64-bit)
* Did this used to work? Never

**Comment by aoldershaw** [comment] 2021-04-07 00:13
Going to close this as a duplicate of #3521. For some clarification as to why it's not trivial to just truncate the build log, see https://github.com/concourse/concourse/issues/3521#issuecomment-473441314

**Closed by aoldershaw** 2021-04-07 00:13 UTC
Labels: bug
