### ISSUE TITLE
setuid root executables lose sticky bit above Concourse version 3.0.1

### ISSUE THREAD

**Issue by thardeck** [concourse/concourse#1569] opened 2017-09-07 14:51 UTC
The setuid issue as described in #802 is not fixed yet. We are experiencing this issue with every Concourse version after 3.0.1.

The issue happens with baggeclain btrfs but also overlayfs. I have reproduced it with btrfs and Concourse 3.4.1 and also in the Concourse Lite Vagrant Box 3.2.1 which uses overlayfs I suppose.

Concourse Lite 3.4.1 had DNS issues so I could not test it there.

This is the error message:

```
=== Configuring 'base_debootstrap' stage ===
== Started Thu Sep  7 14:41:07 UTC 2017 ==
sudo env  /mnt/stemcells/null/null/ubuntu/build/build/stages/base_debootstrap/config.sh /mnt/stemcells/null/null/ubuntu/build/build/etc/settings.bash 2>&1
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

For help with stemcell building, see: <https://github.com/cloudfoundry/bosh/blob/master/bosh-stemcell/README.md>

rake aborted!
Failed: 'sudo env  /mnt/stemcells/null/null/ubuntu/build/build/stages/base_debootstrap/config.sh /mnt/stemcells/null/null/ubuntu/build/build/etc/settings.bash 2>&1' from /tmp/build/e1bf2b15/src, with exit status 256

 sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set/home/ubuntu/.gem/ruby/2.3.1/gems/bosh-core-1.3262.24.0/lib/bosh/core/shell.rb:52:in `report'
```

The issue can be reproduced with this manifest. It works fine in 3.0.1 but no version above.
```
---
jobs:
  - name: build-os-image-ubuntu-trusty
    serial_groups: [builds]
    plan:
      - aggregate:
        - get: src
          trigger: true
        - get: ci
          trigger: true
      - task: build-os-image
        file: ci/tasks/build-os-image-ubuntu-centos.yml
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      ubuntu
          OPERATING_SYSTEM_VERSION:   trusty

resources:
  - name: ci
    type: git
    check_every: 30m
    source:
      uri: https://github.com/SUSE/bosh-linux-stemcell-builder-ci.git
      branch: master

  - name: src
    type: git
    check_every: 30m
    source:
      uri: https://github.com/SUSE/bosh-linux-stemcell-builder.git
      branch: opensuse_stemcell_with_patched_go_agent
```

**Comment by jtarchie** [comment] 2017-09-07 15:01
@thardeck can you follow with what type of workers you have?

**Comment by thardeck** [comment] 2017-09-07 15:10
@jtarchie 
Our main setup got three `large` workers with btrfs running on OpenStack.

Since I did not wanted to recreate the whole setup again I have tried to setup Concourse Lite 3.4.1 but the vm could not reach github.com because of DNS issues so I used the Vagrant Box with Concourse 3.2.1 where I was able to reproduce the issue.

**Comment by vito** [comment] 2017-09-07 15:40
There are a lot of version numbers and scenarios being thrown around here so it may be worth clarifying the timeline of breakage on our end:

The root of this problem will be cases where we have to `chown` files, as that's when the bit is lost. The only time we need to `chown` is when using a *privileged* file tree for an *unprivileged* container, or an *unprivileged* file tree with a *privileged* container (i.e. vice-versa).

In versions <=3.0.1, all fetched resources were privileged, so we only performed the `chmod`ing when they were used for an unprivileged task. All resources were privileged, so that was the only case.

As of 3.1.0+, all resources are now *un*privileged by default, and we make sure all fetched resources are unprivileged (even if fetched by a privileged resource, e.g. `docker-image`). This change was made as part of #1045 because `overlay` has a performance overhead to `chmod`ing, and unprivileged containers are more typical, so it's best to have the data-at-rest be optimized for their use case. This introduced an initial regression: all `docker-image` fetched images were now `chmod`ded, to become unprivileged, so even tasks that were privileged before now broke.

As of 3.4.0+, we now preserve the `setuid` bit by restoring it after the `chmod`. So that specific case should be fixed: https://github.com/concourse/baggageclaim/commit/344fe25fe49a3bb0b2d93105b1a6f3efc8eb4626

@thardeck What would really help is following the lifetime of the `setuid` files. For example: do they come from a `rootfs`, from a `get`, or from a task's output? Does the file have to be transferred across workers (e.g. due to being fetched on worker A but transferred to worker B)?

That being said, I don't think it's particularly interesting to test versions [3.1.0,3.4.0) as we know there was a regression that was fixed. It would be a shame if there are actually two different ways that your pipeline exercises `setuid` breakage and we've fixed one but have no way of knowing that it's actually a new case that we just haven't covered yet, as opposed to our fix in 3.4.0 being completely ineffective.

Thanks for the repro pipeline - we can at least try that ourselves if you can't get DNS working. (Though I'd like to see why that's failing - separate issue perhaps?)

**Comment by thardeck** [comment] 2017-09-20 09:02
One of the issues we also encountered are "sudo env" calls from Groundcrew to configure an http proxy which are most likely run before the build.sh is executed.

**Comment by thardeck** [comment] 2018-02-12 14:36
Using btrfs as baggageclaim driver fixes the issue for us.

I have heard that the bosh stemcell pipeline also uses btrfs workers to build the stemcell so I have switched from the default Overlayfs and it works for us now with Concourse 3.8.0.

**Closed** 2018-03-08 19:04 UTC
