### ISSUE TITLE
Local users deleted after upgrade 4.1.0 to 4.2.1

### ISSUE THREAD

**Issue by sshuvaev** [concourse/concourse#2828] opened 2018-11-19 19:44 UTC
## Bug Report

After upgrade from 4.1.0 to 4.2.1 all local users gone from concourse. Just one user concourse present. When I'm try to add my local users to 4.2.1 user concourse disappeared.

## Steps to Reproduce

1. Up 4.1.0 from docker-compose:
version: '3'

services:
  pgsql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: concourse
      PGDATA: /database
    volumes:
      - ./pgdata:/database

  concourse-web:
    image: concourse/concourse:4.1.0
    links: [pgsql]
    command: web
    depends_on: [pgsql]
    ports:
      - "127.0.0.1:8080:8080"
      - "0.0.0.0:2222:2222"
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_ADD_LOCAL_USER: concourse:123
      CONCOURSE_MAIN_TEAM_LOCAL_USER: concourse
      CONCOURSE_EXTERNAL_URL: https://example.com
      CONCOURSE_POSTGRES_HOST: pgsql
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: concourse
      CONCOURSE_POSTGRES_DATABASE: concourse
2. Add user: docker exec <container> concourse web --add-local-user user1:password
3. Check users: 
docker exec -it <container> bash
psql -U concourse -d concourse
select * from password; 
4. Stop concourse: docker-compose down
5. Up 4.2.1 from docker-compose:
version: '3'

services:
  pgsql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: concourse
      PGDATA: /database
    volumes:
      - ./pgdata:/database

  concourse-web:
    image: concourse/concourse:4.2.1
    links: [pgsql]
    command: web
    depends_on: [pgsql]
    ports:
      - "127.0.0.1:8080:8080"
      - "0.0.0.0:2222:2222"
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_ADD_LOCAL_USER: concourse:123
      CONCOURSE_MAIN_TEAM_LOCAL_USER: concourse
      CONCOURSE_EXTERNAL_URL: https://example.com
      CONCOURSE_POSTGRES_HOST: pgsql
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: concourse
      CONCOURSE_POSTGRES_DATABASE: concourse
6. Check users: 
docker exec -it <container> bash
psql -U concourse -d concourse
select * from password;

## Expected Results

Users persist in new version of concourse
Can add local user to concourse

## Actual Results

Just one user persist in concourse.
Can't add another user to concourse

## Additional Context

Also I'm trying to add other local users in 4.2.1 concourse: 
docker exec <container> concourse web --add-local-user user1:password
After that step user concourse disappeared and just one user user1 persist in concourse db.

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: -
* Browser (if applicable): -
* Did this used to work? No

**Comment by xtremerui** [comment] 2018-11-19 22:30
Your step 2 won't work as this command is actually trying to run another concourse in the same container, which will try to start concourse with only one user you give (user1) and will change the DB auth. But it will fail for sure since the address is already token. Refer to https://github.com/concourse/concourse/issues/2788

You can not add a local user while concourse is running, instead you would need to stop concourse and start it with a **LIST** of local users, which is also the only source of truth of concourse local users EVERY time it starts. There is no data migration expected to happen in this case. This is expected behavior.

**Comment by dober** [comment] 2018-11-19 23:42
>Your step 2 won't work as this command is actually trying to run another concourse in the same container, which will try to start concourse with only one user you give (user1) and will change the DB auth. But it will fail for sure since the address is already token. Refer to #2788

Nope, it will add user, but notify you about another instance is running. It reproducible

Problem is still exist. If you down/up docker container with ATC you will loose all users in password table.
Works only on 4.1.0 as expected

**Comment by dober** [comment] 2018-11-19 23:55
@xtremerui btw  you closed  same issue about month ago [#2662](https://github.com/concourse/concourse/issues/2662)

**Comment by xtremerui** [comment] 2018-11-20 02:46
@dober I did mention running that docker command `will change the DB auth` though I might not be clear enough. That means the command will do exact what you said "flushes all my local users" in the `password` table if no exiting local user is provided in auth config.

And the reason for that is at here
https://github.com/concourse/skymarshal/blob/30842c3e14d692cfe03c324f98f8a15a5b430a54/dexserver/dexserver.go#L86-L121
It is merged in PR https://github.com/concourse/skymarshal/pull/6. You can find entire context there.

For the case to make it work, in the docker file, one needs to include all local users that have added to concourse by using MULTIPLE `--add-local-user` when concourse starting up, then it will look for existing users first and add new. The way that @sshuvaev  just provide one new local user will certainly make it think there is no old local users and thus "flush the whole table".

And here I would like to make it clear again that adding local user programmatically is not expecting ATM. I think it is well explained here https://github.com/concourse/concourse/issues/2788#issuecomment-438727673

In the document that @sshuvaev posted, it is not clear that it can only used when starting the concourse. However, in its parent block https://concourse-ci.org/install.html#section_auth-config it does mention that "An operator will need to provide the following information to concourse web **upon startup**", it **never** tells you that you can run any web command to a running concourse.

I hope this helps.

**Comment by sshuvaev** [comment] 2018-11-20 09:00
![image](https://user-images.githubusercontent.com/44865321/48761203-1cbc2f80-ecb9-11e8-889c-6c50cbd1c2f4.png)

@xtremerui please look at screenshot
I'm down 4.2.1 (with last created user test1) then bring up 4.1.0 and run command --add-local-user.
Then connect to postgres and select from password.
There 3 users:
test1 - last created in 4.2.1
concourse - created from docker-compose.yml
myuser - created in 4.1.0 by command from documentation

In 4.1.0 I'm can add users with working concourse. But in 4.2.1 you say that no way to add local user on fly. Ok, looks like where one way to me - add all my local users to compose and try to upgrade from 4.1.0 to 4.2.1
But in my opinion that is no good way to update/upgrade app with flushing users data stored in DB.
For example, I'm update postgresql db from 4.1 to 4.2 and some data in db disappeared. I'm asking postgresql whats happened and they say me "don't worry, be happy, this is expected behavior"
This is discouraged me.

**Comment by dober** [comment] 2018-11-20 10:46
Anyway its weird
Why set-team --team-name is persistent in db and It needn't add it every startup?

**Comment by marco-m** [comment] 2018-11-20 11:32
As a happy Concourse operator, I agree with @xtremerui. Again, the rationale is expressed both here and in #2788. I would like also to point out that Concourse is a free and open source tool. I can understand frustration (and it happens to me too :-), but venting frustration at developers that give me free tools is not productive for anybody involved.

**Comment by pivotal-jwinters** [comment] 2018-11-20 14:56
As both @xtremerui and @marco-m have pointed out this is [expected behaviour](https://github.com/concourse/concourse/blob/master/skymarshal/dexserver/dexserver.go#L111-L134). `--add-local-user` is not a sub command, its designed as a mechanism to seed the system with users. If you would like to add multiple users to concourse this is possible, you just need to provide the `--add-local-user` flag multiple times. 

```
concourse web ... \
  --add-local-user test1:test1 \
  --add-local-user test2:test2 \
  --add-local-user test3:test3
```

@sshuvaev There was a bug in 4.1.0 that introduced the behaviour you were experiencing, however this was unintended.

**Closed by pivotal-jwinters** 2018-11-20 14:56 UTC
