### ISSUE TITLE
Stemcell 3541.2 gives permission denied on creation of a container

### ISSUE THREAD

**Issue by pivotal-norm** [concourse/concourse#2035] opened 2018-02-14 18:11 UTC
Hi there!

We just tried deploying concourse `3.8.0` with multiple versions of `garden-runc` to gcp on stemcell `3541.2`. There was a `permission denied` issue on creation of any container. It manifested itself with resource boxes going orange with the following error message as per attachment.

![image](https://user-images.githubusercontent.com/35970477/36220445-de04231e-1177-11e8-931c-3c24139add1f.png)

Rolling back to the older stemcell has resolved the issue.

**Comment by vito** [comment] 2018-02-14 18:12
Duplicate of https://github.com/concourse/concourse/issues/2032.

**Closed by vito** 2018-02-14 18:12 UTC
