### ISSUE TITLE
fly execute --inputs-from does not support custom resource types

### ISSUE THREAD

**Issue by talset** [concourse/concourse#1148] opened 2017-05-10 10:28 UTC
Hi there!

# Bug Report

I tried to use ```fly execute --inputs-from ```.

Here is a part of my pipeline jobs definition
```
  - name: extract-data
    plan:
      - get: vault
        params:
          paths:
            - secret/foo
        outputs:
          - name: vault
      - task: extract-data
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: radial/busyboxplus
              tag: latest
          inputs:
          - name: vault
          run:
            path: /bin/sh
            args:
            - -c
            - |
              ls .
```

Here is my vault resource definition

```
- name: vault
  type: vault
  source:
    url: https://vault.foo.io
    expose_token: true
    role_id: foo
    secret_id: bar
    auth_method: AppRole
    paths:
      - secret/foo
```

If I run my pipeline from concourse UI it works perfectly.

So I created a builder.yml containing my task to execute with fly

```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: radial/busyboxplus
    tag: latest

inputs:
- name: vault

run:
  path: /bin/sh
  args:
  - -c
  - |
    ls .
```

How I execute this builder.yml

```
fly -t test execute --config builder.yml --inputs-from mypipeline/extract-data
executing build 8067
no workers satisfying: resource type 'vault'

available workers: 
  - platform 'linux'
  - platform 'linux', tag 'demo'
  - platform 'linux'
errored
```

As you can see "no workers satisfying: resource type 'vault'".
To validate my work, I created a s3 resource on the same way and it works. Any idea why I am not able to use vault resource ?

* Concourse version: 2.7.4
* Deployment type: docker

**Comment by cwinkler** [comment] 2017-05-10 10:48
There is no built-in vault resource. You need to define it.

    resources_types:
    - name: vault
      type: docker-image
      source:
        repository: docurated/concourse-vault-resource

**Comment by talset** [comment] 2017-05-10 10:54
Sorry I did not mentioned this point, but yes my resource type is declared exactly like you said.

It works perfectly in my pipeline, but not with the fly execute

**Comment by vito** [comment] 2017-05-10 11:40
Re-worded a bit to pinpoint the cause. I'm not sure when we'll get to this ourselves but it's at least a known issue. It may be something PR-able, so I'm going to place it in the Help Wanted milestone. It would probably entail adding a set of resource types to the `POST /api/v1/builds` endpoint's payload.

**Comment by talset** [comment] 2017-05-11 14:17
linked to https://github.com/concourse/concourse/issues/318

**Comment by vito** [comment] 2017-05-11 14:45
Cool, I'll close this and update the other with more direction for a PR.

**Closed by vito** 2017-05-11 14:45 UTC
Labels: enhancement
