### ISSUE TITLE
Testflight/Watsjs fail with 'no workers'

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2719] opened 2018-10-23 13:48 UTC
## Bug Report

Lately there have been a bunch of failures in our `testflight` and `watsjs` jobs in our [new pipeline](https://ci.concourse-ci.org/teams/main/pipelines/concourse).

Here are a few samples:

* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/137
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/135
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/131
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/129
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/128
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/120
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/119
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/118
* https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/115
* ...and many more! (to be honest it probably won't help to look at'em all)

The `watsjs` job also appears to show this now and then, though it's less obvious, and it's less frequent, probably because `watsjs` completes much faster. The `testflight` builds that fail only fail after a certain amount of time.

## Steps to Reproduce

A few engineers have claimed to have seen this locally, so just try:

```
# in concourse repo
docker-compose up
ginkgo -nodes=7 ./testflight
```

## Expected Results

The tests should pass consistently.

## Actual Results

The worker appears to just exit after a certain amount of time. I didn't see any logs indicating why. The `guardian` logs indicated a normal shutdown.

My hunch is that it's receiving `os.Interrupt` from the Ifrit `grouper.NewParallel` bit [here](https://github.com/concourse/concourse/blob/master/bin/cmd/concourse/worker.go#L121), indicating that one of the sibling processes exited. (But why?)

## Additional Context

Investigation also showed that the container count on the single worker climbed super high, all the way up to 290, before ever going down. It looked like the sweeper wasn't running nearly as often as it should. I just ran the tests locally with 7 nodes and a few failed with `insufficient subnets remaining in the pool`.

Maybe the worker stalled under so much load? The heartbeat interval is set to 5 seconds, so it would only take 10 seconds for the worker to auto-stall, and the `docker-compose.yml` marks the worker as ephemeral, so it would disappear instead of stalling. This would cause the binary to exit (similar to `concourse retire-worker`).

## Version Info

* Concourse version: dev
* Deployment type (BOSH/Docker/binary): Docker (possibly others?)
* Infrastructure/IaaS: n/a
* Browser (if applicable): n/a
* Did this used to work? yes?

**Comment by xtreme-sameer-vohra** [comment] 2018-10-24 15:32
Increasing the load to `14 nodes` we were able to reliably reproduce the issue locally on a 32GB i5 Mac.

Dropping the `- CONCOURSE_EPHEMERAL=true` flag in `docker-compose.yml` results in test failures, however, the worker doesn't disappear. So, most likely it was the beacon process that was exiting when the `tsa` was shutting down the connection when worker is marked as stalled.

We are going to update the worker so we can more clearly observe which process dies that initiates a shutdown to make debugging easier in the future.

**Comment by jama-pivotal** [comment] 2018-10-29 18:33
This turned out to be a combination of load, aggressive heartbeat intervals, and ephemeral workers.

**Comment by topherbullock** [comment] 2018-11-20 19:08
11/92 "no workers" failures for a periodic job. Seems like this is still a possible flake.

**Comment by vito** [comment] 2018-11-20 20:23
That was due to a gdn upgrade - the worker failed to start because we were
specifying a `--graph` flag which was removed from gdn.

**Comment by cirocosta** [comment] 2018-11-23 15:56
Oh, interesting, just saw the commit here (https://github.com/concourse/concourse/commit/a84adb6b274620ffec0da2bc4eba04d94796b1a2).

It looks like it keeps happening from time to time thought. Getting into the task revealed these logs from `docker logs`: https://gist.github.com/cirocosta/5df3bce2f5c4ecbd637a81aa25cf142e

Looks like it's indeed garden having some issues - before `exit`ing, we can see a bunch of these:

```
{"timestamp":"1542987435.964878559","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/378d078c-60cf-478f-7663-24abc49739f4: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.965311050","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/519b1f3c-5751-456d-5463-b041168a7d1d: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.965763807","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/676e6173-717f-4f3e-6d22-19d0338d261c: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.966211796","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/026541d0-be7a-447f-739e-086601916609: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.966638565","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/f12074f5-2f47-4fda-609b-f6bee0e20866: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.967079163","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/a980f5c5-6231-4f7f-656b-6ec614fdbb96: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.967515230","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/aed0e646-f7eb-4615-724b-553ddb32d81d: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.967954874","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/63b59310-0072-44d1-69fd-98002db9c3aa: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.968384981","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/65fdf6f2-4b33-45b5-62f1-1391f94f6c18: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.968846083","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/85b5faef-387c-4cee-5b49-a4606e572920: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.977852345","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/2c6835ca-a113-469b-5fca-9d6627042d2f: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.978485346","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/56891462-eec3-4168-4cb6-2fb422606a73: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.978944778","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/6a77d6c2-1d02-4063-47b6-d1c65eaaa985: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.979389429","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/49771447-bfca-4691-4862-002adde20dd1: dial tcp 0.0.0.0:7777: connect: connection refused","session":"12.4"}}
{"timestamp":"1542987435.979830265","source":"worker","message":"worker.sweeper-runner.tick.failed-to-destroy-container","log_level":2,"data":{"error":"Delete http://api/containers/6d909435-baae-4528-5cbb-21175302cb5f: dial tcp 0.0.0.0:7777: connect: 
```

thx!

**Comment by ddadlani** [comment] 2019-05-29 15:23
Have we seen this happening recently? Does this still need some work?

**Closed** 2019-05-29 15:25 UTC
Labels: bug, flake, rejected
