### ISSUE TITLE
Clicking a resource or job in the UI does not navigate in Chrome on Windows

### ISSUE THREAD

**Issue by zmb3** [concourse/concourse#1996] opened 2018-01-31 18:28 UTC
Installed Concourse 3.8.0 on Azure recently and some of the users with Windows laptops have noticed that they can't click a job or resource to navigate to the next page.

When they hover over the box, the cursor turns into the I-bar that you typically see when a text box is focused. The workaround is to click the box once (which doesn't appear to do anything) and then press <kbd>enter</kbd>.

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: Azure
* Browser (if applicable): Chrome
* Did this used to work? Not sure

**Comment by labrown** [comment] 2018-02-06 05:28
Seeing the same behaviour with 3.8.0 in Chrome Version 63.0.3239.132 (Official Build) (32-bit)

Workaround works.

**Comment by jama-pivotal** [comment] 2018-02-07 01:18
Interesting. We've noticed similar behaviour on our Macs  running chrome where the cursor turns into an I-bar...but in our case you can still click in. I'll have to make sure to cross-check on Windows if our fix to #1978 fixes this issue as well. Will report back

**Comment by aeijdenberg** [comment] 2018-02-08 04:05
See also https://github.com/concourse/concourse/issues/1785 and https://github.com/concourse/concourse/issues/1999.

I also have this issue from one of my two desktops, but not the other. They are both running Chrome on Mac - and I believe the latest version (of both OS and browser), and they share the same Chrome profile, so any extensions (which I don't think I have any installed) are minimal.

I am able to get to the job by using the "tab" key, and eventually "return" to "click" it.

**Comment by jama-pivotal** [comment] 2018-02-21 15:58
@zmb3 @labrown or @aeijdenberg could you try clicking around on ci.concourse.ci in your Windows boxes to see if it works? I just tested it on our VMs and it looks like #1978 fixed the issue, but wanted to make sure ya'll see it fixed

**Comment by labrown** [comment] 2018-02-21 16:33
@jama-pivotal Sorry, no joy.  Just went there and tried several resources and jobs.  None of them work right.  I still have to "click and press Enter" to get into them.  This happens on both my work laptop and personal desktop (where I'm entering this comment).

If I double-click a resource or job I get a "zoom in" action.  Maybe that helps track down what's going on.

Personal desktop: Version 63.0.3239.132 (Official Build) (64-bit)
Work laptop: Version 63.0.3239.132 (Official Build) (32-bit)

**Comment by jama-pivotal** [comment] 2018-02-21 17:07
Thanks for testing it out so quickly @labrown 

This is annoying, tried to test it again on Chrome 64 and 63 in a Windows 10 VM and clicking through jobs and resources worked fine. Just double checking you tried this on just the plain https://ci.concourse.ci/ and not the beta view right https://ci.concourse.ci/beta/teams/main/pipelines/main  (because beta view is properly broken)

**Comment by labrown** [comment] 2018-02-21 17:19
Confirmed on https://ci.concourse.ci/

**Comment by jama-pivotal** [comment] 2018-02-21 19:10
Interesting. Could you humor me @labrown and and check if its still broken in incognito mode in your 3.8.0, and then if its "fixed" with incognito on 3.9.0 at https://ci.concourse.ci/  Just want to make sure there's an actual difference in behaviour and that we actually fixed something! If its all good I can close this issue and we can treat the heavy caching as a separate problem

**Comment by labrown** [comment] 2018-02-21 19:24
I wish I could.  I don't have access to incognito mode in Chrome on my work laptop (policy restriction), and our work resources are not accessible outside our network.

Best I could do is maybe shut down all my Chrome windows at end of work day, clear cache, and fire up again.  Can't afford to do that mid-workday, though.

**Comment by aeijdenberg** [comment] 2018-02-21 20:42
@jama-pivotal - When I load https://ci.concourse.ci/ I do now see the cursor change to a "finger" when I hover over the jobs, however still nothing happens when I click on them (including in Incognito mode).

Note that I'm on Chrome on Mac - I'll post my `chrome://version/` output below, and when I get to the office later (where until this bug I thought I had identical configuration) I'll compare.

```
Google Chrome | 64.0.3282.167 (Official Build) (64-bit)
-- | --
Revision | bf44778c9ce98ecff1128b225a165728044bbdeb-refs/branch-heads/3282@{#671}
OS | Mac OS X
JavaScript | V8 6.4.388.45
Flash | 28.0.0.161 /Users/aeijdenberg/Library/Application Support/Google/Chrome/PepperFlash/28.0.0.161/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --disable-quic --flag-switches-end
Executable Path | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path | /Users/aeijdenberg/Library/Application Support/Google/Chrome/Profile 7
Variations | bd23585d-3f4a17dfc134752e-b8b72c8859aeb88e-3f4a17df3095aa95-3f4a17dfd52c4ff7-d52c4ff747e5d3db-3d47f4f4b1edbc38-cf4f6ead34d450b1-3f4a17df79616653-3f4a17df9e201a2b-6e3ce1c57f575bb-3d47f4f4d0ecf1da-ca7d8d80f347910c-3f4a17df4b61504a-d25ea6919773d3bd-f23d1dea8e3b2dc5-937025909e5c75f1-1039a2212981bcb4-ca7d8d80f79cb77b-3d47f4f44ea303a6-2e46ed91d92562a9-ca7d8d8090bcbadc-3f4a17df25fc488a-4d2fac8758a025e3-c2b417021bced4a3-90fa85cdb2f0086-ee6dd628ef25c1eb-3f4a17df2d871858-ca7d8d80494d8760-94c7e8c6f47ae82a-86f22ee53ac60855-486e2a9cf296190c-8282a32d4442aae2-6bdfffe7ed1d377-e1cc0f1475f0f0a0-a5822863e2b18481-92bb99a9e7e71889-4ad6057534baa302-d25ea691f5fff3a2-f5fff3a294e68624-803f8fc4f141d4bc-28ad44ada4aaa01-4d2fac87
```

**Comment by labrown** [comment] 2018-02-21 21:18
I now see the finger when I hover over items as well.
Also, both my normal and incognito windows are exhibiting the same "click and hit enter" behaviour to open resource or jobs.
Closed my incognito window, opened another incognito.  accessed https://ci.concourse.ci/ and everything works properly again in that browser window.  Strange.

**Comment by aeijdenberg** [comment] 2018-02-22 00:02
@jama-pivotal - and here's the same from my Chrome in the office that works:

```
Google Chrome | 64.0.3282.167 (Official Build) (64-bit)
-- | --
Revision | bf44778c9ce98ecff1128b225a165728044bbdeb-refs/branch-heads/3282@{#671}
OS | Mac OS X
JavaScript | V8 6.4.388.45
Flash | 28.0.0.161 /Users/aeijdenberg/Library/Application Support/Google/Chrome/PepperFlash/28.0.0.161/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path | /Users/aeijdenberg/Library/Application Support/Google/Chrome/Profile 7
Variations | bd23585d-3f4a17dfc134752e-b8b72c883095aa95-3f4a17dfd52c4ff7-d52c4ff747e5d3db-3d47f4f4b1edbc38-cf4f6ead34d450b1-3f4a17df79616653-3f4a17df9e201a2b-6e3ce1c57f575bb-3d47f4f4d0ecf1da-ca7d8d80f347910c-3f4a17df4b61504a-d25ea6919773d3bd-f23d1dea8e3b2dc5-937025909e5c75f1-1039a221c322f799-2dbe5f92981bcb4-ca7d8d80f79cb77b-3d47f4f44ea303a6-ecbb250ed92562a9-ca7d8d8090bcbadc-3f4a17df2b33233e-ca7d8d8025fc488a-4d2fac8758a025e3-c2b417021bced4a3-90fa85cdb2f0086-ee6dd628ef25c1eb-3f4a17df2d871858-3f4a17df494d8760-94c7e8c6f47ae82a-746c2ad43ac60855-486e2a9cf296190c-fae5d5354442aae2-6e597edeed1d377-e1cc0f1475f0f0a0-e1cc0f14e2b18481-7564fb06e7e71889-4ad6057534baa302-d25ea691f5fff3a2-ca7d8d8094e68624-803f8fc4f141d4bc-28ad44ada4aaa01-4d2fac87
```

Other than the `--disable-quic` flag (which I tried enabling here to see if it triggered the issue), I don't see any differences, other than in the `Variations` which I don't quite understand.

**Comment by aeijdenberg** [comment] 2018-02-22 09:11
Just to add another few data points - on that same problematic Mac at home (where it doesn't work), it also doesn't work in the same way in Safari and Firefox (even in other user accounts on the same computer). It does however work fine on a Chromebook (on the same network).

**Comment by aeijdenberg** [comment] 2018-02-22 10:17
One last note - I was able to briefly get it to work (in all browsers) and then stop again after clicking around in the system accessibility settings. I wasn't however able to get a consistent path to reproducibility though.

**Comment by jama-pivotal** [comment] 2018-02-22 14:05
@labrown and @aeijdenberg I'm a but flummoxed. Doesn't seem OS specific then. I was able to do some testing on Chrome 64 and 63 yesterday as well on OS X and Windows 10. Will have to do some more investigation

**Comment by walked** [comment] 2018-03-24 02:01
@jama-pivotal I'm seeing the same issue; only with Chrome. Firefox is just fine.

Just an additional data point. Concourse v3.9.2, Chrome version Version 65.0.3325.181

Right click --> Open in new tab is my workaround at the moment.

**Comment by jeffgreenca** [comment] 2018-03-28 14:27
On Chrome, incognito window:
Open concourse, log in, can click on pipelines to access builds.

Close all windows, open new incognito window, then:
Open concourse, log in, use scroll wheel to adjust scaling at all, cannot click on pipelines to access builds.

Chrome Version 65.0.3325.181 (Official Build) (64-bit) on Windows, Concourse v3.9.2 (docker).

**Comment by xtremerui** [comment] 2018-04-18 00:34
Issue reproduced on Chromium 68.0.3399.0

After some investigation it seems Chromium renders job node without the <a> wrapper, which should contain an url to job build page. Thus job nodes are not clickable and mouse over it shows no pointer.

**Comment by jama-pivotal** [comment] 2018-04-23 18:35
folks, looks like @xtremerui was able to do some tweaks to make this work under Chromium. Going to accept this for now so it can be packaged into the release. If any of you have time please check out the UI behavior in ci.concourse-ci.org to see if you can click through the div elements. If its still broken please re-open and we can take a look again in the future

**Comment by gokeefe** [comment] 2018-04-28 04:57
On my personal desktop running Chrome, clicking on the tasks on ci.concourse-ci.org works perfectly fine. On my work laptop, also running Chrome, clicking on the tasks on ci.concourse-ci.org does not work at all without doing the click+enter trick.

**Comment by xtremerui** [comment] 2018-04-30 13:39
@gokeefe what is the chrome version of your work laptop? what is the os? Thx

**Comment by jama-pivotal** [comment] 2018-04-30 14:17
Reopening because I too am now afflicted Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by jama-pivotal** [comment] 2018-04-30 20:36
I did a short writeup in a new issue @gokeefe in #2192, basically do a hard refresh in chrome (Cmd + Shift + R) and try clicking on a job without moving the mouse AT ALL when you click in to see if you can get to the new page. Or, the opposite, which is initiate the left click, hold at the bottom, move your mouse a little and release (this won't work)

**Comment by StevenArmstrong** [comment] 2018-06-11 18:08
Still getting this in chrome browser. Any updates on this?

**Comment by gokeefe** [comment] 2018-06-11 21:39
@StevenArmstrong I upgraded Concourse to 3.14.1 over the weekend and no longer have the issue.

**Comment by StevenArmstrong** [comment] 2018-06-12 21:46
Still broken for me in 3.14.1 on chrome Version 67.0.3396.79 👎

**Comment by MuthuvelkumarS** [comment] 2018-07-10 14:17
Still broken for me as well. Chrome Version 61.0.3163.79. Concourse 3.14.1. It worked initially once I setup concourse and then stopped working after a day.

**Comment by gdenn** [comment] 2018-11-11 22:36
Noticed the same starting at 4.x for us on Mac Chrome. My immediate solution was right-click new tab.

**Comment by mtharrison** [comment] 2020-05-04 09:25
Same issue here. It can be quite frustrating and seems fairly random when it opens vs zooms vs does nothing.

**Comment by kosh01** [comment] 2021-09-09 07:14
Me too facing this issue and found out that the chrome plugin BlazeMeter was causing it. It works fine now after the plugin is disabled.

**Comment by xtremerui** [comment] 2023-11-15 03:34
closing stale issue.

**Closed by xtremerui** 2023-11-15 03:34 UTC
Labels: bug, needs-investigation, web-ui, accepted

**Comment by ae-govau** [comment] 2023-11-15 03:40
I appreciated closing the stale issues, but I'll throw in as final note that we still periodically see this.... but now we know the workaround (click the thing, then hit enter) it's less annoying than it used to be before we knew that.
