### ISSUE TITLE
There is no way to actively determine when a worker has been retired and can be shut down

### ISSUE THREAD

**Issue by ebmeierj** [concourse/concourse#2757] opened 2018-11-05 16:48 UTC
## What challenge are you facing?

When scaling down my workers, there does not appear to be any way to tell when a worker has been retired. This means I have to wait an arbitrary time and hope it is completed.

## What would make this better?

The retire-worker command used to output 'worker-not-found' after the worker was successfully retired. Although this was not an ideal way of checking whether the worker has been retired, at least it was reasonably possible to assume the worker had been retired if this log was encountered 

Ideally, however, there would be some mechanism for determining when the worker has been retired and is safe to be shut down. Possibly a return code from the retire-worker command?

One consideration is that the `fly` command is not installed on our workers and even if it were, it would require authentication which is difficult for a scripted action such as auto-scaling. So using fly is not an idea solution for me.

## Are you interested in implementing this yourself?

I have never programmed in go before and I don't know much about the code base. If I could receive some direction on where best to add this feature I would consider it.

**Comment by william-tran** [comment] 2018-11-07 07:52
This has broken the worker lifecycle management in the helm chart: https://github.com/helm/charts/blob/master/stable/concourse/templates/worker-statefulset.yaml#L47

**Comment by cirocosta** [comment] 2019-01-25 23:18
Hey @eedwards-sk ,

Thanks for letting us know about your use case!

It feels to me that the kind of functionality you envision (either retiring or landing when a specific signal is sent) is already implemented: https://github.com/concourse/concourse/blob/0b9f266262d231a499ae3e03e8bc68ab404a4dc3/worker/drain_runner.go#L32-L57 (see https://github.com/concourse/concourse/blob/0b9f266262d231a499ae3e03e8bc68ab404a4dc3/worker/drain_runner_test.go#L155 for an example).

**Comment by eedwards-sk** [comment] 2019-01-26 01:17
@cirocosta So far unfortunately I haven't been able to replicate any of the retire or land behavior on SIGUSR1 or SIGUSR2.

I'm running `concourse worker`, not the bosh `worker` binary, so I'm not sure if that code is related to the bosh worker only (or if the bosh worker is still even a thing). Not sure what else I might be missing? I'll keep experimenting though.

**Comment by vito** [comment] 2019-01-26 03:13
@eedwards-sk Yeah, this behavior was actually all implemented recently and will be released in 5.0.

The new behavior is to initiate landing when the worker receives `SIGUSR1` and retiring when the worker receives `SIGUSR2`. In addition, if a `SIGTERM` is received after retiring is initiated, it will delete the worker. This is useful for timing out the draining when retiring.

This makes draining + timeouts pretty easy to use via things like `start-stop-daemon`:

https://github.com/concourse/concourse-bosh-release/blob/af85d893d8df4bcb7d900b85096d8384ab34d261/jobs/worker/templates/drain.erb#L37-L42

There's probably some way to do this with `systemd` too?

For the original ask in this issue, though, I'm kinda confused because when the worker retires the process already exits automatically. Is that not sufficient? i.e. `concourse retire-worker` (or `SIGUSR2` in the future) and then just watch for the `concourse worker` process to exit.

**Comment by ebmeierj** [comment] 2019-01-28 00:55
@vito - I did not realize the concourse process exits when the worker is retired. The examples I read actually suggested you should stop the concourse process once all the jobs have finished before shutting down the server. Those examples must have been incorrect if this is the case. Assuming the process exits once the worker is retired I should be able to glean the information I need. Thanks!

**Comment by eedwards-sk** [comment] 2019-01-28 15:13
@vito The new SIGUSR1/2 behavior should work for my use case (specifically, just the `retire` signal), as long as #2827 gets fixed, since with systemd when I do a `sytemctl reload concourse-worker` or when `envconsul` sees a change in config, it will fire a retire-worker signal and then launch another worker process.

#2827 indicates a problem when you have an ephemeral worker that re-registers right away, and this is exactly what I would be doing in that case

Sounds like we can close this issue otherwise :)

**Comment by vito** [comment] 2019-01-28 20:42
@eedwards-sk I think having a way to have a worker just hard-delete itself on shutdown and skip draining would be nice, especially for local development. Maybe that could be the default for ephemeral workers? (In any case, I guess this is a separate issue.)

@ebmeierj Yeah, sounds like those docs were a bit misleading; this has always been the behavior. Guess I'll close this out then!

**Closed by vito** 2019-01-28 20:42 UTC
Labels: triage

**Comment by eedwards-sk** [comment] 2019-01-28 21:54
> I think having a way to have a worker just hard-delete itself on shutdown and skip draining would be nice, especially for local development

@vito That's what current behavior does, right?

My use case is for production, which requires doing a drain before restarting to prevent impacting running builds. Where #2827 might bite me is because for example if `envconsul` is setting `CONCOURSE_LOG_LEVEL` and sees a change to its value in consul, it will immediately restart `concourse worker` to pick up the change. I don't want a change in config to interrupt jobs in progress.

The workers are ephemeral because they're in an ASG and are "unique" each time they're created, so when they die they should just "go away". However, I still need to be able to stop/start the worker on the same host (with envconsul), which currently means it will get retired and then re-join under the same name, even though it's "ephemeral".

I'll have to see how it actually works once the 5.0 behavior is released.

**Comment by vito** [comment] 2019-01-28 23:54
> @vito That's what current behavior does, right?

Well, it will if you send it a `SIGUSR2` and then a `SIGTERM`, but e.g. Docker Compose only lets you configure one stop signal. You can just configure `SIGUSR2` at least and trust that it'll eventually go away but it still slows down the dev feedback loop. This is probably unrelated though. 🙂 

For your `envconsul` use case, one thing to note: if you're restarting the process in-place in the same container/VM you shouldn't retire the worker - you should land it and then let it come back. Retiring should only be done when the worker host (whether that's a container or a VM) is going away for good, and all the containers and volumes are gone with it. Landing (`SIGUSR1`) will let you keep the volumes and containers that were running on it.

**Comment by eedwards-sk** [comment] 2019-01-29 00:11
>Well, it will if you send it a SIGUSR2 and then a SIGTERM

systemd sends a SIGKILL as the final kill signal only if you fail to gracefully exit, so it's basically the same as compose et al, you get one trappable signal which can be used to gracefully exit (e.g. SIGUSR2), and then you get `kill -9`'d after a timeout if you didn't exit properly.

so I'm hoping SIGUSR2 is enough to do the same as what `concourse retire-worker` would do, which is drain and then fully exit / stop processes (without requiring a follow-up signal)

>For your envconsul use case, one thing to note: if you're restarting the process in-place in the same container/VM you shouldn't retire the worker - you should land it and then let it come back. Retiring should only be done when the worker host (whether that's a container or a VM) is going away for good, and all the containers and volumes are gone with it. Landing (SIGUSR1) will let you keep the volumes and containers that were running on it.

I would, but as I said, with current SIGUSR1 behavior, I can't :(

For that to work, I'd need to have a signal that could issue a land and then automatically start back up again (same process), like a 'rehup' as per my above comments (used for `systemctl reload` or the envconsul reload). Because the land signal doesn't (won't) work like that, my re-load has to be a stop/start, and a stop/start is either always a retire or no retire, and thus needs to be a retire or it won't retire on system shutdown and will kill tasks in progress.

I'm also noticing that concourse leaves its children around sometimes. I had to change systemd KillType to 'mixed' so that it SIGKILLs any leftover processes after the main process exits. I found even after a proper retire that `/tmp/garden-init` was still running when `concourse` exited.

Landing / Retiring is without a doubt still the hardest thing for me to model cloud systems in aws around, but it's been getting MUCH better. Ephemeral helps a lot because ASG instances may die and never come back, so cleanup of leftover nodes was an operational burden.

**Comment by vito** [comment] 2019-01-29 00:33
> For that to work, I'd need to have a signal that could issue a land and then automatically start back up again (same process), like a 'rehup' as per my above comments (used for `systemctl reload` or the envconsul reload). Because the land signal doesn't (won't) work like that, my re-load has to be a stop/start, and a stop/start is either always a retire or no retire, and thus needs to be a retire or it won't retire on system shutdown and will kill tasks in progress.

I see. So really you don't have a choice because there's no 'reload', and so you have to stop/start, and you can only define stop/start as retiring for other reasons. Otherwise landing would make more sense.

You'll have to be careful though. Because you're retiring but keeping state around, you could end up with leaks as containers and volumes stick will stick around - the ATC will have forgotten them, because the worker disappeared, and so its GC won't know it needs to destroy them.

> I'm also noticing that concourse leaves its children around sometimes. I had to change systemd KillType to 'mixed' so that it SIGKILLs any leftover processes after the main process exits. I found even after a proper retire that `/tmp/garden-init` was still running when `concourse` exited.

This is intentional. Containers are left running because it can re-attach to them when the worker comes back. Workers can actually be stopped without landing or retiring, and as long as they come back quickly enough, go back to running and the ATC will re-attach to any in-flight work.

This allows for drain timeouts to be 'best-effort' while still allowing builds that were running beyond the drain timeout to survive a deploy. But this only makes sense for either landing or in-place restarts without draining, so this isn't very useful for you and in fact relates to my previous point (ATC doesn't know to garbage-collect them because from its perspective they all disappeared with the worker).

**Comment by eedwards-sk** [comment] 2019-01-29 00:45
>This is intentional. Containers are left running because it can re-attach to them when the worker comes back. Workers can actually be stopped without landing or retiring, and as long as they come back quickly enough, go back to running and the ATC will re-attach to any in-flight work.

That's actually very interesting! If that means I can kill and re-start the parent process without stopping jobs-in-progress, then it may work as a "reload". e.g. maybe I could send a SIGTERM for the "rehup" signal, and then a SIGUSR2 for the stop signal?

The whole reason I wanted to drain/land on restart was to prevent interrupting work-in-progress, because I assumed that's what killing the parent worker process would do.

Also sorry for derailing this issue.

**Comment by vito** [comment] 2019-01-29 15:53
@eedwards-sk Right. The only gotcha however is you may lose windows of build output, and right now if a worker is down just as a resource finishes, builds may error with `unexpected EOF`. This will be fixed with the new resource interface, though (concourse/rfcs#1).

Because it's a bit finnicky we don't really document or recommend anyone do it in the wild. But once the resource change is made it should become a lot smoother. :slightly_smiling_face: 

And no worries - I derailed it too, heh.

**Comment by eedwards-sk** [comment] 2019-01-29 19:25
@vito I haven't been able to reproduce the behavior you described with the control groups in 4.2.2. Is this an upcoming 5.0 change?

currently, even if I run outside of systemd (to eliminate that as a possibility), once the subprocesses are spawned from the `concourse` worker binary, if I `kill` the parent process, it leaves the children running, as expected

however, the moment I launch the concourse worker binary again, it kills all the children in the cgroup!

**Comment by vito** [comment] 2019-01-29 21:19
@eedwards-sk Ah, yeah that's fixed in 5.0. It was an issue affecting the binaries - they didn't configure Garden-runC with a path for it to store state on shutdown/restore. Once we started using the binaries in the BOSH release (#2575) I noticed the issue and fixed it.
