### ISSUE TITLE
Feature request: ability to specify artifacts inputs for the resource put step

### ISSUE THREAD

**Issue by stefan-de-koning** [concourse/concourse#1451] opened 2017-08-08 09:14 UTC
# Feature Request

## What challenge are you facing?

In our pipelines we found that in certain cases the put action of the docker-image-resource was taking very long. It appears to freeze up at the initialization stage and more often than not it will fail with a BaggageClaim timeout: `Post /volumes: net/http: timeout awaiting response headers` (see also: https://github.com/concourse/concourse/issues/1333 )

This particular build plan has a very large artifact - our project and build cache, which is both large in size as well as file-count. It seems that during the put action, all artifacts are mapped into the docker-image-resource container (https://concourse.ci/put-step.html). However, the image resource has no need for this large artifact - instead it requires another, smaller, artifact output, which contains only the Dockerfile and the application JAR. It seems that the BaggageClaim timeout is related to preparing the volume with all the artifacts in there, even though we really only need the Dockerfile artifact to be available.

## A Modest Proposal

The BaggageClaim timeout issues are discussed here (https://github.com/concourse/concourse/issues/1368). However, for this particular use case, I suggest to introduce the `inputs` argument for the `put` action. This `inputs` argument would behave exactly the same as `inputs` in the task config (see: https://concourse.ci/running-tasks.html#inputs). Hopefully this would prevent unnecessary mapping of volumes and the timeouts related to them.

**Comment by vito** [comment] 2017-08-14 14:22
Dupe of https://github.com/concourse/concourse/issues/1202

For what it's worth, this won't fix the timeout issue. That's a per-volume issue, and each input is its own volume. So it would only fix that if you were able to limit-"out" the one that was causing the timeout.

**Closed by vito** 2017-08-14 14:22 UTC
Labels: area: efficiency, type: enhancement
