### ISSUE TITLE
Concourse web UI freezes when job requires resource that has passed itself

### ISSUE THREAD

**Issue by evanshort73** [concourse/concourse#84] opened 2015-07-24 20:45 UTC
If your pipeline contains

```
jobs:
  - name: my-job
  plan:
  - get: my-resource
    passed: my-job
    trigger: true
```

then when you try to look at that pipeline in the web UI, the display area is black and Chrome eventually says that the page has frozen.

**Comment by Osis** [comment] 2017-03-16 17:01
Confirmed that this still happens today, but in a different way.

**UI**
![screen shot 2017-03-16 at 11 05 51 am](https://cloud.githubusercontent.com/assets/347097/24003968/5f5dbadc-0a3b-11e7-8cd1-53e25a3204dc.png)

**Network**
![screen shot 2017-03-16 at 11 06 17 am](https://cloud.githubusercontent.com/assets/347097/24008607/78ac37cc-0a48-11e7-9a8e-fe794633f4ef.png)

**Comment by clarafu** [comment] 2017-05-12 15:28
I'm going to close this issue because with the current version of Concourse, the passed constraint just wraps back to itself (in a circle). This might cause it to never trigger but it does not freeze the page.

**Closed by clarafu** 2017-05-12 15:28 UTC
Labels: bug
