### ISSUE TITLE
Relative job dates in web UI are off by several years

### ISSUE THREAD

**Issue by supertopher** [concourse/concourse#798] opened 2016-11-29 20:01 UTC
# Bug Report

* Concourse version: v2.3.1
* Deployment type: BOSH
* Infrastructure/IaaS: AWS
* Browser (if applicable): Chrome
* Did this used to work? Yeppers (though possibly in another version of concourse)

As shown below our relative dates are pretty far off even though absolute times seem to be correct.

![screen shot 2016-11-29 at 11 53 12 am](https://cloud.githubusercontent.com/assets/2591516/20726644/55d615b8-b62b-11e6-9687-c22b1913c48b.png)

/cc @tushar-dadlani

**Comment by chendrix** [comment] 2017-06-06 23:52
Is your local time set different from your browser time or something?

**Comment by jama-pivotal** [comment] 2017-11-13 17:22
Tried to reproduce on Concourse 3.6.0 by modifying my local time but couldn't reproduce. @supertopher or @tushar-dadlani are you still experiencing this problem?

**Comment by jama-pivotal** [comment] 2018-01-29 16:24
Closing due to staleness

**Closed by jama-pivotal** 2018-01-29 16:24 UTC
Labels: bug, web-ui
