### ISSUE TITLE
6.5.1 Workers fail to register

### ISSUE THREAD

**Issue by ChrisScottThomas** [concourse/concourse#6088] opened 2020-09-28 06:59 UTC
## Summary

Workers fail to register after upgrading from `6.4.1` to `6.5.1`.

## Steps to reproduce

We have Concourse deployed in AWS, with one web node and three workers.  We have had this running for some time (`6.0.0`) on barely unchanged infrastructure, that we manage with Terraform.

It's installed by passing the version we require into a small bootstrap script, that grabs and extracts the version tarball.

```
concourse_tarball="concourse-${concourse_version}-linux-amd64.tgz"
https_proxy="${https_proxy}" curl -s -L -O https://github.com/concourse/concourse/releases/download/v${concourse_version}/$concourse_tarball
tar -xzf $concourse_tarball -C /usr/local
```

Our deployment method is as follows:

Set this to the version we require:
```
variable "concourse" {
  description = "concourse version to install"
  type        = map(string)

  default = {
    version = "6.4.1"
  }
}
```
 in the `variables.tf`, and run `terraform apply`, then terminate the workers and web nodes.  AutoscalingGroups bring the infra back up on the new version.

If I change that version to 6.5.1, the web and worker nodes come up just fine, but wed nodes can not talk to workers and the workers can not register with the web nodes.

As soon as I roll back to 6.4.1 (reversing the above step), it works and the workers register just fine.

## Expected results

Workers register, as there are no breaking changes around this.

## Actual results

Workers run, but do not register with the web node.

## Triaging info

* Concourse version: 6.5.1
* Did this used to work?
It has worked for every other upgrade we have rolled out.  With nothing in the change notes around this, I would assume this pattern should still be working now.

**Comment by aoldershaw** [comment] 2020-09-28 15:50
I wonder if this is related to https://github.com/concourse/concourse/releases#5897? Do you see anything of note in the web or worker logs, perhaps related to TSA registration?

**Comment by ChrisScottThomas** [comment] 2020-09-29 08:15
> I wonder if this is related to https://github.com/concourse/concourse/releases#5897? Do you see anything of note in the web or worker logs, perhaps related to TSA registration?

I'll have to recheck, as we've rolled back to do some other changes.  We don't even get as far as being able to login though, so I'm not sure how Oauth2 tokens would be effecting?

**Comment by aoldershaw** [comment] 2020-09-29 15:59
The TSA component responsible for worker registration fetches an OAuth token on behalf of the workers that it uses to communicate with the API (including the register worker endpoint).

I'm not exactly sure whether this is the root cause, though it does seem suspicious that it works on 6.4.1 but not 6.5.1

**Comment by ChrisScottThomas** [comment] 2020-09-30 11:25
Workers are pumping out errors such as:
```
{
    "timestamp": "2020-09-30T11:08:53.191841153Z",
    "level": "error",
    "source": "worker",
    "message": "worker.container-sweeper.tick.failed-to-connect-to-tsa",
    "data": {
        "error": "dial tcp x.y.z.a:2222: i/o timeout",
        "session": "6.1"
    }
}
```
```
{
    "timestamp": "2020-09-30T11:09:53.187674291Z",
    "level": "error",
    "source": "worker",
    "message": "worker.container-sweeper.tick.failed-to-dial",
    "data": {
        "error": "all worker SSH gateways unreachable",
        "session": "6.1"
    }
}
```

Web node constantly emits this error:
```
{
    "timestamp": "2020-09-30T11:12:14.877376973Z",
    "level": "error",
    "source": "tsa",
    "message": "tsa.connection.channel.command.register.failed-to-fetch-containers",
    "data": {
        "command": "forward-worker",
        "error": "bad response: invalid character '<' looking for beginning of value",
        "remote": "x.y.z.a:47066",
        "session": "33.4.1.3"
    }
}
```
`"error": "bad response: invalid character '<' looking for beginning of value",` - to me looks like it's getting a response like:
```
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Just want to reiterate it is not down to networking, even though that's exactly what it looks like, as a revert to `6.4.1` fixes all issues.

**Comment by ChrisScottThomas** [comment] 2020-10-08 06:30
The issue persists in `6.6.0`.
Without help here I think we're stuck at `6.4.1`

**Comment by aoldershaw** [comment] 2020-10-10 02:10
Hey, sorry for the lack of communication on this. Is there anything in the nginx logs by any chance?

**Comment by ChrisScottThomas** [comment] 2020-10-10 06:43
```1602261504.455      0 10.x.y.xx TCP_DENIED/403 4147 GET http://ip-10-x-y-xx.eu-west-2.compute.internal:32965/containers - HIER_NONE/- text/html```

The squid proxy logs are heaving with errors like this.  Looks like it's trying to get on the Internet to talk between workers/nodes. It feels like something has fundamentally changed after 6.4.1 and it missed the change log.

**Comment by aoldershaw** [comment] 2020-10-10 13:59
Hmm, thanks for the info. I'm now thinking this may be an unexpected side effect of the change in https://github.com/concourse/concourse/releases#5845 - tagging @xtreme-sameer-vohra as he should have the most context

**Comment by xtreme-sameer-vohra** [comment] 2020-10-13 14:46
It appears as though Garden server might be having trouble. 

@ChrisScottThomas do you see any other preceding errors in the worker logs ? Could you also run `curl localhost:7777/containers` on the worker VM. Thats the request the TSA is attempting to make during the `tsa.connection.channel.command.register.failed-to-fetch-containers` failure.

**Comment by ChrisScottThomas** [comment] 2020-10-13 14:54
From the worker, I can:
```
root@ip-10-xx-y-zz ~]# curl localhost:7777/containers
```
and it responds:
```
{"Handles":[]}
```

**Comment by ChrisScottThomas** [comment] 2020-10-13 15:09
It's unclear why it's suddenly trying to go onto the internet to make those requests, as the above error comes from our squid proxy gating access to WWW.  This does not occur in `6.4.1`

**Comment by xtreme-sameer-vohra** [comment] 2020-10-14 21:21
> From the worker, I can:
> 
> ```
> root@ip-10-xx-y-zz ~]# curl localhost:7777/containers
> ```
> 
> and it responds:
> 
> ```
> {"Handles":[]}
> ```

Looks like garden is coming up fine. AFAIK there haven't been any changes to the registration logic in the v6.5 or v6.6. The [garden client change](https://github.com/concourse/concourse/releases#5845) should be transparent and it is the same version used by the `atc`.  
The go version used to build concourse changed from `1.14.5` for `6.4.0` to `1.15` for `6.5.0`. There are changes to `net/*` packages.

Could you help narrow the problem down;
- Can filter logs for `forwarded-tcpip`?  For the `bind-addr` & `bound-port` in the message, what response do you get performing `curl bind-addr:bound-port/containers` ? One of these will correspond with `baggageclaim` so the endpoint would be `/volumes` instead
- Or do you see `garden address SOME_ADDRESS not forwarded` in the logs ?
- Are you able to verify if the issue exists without the proxy ? 
- What is the topology of the deployment (web and workers with the proxy) ?
- Is there a docker-compose setup that reproduces the issue ?

**Comment by ChrisScottThomas** [comment] 2020-10-16 10:29
> * Can filter logs for `forwarded-tcpip`?  For the `bind-addr` & `bound-port` in the message, what response do you get performing `curl bind-addr:bound-port/containers` from the web node? One of these will correspond with `baggageclaim` so the endpoint would be `/volumes` instead

Which logs? Rudimentary search in both web and workers show nothing.  When do these messages appear? The nodes have been running for a while.

How are nodes are configured is here: [web](https://github.com/dwp/aws-concourse/blob/master/terraform/modules/concourse_web/web_config.tf) and [worker](https://github.com/dwp/aws-concourse/blob/master/terraform/modules/concourse_worker/worker_config.tf)

> * Or do you see `garden address SOME_ADDRESS not forwarded` in the logs ?

which logs? Looking in the workers, no.

> * Are you able to verify if the issue exists without the proxy ?

Not really, as disabling the proxy won't stop the traffic trying to use an external route.  And me reverting to `6.4.1` does not make any network changes to my deployment.  The _only_ thing that changes is the version of Concourse installed.

> * What is the topology of the deployment (web and workers with the proxy) ?

[Here](https://github.com/dwp/aws-concourse/blob/master/docs/architecture.png)

> * Is there a docker-compose setup that reproduces the issue ?

No.

**Comment by xtreme-sameer-vohra** [comment] 2020-10-16 17:03
> > * Can filter logs for `forwarded-tcpip`?  For the `bind-addr` & `bound-port` in the message, what response do you get performing `curl bind-addr:bound-port/containers` from the web node? One of these will correspond with `baggageclaim` so the endpoint would be `/volumes` instead
> 
> Which logs? Rudimentary search in both web and workers show nothing. When do these messages appear? The nodes have been running for a while.

These would appear in the [`web` logs](https://github.com/concourse/concourse/blob/master/tsa/tsacmd/remote_cli.go#L48-L51)  from the `tsa` component during the worker registration process.  They set to `info` level. 

> 
> How are nodes are configured is here: [web](https://github.com/dwp/aws-concourse/blob/master/terraform/modules/concourse_web/web_config.tf) and [worker](https://github.com/dwp/aws-concourse/blob/master/terraform/modules/concourse_worker/worker_config.tf)
> 

The log level is set to `error`,  what do you observe during the registration process if the log level would be set to `debug`  on the `web` and `worker`?

> > * Or do you see `garden address SOME_ADDRESS not forwarded` in the logs ?
> 
> which logs? Looking in the workers, no.

These would appear in the [`web` logs](https://github.com/concourse/concourse/blob/master/tsa/tsacmd/remote_cli.go#L62) from the `tsa` component during the worker registration process.  They set to `info` level.

> 
> > * Are you able to verify if the issue exists without the proxy ?
> 
> Not really, as disabling the proxy won't stop the traffic trying to use an external route. And me reverting to `6.4.1` does not make any network changes to my deployment. The _only_ thing that changes is the version of Concourse installed.
> 

I might have misunderstood the purpose of the `proxy`. Is the purpose of the `proxy` for workloads running on the worker using the `--http-proxy=` or `--https-proxy=` flags on the worker or is it meant for the `worker` to be able to reach the `web` for registration ? If it is the latter, then testing without it would be relevant.  

> > * What is the topology of the deployment (web and workers with the proxy) ?
> 
> [Here](https://github.com/dwp/aws-concourse/blob/master/docs/architecture.png)

Thanks. I don't see the proxy in this diagram. Looks like each `CS-{a,b,c}` are each a standalone Concourse deployment and each worker in the box connects to the web in the same box directly ? 🤔 

> 
> > * Is there a docker-compose setup that reproduces the issue ?
> 
> No.

**Comment by ChrisScottThomas** [comment] 2020-10-17 09:57
> These would appear in the [`web` logs](https://github.com/concourse/concourse/blob/master/tsa/tsacmd/remote_cli.go#L48-L51) from the `tsa` component during the worker registration process. They set to `info` level.
 
> The log level is set to `error`, what do you observe during the registration process if the log level would be set to `debug` on the `web` and `worker`?

I'll switch the log level and investigate both the above.
 
> I might have misunderstood the purpose of the `proxy`. Is the purpose of the `proxy` for workloads running on the worker using the `--http-proxy=` or `--https-proxy=` flags on the worker or is it meant for the `worker` to be able to reach the `web` for registration ? If it is the latter, then testing without it would be relevant.

It's just a squid proxy that gates what can be accessed when going to WWW.   The web and worker nodes are on a private vpc and talk directly.

> Thanks. I don't see the proxy in this diagram. Looks like each `CS-{a,b,c}` are each a standalone Concourse deployment and each worker in the box connects to the web in the same box directly ? 🤔

yeah it's a little off and hasn't been updated in some time.  There's actually one web node and three workers.  The proxy is around where the IGW is.  The three workers register with the one web node.  It is one deployment of Concourse.

**Comment by ChrisScottThomas** [comment] 2020-10-17 11:56
> * Can filter logs for `forwarded-tcpip`?  For the `bind-addr` & `bound-port` in the message, what response do you get performing `curl bind-addr:bound-port/containers` from the web node? One of these will correspond with `baggageclaim` so the endpoint would be `/volumes` instead

```"message": "tsa.connection.channel.command.forwarded-tcpip",
    "data": {
        "bind-addr": "0.0.0.0:7777",
        "bound-port": 46775,
        "command": "forward-worker",
        "remote": "10.xx.y.zz:34196",
        "session": "1.3.1"
    }```

There are three of these with three separate `bound-port`'s and three with `"bind-addr": "0.0.0.0:7788",` and three separate `bound-port`'s
Each of the `:7777` ones returns:

```curl 0.0.0.0:46775/containers
{"Handles":[]}
```
Each of the `:7788` ones returns:
```
curl 0.0.0.0:40515/volumes
[]
```

I don't see any messages with "not forwarded".

registration efforts look like this:

```
{
    "timestamp": "2020-10-17T11:07:26.594521190Z",
    "level": "info",
    "source": "tsa",
    "message": "tsa.connection.channel.command.register.start",
    "data": {
        "command": "forward-worker",
        "remote": "10.xx.y.zz:42240",
        "session": "47.4.1.3096",
        "worker-address": "ip-10-xx-y-aaa.eu-west-2.compute.internal:35519",
        "worker-platform": "linux",
        "worker-tags": ""
    }
}
```

```
{
    "timestamp": "2020-10-17T11:07:26.598457463Z",
    "level": "error",
    "source": "tsa",
    "message": "tsa.connection.channel.command.register.failed-to-fetch-containers",
    "data": {
        "command": "forward-worker",
        "error": "bad response: invalid character '<' looking for beginning of value",
        "remote": "10.xx.y.zz:42240",
        "session": "47.4.1.3096"
    }
}
```

```
{
    "timestamp": "2020-10-17T11:07:26.600775904Z",
    "level": "debug",
    "source": "tsa",
    "message": "tsa.connection.request.forward-conn.tcpip-io-complete",
    "data": {
        "addr": "0.0.0.0:36261",
        "remote": "10.xx.y.zz:42240",
        "requested-addr": "0.0.0.0:7788",
        "session": "47.2.3095",
        "type": "tcpip-forward"
    }
}
```

```
{
    "timestamp": "2020-10-17T11:07:26.600859680Z",
    "level": "info",
    "source": "tsa",
    "message": "tsa.connection.channel.command.register.failed-to-reach-worker",
    "data": {
        "baggageclaim-took": "2.335565ms",
        "command": "forward-worker",
        "garden-took": "3.919589ms",
        "remote": "10.xx.y.zz:42240",
        "session": "47.4.1.3096"
    }
}
```

```
{
    "timestamp": "2020-10-17T11:07:26.600880246Z",
    "level": "info",
    "source": "tsa",
    "message": "tsa.connection.channel.command.register.done",
    "data": {
        "command": "forward-worker",
        "remote": "10.xx.y.zz:42240",
        "session": "47.4.1.3096",
        "worker-address": "ip-10-xx-y-aaa.eu-west-2.compute.internal:35519",
        "worker-platform": "linux",
        "worker-tags": ""
    }
}
```

Looks like a possible issue in the `bind-addr` using `0.0.0.0` ? As you can see they all share internal 10 addresses, so should not be routing to the internet, and they do not route to the internet in `6.4.1`.

**Comment by ChrisScottThomas** [comment] 2020-10-21 06:54
Forcing `CONCOURSE_TSA_PEER_ADDRESS=127.0.0.1` aka defaults, fixed the issue.
Perhaps we have been doing something incorrect this whole time, and whatever was fixed has brought that to light? I'm not sure 'why' it has resolved the issue, so any hints here would be appreciated.

**Comment by xtreme-sameer-vohra** [comment] 2020-10-21 20:22
Was `CONCOURSE_PEER_ADDRESS` configured previously to a non-default value ? 
`CONCOURSE_TSA_PEER_ADDRESS` is set to the value of `CONCOURSE_PEER_ADDRESS`. This corresponding code hasn't changed in Concourse since ~2019.

**Comment by ChrisScottThomas** [comment] 2020-10-22 04:03
> Was `CONCOURSE_PEER_ADDRESS` configured previously to a non-default value ? 
> `CONCOURSE_TSA_PEER_ADDRESS` is set to the value of `CONCOURSE_PEER_ADDRESS`. The corresponding code hasn't changed in Concourse since ~2019.

Yes it has always been a non-default value.

The only change made, was the version of Concourse installed.

**Comment by xtreme-sameer-vohra** [comment] 2020-10-24 00:58
Hmm, taking a quick look I wasn't able to identify anything in the mentioned releases that would explain the change 🤔 
I am going to close the issue assuming you were able to upgrade successfully. Feel free to open the issue if that wasn't the case.

**Closed by xtreme-sameer-vohra** 2020-10-24 00:58 UTC
Labels: bug
