### ISSUE TITLE
Volume Failure Creations Should State Where

### ISSUE THREAD

**Issue by rfliam** [concourse/concourse#1950] opened 2018-01-11 02:19 UTC
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Feature Request

## What challenge are you facing?

Concourse when hitting one of many conditions (out of disk, stuck worker, etc) will reporting the following error:

```javascript
{
  "timestamp": "1515636673.679764986",
  "source": "atc",
  "message": "atc.syncer.pillar:radar.scan-resource-type.interval-runner.tick.failed-to-fetch-image-for-container",
  "log_level": 2,
  "data": {
    "container": "c64a5cdf-06dc-4f05-77b8-491607d0e769",
    "error": "failed to find created volume in baggageclaim. Volume handle: dbe28302-1743-418e-66c7-f8467789d8d3",
    "pipeline-scoped-name": "pillar:resource-type:pull-request",
    "session": "52.11.227.1.3"
  }
}
```
 This error _does not include_ the node which _failed_ to create the volume. On large deployments identifying the dead worker is... difficult. Errors of this nature _need_ to report the failing node.

More importantly nodes which demonstrate a high failure rate generating containers, pulling images, etc. (things that result in an "orange" build) should be _automatically_ routed around. Having to take intervention manually defeats the purpose of having a highly available concourse cluster.

**Comment by vito** [comment] 2018-01-12 15:29
Duplicate of #800.

> More importantly nodes which demonstrate a high failure rate generating containers, pulling images, etc. (things that result in an "orange" build) should be automatically routed around. Having to take intervention manually defeats the purpose of having a highly available concourse cluster.

This sounds like a (pretty complicated!) separate issue.

**Closed by vito** 2018-01-12 15:29 UTC
