### ISSUE TITLE
Concourse 5.0 set up issue with AWS 

### ISSUE THREAD

**Issue by UmamaheshMaxwell** [concourse/concourse#3493] opened 2019-03-13 07:10 UTC
Hi Guys,
We have been trying to setup `concourse 5.0.0` (we already set up `4.2.2`) in our AWS. We have created two instances one is for web and another is for worker. We are able to see the site up and running but we are not able to run our pipeline. we checked the logs and noticed that worker throwing the below error.

```
Worker.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"9.1.4"}}
```
We are assuming worker is struggling to connect to web instance and wondering if this could be due to missing gdn configuration. we want to try --garden-config file to see if that fixes the problem.

can somebody suggest how do we write garden config file ?

**Comment by marco-m** [comment] 2019-03-13 08:49
Hello, this is not a bug, it is more troubleshooting. For this kind of questions, could you please use https://discuss.concourse-ci.org/ instead ? And please close this issue ? thanks!

**Comment by UmamaheshMaxwell** [comment] 2019-03-13 21:02
Thank you, Sure we figured out the issue anyway !!!

**Closed** 2019-03-13 21:02 UTC
Labels: bug

**Comment by phillbaker** [comment] 2019-04-29 21:34
Something we noticed while upgrading our workers to v5 was that on one worker the `gdn` binary was failing to start, with the error message:
```
{"timestamp":"2019-04-29T20:26:28.441411431Z","level":"error","source":"guardian","message":"guardian.failed-to-load-properties","data":{"error":"EOF","propertiesPath":"/opt/concourseci/worker/garden-properties.json"}}

```

Somehow an empty file was created at `/opt/concourseci/worker/garden-properties.json`, so the clean up for us was:
```
rm /opt/concourseci/worker/garden-properties.json
```
