### ISSUE TITLE
When a user is not in any team, better to show some an error page rather than 401

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3274] opened 2019-02-12 12:30 UTC
## Bug Report

We built a latest version of Concourse from `main` branch, and deployed a 5.0 preview cluster. When I logged on with a LDAP credential, I forgot to add my LDAP account to a team, then I got a page like the screen shot:

![concourse-error-not-in-team](https://user-images.githubusercontent.com/18585861/52635342-9a808780-2f04-11e9-926c-949f72a32380.png)
 
I think it would be better to show a page that tells like "you are not in any team, contact the administrator to add you to some team".

## Version Info

* Concourse version: build from main branch
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: K8S (ATC)
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by xtreme-james-cooper** [comment] 2019-02-12 16:40
Duplicate of https://github.com/concourse/concourse/issues/2698

**Closed by xtreme-james-cooper** 2019-02-12 16:41 UTC
Labels: bug
