### ISSUE TITLE
failed build page will get stuck at bottom scroll

### ISSUE THREAD

**Issue by ships** [concourse/concourse#1930] opened 2018-01-02 20:08 UTC
# Bug Report

Mouse scroll events can get stuck at the bottom of the scroll range on build page. Using arrow keys will rescue from this and can scroll in either direction, but mouse scrolls are not received when trying to scroll up. Scroll down still bumps the whole pane, so it seems the mouse scroll first responder must change when you are scrolled all the way down.

Note that this happens only on red builds for me, but will happen even if the failed task is folded (as long as some task is unfolded with enough output to need scrolling).

Confirmed that this does not occur on Safari, but haven't tested on Firefox.

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome 63.0.3239.108 
* Did this used to work? Unknown

**Comment by benmoss** [comment] 2018-01-04 20:24
I'm having this issue too! whatsmybrowser.org/b/FLFAJ6Q

**Comment by jraqula** [comment] 2018-01-10 00:36
after some code digging, it seems possible that in this condition, the mouse scroll event ends up invoking this native method: https://github.com/concourse/web/blob/20088d2387bb50ce47199e88c8f0e010e4a3249b/elm/src/Native/Scroll.js#L24-L29

That method scrolls the element to the left, which is not possible.

**Comment by vito** [comment] 2018-01-12 20:15
Duplicate of #1826.

**Comment by jraqula** [comment] 2018-01-17 22:18
@vito not a dupe of that one, or at least I am able to scroll up with arrow keys -- only mouse wheel fails to scroll. (It does not appear to even notice that I am scrolling; that issue reports that there is some motion)

**Comment by jraqula** [comment] 2018-01-24 20:06
@vito please re-open ? are you convinced these are dupes?

**Comment by vito** [comment] 2018-01-24 20:27
@jraqula I'm not convinced that we need more than one bug open for this, as they'll likely end up being tackled at the same time. There are probably all kinds of perceivable differences between different browsers, inputs, etc., but I don't want a bug for each and every one. Having the information available in interlinked closed issues is enough.

**Comment by jraqula** [comment] 2018-01-24 20:28
fair enough ~.`

**Comment by vito** [comment] 2018-01-24 20:30
Sike! I'd rather open yours at this point since it has probably the most recent/accurate information. I'll close the other two.

**Comment by galen-pivotal** [comment] 2018-03-12 18:56
This happens on Firefox to me all the time and it is quite annoying. Currently Firefox 58.0.2 on Mac OS 10.13.3. Arrow keys, scroll wheel, PageUp, Home all have issues. If I hold one of PageUp/Home for a while it lets me scroll after a while. I see the page bumping up a bit and then scrolling back to bottom for the duration of the stuckness, looks like the image in #1826 .
You should be able to see this on the Apache Geode Concourse, at least on any of the Test jobs, including jobs that aren't the currently running job:
https://concourse.apachegeode-ci.info/teams/main/pipelines/develop?groups=main

**Comment by krishicks** [comment] 2018-04-26 16:03
This is broken for me as well, and having smooth scrolling off makes it worse.

I was using Chrome and didn't have too many issues with being able to get control of my scrolling back, but when I switched to Firefox had no end of trouble.

I recently turned smooth scrolling off on Chrome and have the same trouble as on Firefox, which also happened to have smooth scrolling off.

**Comment by xtremerui** [comment] 2018-05-04 20:45
@krishicks what is the os and the browser version? I can't reproduce this locally with latest chrome and firefox. On chrome turning off smooth scrolling is not an option for osx and for firefox it works with smooth scrolling on/off.

**Comment by xtremerui** [comment] 2018-05-04 20:53
@galen-pivotal is this still happening of your pipeline? I followed the link you posted and couldn't reproduce the issue using firefox 56.0 and 59.0.3.

**Comment by krishicks** [comment] 2018-05-04 21:26
@xtremerui I have issues on:

* Chromium 64.0.3279.0 Linux
* Firefox 59.0.2 Linux

I have seen the issue on Mac as well, though I don't have the versions handy.

With Firefox I have the worst success, where even grabbing the scroll indicator and going to the top of the page results in a fight for scroll dominance.

**Comment by xtremerui** [comment] 2018-05-08 16:41
@krishicks I would encourage you to try with a fresh installed browser maybe? We have noticed for some browser plugins concourse ui will acting weird. I can't reproduce the issue on chrome/firefox for linux.

**Comment by krishicks** [comment] 2018-05-09 20:08
@xtremerui I don't think your suggestion is reasonable, given I'm not the only person that is having this problem.

**Comment by xtremerui** [comment] 2018-05-14 14:47
Notice I have seen the same issue on Chrome 63.0.3239.132 osx. After upgrade chrome to  66.0.3359.170 the issue is gone. So I would encourage whoever have the issue to upgrade to latest version of the browser.

**Comment by krishicks** [comment] 2018-05-14 15:40
I see the issue on Firefox 60, the latest release as of a few days ago.

**Comment by jryan128** [comment] 2018-09-13 20:17
I'm seeing this on Firefox 62

**Comment by holyjak** [comment] 2019-02-21 12:12
I see this on FF 65.0.1 Quantum (OSX) while Chrome 72.0 is ok

**Comment by scottschulthess** [comment] 2019-02-21 19:59
I'm getting this right now on chrome 72.    It's not very consistent though, but it seems like there is javascript that causes it to scroll down after expanding the build log and sometimes it prevents you from scrolling up

**Comment by vito** [comment] 2019-02-23 22:06
@scottietremendous Thanks for the tip, maybe that'll help find a repro.

@ anyone reporting this, any additional info helps - if you can get a reliable way to reproduce this we can fix it much quicker!

**Comment by StevenArmstrong** [comment] 2019-02-25 08:58
It normally happens when there are multiple task blocks on the same job.
The work around is to scroll all the way to the top of the logs quickly
then scroll back down. This way it stops sticking you to the bottom. Maybe
that gives anymore indication of the cause.

**Comment by xtremerui** [comment] 2023-11-15 02:57
closing stale issue.

**Closed by xtremerui** 2023-11-15 02:57 UTC
Labels: bug, needs-investigation, web-ui, help wanted
