### ISSUE TITLE
Build UI task output never stops loading

### ISSUE THREAD

**Issue by erikatniche** [concourse/concourse#781] opened 2016-11-16 20:22 UTC
* Concourse version: `v2.4.0`
* Deployment type: binaries on Ubuntu 14.04; 2 worker machines, 1 machine with web/worker/postgres
* OS: Windows 7
* Browser: Chrome Version 54.0.2840.99 m

Job/task output never loads in the build UI. The loading indicator spins forever: 
![image](https://cloud.githubusercontent.com/assets/9382249/20364169/1ec69054-ac10-11e6-9f7a-a76e27fe2ead.png)

Directly requesting the events URL (`http://devvm-concourse:8080/api/v1/builds/718/events`, for example) also hangs forever.

If I shut down the ATC process, the event stream flushes and the output shows up as expected.

**Comment by vito** [comment] 2016-11-29 19:07
If you've got a reverse-proxy, make sure it's not buffering the response.

**Comment by erikatniche** [comment] 2016-11-29 19:39
There is no reverse proxy. We access Concourse directly through the ATC's port 8080.

**Comment by darthlukan** [comment] 2016-11-30 22:14
We're also seeing this behavior:

Concourse version: 2.5.0
Deployment type: Docker on AWS using the provided [docker-compose.yml](http://concourse.ci/docker-repository.html)
OS: Linux (Ubuntu 16.04.1 LTS AMI)
Browser: Chrome 54.0.2840.100 (64-bit)

While the task is running, if I repeatedly refresh the job page, I might get some output, but once it completes, it goes right back to loading. Trying to view the output of previously completed jobs results in the same behavior: Infinite loading indicator just as is display in the OP.

**Comment by johnrengelman** [comment] 2016-12-01 17:19
I'm also experiencing this issue but my concourse-web server is behind an AWS ELB.
hitting the /events endpoint directly, returns output, it's just never rendered on the page.
Chrome will eventually report a `net::ERR_INCOMPLETE_CHUNKED_ENCODING` error as well.

**Comment by johnrengelman** [comment] 2016-12-01 17:51
My issue was related to another LB int he chain (Traefik). Removing that and it works fine.

**Comment by darthlukan** [comment] 2016-12-14 19:49
I just updated to Concourse 2.5.1 and this issue is not present (I can go back in the UI and see the output from previous builds as well!). It does not get stuck at "Loading", instead I see what I expect: Output from the build.

**Comment by erikatniche** [comment] 2016-12-14 20:49
I'm still seeing improper behaviour. Changes from original bug filing:
Concourse: v2.5.1
Chrome: 55.0.2883.87 m

**Comment by mastercactapus** [comment] 2017-02-14 20:30
Seeing this in 2.7.0, for some jobs, not others

In the console:

```
failed to fetch plan: UnexpectedPayload "Expecting an object at _.inputs[0].version but instead got: null"
```

**Comment by mastercactapus** [comment] 2017-02-16 19:46
@erikatniche do you have any resources (probably output-only) that output something like echo "{}"?

I found that the versioned_resources table had values where version='null' that caused issue. Removing those entries allowed those builds to load in my case. 

I updated the resource types' /opt/resource/in to `jq "{version: .version}"` (pass-through version) and so far smooth sailing. At least until a proper fix can be pushed out.

**Comment by pepito987** [comment] 2017-04-12 17:30
Hi, I'm having issues as well. The only way so far is to stop the ATC process.
I also tried to hit the api endpoint but with the same result (keep loading) `api/v1/builds/BUILD_ID/events`
Running with:
osx: 10.11.6
Chrome:  57.0.2987.133 (64-bit)
Vagrant: 1.9.1
VBoxManage: 5.1.14r112924

**Comment by ti-mo** [comment] 2017-05-05 14:40
Hi, also facing the same issue:

```
failed to fetch plan: BadPayload "Expecting an object at _.inputs[3].version but instead got: null"
```

Concourse 2.7.4

I assume this is a problem with a custom resource type we're running; any idea how this can be fixed systematically?

**Comment by ti-mo** [comment] 2017-05-08 12:59
I've been able to track down our instance of this error to a misbehaving custom resource type we were using.

In `in`, it has: `echo '{}' >&3`. This is returned by the job status endpoint as:
```
{
  "inputs": [
    {
      ...
      "version":null,
    }
}
```

We've made a small change to this `echo` statement in the `in` script of this resource and turned it into `echo '{"version":{"ref":"none"}}'`, like the Slack notification resource does.

This solved the problem for us!

**Comment by derBroBro** [comment] 2017-05-25 16:12
I had the same issue and for me the AntiVirus (sophos) blocked the /events url. Other concourse urls where not affected.

**Comment by chendrix** [comment] 2017-06-06 01:15
I'm inclined to close this because I see 1) improper behavior from custom resource types, and 2) issues with external software

**Closed** 2017-08-14 14:57 UTC
Labels: area: web-ui, workflow: go-around

**Comment by loafoe** [comment] 2018-02-05 19:13
For anyone who has Sophos installed, turning OFF the "Block malicious downloads from websites.." option in the Web Filtering section fixes the issue

**Alternative fix**: Serve Concourse on HTTPS (TLS)

<img width="764" alt="screen shot 2018-02-05 at 20 05 17" src="https://user-images.githubusercontent.com/14123216/35823687-a7230108-0ab0-11e8-9d92-4cc3048d5fee.png">

**Comment by gunta** [comment] 2019-04-04 08:30
This looks like the root cause. https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/sophos-anti-virus-for-mac-home-edition/5750/sophos-av-blocks-server-sent-events-sse-on-mac-os-x-yosemite

**Comment by vito** [comment] 2019-10-16 20:15
@oversize Sounds like https://github.com/concourse/concourse/issues/4493 - we're fixing it! :+1:
