### ISSUE TITLE
Problem with cf auth configuration

### ISSUE THREAD

**Issue by stoennies** [concourse/concourse#4880] opened 2019-12-11 11:33 UTC
## Bug Report

I have an issue with the configuration of a team. I have the following configuration:
```roles:
- name: owner
  cf:
    users: ["OWNER1"]
- name: member
  cf:
    spaces: ["ORG:SPACE-NAME_1"]
- name: pipeline-operator
  cf:
    spaces: ["ORG_SPACE-NAME_2"]
- name: viewer
  cf:
    orgs: ["ORG"]
```

And the OWNER1 is member of the cf space SPACE_NAME_1.
When I log into concourse as OWNER1 I recieve the role member and not owner.
Why? 

## Version Info

* Concourse version: 5.7.2

**Comment by xtremerui** [comment] 2019-12-12 20:04
Could you double check that your username is correct (must be exact the same as in CF UAA)?

**Comment by stoennies** [comment] 2019-12-13 07:44
Ok I just did:

`cf space-users ORG SPACE`

I recieve
`SPACEMANAGER
USERX
`

And this is exact the same string I provide in my yml file.

**Comment by pivotal-jamie-klassen** [comment] 2019-12-13 13:01
@stoennies I'm wondering if this might be a duplicate of #4399. How did you determine that you are receiving the `member` role and not the `owner` role? Do you actually get `not authorized` errors when you try to reconfigure the team with a command like `fly set-team` or `fly rename-team`? Or does the web UI just show a chip that says `MEMBER` beside that team's name on the dashboard? If `fly userinfo` has something like `<team name>/owner` in the output then I think we're in this scenario.

**Closed** 2020-02-18 17:44 UTC
Labels: bug, wontfix
