### ISSUE TITLE
When `get` step specifies a version I don't have to `fly check-resource` for it

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#2863] opened 2018-11-23 17:15 UTC
## What challenge are you facing?

My team currently pins dependencies in the get steps using the `version` field.
When we duplicate a pipeline for a feature branch this means that we have to run `fly check-resource` for any dependency with newer versions.
It's a no brainer to run `fly check-resource` except if you forget it takes a bit of a brain to realize why some jobs aren't running. So it's kind of a semi-brainer.

## What would make this better?

I dunno if it would be problematic to automatically check for pinned resource versions, but if it's not it would be a minor quality of life improvement for people who generate feature-branch pipelines with pinned resource versions in the get steps.

## Are you interested in implementing this yourself?

Not really.

**Comment by dprotaso** [comment] 2018-11-23 17:16
> Not really.

😢

**Comment by ralekseenkov** [comment] 2018-11-29 20:33
What happens if you don't call `fly check-resource`?
We had issues with some hanging jobs waiting for new resource versions, but I don't know if it's the same issue or not.
It would be great to have a short step-by-step repro example.

**Comment by danger-ranger** [comment] 2018-12-04 15:01
I don't have time to run this experiment right now but this is what I think the current behaviour is

1. Write a pipeline yml with a single job with a single get step
1. In the get step specify a version that is not latest
1. Set the pipeline
1. Trigger the job
1. Observe that the job is "waiting for a suitable set of input versions"
1. Use fly to force check for that version of the resource: `fly check-resource --from`
1. Observe that the job starts and succeeds.

**Comment by vito** [comment] 2019-01-29 21:02
Closing this as it's a dupe of https://github.com/concourse/concourse/issues/882.

As mentioned in #882 this should be fixed with concourse/rfcs#1 where `check` will return all versions, not just starting from pipeline configure time.

**Closed by vito** 2019-01-29 21:02 UTC
Labels: triage
