### ISSUE TITLE
ATC/fly quietly treats resource-fetching container like it is the check container for an instance of the resource

### ISSUE THREAD

**Issue by donaldguy** [concourse/concourse#958] opened 2017-03-10 01:17 UTC
# Bug Report

## The bug

During initial fetch (and possibly periodically later) of a new `resource_type` the container doing that (generally) docker fetching masquerades as a check container for the (first?) resource of the type.

This results, especially in instances where resource image fetch is failing (e.g. because of concourse/docker-image-resource#43 ), in the appearance that concourse is creating check containers for a resource using the wrong image!

`fly cs` shows a line like
```
af634975-c0f2-4b45-478c-fef46b7e99a4  00:04:17  00:05:00  i-99999  dg.ci-npm-cache  none       none  none  check  npm-factory-both     n/a

```

`fly check-resource` gives the output of `concourse/docker-image-resource`'s `/opt/resource/check`

`fly hijack` quietly drop you into the container trying to fetch the resource image.

## UX Suggestions

Very possibly `fly set-pipeline` that introduces a new resource_type should not return until that image has been successfully fetched to at least one worker and return an appropriate error message after some amount of failure.

To the extent that lazily loading resources is desirable:

I would prefer that a resource fetching container be (e.g. in `fly cs`) a unique type of container, neither `get` nor `check`, possibly `resource-check` or if one doesn't want to disrupt table layout, `resck`, `resrx`. Either the above or the name associated with the container should be the name of the resource type not of the resource using it.

To the extent the shadowing is architecturally expedient, a flag should be added to mark these and `fly check-resource` or an uncontested hijack should include ouput such as `WHILE LOADING NEW RESOURCE_TYPE FOR THIS RESOURCE!!: `

a menu for hijack should include some indication. Currently in the transient state of shortly after fetch you see
```
1: resource: npm-factory-both, type: check
2: resource: npm-factory-both, type: check
3: resource: npm-factory-both, type: check
```

It would be better to either be as

```
1: resource: npm-cache, type: check
2: resource: npm-cache, type: check
3: resource: npm-factory-both, type: check
```

```
1: resource: npm-factory-both, type: check, FOR RESOURCE_TYPE
2: resource: npm-factory-both, type: check, FOR RESOURCE_TYPE
3: resource: npm-factory-both, type: check
```

or if, as I gather there is a possibility of new versions of a resource being fetched between runs of a pipeline, it may just be desirable to do as e.g.

```
1: resource: npm-factory-both, type: check, source: {repository: concourse/docker-image-resource, tag: latest}, version: sha256:e50ba
2: resource: npm-factory-both, type: check, source: {repository: concourse/docker-image-resource, tag: latest}, version: sha256:e50ba
3: resource: npm-factory-both, type: check, source: {repository: ymedlop/npm-cache-resource, tag: } version: sha256:9f6d
```

## My sob story

I was trying to make use of https://github.com/ymedlop/npm-cache-resource

I wrote:
```yaml
resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: 6}
```

I followed the rest of that resources README and instantiated an instance of that resource as
```
- name: npm-factory-both
  type: npm-cache
  source:
    <<: *src-factory-git-source
...
```

`fly set-pipeline` happily accepted the submission and the jobs using this new resource type promptly hung with no available versions.

had I run it, `fly validate-pipeline` also wouldn't have complained (verified after the fact).

Being no stranger at debugging concourse, I ran `fly check-resource -r dg.ci-npm-cache/npm-factory-both` and got back

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to read request: json: cannot unmarshal number into Go value of type string
```
If  you are concourse-omniscient or better at google than I was, you might recognize this as concourse/docker-image-resource#43 but I did not. Working with a new third party resource I assumed I had screwed up configuring it. But there weren't really any numbers in my `source:` so I was pretty confused

My next step was to run `fly hijack -c  dg.ci-npm-cache/npm-factory-both` and I promptly got a bash prompt with no sign of any trouble.

I was looking at the source for https://github.com/ymedlop/npm-cache-resource/blob/master/assets/check so I figured in there might be a good place to inject some logging. I went to edit the file, and to my surprise `/opt/resource/check` was a binary!

Looking around the container, it became clear this was a concourse/docker-image-resource container. Given that `fly cs` listed it as a check container for this resource, and that manually `docker pull`ing and `docker run`ing the image elsewhere I verified it matched the source, I was left to conclude that concourse was using the wrong image for the resource! I was very confused.

After about 45 minutes of confusion, while digging through ATC logs, I noticed the check output was the same as the data attached to the messages tagged `atc.syncer.dg.ci-npm-cache:radar.scan.tick.init.image.failed-to-get-latest-image-version`.

Finally it clicked that where there *was* a number was in the tag portion of my resource_type block. I added quotes around it, and found that now `fly hijack -c  dg.ci-npm-cache/npm-factory-both` offered me a choice of three check containers to hijack: the first two matching the docker-image-resource image and the third matching the ymedlop/npm-cache-resource image

@mariash on slack confirmed that:
>I just verified locally with custom resource. It creates several check containers. One for docker image, for resource type and for resource itself. So if you hijack into the one for resource it will give you correct container, not docker image one

Now in the steady state post change, running `fly hijack -c  dg.ci-npm-cache/npm-factory-both` puts me in a correct looking container immediately and indeed my job in my pipeline ran! (and promptly failed due to native npm module dependencies, as I expected 😞 )

* Concourse version: 2.7.0
* Deployment type (BOSH/Docker/binary): binary on Ubuntu 16.04
* Infrastructure/IaaS: AWS

**Comment by vito** [comment] 2017-05-09 15:39
This should be fixed with v2.8.0 once we ship the "life" refactor. Check containers for custom resource types and `image_resource`s in a task are now associated with a more abstract "resource config" rather than the origin of the check. This also means hijacking a task that uses an `image_resource` will now hop you right in to the task rather than asking if you want to hijack the `check` or the `get` of the task.

To fix the root cause of this, though, we'll want to add visibility into the resource types themselves. Resources show up as orange boxes in the pipeline, and they may even have errors from their custom types bubble up into them, but having visibility isolated to just the custom types would greatly help.

In any case, I'm gonna close this as the original issue as reported (confusion between check containers) should now be fixed. :)

**Closed** 2017-05-09 15:39 UTC
Labels: troubleshooting
