### ISSUE TITLE
UI feature request: "favorite" pipelines

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#4610] opened 2019-10-17 05:05 UTC
## What challenge are you facing?

In our practice, some team has a lot of pipelines, out from those pipelines, the team admin regularly keep eyes on a few pipelines only. But the team admin is always frustrated with finding a pipeline from a long list.

## What would make this better?

If Concourse UI allows user to mark "favorite" pipelines, then team admins in question will be more than happy.

To extend the idea, it would be even better is user can tag pipelines and filter pipelines by tags.

## Are you interested in implementing this yourself?

No. As I, as well as my team, are all backend developers, we are not familiar with frontend UI development.

**Comment by pivotal-jamie-klassen** [comment] 2019-10-21 16:24
#4279 seems related, and this issue itself might be a duplicate of #2647 - @evanchaoli do you think we need both?

**Comment by evanchaoli** [comment] 2019-10-21 19:32
@pivotal-jamie-klassen I think #2647 is what I need.

**Closed** 2019-10-22 13:32 UTC
Labels: enhancement, web-ui
