### ISSUE TITLE
concourse/bin should supply required uid gid mapping flags to Garden 1.9.5

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#1740] opened 2017-10-24 10:45 UTC
Paired with @callisto13 on [an issue in the Garden backlog](https://www.pivotaltracker.com/story/show/152196483) around Concourse and Garden runC 1.9.5. 

Here's what we found:

As part of [#150710163](https://www.pivotaltracker.com/n/projects/1158420/stories/150710163), the flags for `--garden-uid-map-start` `--garden-uid-map-length` `--garden-gid-map-start` `--garden-gid-map-length` are now required on the `GardenServer`, but `concourse/bin` doesn't set defaults for, or require those flags to be passed.

We should consider having sane defaults in `worker_linux.go` (here's what Garden does in [their ctl script](https://github.com/cloudfoundry/garden-runc-release/blob/13b9548733dd8a1c1bb87256ebe8d797dae97b45/jobs/garden/templates/garden_ctl.erb#L323-L326)), and optionally allow them to be set (which works currently).

Might want to also consider how this can be used to limit the ability for privileged containers at the Garden server level, and implications this has on running Concourse binaries in Docker / K8s

**Comment by vito** [comment] 2017-10-24 13:03
Ah that makes sense. Good find!

**Comment by Callisto13** [comment] 2017-10-24 13:34
Hey @vito - don't rush to do this just yet... we decided that this should have sensible defaults and that we shouldn't be breaking expected behaviour

**Comment by vito** [comment] 2017-10-24 13:40
@Callisto13 Ok, thanks! 👍

**Comment by Callisto13** [comment] 2017-10-25 09:45
@vito 
We have now pushed a fix in Garden to calculate defaults for these mapping ranges. This should appear in the next release so feel free to close this issue.
If you want to go ahead and use 1.9.5, setting the values to the ones Garden uses in its [ctl script](https://github.com/cloudfoundry/garden-runc-release/blob/13b9548733dd8a1c1bb87256ebe8d797dae97b45/jobs/garden/templates/garden_ctl.erb#L323-L326) will work.

**Comment by jama-pivotal** [comment] 2017-10-30 17:53
Closing this issue since Garden now calculates defaults

**Closed by jama-pivotal** 2017-10-30 17:53 UTC
Labels: deployment: binary, deployment: docker, deployment: docker-compose, deployment: kubernetes
