### ISSUE TITLE
fly execute ignoring `.git` directory for input

### ISSUE THREAD

**Issue by TimJones** [concourse/concourse#2173] opened 2018-04-20 10:01 UTC
# Bug Report

I'm writing a task that works off [GitHub Pull Requests](https://github.com/jtarchie/github-pullrequest-resource) and using `fly execute` to test it. I noticed that it was always failing when I tried interacting with anything from the `.git` dir. So I isolated my case and noticed that when the local directory is passed to the worker as an input, the `.git` directory is ignored.

test-git.yaml:
```yaml
---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: busybox
inputs:
  - name: project-pr
run:
  path: ls
  args:
    - -lAh
    - project-pr

```

```shell
$ fly-sah execute --config ci/tasks/git-test.yaml --input project-pr=.
executing build 47459 at https://ci.spotahome.net/builds/47459 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  693k    0  693k    0     0   693k      0 --:--:-- --:--:-- --:--:-- 5827k
initializing
Pulling busybox@sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64...
sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64: Pulling from library/busybox
f70adabe43c0: Pulling fs layer
f70adabe43c0: Verifying Checksum
f70adabe43c0: Download complete
f70adabe43c0: Pull complete
Digest: sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64
Status: Downloaded newer image for busybox@sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64

Successfully pulled busybox@sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64.

running ls -lAh project-pr
total 2080
-rw-r--r--    1 1000     1000          47 Apr  4 11:03 .dockerignore
-rw-r--r--    1 1000     1000         909 Apr  9 15:37 .env
-rw-r--r--    1 1000     1000         579 Mar 15 15:12 .gitignore
-rw-r--r--    1 1000     1000         607 Mar 15 15:12 .php_cs.dist
-rw-r--r--    1 1000     1000        2.4K Mar 15 15:12 README.md
drwxr-xr-x    1 root     root          36 Apr 20 09:53 bin
drwxr-xr-x    1 root     root          12 Apr 20 09:53 charts
drwxr-xr-x    1 root     root         112 Apr 20 09:53 ci
-rw-r--r--    1 1000     1000        2.3K Apr  4 11:03 composer.json
-rw-r--r--    1 1000     1000      227.0K Apr  4 11:03 composer.lock
-rw-r--r--    1 1000     1000        1.8M Mar 15 15:12 composer.phar
drwxr-xr-x    1 root     root         106 Apr 20 09:53 doc
drwxr-xr-x    1 root     root         136 Apr 20 09:53 docker
drwxr-xr-x    1 root     root          20 Apr 20 09:53 git-hooks
drwxr-xr-x    1 root     root           8 Apr 20 09:53 keyrings
-rw-r--r--    1 1000     1000        1.3K Mar 15 15:12 phpstan.neon
-rw-r--r--    1 1000     1000         473 Mar 15 15:12 phpunit.xml
drwxr-xr-x    1 root     root          74 Apr 20 09:53 scripts
drwxr-xr-x    1 root     root          54 Apr 20 09:53 var
succeeded

$ ls -lAh
total 2.1M
drwxr-xr-x  2 tim tim  4.0K Mar 19 16:54 bin/
drwxr-xr-x  3 tim tim  4.0K Mar 15 16:12 charts/
drwxr-xr-x  4 tim tim  4.0K Apr 20 10:52 ci/
drwxr-xr-x  3 tim http 4.0K Mar 28 18:17 .composer/
-rw-r--r--  1 tim tim  2.3K Apr  4 13:03 composer.json
-rw-r--r--  1 tim tim  227K Apr  4 13:03 composer.lock
-rw-r--r--  1 tim tim  1.8M Mar 15 16:12 composer.phar
drwxr-xr-x  4 tim tim  4.0K Mar 19 16:54 doc/
drwxr-xr-x  2 tim tim  4.0K Apr 19 17:07 docker/
-rw-r--r--  1 tim tim    47 Apr  4 13:03 .dockerignore
-rw-r--r--  1 tim tim   909 Apr  9 17:37 .env
drwxr-xr-x  7 tim tim  4.0K Apr 20 11:56 .git/
drwxr-xr-x  2 tim tim  4.0K Mar 15 16:12 git-hooks/
-rw-r--r--  1 tim tim   579 Mar 15 16:12 .gitignore
drwxr-xr-x  3 tim tim  4.0K Mar 15 16:12 keyrings/
-rw-r--r--  1 tim tim   607 Mar 15 16:12 .php_cs.dist
-rw-r--r--  1 tim tim  1.4K Mar 15 16:12 phpstan.neon
-rw-r--r--  1 tim tim   473 Mar 15 16:12 phpunit.xml
-rw-r--r--  1 tim tim  2.5K Mar 15 16:12 README.md
drwxr-xr-x  2 tim tim  4.0K Mar 15 16:12 scripts/
drwxr-xr-x  4 tim tim  4.0K Mar 15 16:12 var/
drwxr-xr-x  2 tim tim  4.0K Mar 28 15:59 web/
```

I was also surprised to see that directory ownership is changed, but not file ownership.

* Concourse version: 3.9.1
* Deployment type: Docker on K8S (ATC), binary on ASG (workers)
* Infrastructure/IaaS: AWS

**Comment by xtremerui** [comment] 2018-04-20 17:59
@TimJones have you tried running `fly execute --include-ignored` ?

**Comment by jama-pivotal** [comment] 2018-05-02 15:05
@TimJones was @xtremerui 's suggestion able to help you?

**Comment by jasonkeene** [comment] 2018-05-19 02:07
`--include-ignored` worked for my situation, I just found it odd since `.git` dir is not ignored. I'd like to be able to include `.git` without including files that are ignored since `.git` is required for some tasks and I don't want to upload ignored files that could be very large just to get `.git`. Perhaps this should be the default behavior or perhaps a flag?

**Comment by vito** [comment] 2019-01-03 16:49
@jasonkeene We actually make sure to ignore `.git` as it tends to grow pretty large, so I personally would rather have it ignored by default as this only affects tasks that actually run `git` operations and ignoring it really helps tighten up feedback loops (more often than not) .

I'm going to close this as it's working as intended and this is unlikely to be something we have the bandwidth for ourselves. For now I'd suggest just using `--include-ignored`, though I'd be happy to see a PR to add another flag like `--include-git` or something, since it seems pretty trivial.

**Closed by vito** 2019-01-03 16:49 UTC

**Comment by KleptoKat** [comment] 2019-03-08 03:00
> @jasonkeene We actually make sure to ignore `.git` as it tends to grow pretty large, so I personally would rather have it ignored by default as this only affects tasks that actually run `git` operations and ignoring it really helps tighten up feedback loops (more often than not) .
> 
> I'm going to close this as it's working as intended and this is unlikely to be something we have the bandwidth for ourselves. For now I'd suggest just using `--include-ignored`, though I'd be happy to see a PR to add another flag like `--include-git` or something, since it seems pretty trivial.

I would love an include-git command as I have found myself unable to upload a repo because of an included node_modules folder which is getting in the way of me testing my execution locally. I've resorted to uploading the repo to git and testing it from a pipeline.
