### ISSUE TITLE
Navigating back from job to pipeline sometimes results in blank page

### ISSUE THREAD

**Issue by georgehaidar** [concourse/concourse#805] opened 2016-12-04 22:43 UTC
# Bug Report

Open a job page then hit `Cmd-[` to go back to pipeline page and it will be blank as in the screenshot attached. If this doesn't happen immediately, try a few times. Interestingly, I am unable to get into this bad state if I click the back button on the browser - only happens using the keyboard shortcut.

* Concourse version: 2.5.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: AWS ECS
* Browser (if applicable): Chrome 55.0.2883.75 (64-bit) on OS X El Capitan 10.11.6
* Did this used to work? Yes

<img width="1440" alt="screen shot 2016-12-05 at 9 29 48 am" src="https://cloud.githubusercontent.com/assets/17603282/20869810/bbcf79e8-bace-11e6-9c8b-00608d6cf8ac.png">

**Comment by vito** [comment] 2016-12-05 00:24
Dupe of https://github.com/concourse/concourse/issues/738 - but thanks for providing the info, it may help.

**Closed by vito** 2016-12-05 00:24 UTC
Labels: unscheduled
