### ISSUE TITLE
Non-existent pipeline throws insufficient error message

### ISSUE THREAD

**Issue by ascherbaum-pivotal** [concourse/concourse#756] opened 2016-11-07 21:58 UTC
# Feature Request

## What challenge are you facing?

If a pipeline does no longer / not exist, the CI website throws a general error: "experiencing turbulences". That is in no way helpful!

The website should instead state: "404 - pipeline not found", or something similar useful.

**Comment by chendrix** [comment] 2017-05-23 22:41
Closing as duplicate of #1131

**Closed by chendrix** 2017-05-23 22:41 UTC
