### ISSUE TITLE
Titles for pipelines

### ISSUE THREAD

**Issue by SpaceTrucker2196** [concourse/concourse#1702] opened 2017-10-06 16:10 UTC
# Feature Request
Add a option for a title on the pipeline web view

## What challenge are you facing?

A number of our builds have similar pipeline have a similar look and it's hard to tell on a distant build monitor what build you're looking at. Add and option for a title block above the pipeline.

**Comment by pn-santos** [comment] 2018-03-01 16:03
Just pointing out that his issue is duplicate of #295

**Closed** 2019-04-08 15:26 UTC
Labels: enhancement, web-ui
