### ISSUE TITLE
Providing --external-url without http causes auth to fail in strange ways

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#485] opened 2016-06-19 01:17 UTC
Without supplying `http:` on a `concourse web ..... --external-url....` command, auth redirect pops into my url but never does anything. This is both frustrating and mysterious. Perhaps some validation on the cli side or better messaging on the auth side could help this.

**Comment by vito** [comment] 2016-06-19 02:06
what version of concourse? this should be fixed already

**Comment by jadekler** [comment] 2016-06-19 21:10
```
[ec2-user@ip-172-31-30-19 ~]$ concourse -v
1.3.1
```

**Comment by vito** [comment] 2016-07-05 20:53
Seems to work here:

```
~/g/s/g/c/bin (master) $ concourse -v
1.3.1
~/g/s/g/c/bin (master) $ concourse web --external-url google.com
invalid argument for flag `--external-url' (expected atccmd.URLFlag): missing scheme in 'google.com'
```

**Comment by vito** [comment] 2016-07-15 14:30
Closing partly due to inactivity and partly because we can't reproduce it. Reopen if you can though!

**Closed by vito** 2016-07-15 14:30 UTC
Labels: in-flight
