### ISSUE TITLE
Concourse resource to write to Google chat spaces 

### ISSUE THREAD

**Issue by sethiyash** [concourse/concourse#8956] opened 2024-05-02 12:53 UTC
## Summary
Looking for a concourse resource or some other way to notify about the pipeline status on the google chat spaces.
I have found [this](https://github.com/CloudInn/concourse-hangouts-resource) but doesn't looks like it gets managed anymore. 
Other, is [this](https://github.com/spring-io/google-chat-notify-resource) one but looks like this has not been publised yet. 
Is there any way if I have the Google Chat webhook URL I can post the message. 

I have also tried doing:
```
curl -H 'Content-Type: application/json' -d "{\"text\": \"$text_content\"}" "$webhook_url"
```
This works from my local but when trying to do it from the concourse pipeline it throws following error:
```
{
  "error": {
    "code": 403,
    "message": "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.",
    "status": "PERMISSION_DENIED"
  }
}
```

## Triaging info

* Concourse version:
* Browser (if applicable):
* Did this used to work?

**Comment by taylorsilva** [comment] 2024-05-02 16:33
Closing because not a bug and you already opened a discussion post about this.

**Closed by taylorsilva** 2024-05-02 16:33 UTC
Labels: bug
