### ISSUE TITLE
Low contrast text in build-header when build is running 

### ISSUE THREAD

**Issue by Scottapotamas** [concourse/concourse#7777] opened 2021-11-09 07:24 UTC
## Summary

The text in the `build-header` uses `#e2e2e2`. With the light yellow background `#fad43b`used when the build is in flight, this text is pretty hard to read compared to previous versions.

![image](https://user-images.githubusercontent.com/460325/140876477-70fefa21-dc25-4ee3-8c12-876f178405f7.png)

To provide an objective comparison between other display states, the 'in progress' state gets a WCAG Colour and Contrast values of 1.11 for the `buildname #num` text.

## Expected results

For reference, the background colours used for other build states are at least legible (though some don't meet accessibility recommendations

Build success - 1.91 !

![image](https://user-images.githubusercontent.com/460325/140877072-e6ad7fc0-3d06-4d27-8755-ab96af235d21.png)

Build error - 1.92 !

![image](https://user-images.githubusercontent.com/460325/140877124-12215193-71ba-4517-82a7-9a3981732dc8.png)

Build fail - 3.03 AA

![image](https://user-images.githubusercontent.com/460325/140877159-9e6f9523-2440-4fc5-ae2e-894919505a42.png)

Build cancelled - 6.45 AAA

![image](https://user-images.githubusercontent.com/460325/140877491-2361065b-e166-41a9-9751-26467b7013dc.png)

## Additional Context

![image](https://user-images.githubusercontent.com/460325/140876429-cae9c830-134c-49d4-8430-9eaac0e3c395.png)

## Triaging info

- `Concourse 7.6.0`
- `Firefox 94.0`
- `Chrome 95.0.4638.69`
- Previous colour scheme in `7.4.0` didn't have this issue.
- "Flawless eyesight", Solus Linux `5.14.16-204` + nVidia `470.82.00`

Probably related to changes in https://github.com/concourse/concourse/pull/7497?

**Comment by taylorsilva** [comment] 2021-11-09 20:25
Duplicate of #7752 and resolved by #7756

**Closed by taylorsilva** 2021-11-09 20:25 UTC
Labels: bug
