### ISSUE TITLE
web/tsa: Missing TSA host-key results in panic on startup

### ISSUE THREAD

**Issue by mastercactapus** [concourse/concourse#4010] opened 2019-06-12 21:26 UTC
## Bug Report

Panic on startup when TSA host key is missing.

## Steps to Reproduce

Start `concourse web` with tsa-host-key unset

## Expected Results

Assuming it is required, output a somewhat descriptive error message.

If not required, then normal startup.

## Actual Results

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f0f55]

goroutine 1 [running]:
crypto/rsa.(*PrivateKey).Public(0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/rsa/rsa.go:100 +0x5
golang.org/x/crypto/ssh.NewSignerFromSigner(0x7f875d7a1038, 0xc000011690, 0xc000011690, 0x7f875d7a1038, 0xc000011690, 0x417201)
	/tmp/build/70f2e240/gopath/pkg/mod/golang.org/x/crypto@v0.0.0-20190313024323-a1f597ede03a/ssh/keys.go:720 +0x35
golang.org/x/crypto/ssh.NewSignerFromKey(0x1baa020, 0xc000011690, 0x37e78b0, 0xc0008eb500, 0x7f875d81a6d0, 0x0)
	/tmp/build/70f2e240/gopath/pkg/mod/golang.org/x/crypto@v0.0.0-20190313024323-a1f597ede03a/ssh/keys.go:695 +0x1c2
github.com/concourse/concourse/tsa/tsacmd.(*TSACommand).configureSSHServer(0xc0000aa9c0, 0xc000778530, 0xc000a5ce10, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc0009ba460, 0x0, ...)
	/tmp/build/70f2e240/concourse/tsa/tsacmd/command.go:178 +0x2af
```

## Version Info

* Concourse version: 5.3.0 (upgrading from 5.0.1)
* Deployment type (BOSH/Docker/binary): Kubernetes/docker
* Did this used to work? On version 5.0.1 it did (even if it shouldn't have)

**Comment by pivotal-bin-ju** [comment] 2019-06-14 15:23
Hi @mastercactapus,

I could not reproduce this bug today.
I tried concourse `5.3.0`,  and `5.0.1`. both of them looks fine.

I ran the command:

```
~/w/concourse ((v5.0.1)) $ docker run -it --rm concourse/concourse:v5.0.1 web
```
and the output was:

```
{"timestamp":"2019-06-14T15:03:35.248499800Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
{"timestamp":"2019-06-14T15:03:35.257634800Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 127.0.0.1:5432: connect: connection refused","session":"3"}}
{"timestamp":"2019-06-14T15:03:40.267821100Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 127.0.0.1:5432: connect: connection refused","session":"3"}}
{"timestamp":"2019-06-14T15:03:45.282999700Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 127.0.0.1:5432: connect: connection refused","session":"3"}}
{"timestamp":"2019-06-14T15:03:50.293949900Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 127.0.0.1:5432: connect: connection refused","session":"3"}}
{"timestamp":"2019-06-14T15:03:55.308513100Z","level":"error","source":"atc","message":"atc.db.failed-to-open-db-retrying","data":{"error":"dial tcp 127.0.0.1:5432: connect: connection refused","session":"3"}}
```
If you look at the Dockerfile under `concourse` folder, we have:

```
... ...

RUN mkdir -p /concourse-keys
RUN concourse generate-key -t rsa -b 1024 -f /concourse-keys/session_signing_key
RUN concourse generate-key -t ssh -b 1024 -f /concourse-keys/tsa_host_key
RUN concourse generate-key -t ssh -b 1024 -f /concourse-keys/worker_key
RUN cp /concourse-keys/worker_key.pub /concourse-keys/authorized_worker_keys
```
Keys are generated when we build the container image.

Did you build `concourse` on your own (on mac) ? 
Any `rsa` package (through some tool like `openssl`) on your env?

**Comment by pivotal-jamie-klassen** [comment] 2019-08-02 12:28
We might have discovered the underlying issue here: #4138, but just in case this is not related to the environment variable thing I won't close this.

**Closed** 2019-10-08 13:43 UTC
Labels: bug, wontfix
