### ISSUE TITLE
Jobs start without getting triggered

### ISSUE THREAD

**Issue by RaphaelVogel** [concourse/concourse#4258] opened 2019-08-12 08:38 UTC
## Bug Report
Concourse (since 5.3) keeps triggering some jobs repeatedly, without any trigger, resulting in unnecessary (even harmful) job executions. This happens occasionally.

## Steps to Reproduce
We us a pipeline like this here (shortened): https://gist.github.com/RaphaelVogel/d55c473cafe6948c6e7d51da9dbf6bf2
The git resource (`git-kubernetes-staging_landscape-staging-garden-master_master`) is not triggering, only the time resource, but we see jobs get triggered more often than the 4h time intervall.  

## Expected Results
Jobs should only start every 4h

## Version Info

* Concourse version: 5.3
* Deployment type (K8s helm chart):

**Comment by itsdalmo** [comment] 2019-08-12 11:55
I think we might be seeing the same issue here, I detailed my own here https://github.com/concourse/concourse/issues/3910; as a user the outcome is that jobs might trigger for no apparent reason.

**Comment by clarafu** [comment] 2019-08-12 15:20
@RaphaelVogel That's interesting, for those builds that got triggered more often than the 4h time interval, can you show me which resource that build triggered off of? (It should show a yellow arrow for the resource that is triggered off of). Would you also be able to double check that those builds were not manually triggered? You can check that through finding one of those builds that got triggered before the 4h time interval (you can find them by looking for a build that has no yellow arrows indicating which resource the build triggered off of) and peek into your db and check the `manually_triggered` field on the builds table for that build. Thanks!

**Comment by robwhitby** [comment] 2019-08-14 17:24
Not sure, but I think we are seeing the same bug too. A job is triggered with the same inputs that have already passed. None of the resources have a yellow arrow, and `manually_triggered = false` in the db.

It seems like it *might* happen when a new version appears, the job is sometimes triggered "too quick" and runs with the previous versions, with a build using the new versions then queued up behind. 

Here are 6 runs of a job (latest first) where the problem happened twice. The values of `start_time` and `create_time` I got from the `builds` table. There are 2 resource inputs, `git` and `version`. Only `version` is set to trigger builds. Both resources check every 1m.

| build | start_time | create_time | git       | version |
| ----- | ---------- | ----------- | --------- | ------- |
| 421   | 16:20:00   | 16:20:00    | d6084d38 | 0.160.0 |
| 420   | 16:06:44   | 16:01:57    | fb2c771b9 | 0.159.0 |
| 419   | 16:01:48   | 16:01:47    | 7834fac22 | 0.158.0 |
| 418   | 15:24:26   | 15:20:21    | 7834fac22 | 0.158.0 |
| 417   | 15:20:11   | 15:20:11    | cdb65c4f6 | 0.157.0 |
| 416   | 11:33:44   | 11:33:44    | cdb65c4f6 | 0.157.0 |

Build `417` is a re-run of `416`, created **10s** before `418`.  And then build `419` is a re-run of `418` **10s** before `419`.

Any suggestions on what I can do to debug further?

**Comment by clarafu** [comment] 2019-08-15 15:10
@robwhitby Thanks a lot, that's really great information! It is really interesting how the `start_time` and `create_time` of the build before is very close to the `create_time` of the build after. There might be some race condition happening and it queues up two builds almost at the same time. Would you be able to give me the structure of your resource configuration and your job config so we can try to reproduce this issue? Also do you have multiple ATCs with your Concourse cluster?

**Comment by robwhitby** [comment] 2019-08-16 14:21
@clarafu Hi, we have 3 atc nodes, below is a simplified version of the pipeline. 

* `git` resource triggers the `update` job
* `update` job puts new `version` (a semver resource)
* downstream jobs are triggered by `version` that has passed `update`

The bug only happens on the first job after the `version` is bumped.

Thanks for investigating!

![Screen Shot 2019-08-16 at 15 15 52](https://user-images.githubusercontent.com/176209/63173901-c35f1200-c038-11e9-909b-4963ef29db3a.png)

```yaml
jobs:
- name: update
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: git
        trigger: true
  - put: version
    params:
      bump: minor
    attempts: 2
  - task: update
    config:
      ...
      inputs:
      - name: git
      - name: version
    attempts: 2
- name: task 1
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: git
        passed:
        - update
      - get: version
        passed:
        - update
        trigger: true
  - task: task 1
    config:
      ...
      inputs:
      - name: git
      - name: version
```

**Comment by itsdalmo** [comment] 2019-10-16 09:12
I believe this issue is still relevant - just waiting for feedback from maintainers :)

**Comment by vito** [comment] 2019-10-21 14:59
I'm going to tentatively put this as an 'end goal' in the Algorithm v3 project in hopes that whatever mysterious behavior here is resolved by our complete redesign/rearchitecture of the scheduling/input selection algorithm.

**Comment by vito** [comment] 2020-02-20 22:06
We'll have v6.0 out with the new scheduler probably tomorrow or early next week. If this is something you still see fairly often in a particular pipeline, you could try moving that pipeline over to 6.0 and see if it fixes it. :pray: 

I'm going to close this out for now since it seems like we were never able to come up with a straightforward repro that I can really confirm that we fixed. So I guess just let me know if it still happens with 6.0 and we can reopen!

**Closed by vito** 2020-02-20 22:06 UTC
Labels: bug, core
