### ISSUE TITLE
fly execute -o results in panic: tar extract failed

### ISSUE THREAD

**Issue by baszalmstra** [concourse/concourse#541] opened 2016-07-18 10:20 UTC
Running `fly execute` on windows without -o works like a charm. Specifying -o and a directory results in this error:

```
panic: tar extract failed (write |1: The pipe is being closed.). output: ""

goroutine 7 [running]:
panic(0x8df720, 0xc082230de0)
        /usr/local/go/src/runtime/panic.go:481 +0x3f4
github.com/concourse/fly/commands/internal/executehelpers.Download(0x12b5140, 0xc08211f290, 0xc08205e090, 0x6, 0xc082056240, 0x21, 0xc0821408d0, 0x24, 0xc082157200, 0x51, ...)
        /tmp/build/84f3a02a/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x58e
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0x12b5140, 0xc08211f290, 0xc08205e090, 0x6, 0xc082056240, 0x21, 0xc0821408d0, 0x24, 0xc082157200, 0x51, ...)
        /tmp/build/84f3a02a/concourse/src/github.com/concourse/fly/commands/execute.go:103 +0x4f
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
        /tmp/build/84f3a02a/concourse/src/github.com/concourse/fly/commands/execute.go:107 +0xa29
```

**Comment by vito** [comment] 2016-08-11 03:57
think this is a dupe of https://github.com/concourse/fly/issues/86 - reopen if it doesn't seem like it. thanks!

**Closed by vito** 2016-08-11 03:57 UTC
Labels: unscheduled

**Comment by airtonix** [comment] 2017-10-27 06:59
@vito Can't see that ticket anymore so can't confirm if it is in fact a duplicate, but my fly client on windows 10, atc server in rancher on coreos is still exhibiting this problem. 

i suspect its due to that way fly assumes the path of `tar`: 

```

C:\Data\Projects\Fusion\fusion-concourse-add-pipeline-ui [master ≡ +0 ~1 -0 !]> cross-env TAG_TEMPLATE=ci/tag.tmpl fly execute -c .\ci\concourse__template-slack-message.yml -t admin -i repo=./ -o build=./dist/build
executing build 26 at http://concourse.fusion.one/builds/26
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2622k    0 2622k    0     0  28.0M      0 --:--:-- --:--:-- --:--:-- 28.4Mupload request failed: Put http://concourse.fusion.one/api/v1/pipes/5e54ad24-0e1a-496b-7015-125d267b71ba: tar compress failed (exit status 1). output: "/c/Program Files/Git/usr/bin/ta
r: .: file changed as we read it\n"
100 22.9M    0 22.9M    0     0  25.7M      0 --:--:-- --:--:-- --:--:-- 25.7M
initializing
running sh -exc cp -R ./repo/* ./build/

handlebars build/package.json < build/ci/slack-message--failure.tmpl > build/slack-message-failure
echo "Slack Success Message"
cat ./build/slack-message-failure

handlebars build/package.json < build/ci/slack-message--success.tmpl > build/slack-message-success
echo "Slack Failure Message"
cat ./build/slack-message-success

+ cp -R ./repo/Dockerfile ./repo/ci ./repo/concourse-ui.sublime-project ./repo/concourse.yml ./repo/docker-compose--build.yml ./repo/docker-compose.yml ./repo/grant.config.js ./repo/npm-debug.log ./repo/nuxt.config.js ./repo/package.json ./repo/project.sublime-
project ./repo/src ./repo/yarn-cache ./repo/yarn.lock ./build/
+ handlebars build/package.json
+ echo Slack Success Message
Slack Success Message
+ cat ./build/slack-message-failure
Build Failed concourse-ui:1.0.0
<http://concourse.rancher.fusion.one/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME[$BUILD_NAME]>+ handlebars build/package.json
+ echo Slack Failure Message
Slack Failure Message
+ cat ./build/slack-message-success
Build Success concourse-ui:1.0.0
<http://concourse.rancher.fusion.one/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME[$BUILD_NAME]>

`$ docker pull docker.fusion.com.au/concourse-ui:1.0.0`
panic: tar extract failed (exit status 2). output: "/c/Program Files/Git/usr/bin/tar: C\\:\\\\Data\\\\Projects\\\\Fusion\\fusion-concourse-add-pipeline-ui\\\\dist\\build: Cannot open: No such file or directory\n/c/Program Files/Git/usr/bin/tar: Error is not rec
overable: exiting now\n"

goroutine 38 [running]:
github.com/concourse/fly/commands/internal/executehelpers.Download(0xcfe180, 0xc0421b8070, 0xc04200a400, 0x5, 0xc0422320f0, 0x43, 0xc04221e1b0, 0x24, 0xc042232140, 0x4d, ...)
        C:/var/vcap/data/concourse_windows/containers/00003i45kht/tmp/build/734c03a2/concourse/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:30 +0x278
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xcfe180, 0xc0421b8070, 0xc04200a400, 0x5, 0xc0422320f0, 0x43, 0xc04221e1b0, 0x24, 0xc042232140, 0x4d, ...)
        C:/var/vcap/data/concourse_windows/containers/00003i45kht/tmp/build/734c03a2/concourse/src/github.com/concourse/fly/commands/execute.go:126 +0x84
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
        C:/var/vcap/data/concourse_windows/containers/00003i45kht/tmp/build/734c03a2/concourse/src/github.com/concourse/fly/commands/execute.go:124 +0x95e
```
