### ISSUE TITLE
Feature request: Concourse should store history of pipelines

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#416] opened 2016-05-03 14:21 UTC
This would allow auditing, which I imagine will be valuable in commercial/enterprise settings, as well as facilitating an easy and quick revert to a previous state of the pipeline(s).

**Comment by jchesterpivotal** [comment] 2016-06-02 15:37
We've got a hacky workaround for seeing existing logs, which is to create empty jobs with the same name as jobs we've renamed or retired.

**Comment by vito** [comment] 2016-10-06 22:08
An alternative to chew on would be to have pipelines configured as resources themselves. Then you could use a `git` repo with a pipeline .yml in it (or .ymls) and have all the audit trailing and signing from Git.

**Comment by jchesterpivotal** [comment] 2016-10-07 14:57
That's an interesting idea. Fits the save-config-to-git-then-deploy pattern. 

It leaves the question of how best to interact when you are developing or debugging a pipeline. Use `-dev` pipelines? Have a separate deployment?

**Comment by vito** [comment] 2016-10-07 15:08
@jchesterpivotal I suppose you'd just make another resource pointing at a branch. It's a tradeoff: you'll have to make git commits and pushes every time, but hey, you wanted an audit trail, right?

Alternatively you could just `set-pipeline` to a separate pipeline all day and commit and push only once you see it working over there.

**Comment by jchesterpivotal** [comment] 2016-10-20 14:52
Actually, on further reflection (meaning: stumbling on a problem), I disagree with myself that versioning through git is a win.

The problem is job renaming. If I pick the wrong name, I face a gross choice: stick with the wrong name, or lose history up to [the arrival of Confucian values](https://en.wikipedia.org/wiki/Rectification_of_names). 

It would be nice if I didn't have to do that. I don't know if this could be done with something like:

`fly rename-job --old oldname --new newname`

or

`fly set-pipeline ... --rename-job newname=oldname`

or

```
jobs:
  - name: newname
    old_names:
        - oldname
```

**Comment by vito** [comment] 2016-10-20 16:01
@jchesterpivotal The last solution there would work, and only be needed by one commit. Don't think that's particularly related to versioning with git; that problem exists today regardless.

**Comment by jchesterpivotal** [comment] 2016-10-20 20:48
I'm afraid I don't follow you at all :|

**Comment by vito** [comment] 2016-10-20 21:23
@jchesterpivotal How is renaming jobs made worse by versioning with git? It's an existing problem today, and there's no way to do it. Can't really make it any worse. Something like having the new job reference the job it migrated from could be done with both `set-pipeline` today and by pushing to `git`.

**Comment by vito** [comment] 2017-10-02 19:48
We're doing some investigation on this on https://github.com/concourse/concourse/issues/1200 - I'm gonna close this to consolidate. I think it's a good idea, though.

**Closed by vito** 2017-10-02 19:48 UTC
Labels: area: auditability, type: enhancement
