### ISSUE TITLE
No working documentation for performing database backup and restore

### ISSUE THREAD

**Issue by cobyrne-pivot** [concourse/concourse#1760] opened 2017-10-30 19:29 UTC
# Feature Request

## What challenge are you facing?

We need a way to reliably back up and restore a concourse deployment. We needed this recently for the purposes of migrating to a new concourse deployment. Probably we should also be running periodic backups.

We need this functionality because build history is nice. But also because this concourse deployment is used by multiple teams and contains pipelines for multiple projects, some of which are not in active development (but with periodic jobs we still care about). It's very expensive to set up all the pipelines again from a fresh concourse deploy.

We followed the steps described [here](https://docs.pivotal.io/p-concourse/backing-up.html). When we restored we encountered [this issue](https://github.com/concourse/concourse/issues/1745). The solution was to manually recreate an index, and in the future we should perform a more limited backup and restore of just data tables. But which tables specifically need to be restored to preserve pipeline and job definitions as well as build history?

## A Modest Proposal

Please provide a reliable way to migrate between concourse deployments. It would be amazing if this was automate-able with fly, but that may not be possible given concourse doesn't own the DB. It would be nice to at least have clear, working instructions on how to do this by hand.

**Comment by marco-m** [comment] 2017-11-02 19:51
This seems a duplicate of #1420. I suggest to have a look at all the issues tagged "area:docs" and vote for the ones important for you.

**Comment by cobyrne-pivot** [comment] 2017-11-02 22:57
Thanks, Marco, I didn't know about that tag. I did just take a look through "area:docs" and the issue you linked, but I don't quite see a duplicate. 

I do agree backup/restore is probably an important part of upgrading safely, but we got into trouble just trying to migrate to a new deployment without upgrading anything, so I'm not sure the two should be entirely conflated.

**Closed** 2019-08-07 23:24 UTC
Labels: docs, wontfix
