### ISSUE TITLE
Investigate the worker disk reaching 80% capacity on CI

### ISSUE THREAD

**Issue by navdeep-pama** [concourse/concourse#7972] opened 2022-01-17 18:44 UTC
Volume GC logic
- Archive pipelines
- Other flows

**Comment by xtremerui** [comment] 2022-01-20 02:13
Found the root cause: volumes of task cache is not GCed in archived pipelines. 

Thus the disk usage is super high in ci pr worker as there is frequently pr pipeline archiving in which some tasks have utilized cache like this one https://github.com/concourse/ci/blob/61dac3e4123f7857e4ee74b740f45f22dfe16105/tasks/docker-compose-testflight.yml#L14-L15

while above behaviour is perfectly OK, we don't seem to running the [task cache collector](https://github.com/concourse/concourse/pull/7272) at all ... 

PR incoming to fix this

**Comment by xtremerui** [comment] 2022-01-20 15:46
Gonna close this one as we have the issue created here https://github.com/concourse/concourse/issues/7986

**Closed by xtremerui** 2022-01-20 15:46 UTC
Labels: bug
