### ISSUE TITLE
failed-to-find-created-volume-in-baggageclaim

### ISSUE THREAD

**Issue by mbjelac** [concourse/concourse#1194] opened 2017-05-23 07:33 UTC
# Bug Report

* Concourse version: 3.0.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: 
    privately hosted virtual machine:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
* Browser (if applicable): Chrome 58.0.3029.110 (64-bit)
* Did this used to work? - Yes!

Error on checking resource ("checking failed"):
```
failed-to-find-created-volume-in-baggageclaim
```

This is an error on *all* types of resources (I currently use git and maven).

Possibly related issues: #896, #1171,  #373 

Workers:
```
fly -t ci workers
name          containers  platform  tags  team  state    version
084fa9e06b13  0           linux     none  none  running  1.0
```

What other data do you need?

Currently my whole CI is blocked by this. I don't want to delete/restart anything until you inform me of additional data I should gather. This is actually a general question - how do I gather troubleshooting data? Where are the web/worker logs? My `docker logs concourse-web/worker` is polluted by pings and whatever. No use at all...

**Comment by ese** [comment] 2017-05-23 08:11
I get this situation some times when reboot my wokers with 3.0.0

**Comment by mbjelac** [comment] 2017-05-23 12:32
I couldn't wait for the feedback on my question, had to restart.

But wait, it isn't that easy!

I tried:

- restart worker container
- destroy + add pipeline
- stopping all Con containers + restarting all (docker-compose down + up)

None of that worked.

Then:

- stopping worker container, removing its volume data, restart: worked, but workers stalled
- pruning stalled workers

Success at last!

I hope I get some feedback on why this is happening or at least what data to send to you when it happens again. Otherwise, I'll have to automate the above clean-up process... or maybe switch to another CI technology as this one currently seems too buggy.

**Comment by vito** [comment] 2017-05-23 14:57
Are your workers coming back under the same name after having all volumes/containers destroyed? That'll throw a wrench into the gears at the moment, as Concourse expects the name of a worker to match its lifecycle, and the ATC doesn't deal well with containers and volumes that we know we created before disappearing out from under it.

**Comment by emcniece** [comment] 2017-05-26 00:06
Hit this as well, fortunately Rancher provides unique names for each container so the fix was to run Rancher's "upgrade" command which recreates the container with the same options.

Using a [Rancher catalog item](https://github.com/emcniece/rancher-catalog/tree/master/templates/concourse/1) for my setup.

**Comment by mbjelac** [comment] 2017-05-26 07:08
Sorry for the late answer...
I don't think the workers have the same name ... here is the worker list:

```
fly -t ci workers
name          containers  platform  tags  team  state    version
12107ccf8b9e  0           linux     none  none  running  1.0

the following workers have not checked in recently:

name          containers  platform  tags  team  state    version
69d0921c9cd3  0           linux     none  none  stalled  1.0
94dfa19393c0  0           linux     none  none  stalled  1.0
```

After I prune the stalled ones, things recover.

This just happened after the partition for the worker state got filled to 100%.
I cleaned it and pruned the workers.

**Comment by mbjelac** [comment] 2017-05-26 08:44
It happened again, but this time disk space is not the issue.

```
Filesystem             Size  Used Avail Use% Mounted on
...
...docker_Concourse    8.8G  2.0G  6.3G  24% ...
```

Here is the worker list:

```
fly -t ci workers
name          containers  platform  tags  team  state    version
12107ccf8b9e  0           linux     none  none  running  1.0
```

The virtual machine hosting the docker that runs Concourse was rebooted (with `reboot`) about 20mins ago... Is there maybe an issue in stopping the concourse-worker container?

**Comment by philicious** [comment] 2017-05-30 16:55
I'm having the same issue with the Vagrant based Concourse.
Any hints on how to recover would be appreciated

**Comment by mbjelac** [comment] 2017-06-01 07:40
Happened again... brushed under the carpet in the same way as before.

*Upgraded to 3.1.1.*

I'll continue to report the baggageclaim issue here if it reoccurs.

**Comment by mcb** [comment] 2017-06-02 12:07
Same here. Running 3.1.1 on vagrant though.

**Comment by marco-m** [comment] 2017-06-02 20:26
Same, Vagrant 3.0.1

**Comment by bacoboy** [comment] 2017-06-05 18:05
Seeing this on ubuntu16.04 w/ 3.1.1:

```json
{"timestamp":"1496685552.503259897","source":"baggageclaim","message":"baggageclaim.repository.get-volume.volume-not-found","log_level":1,"data":{"session":"3.4619728","volume":"58ee6b65-25d9-4ead-4b00-05798fe28e56"}}
```

Had to replace the workers to get up and running again.

**Comment by philicious** [comment] 2017-06-06 13:00
@mbjelac could you elaborate how exactly you recover from this ? i.e. the commands you run so we can try the same. it has happened again for me and have to recreate the vagrant VM. which is acceptable as its a local VM for playing around but still pretty annoying

**Comment by mbjelac** [comment] 2017-06-06 13:39
@philicious I run all my stuff in docker containers, but this should be applicable to VM services:

1. Stop worker service
1. Delete the contents of the `worker-state` folder
1. Start worker service
1. Wait
1. Prune stalled workers with Fly

The only difference is that I don't stop/start only the worker but all Concourse components because I set them up with docker-compose, so its easier to just `docker-compose down` + `docker-compose up -d`. But the web and DB components shouldn't be a factor in this... I think. :)

**Comment by mbjelac** [comment] 2017-06-06 13:40
Oh, forgot to mention: I haven't run into this problem since running `3.1.1`.

**Comment by philicious** [comment] 2017-06-06 16:16
thx @mbjelac 

ye my Vagrant box is also at 3.1.1 since I had to recreate it due to this issue. I hope its fixed with that and wont have to worry bout it anymore. If it should happen again, I'll give your fix a shot :)

**Comment by spgreenberg** [comment] 2017-06-08 15:35
We are seeing this on multiple 3.1.1 vagrant installs as well.

**Comment by blakebarnett** [comment] 2017-06-08 18:26
Seeing this with 3.1.1 on kubernetes 1.6.4 also.

**Comment by blt** [comment] 2017-06-09 02:15
To further what @blakebarnett has said, we're seeing this on a fresh installation of 3.1.1 with only one pipeline, which looks like so: 

```---
resources:
  - name: pysup
    type: git
    source:
      uri: git@github.com:postmates/pysup.git
      access_token: {{github-access-token}}
      private_key: {{github-private-key}}
  - name: pysup-test-image
    type: docker-image
    source:
      email: {{quay-email}}
      username: {{quay-username}}
      password: {{quay-password}}
      repository: quay.io/postmates/pysup-image

jobs:
  #
  # master_build
  #
  - name: pysup-master-test-img
    plan:
      - get: pysup
        trigger: true
      - put: pysup-test-image
        params:
          build: pysup
          dockerfile: pysup/Dockerfile

  - name: master-test
    plan:
      - get: pysup-test-image
        passed:
          - pysup-master-test-img
      - get: pysup
        passed:
          - pysup-master-test-img
      - task: test
        image: pysup-master-test-img
        config:
          platform: linux
          inputs:
            - name: pysup
          run:
            dir: pysup
            path: sh
            args:
              - -exc
              - |
                make test
```

The project dockerfile is

```
FROM alpine:3.5

RUN apk add --update --no-cache alpine-sdk python py-pip python2-dev && \
    pip install --upgrade pip

ADD . /pysup

RUN cd /pysup && \
    pip install -r dev-requirements.txt && \
    pip install -r requirements.txt && \
    cd / && \
    rm -rf /pysup
```

We thought that maybe the lack of privilege was the problem but sprinkling `privileged: true` into the resources brought out errors that look like `failed-to-find-created-volume-in-baggageclaim`. Unmodified pipelines will fail intermittently on this deployment.

**Comment by philicious** [comment] 2017-06-09 12:24
now also happened for me with 3.1.1

@mbjelac where is that worker-state folder located? couldnt find any folder with that name

**Comment by mbjelac** [comment] 2017-06-09 13:34
Heh, like I said, I use Docker for all this, maybe its a different setup.

Here are the root folders of my Concourse worker container:

```
~$ docker exec -it con-worker ls -lha /
total 80K
drwxr-xr-x  48 root root 4.0K Jun  9 13:31 .
drwxr-xr-x  48 root root 4.0K Jun  9 13:31 ..
-rwxr-xr-x   1 root root    0 Jun  6 09:31 .dockerenv
drwxr-xr-x   2 root root 4.0K May 31 19:29 bin
drwxr-xr-x   2 root root 4.0K Apr 12  2016 boot
drwxrwxr-x   2 1002 1002 4.0K Apr 28 14:18 concourse-keys
drwxr-xr-x  14 root root 3.8K Jun  6 09:31 dev
drwxr-xr-x  48 root root 4.0K Jun  6 09:31 etc
drwxr-xr-x   2 root root 4.0K Apr 12  2016 home
drwxr-xr-x   9 root root 4.0K May 31 19:29 lib
drwxr-xr-x   2 root root 4.0K May 10 16:23 lib64
drwxr-xr-x   2 root root 4.0K May 10 16:23 media
drwxr-xr-x   2 root root 4.0K May 10 16:23 mnt
drwxr-xr-x   2 root root 4.0K May 10 16:23 opt
dr-xr-xr-x 241 root root    0 Jun  6 09:31 proc
drwx------   2 root root 4.0K Jun  9 13:31 root
drwxr-xr-x   7 root root 4.0K Jun  6 09:32 run
drwxr-xr-x   2 root root 4.0K May 31 19:29 sbin
drwxr-xr-x   2 root root 4.0K May 10 16:23 srv
dr-xr-xr-x  13 root root    0 Jun  6 09:31 sys
drwxrwxrwt   2 root root 4.0K Jun  9 13:30 tmp
drwxr-xr-x  18 root root 4.0K May 31 19:29 usr
drwxr-xr-x  16 root root 4.0K May 31 19:29 var
drwxr-xr-x   6 root root 4.0K Jun  1 07:30 worker-state
```

If I remember correctly, when I was troubleshooting, I found the last folder's name most interesting so I tried to fix the problem by deleting its contents. :) And it worked.

**Comment by philicious** [comment] 2017-06-09 13:53
ah ok. according to the dockerfile, the worker-state/ folder is the workdir and in vagrant the worker is started with `--work-dir=/tmp/concourse` , so I will try deleting that folder next time it happens

**Comment by vito** [comment] 2017-06-10 14:23
We should probably handle this case by just creating the volume again. It's weird for a volume to disappear after we've created it, and that may point to something wrong in your deployment automation, but we can at least be durable to it.

**Comment by vito** [comment] 2017-06-12 14:44
To anyone running in to this in Vagrant, could you provide a bit more info? For example, does this happen right out of the box, or is your host machine or the VM being rebooted/put to sleep, etc. etc.?

**Comment by philicious** [comment] 2017-06-12 15:40
@vito so I've seen this couple times now and it just happens suddenly. UI says "bla turbulence" and concourse is dead. Also I cannot `vagrant ssh`anymore. I then `vagrant reload` (reboot) the VM and concourse is up again but has this error with baggage-claim. 
I couldnt get it back to a working state so I always `vagrant destroy` `vagrant up` a new VM. 
fortunately setting up the pipelines is as easy as runniny a single `fly` command

**Comment by clarafu** [comment] 2017-06-12 15:46
We found that the volumes all disappear when vagrant is rebooted because work-dir is pointing to a tmp directory in concourse-lite. We changed it so it does not point to tmp here https://github.com/concourse/concourse-lite/commit/6e4600716726fd601a0e28356d6053fd1a6a08f6. But this only solves the problem for the vagrant box users getting the "failed to find created volume in baggageclaim". 

For everyone else that is running into this, can you leave a comment on how to reproduce this error with the way you deployed your workers? For example, is it that your workers always have a static name or do you have some configuration that makes this error happen every time you recreate your workers, etc.

**Comment by spgreenberg** [comment] 2017-06-12 16:11
@vito It happened multiple times during a class.  I believe each time was
related to a reboot/sleep/crash.

**Comment by vito** [comment] 2017-06-14 19:02
I'm going to close this for now as we've fixed the Vagrant box.

For everyone else, please make sure that your worker name correctly matches the lifecycle of the worker's VM/disk state/etc. This means that when a worker goes away and loses all of its data, the worker should be retired in Concourse or come back under a new name. This has been the case ever since [v2.6.0](http://concourse.ci/downloads.html#v260), but v3.0.0+ doesn't handle it as well as its bookkeeping for volumes/containers is a bit more strict.

Our Vagrant box has the name hardcoded as "concourse", and its data would go away on reboot because it placed the work-dir under `/tmp`, so that's an example of a misconfiguration. Now it'll come back with all the state on disk still there.

We could definitely be more durable to this, but I'd rather make sure we've characterized the issue correctly before taking action, as if you've got a misconfigured deployment, you may be bitten in more subtle ways, even if we do try to be durable to it.

**Closed** 2017-06-14 19:02 UTC
Labels: area: resiliency, needs-investigation, type: bug
