### ISSUE TITLE
Programmatically detect Concourse CI environment

### ISSUE THREAD

**Issue by watson** [concourse/concourse#2105] opened 2018-03-21 14:22 UTC
# Feature Request

## What challenge are you facing?

I'm maintaining [is-ci](https://github.com/watson/is-ci/issues/13), a module for detecting your code is running in a CI environment, and [ci-info](https://github.com/watson/ci-info), a module for getting more information about the CI environment.

Recently an issue was opened on is-ci asking me to detect the presence of Concourse: watson/is-ci#13

The way I normally do this is to detect CI-specific environment variables. But as far as I can see, Concourse doesn't expose/set any environment variables, so I don't know if it's possible to detect.

## A Modest Proposal

It would be nice if Concourse would expose an environment variable by default (e.g. `CONCOURSE=true`).

I'm however not sure if this would work inside of Docker containers, but as I'm not a Concourse user my self, there's a lot of stuff about running Concourse my self that I don't know. So it might not be an issue.

**Comment by vito** [comment] 2018-03-22 15:03
Hah! That's kind of funny because we sort of make a point to *not* expose any Concourse-specific information to tasks. I'm not sure if we'll do anything about this, at least without knowing why people want it.

**Comment by oliveti** [comment] 2018-06-06 09:18
Hi,

The use case : Lerna version 2.x is using the library 'is-ci' to determine if it runs on CI and disable colors. Have a look here : https://github.com/lerna/lerna/blob/5b015996e4824527f3aff684611c112562edddf6/core/cli/index.js

I understand you make a point to not expose any concourse specific, but in the end, some terminal features are not working on the web view of concourse. So that could make sense to expose the fact the process is running on concourse.

**Comment by shinmyung0** [comment] 2018-09-12 06:42
I think it would be great to have a way to set global environment variables (cluster wide) to provide context to some jobs. We have teams requesting params like `ci_env=prod` so that they can reuse the pipeline code for both dev and prod deployments yet have conditional logic for different environment levels. We are addressing this problem currently by putting in values in credhub like ((ci_env)) but not only does this not work in a global scope, but it also doesnt fit the criteria of a credential. Because we lock down access to our credhub it becomes even more of a pain when we have to maintain a set of arbitrary credhub values to provide more contexts to builds.

**Comment by kaedys** [comment] 2018-11-29 19:53
I'd like to +1 this request. We have a binary that is allowed to run without several CLI arguments when in concourse, but must include them if our devs run it locally. Right now, we have no solid way to actually *enforce* that difference. Having a $CONCOURSE env var defined would be an immense help for our use case.

**Comment by vito** [comment] 2019-03-12 18:54
@kaedys Couldn't you just set `params: {CONCOURSE: true}` in the pipeline?

@shinmyung0 In my experience, having many levels of env config can quickly turn into a nightmare as it can be difficult to find where exactly a value is coming from.

**Comment by kaedys** [comment] 2019-03-14 01:12
@vito we could do that, but then _every single user_ has to do that.  Our tool is part of a deployment infrastructure that is used by some 30 different teams at my company.  Requiring that they set that parameter in _every single pipeline_, in _every single task_, is just a _little_ bit excessive, no?

Like, I understand that y'all are going for this pure stateless system, but it seems self-obvious that code being able to be aware of whether it's being run within Concourse or not has valid uses cases.  To elaborate on my early example, that tool is permitted to be run by our users via Concourse for non-production deployment destinations, but _not_ for production destinations.

We do this for several reasons.  One, we piggy-back off gcloud's authentication, but that's only deemed necessary for production deployments.  Two, we don't want "accidents" in production coming from misconfigured pipelines, so we mandate that those things normally set in the pipeline configuration instead be explicitly provided as arguments to the application, and that the application be run locally so they arguments be explicitly configured each time a production deployment occurs.

Now, for the moment, the only way we could "detect" if they are on Concourse is to have them set the $CONCOURSE environment var in each relevant task in their own pipelines. This would require close to a thousand pipelines to be updated across our company, which isn't a feasible ask.  Being about to easily and _intrinsically_ detect whether an application of ours is running within Concourse or not enables us to define a lot of modal behavior only permitted or specifically restricted when in Concourse.  Currently our only options in that respect are
- Have every user update every single pipeline.
- Fork the binary and create a "Concourse" version and a "local" version, and only expose the latter to our users.  This requires us to maintain two distinct code bases that do the exact same thing, and ensure perfect parity between them.
- Abandon the idea of easing certain restrictions while in Concourse, which largely negates our _use case_ for Concourse in the first place (being able to pre-configure deployment parameters for common deployment cases, like regression testing).

**Comment by vito** [comment] 2019-03-14 02:43
@kaedys All I suggested was setting a param in a task, not setting 1,000 params in 1,000 pipelines across 30 teams in your company. If I know a bit more about your use case I can make better suggestions. 🙂

"Am I running in CI?" implies something else. The real question being asked is "am I deploying to prod?" Or maybe for someone else it's "should I emit code coverage?" or "should I send a notification?"

When knowing the script is running in CI isn't enough, and it the question becomes "am I in this *particular* CI", how would you configure that?

When you want to emit code coverage across all your tasks, but you *don't* want to deploy to prod, how would your tools have to change?

Sharing tools between dev and CI makes a lot of sense, and these are reasonable questions for those tools to ask. I just don't like adding implicit behavior, I don't like overloading variables, and I don't like features that couple tools and scripts to Concourse. These kinds of practices make them brittle, and they may have to be changed if you want to run them somewhere else or if you switch to another CI system.

Is there a level of setting `params` that you would be comfortable with (despite my concerns in https://github.com/concourse/concourse/issues/2105#issuecomment-472135872)?

How is your tool provided to the pipeline? If it's provided by a Docker image, couldn't you just set `PRODUCTION=true` there? This would automatically propagate to all the tasks that use or are based on the image.

Maybe you should be using a resource instead, since it sounds like this is for a tool that has side-effects? That way the tool could obviously know it's running in CI.

Maybe there's more context to provide to understand this better?

Thanks!

**Comment by kaedys** [comment] 2019-03-14 18:54
> Is there a level of setting params that you would be comfortable with

For the detection of if the tool is running in CI or not, I don't see how it being in params is viable.  Every single user of our binary runs that binary via a Concourse pipeline.  If the only way we can detect if it's in CI is via a param they set, then _every single one_ has to set that param, in _every single one of their pipelines_.  I don't see a way around that requirement if it's a param in the pipeline, because this binary is used in thousands of pipelines across our company.

> How is your tool provided to the pipeline? If it's provided by a Docker image, couldn't you just set PRODUCTION=true there? This would automatically propagate to all the tasks that use or are based on the image.
It's currently simply a binary pulled from an artifactory repository.  We're investigating wrapping it in a docker container, but thus far have not done so, and there's debate amongst by coworkers on the efficacy of it for this use case.

> Maybe you should be using a resource instead, since it sounds like this is for a tool that has side-effects? That way the tool could obviously know it's running in CI.

Are you suggesting having concourse itself somehow be a resource?  Or generating a more-or-less phony resource simply to detect if it's running in Concourse?  In either case, this is defined in the pipeline config, so how is this significantly different from setting it as a param?

**Comment by vito** [comment] 2019-03-14 19:56
> If the only way we can detect if it's in CI is via a param they set, then _every single one_ has to set that param, in _every single one of their pipelines_.

This sky-is-falling response is making it really difficult to help you. I never suggested setting params on pipelines. I asked if setting params at *any* level would be sufficient - whether that's team, Concourse-wide, etc. Knowing this information will help understand your use case, even though I'd rather not have param config so far away from the pipeline as it makes them less portable.

> Are you suggesting having concourse itself somehow be a resource? Or generating a more-or-less phony resource simply to detect if it's running in Concourse? In either case, this is defined in the pipeline config, so how is this significantly different from setting it as a param?

I was suggesting packaging your tool as a [resource type](https://concourse-ci.org/resource-types.html) and using it that way in your pipeline instead, since it sounds like it's performing state changes, and resources are typically used for that kind of thing, not tasks. This way you could package your tool in a Docker image and provide a higher-level Concourse interface. This would let you pre-configure the tool so that it knows it's "in CI". I don't know if this is a good idea, so please don't bite my head off if I'm wrong, since all I can do right now is throw guesses at the wall and see what sticks.

---

Either way, I'm still not convinced that "am I in CI?" is an appropriate input that should be used to determine important things like that. This is an [XY problem](http://xyproblem.info/), and I'm trying to peel back the layers of this onion to find a solution that will work for you without giving everyone else a loaded gun to point at their foot. If you're not interested in finding another solution or don't have the time to provide more information, that's fine.

**Comment by kaedys** [comment] 2019-03-18 18:03
> This sky-is-falling response is making it really difficult to help you. I never suggested setting params on pipelines. I asked if setting params at any level would be sufficient - whether that's team, Concourse-wide, etc. Knowing this information will help understand your use case, even though I'd rather not have param config so far away from the pipeline as it makes them less portable.

Wait, perhaps I'm missing something here.  I was unaware that there was a way of setting parameters beyond the pipeline scope.  Are you saying there's some location we could set such a CI parameter and have it apply to every pipeline run, either globally to our deployed Concourse server or individually for all pipelines run by a team?

> I was suggesting packaging your tool as a resource type and using it that way in your pipeline instead

Perhaps I'm misunderstanding the terminology here.  Here's the process in the majority of our pipelines:
* Job 1 - Build artifact and upload
  * Task 1 - Run unit tests and build binary (Inputs: our runner script and the code repo in question)
  * Task 2 - Runs one of our tools to upload the artifact a remote artifact storage
* Job 2 - Build image and deploy
  * Task 1 - Runs another of our tools.  This tool builds a chef image based on a base image and the previously uploaded artifact, but this image build can only occur in a non-production environment to ensure that all images are deployed to a staging/QA environment before production.  The tool then fires an external API call to a server utility we host that runs the actual deployment process on GCP.

Now, classifying those tools as "resources" seems like it would be odd.  My understanding is that resources are items used as input to jobs and tasks.  Are you suggesting that we pre-bake the tools in question into their own containers and set those containers to specify that they are "CI" containers (likely via an internal environment variable, but there are plenty of ways), and then source the relevant container as a "resource" used by a job?

Actually, just checked with the engineer working on containerizing that tool, and it sounds like it _far_ more progressed than I thought it was.  We can probably do exactly that on a much shorter timeframe than I anticipated.

**Comment by Anticom** [comment] 2019-07-04 07:22
> Hah! That's kind of funny because we sort of make a point to _not_ expose any Concourse-specific information to tasks. I'm not sure if we'll do anything about this, at least without knowing why people want it.

IMHO this defeats the point of being the *environment*. The environment variables should give you information about... well, the environment the software is running on. And if this environment happens to be a CI server, it should expose that information.

> @kaedys Couldn't you just set `params: {CONCOURSE: true}` in the pipeline?

If we where to set this env ourselves no other package maintainer could rely on the name `CONCOURSE`.

**Comment by kaedys** [comment] 2019-09-04 16:15
I think this is still a live issue, to be honest.  In fact, it would be nice if Concourse exposed more information than just that the process is being run within Concourse.  One thing we've struggled with lately is that Concourse does not expose the _user_ that triggered the pipeline (our Concourse is integrated with our corporate SSO system, so our "username" in Concourse is our LDAP ID).  This makes it impossible for us to keep track of who kicked off a process, or for any downstream applications to record that information either.

Since Concourse is our de facto solution for non-production deployment pipelines, it would be extremely useful if Concourse were to expose this information (which, by implication, requires Concourse to expose that it's, well, Concourse), as it would permit our application to then record _who_ kicked off deployments.

**Comment by olbrich** [comment] 2019-09-04 16:52
I will also note that several CI services do this and also provide additional build specific details.

https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

**Comment by kaedys** [comment] 2019-11-05 18:58
Yes, this is still an important issue.  Not having the capability to detect who kicked off a pipeline run, or any information about that run, or in fact that it is even in the context of a Concourse pipeline, is a significant limiter on the usefulness of Concourse as a whole.  I get that Concourse is _super_ gung-ho about isolating builds and having _zero_ stateful information, but that just flat out does not align with the way CI/CD is generally implemented within the software industry.  Applications should have the ability to record information about their run context, to detect that they are being run in a CI setting, and ideally to be able to determine and record information about that run and the larger Concourse context for the run (such as who started the pipeline, or if it was automatically triggered).

**Comment by vito** [comment] 2019-11-05 20:16
@kaedys It is not in our interest align with how CI/CD is *generally* implemented, it is in our interest to define how we think it *should* be implemented based on what we've learned from being in the software industry. If we don't want to learn from our mistakes and try to move the industry forward, I don't know why we're bothering to write yet another CI/CD tool.

Honestly, at this point I'm going to just close this issue and lock the discussion. We're not getting any closer to understanding the use cases behind the request by having the issue framed around the specific solution like it is now (no fault to the OP who is just maintaining a library and looking to add Concourse support - the title is just a bit of a Google honeypot).

If the request is "Concourse should expose all kinds of information to my tasks," that is not an ask I can simply say yes to, because it's a conscious decision *not* to based on our experience with CI/CD and seeing the pitfalls of such a brittle interface firsthand. I understand that people feel passionately about this, and on its face it's a pretty simple ask. I get it.

I ask that y'all open issues clearly outlining the specific challenge you're facing - at a high level! A challenge isn't "Concourse doesn't give me this information", it's "I need to be able to audit my pipeline" or "I need to be able to annotate my assets with metadata so I can trace it back to something", etc. Then we can actually work towards a solution after understanding the problem instead of working backwards from a solution that doesn't fit the Concourse model.

**Closed by vito** 2019-11-05 20:16 UTC
Labels: enhancement
