### ISSUE TITLE
Allow underscore as part of identifier schema; forbidding it is too restrictive and breaks workflows

### ISSUE THREAD

**Issue by issmirnov** [concourse/concourse#6070] opened 2020-09-16 05:22 UTC
## Summary

The current [identifier schema](https://concourse-ci.org/config-basics.html#schema.identifier) is more restrictive than the prior allowed naming schemes. This breaks workflows that require folders with underscores.

## Steps to reproduce

Create any workflow that requires a folder with an underscore. At this time, it seems impossible to use such a name as an identifier.

Note that even with the `get.resource` param set to an underscore, the validation still fails due to an invalid schema.

## Expected results

Schema names should not be this restrictive. My use case is testing ansible roles, where the universal syntax is `$username.role_name`. As such, there's no easy way to test these roles without adding tons of fluff where directories are renamed.

## Actual results

```
  - jobs.ansible-role-ubuntu-desktop.plan.do[0].in_parallel.steps[3].get(issmirnov.compile_zsh): 'issmirnov.compile_zsh' is not a valid identifier: illegal character '_'
```

## Additional context

Ansible role names are incompatible with concourse naming schemas. This breaks existing workflows.

## Triaging info

* Concourse version: 6.5
* Did this used to work? Yes, in all versions prior to 6.0

## Full pipeline definition

<details><summary>pipeline.yml</summary>
<p>

```yaml
---
ansible_role_tester: &ansible_role_tester
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: issmirnov/dcind
  run:
    path: sh
    args:
      - -exc
      - |
        source /docker-lib.sh > /dev/null 2>&1
        # https://github.com/meAmidos/dcind/blob/master/docker-lib.sh#L56 # Inject registry.
        start_docker "http://docker-registry.puma" "http://docker-registry.puma" > /dev/null 2>&1

        # docker debug for caches.
        ls /var/lib/docker

        mkdir -p report # output
        export ROOT=$PWD
        cp art_bin/ansible-role-tester $ROLE
        [ -d cfssl_bin ] && cp -r cfssl_bin $ROLE/tests/
        cd $ROLE

        # iterate over all available playbooks
        for f in tests/*.yml; do
          if [ "$f" = "tests/requirements.yml" ] ;then continue; fi
          ./ansible-role-tester full -t ubuntu1804 --extra-roles $ROOT --library "$(pwd)/tests/library" --report --report-output ../report/report.json --playbook $f
          # check results
          if [[ "$(jq '.Ansible.Run.Result' ../report/report.json)" != "true" ]]; then
              echo "Run failed";
              exit 1;
          fi
          if [[ "$(jq '.Ansible.Idempotence.Result' ../report/report.json)" != "true" ]]; then
              echo "Idempotence failed";
              exit 2;
          fi
          # reset report file
          rm ../report/report.json # cleanup
        done
compile_art: &compile_art
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: golang
      tag:  1.12.1
  outputs:
    - name: art_bin
  run:
    path: sh
    args:
      - -exc
      - |
        export ROOT=$PWD
        export GOPATH=$PWD
        go get github.com/fubarhouse/ansible-role-tester
        cd src/github.com/fubarhouse/ansible-role-tester
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -ldflags '-w -extldflags "-static"'
        cp ansible-role-tester $ROOT/art_bin/
  caches:
    - path: art_bin
compile_cfssl: &compile_cfssl
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: golang
      tag:  1.12.1
  caches:
    - path: cfssl_bin
  outputs:
    - name: cfssl_bin
  run:
    path: sh
    args:
      - -exc
      - |
        export GOPATH=$PWD
        # Download and install.
        go get -u github.com/cloudflare/cfssl/cmd/...
        cp bin/cfssl* cfssl_bin/

        # sanity check.
        ./cfssl_bin/cfssl version
fail_email: &fail_email
  put: send-an-email
  params:
    subject_text: "[❌ FAILED] CI: build #${BUILD_NAME} on ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}!"
    body_text: |
      Oh no! Build #${BUILD_NAME} on ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME} failed!
      Build ID: ${BUILD_ID}
      Build Name: ${BUILD_NAME}
      Build Job Name: ${BUILD_JOB_NAME}
      Build Pipeline Name: ${BUILD_PIPELINE_NAME}
      ATC External URL: ${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}

success_email: &success_email
  put: send-an-email
  params:
    subject_text: "[✔️ PASSED] CI: build #${BUILD_NAME} on ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}."
    body_text: |
      Congrats, your commit worked.
      Build ID: ${BUILD_ID}
      Build Name: ${BUILD_NAME}
      Build Job Name: ${BUILD_JOB_NAME}
      Build Pipeline Name: ${BUILD_PIPELINE_NAME}
      ATC External URL: ${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
gitea_private_key: &gitea_private_key |
  -----BEGIN RSA PRIVATE KEY-----
  REDACTED
  -----END RSA PRIVATE KEY-----
resource_types:
  - name: email
    type: registry-image
    source:
      repository: pcfseceng/email-resource
      tag: latest

resources:
  - name: daily-timer
    type: time
    source:
      interval: 24h

# === ANSIBLE ===
  - name: ansible-role-cfssl
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: issmirnov.goss
    type: git
    source:
      uri: REDACTED
      branch: master

  - name: ansible-role-provision
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: ansible-role-server
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: ansible-role-ubuntu-desktop
    type: git
    source:
      uri: REDACTED
      branch: master
      private_key: *gitea_private_key

  - name: issmirnov.zap
    type: git
    source:
      uri: https://github.com/issmirnov/ansible-role-zap.git
      branch: master


  - name: issmirnov.compile-zsh
    type: git
    source:
      uri: https://github.com/issmirnov/ansible-role-compile-zsh.git
      branch: master

  - name: issmirnov.dotfiles
    type: git
    source:
      uri: https://github.com/issmirnov/ansible-role-dotfiles.git
      branch: master

  # Explicitly define requirments, since reusing similar config for running the roles.
  # We can always go back to passing the --requirments flag to ansible-role-tester
  # FWIW, this is nice since i'll pick up breaking changes sooner.
  - name: oefenweb.swapfile
    type: git
    source:
      uri: https://github.com/Oefenweb/ansible-swapfile.git
      branch: master

  - name: jnv.unattended-upgrades
    type: git
    source:
      uri: https://github.com/jnv/ansible-role-unattended-upgrades.git
      branch: master

# === EMAIL ===
  - name: send-an-email
    type: email
    source:
      smtp:
        host: smtp.mailgun.org
        port: "587"
        username: ((username))
        password: ((password))
      from: ((from_email))
      to: [ ((my_email))]
########
# JOBS #
########
jobs:
  - name: issmirnov.compile-zsh
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-compile-zsh
          resource: issmirnov.compile-zsh
          params: {depth: 1}
          trigger: true
        - get: issmirnov.goss
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-art
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-compile-zsh
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-compile-zsh
            - name: issmirnov.goss
          outputs:
            - name: report


  - name: ansible-role-provision
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-provision
          params: {depth: 1}
          trigger: true
        - get: issmirnov.compile-zsh
          resource: issmirnov.compile_zsh
          params: {depth: 1}
          trigger: false
          passed: [issmirnov.compile-zsh]
        - get: issmirnov.goss
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-art
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-provision
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: issmirnov.compile-zsh
            - name: ansible-role-provision
            - name: issmirnov.goss

  - name: ansible-role-ubuntu-desktop
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-provision
          params: {depth: 1}
          trigger: true
          passed: [ansible-role-provision]
        - get: ansible-role-ubuntu-desktop
          params: {depth: 1}
          trigger: true
        - get: issmirnov.dotfiles
          params: {depth: 1}
          trigger: true
        - get: issmirnov.compile-zsh
          resource: issmirnov.compile-zsh
          params: {depth: 1}
          trigger: false
          passed: [ansible-role-provision]
        - get: issmirnov.goss
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-art
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-ubuntu-desktop
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: issmirnov.compile-zsh
            - name: issmirnov.dotfiles
            - name: ansible-role-provision
            - name: ansible-role-ubuntu-desktop
            - name: issmirnov.goss

  - name: ansible-role-server
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-server
          params: {depth: 1}
          trigger: true
        - get: oefenweb.swapfile
          params: {depth: 1}
          trigger: true
        - get: jnv.unattended-upgrades
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-server
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-server
            - name: oefenweb.swapfile
            - name: jnv.unattended-upgrades

  - name: issmirnov.dotfiles
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-dotfiles
          resource: issmirnov.dotfiles
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-dotfiles
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-dotfiles

  - name: issmirnov.zap
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-zap
          resource: issmirnov.zap
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-zap
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-zap

  - name: ansible-role-cfssl
    on_failure: *fail_email
    on_success: *success_email
    plan:
      - in_parallel:
        - get: ansible-role-cfssl
          params: {depth: 1}
          trigger: true
      - get: daily-timer
        trigger: true
      - task: compile-art-binary
        config:
          <<: *compile_art
      - task: compile-cfssl-binaries
        config:
          <<: *compile_cfssl
      - task: run-arter
        attempts: 2
        privileged: true
        params:
          ROLE: ansible-role-cfssl
        config:
          <<: *ansible_role_tester
          inputs:
            - name: art_bin
            - name: ansible-role-cfssl
            - name: cfssl_bin

```

</p>
</details>

**Comment by luispabon** [comment] 2020-10-11 21:18
Space is also not a valid identifier. There's no difference between one character and another an `a` and a `b` and `_` and ` ` are the exact same thing. Artificially limiting what can be used on a job name like this is hard to justify.

I'm losing history now on a whole bunch of jobs because I'm being forced to rename them not to use spaces.

**Comment by jimconner** [comment] 2020-11-04 13:20
Losing support for the underscore character is very problematic for anyone using concourse with ansible. Asible always considers the hypen to be subtraction, so not possible to have vars named some-var as it tries to subtract 'var' from 'some'. Our config store has all of the names in a format that ansible is happy with, and until recently concourse was also happy with. Not sure how we can work around this unless we duplicate ever value we're storing under two different key names.. one with hyphens and one with underscores. 

Please allow underscore once again. Life is scarely worth living without it.

**Comment by vito** [comment] 2020-11-04 17:00
Thanks for the feedback - the identifier validation is currently a warning instead of an error so that we can work out the kinks in the plan, since we figured not everyone would see concourse/rfcs#40 despite our best efforts.

I figured restricting `_` might be the most "controversial" change, but it seemed worth trying to standardize Concourse naming conventions across users, and `foo-bar` is the most common naming scheme. I think it'd be awkward for someone to work at one company that uses `foo_bar` everywhere and then move to another company that uses `foo-bar` everywhere. Maybe this can be relaxed if we can have a clear way to suggest that one is preferable without outright preventing it. 🤔 For example, programming languages have the advantage that their `stdlib` suggests the prevailing naming conventions, but I don't think that really exists with Concourse.

I'm afraid I don't have much experience using Ansible myself so some of this feedback is kind of difficult for me to understand without more concise examples (i.e. a minimal pipeline config) of something that's currently impossible or painful to do. I'm having trouble filtering the signal from the noise.

@jimconner Would you mind providing a concise example of this? Is it related to `((vars))`? Are you using pipeline and/or job names to parameterize var access or something?

@issmirnov Would configuring [`path`](https://concourse-ci.org/tasks.html#schema.input.path) be too troublesome in the long run? We really don't want resource names to have to be so tightly coupled to folder names, which is why inputs support having a logical name mapped to a concrete path. The path defaults to the name because typically the names and paths are both pretty "normal." I understand this might be require a bit of boring mechanical work upfront, but I'd like to know if this would be too painful over time, or whether it's a non-starter.

Broadly speaking, I expect the introduction of validations to require changes in some pipelines, and I'm sorry for the churn, but I think it's important in the long run to close this gap. I'd like to fully understand these use cases to determine if they're truly intractable with the new validations (imagining they were present in Concourse from day 1) or if there are reasonable ways to adapt.

@luispabon The justification for this change was outlined in concourse/rfcs#40, and we requested feedback in a [blog post](https://blog.concourse-ci.org/rfc-roundup-june-10th-2020/) which was then [tweeted](https://twitter.com/concourseci/status/1270806238188707840). To avoid losing history you can configure [`old_name`](https://concourse-ci.org/jobs.html#schema.job.old_name) on the job, as recommended in the RFC.

I don't expect identifier validation to be a foreign concept to new users; Go artificially limits what characters may be used in method names, GitHub artificially limits what can be used in a repo name, etc. etc.

Thanks all! I wish we were able to communicate this more broadly to gather this kind of feedback earlier, but I'm not really sure what more to do - blog posts and tweets are the primary mechanism, but not everyone follows them. Happy to field suggestions for better ways to go about communicating these changes ahead of time. (Discord? "Future" release notes?)

**Comment by jimconner** [comment] 2020-11-05 10:13
@vito - Thanks for responding on this issue. Our issue is related specifically to ((vars)) naming.

We're using `pass` (passwordstore.org) for storing a variety of config values in yaml snippets along the following lines.

```
minio_access_key_id: someusername
minio_endpoint: http://minio-url.our-org.com:9001
minio_ip: 10.1.2.3
syslog_address: syslog-endpoint.our-org.com
```

With our concourse pipelines, we call the relevant `pass` commands to fetch yaml snippets we want and feed them into concourse via -l secrets option. We do a similar thing with feeding vars into ansible, dynamically generating string that we can feed into ansible via it's --extra-vars option.

Ansible's definition for variable naming is "Variable names should be letters, numbers, and underscores. Variables should always start with a letter." Within ansible's interpolation the '-' character always represent subtraction meaning that you can never use hyphens in var names 

```
vars:
  ramsize: "{{ ansible_memtotal_mb-fudge_factor }}"
```

Obviously there are ways we can work around this... as we're dynamically generating the values that we're feeding into concourse and ansible respectively we can pipe through sed to convert underscores to hyphens for concourse to use, but it would be nice not to have to do this. I note also that Python doesn't allow hypens in var names for similar reasons.

Just to clarify here, the issue isn't specifically around using ansible within concourse pipelines - It is that both tools have a different idea of what makes up a valid variable name and that makes it challenging when a common configuration store is used to feed into both.

**Comment by luispabon** [comment] 2020-11-05 10:53
Fair play. Another reason to leave underscore as allowed character for me is the fact that `unders_scored` words count as one word instead of `two-words` when it comes to double-click to select, which I personally use plenty for copy paste chores. You can select the whole thing with two clicks instead of click-drag.

**Comment by vito** [comment] 2020-11-05 14:17
@jimconner `((vars))` allow underscores and all kinds of special characters though; Concourse doesn't treat them as identifiers. Only the var source name (`source` in `((source:path.fields))`) has to be an identifier, or `.` for the build-local var source, but I don't think that affects your workflow. Recent versions even allow `:` and `.` by explicitly quoting the path/fields. ([Here are the syntax docs.](https://concourse-ci.org/vars.html#var-syntax)) What actually fails when you try to do this?

@luispabon You know, I noticed the inconsistency with `foo-bar` and the `foo_bar` in the config schema recently, and it blows my mind that no one else has brought it up until now. 😆 It seems like `foo-bar` for names and `foo_bar` for config fields either makes sense to people, or they've just been influenced by existing Concourse examples and are going with the flow, all the while thinking it's a little strange but not bothering to speak up about it.

To be honest, I'm seeing a lot of technical reasons to reverse the validation to allow `_` and forbid `-`, but that seems like an even more radical change given how common it is. Maybe it would just take getting used to.

There's still a chance that we just allow both, but I *really* don't want to end up with a 50/50 split of conventions within the Concourse ecosystem. We plan to expand `resource-types.concourse-ci.org` to support sharing reusable pipeline configs, and it'd be real awkward if it was a mixed bag. Subtle reasons such as yours are perfectly valid @luispabon but they suggest that certain folks would use `_` rather than `-` universally rather than situationally, which is a pattern that would lead to fragmentation.

**Comment by luispabon** [comment] 2020-11-05 14:50
I think you should allow both and let developers deal with their own naming conventions. Too much friction on such a small thing is annoying, and I'm sure we all want concourse pipelines to be as effortless as possible.

**Comment by jimconner** [comment] 2020-11-05 16:54
@vito "Concourse doesn't treat them as identifiers." - It's entirely possible I got totally the wrong end of the stick with the invalid identifiers thing. Someone on my team ran into the invalid character message and it triggered my '_' vs '-' rant mode. I found the issue here and made the assumption that it was for vars too. Now that I check back on the message my team-mate posted I can see that it was actually for a job name.

I don't think that the  '-' vs '_' battle is a thing that can never be won. '_' isn't valid in DNS or URLs (without URL encoding) and '-' means minus half the time. It's impossible to standardise.

**Comment by analytically** [comment] 2020-11-18 16:35
Ran into this while trying to name a resource `amazon-linux-2-x86_64-ami`.

**Comment by vito** [comment] 2020-11-27 00:45
Alrighty - let's go ahead and just allow both `_` and `-`; seems a lot more reasonable based on the feedback so far. I'll drag this into the backlog, but feel free to submit a PR if we don't get to it in time. 👍

I'll reword the title so the work-to-be-done is clearer to whoever picks it up.

Thanks all!

**Closed** 2021-01-07 19:15 UTC
Labels: bug
