### ISSUE TITLE
Concourse dashboard search doesn't autocomplete teams if you're not logged in

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#3353] opened 2019-02-20 21:25 UTC
## Bug Report

Concourse dashboard search doesn't autocomplete teams if you're not logged in. I started noticing this on the latest Concourse 5.x release on https://ci.concourse-ci.org/

## Steps to Reproduce

1. Go to the dashboard https://ci.concourse-ci.org/
2. Make sure you're not logged in
3. Type 'team: `

## Expected Results

Expected to see the top 10 matching results as per   
![screen shot 2019-02-20 at 4 24 35 pm](https://user-images.githubusercontent.com/19274230/53125466-0cbc2200-352c-11e9-9ab6-d07e510b271f.png)

## Actual Results

No dropdown appeared!

## Additional Context

If you login and then try again, you'll see the autocomplete suggestions

## Version Info

**Comment by pivotal-jamie-klassen** [comment] 2019-02-20 21:28
Duplicate of #3322?

**Comment by vito** [comment] 2019-02-23 22:22
@pivotal-jamie-klassen forgot to drag that one in, i'll just close it

**Closed** 2019-03-19 17:54 UTC
Labels: bug, web-ui
