### ISSUE TITLE
long periods of no output + worker rebalancing causes containerd containers to exit

### ISSUE THREAD

**Issue by gaigaslab-operations** [concourse/concourse#6632] opened 2021-03-03 20:02 UTC
## Summary

We are running tanzu bbr and om processes in concourse that take a long time with no output.  Specifically, when the bbr validate process runs on a 500+GB blobstore OR a stemcell upgrade in an environment with many instances of on-demand redsi/rabbitmq.  The errand 'upgrade-all-service-instances' in the redis/rabbitmq update does not provide any output until all the service instances are updated.

When we migrated from 6.7.2 to 7.0.0 and enabled our workers to use runtime containerd instead of garden, we experienced the task being killed after 1 hour of output inactivity with the following message:

```
Backend error: Exit status: 500, message: {"Type":"","Message":"load proc: process does not exist task: not found: unknown","Handle":"","ProcessID":"","Binary":""}
```

When we switch back to garden, these problems go away

We could not find any settings to control this behavior, although we did try:
containerd.request_timeout: 24h
(this is a BOSH deployment of Concourse)

## Steps to reproduce

Run bbr or om on a process that goes over 1h without output

## Expected results
Task completes if the command completes

## Actual results
Task is terminated with:
```
Backend error: Exit status: 500, message: {"Type":"","Message":"load proc: process does not exist task: not found: unknown","Handle":"","ProcessID":"","Binary":""}
```

## Triaging info

* Concourse version: 7.0.0
* Browser (if applicable): N/A
* Did this used to work? Yes - using garden runtime and it still does with garden runtime

**Comment by gaigaslab-operations** [comment] 2021-03-04 02:05
I was able to reproduce this behavior - but it took longer than 1 hour - almost 2 hours:

```
jobs:
- name: sleeptest
  plan:
  - task: sleeptest
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bash
          tag: latest
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo Starting
          touch inputfile
          date
          yes > /dev/null
          date

```

**Comment by gaigaslab-operations** [comment] 2021-03-04 14:07
New information.  Apparently, my initial 1 hour assertion is false (or incomplete).  Analyzing repeated failures of the above pipeline show a pattern where the pipeline is terminated with the above error at the same minute/second (different hour) every occurrence.  At 43 minutes and 51 seconds after the hour, each of these runs was terminated.

That is ODD!

```
538487  sleeptest/sleeptest/14                errored    2021-03-04@01:51:04-0500  2021-03-04@05:43:51-0500  3h52m47s  platform-proving-grounds  <redacted email>
525383  sleeptest/sleeptest/13                errored    2021-03-03@17:55:16-0500  2021-03-03@21:43:50-0500  3h48m34s  platform-proving-grounds  <redacted email>
520273  sleeptest/sleeptest/12                errored    2021-03-03@14:50:27-0500  2021-03-03@17:43:51-0500  2h53m24s  platform-proving-grounds  <redacted email>
```

**Comment by kirillbilchenko** [comment] 2021-03-04 16:01
having the same issue but with a different pattern so only some specific tasks were failing, we updated our workers to 7.0.0 and containerd runtime. Facing the same error even after 3 mins sometimes.

**Comment by taylorsilva** [comment] 2021-03-04 20:00
I took the pipeline @gaigaslab-operations posted and left it running on my machine for 2.5hrs. It never failed or returned the `load proc` error.

I brought up my local concourse using docker-compose with the `concourse/concourse:7.0.0` image.

**Comment by gaigaslab-operations** [comment] 2021-03-04 21:11
@taylorsilva Can you just let it run?  While on 'bbr', it fails consistently after 1h, I have seen the above fail after 2, 3, 4, 5hrs.

It just failed again - this time after over 4 hours.
```
550785  sleeptest/sleeptest/15                errored    2021-03-04@09:04:26-0500  2021-03-04@13:43:50-0500  4h39m24s  platform-proving-grounds  <redacted>
```

**Comment by taylorsilva** [comment] 2021-03-04 21:28
Sure, I'll let it run longer. Had to do other work so that's why I eventually brought it down. Running it also turns my mac into a nice space heater 😝

**Comment by gaigaslab-operations** [comment] 2021-03-04 21:34
Oh, try this one.

**Comment by taylorsilva** [comment] 2021-03-05 02:51
4hrs later, I got it. Dumping a bunch of info to dig into later.
<img width="1265" alt="Screen Shot 2021-03-04 at 9 48 12 PM" src="https://user-images.githubusercontent.com/4583837/110060121-65397300-7d33-11eb-9118-4f3081ebc3ae.png">

Logs:
[6632-web.log](https://github.com/concourse/concourse/files/6087856/6632-web.log)
[6632-worker.log](https://github.com/concourse/concourse/files/6087857/6632-worker.log)

```
▪ fly -t dev cs
handle                                worker        pipeline             job        build #  build id  type   name       attempt
2b256471-155b-4bac-686b-45283a16b1cc  1a01362753c5  wait-no-output-6632  sleeptest  2        2         task   sleeptest  n/a
7fe4c018-7708-447a-7904-b9b4ababc813  1a01362753c5  wait-no-output-6632  sleeptest  2        2         check  image      n/a

▪ fly -t dev vs -d
handle                                worker        type           identifier
4882747b-d90a-486a-5584-faa9e4d2abfd  1a01362753c5  container      container:7fe4c018-7708-447a-7904-b9b4ababc813,path:/,parent:ee5ddbc5-0a0e-4202-4962-1e9b3887a972
5e196854-0f64-4d38-63dc-d89097516d61  1a01362753c5  container      container:2b256471-155b-4bac-686b-45283a16b1cc,path:/tmp/build/50b9a781
63ba473a-0490-472d-7951-5678b5fed2bf  1a01362753c5  container      container:7fe4c018-7708-447a-7904-b9b4ababc813,path:/scratch
7fd9ae03-952a-4b1c-6707-72a379bc8a78  1a01362753c5  resource       name:docker-image,version:1.5.2
a04fcb40-4748-4b71-7a6b-be309b34e711  1a01362753c5  container      container:2b256471-155b-4bac-686b-45283a16b1cc,path:/scratch
e7146182-ac85-422b-5d3c-9482d81f0330  1a01362753c5  container      container:2b256471-155b-4bac-686b-45283a16b1cc,path:/,parent:7fd9ae03-952a-4b1c-6707-72a379bc8a78
ee5ddbc5-0a0e-4202-4962-1e9b3887a972  1a01362753c5  resource-type  name:docker-image,version:1.5.2
```

**Comment by taylorsilva** [comment] 2021-03-05 15:12
The interesting log lines from the web:
```
{"timestamp":"2021-03-05T02:30:11.358938100Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.task-step.registering-outputs","data":{"build":"2","build_id":2,"job":"sleeptest","job-id":1,"outputs":null,"pipeline":"wait-no-output-6632","session":"22.62.2.3","step-name":"sleeptest","team":"main"}}
{"timestamp":"2021-03-05T02:30:11.359003100Z","level":"info","source":"atc","message":"atc.tracker.notify.run.errored","data":{"build":"2","build_id":2,"error":"Backend error: Exit status: 500, message: {\"Type\":\"\",\"Message\":\"load proc: process does not exist task: not found: unknown\",\"Handle\":\"\",\"ProcessID\":\"\",\"Binary\":\"\"}\n","job":"sleeptest","pipeline":"wait-no-output-6632","session":"22.62.2","team":"main"}}
{"timestamp":"2021-03-05T02:30:11.371671300Z","level":"info","source":"atc","message":"atc.tracker.notify.run.finish.errored","data":{"build":"2","build_id":2,"error":"Backend error: Exit status: 500, message: {\"Type\":\"\",\"Message\":\"load proc: process does not exist task: not found: unknown\",\"Handle\":\"\",\"ProcessID\":\"\",\"Binary\":\"\"}\n","job":"sleeptest","pipeline":"wait-no-output-6632","session":"22.62.2.9","team":"main"}}
{"timestamp":"2021-03-05T02:30:11.374923000Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.lock.release.released","data":{"build":"2","build_id":2,"id":[1,2],"job":"sleeptest","pipeline":"wait-no-output-6632","session":"22.62.2.1.2","team":"main"}}
```
Going to dig into this more later today.

**Comment by gaigaslab-operations** [comment] 2021-03-15 16:30
Any update, @taylorsilva ?

**Comment by taylorsilva** [comment] 2021-03-15 17:51
I did look through the code on the web and worker to get an idea of what the code path was. No new insights though. I have no idea why this message is leaking out. This is in our backlog so we'll eventually get into it: https://project.concourse-ci.org/projects/MDc6UHJvamVjdDExODQzMjcw

**Comment by aoldershaw** [comment] 2021-03-17 18:54
Sure enough, we setup a job in https://ci.concourse-ci.org/teams/main/pipelines/test-issue-6632, and saw the issue occur again. In the logs, right before the `process does not exist` error, we again see:

```
worker.beacon-runner.beacon.rebalance.run.command-exited-after-signal
```

...so it definitely seems related to rebalancing

**Comment by chenbh** [comment] 2021-03-18 22:23
Got a reproducible by setting the `CONCOURSE_REBALANCE_INTERVAL=30s` and `CONCOURSE_CONNECTION_DRAIN_TIMEOUT=10s`. Another quick way of reproducing the same behaviour without surfacing the error is to restart the web node once a build has started. The worker logs should still print the task has exited with code 129:
```
{"timestamp":"2021-03-18T22:00:20.396736900Z","level":"info","source":"worker","message":"worker.garden.garden-server.run.exited","data":{"handle":"f080e70a-20cd-4cd8-56fa-75f06186243c","id":"task","session":"1.4.68","status":129}}
```

What's happening is that:
1. the worker attempts to rebalance
2. it closes the current ssh-forward session
3. which waits for the timeout period to drain any connections
4. it then forcibly kills any ongoing stdin/out/err streaming
5. for some unknown reason, this causes containerd to send a `SIGHUP` signal (only found out via `strace`-ing the pid) to the process
6. the worker reconnects to the atc
7. the atc attempts to re-attach to what it thinks is a running process

We're pretty sure it's containerd (either the client library or the actual runtime) that's doing and not garden since we no `Kill` or `Signal` calls ever came through our garden shim.

**Comment by chenbh** [comment] 2021-03-23 20:52
The no output part is actually important here, the `CONCOURSE_CONNECTION_DRAIN_TIMEOUT` is reset every time some data is passed through the SSH connection. 

1. the SSH connection is idle for long enough (i.e. nothing written to stdout for **all** tasks running on the worker / using the same connection) 
2. [the connection is killed](https://github.com/concourse/concourse/blob/bde03716651a312affed2c7c514c87f0c79389e6/tsa/client.go#L97-L99) which cancels the `stdin` streaming ((well it cancels all the other streams, but the `stdin` is the only important one)
3. containerd is doing `io.Copy` from the stdin stream to a FIFO pipe on the system
4. runC is setup to treat that FIFO pipe as the [console/terminal](https://github.com/opencontainers/runc/blob/master/docs/terminals.md)
5. when the `io.Copy` errors because the `stdin.Read()` errors, [containerd closes the console](https://github.com/containerd/containerd/blob/05f951a3781f4f2c1911b05e61c160e9c30eaa8e/runtime/v2/runc/platform.go#L79-L82)
6. that causes `SIGHUP` for unix systems

**Comment by chenbh** [comment] 2021-03-23 21:24
Guardian with containerd backend (`--use-containerd-for-processes`, `--containerd-socket /run/containerd/containerd.sock`) fails in the same way, albeit their error handling is slightly better and marks the container as having failed rather trying to create a new one.

Possible solutions we came up with:
1. Create a "MITM" stdin writer that forwards the stdin stream for as long as it can, and if the stdin stream dies for whatever reason, just do nothing and keep the pipe alive for containerd
2. Take a deeper look at containerd docs and see if we can configure it so that closing the stdin pipe doesn't close the console
3. Build a smart solution where the worker keeps track of stdin pipe by handle/proc id, and reconnects stdin streams to stdin pipes if it gets interrupted midway.

**Closed** 2021-04-26 14:47 UTC
Labels: bug

**Comment by gaigaslab-operations** [comment] 2021-04-26 17:48
What release will include this fix?  I didn't see it in the latest release.

**Comment by chenbh** [comment] 2021-04-27 18:37
@gaigaslab-operations it'll be out in the next release, which should be 7.3.0 targeted around May 6
