### ISSUE TITLE
Lots of `unknown handle` errors since upgrading to 3.0.1 & 3.1.1

### ISSUE THREAD

**Issue by gerhard** [concourse/concourse#1255] opened 2017-06-06 17:18 UTC
Since upgrading Concourse to 3.0.1 & now 3.1.1, we started seeing many `unknown handle` errors, across all pipelines, in both AWS & vSphere:

![image](https://user-images.githubusercontent.com/3342/26842287-337028bc-4ae4-11e7-8638-89ff48ed7f0b.png)

We have re-created the workers, the errors are not going away. Is this a known bug? What else can we try?

* Concourse version: 3.1.1
* Deployment type: BOSH
* Infrastructure/IaaS: same issues across 2 independent Concourse deployments, vSphere & AWS
* Did this used to work? Yes

**Comment by mvdkleijn** [comment] 2017-06-08 16:10
Experiencing the same issue here. We:

- Recreated the workers
- Restarted ATC

Our info:

- Concourse version: 3.1.1
- Deployment type: BOSH
- Infrastructure/IaaS: Openstack
- Did this used to work? Yes

When I run `fly -t admin containers`, I actually do see the "unknown handle" listed but its for pipeline, job, etc "none".

After manually triggering the build, the build still fails with the same reference to the same handle. However, running the `containers` command again, the handle has now disappeared from the list and I see a new handle in the containers list for that pipeline/job.

Strange thing is... is you now again manually trigger it, the build succeeds and the error does not show up.

Any ideas?

**Comment by mvdkleijn** [comment] 2017-06-09 12:56
@vito Any ideas? :smile:

**Comment by vito** [comment] 2017-06-10 14:16
@mvdkleijn @gerhard Next time this happens could you collect all the logs mentioning that handle and throw them in a gist? It's hard to make a call on this without knowing what the container was for.

I suspect it may be related to custom resource types.

**Comment by kelvich** [comment] 2017-06-16 07:42
Also experiencing the same after restart of both tsa and worker (3.1.1).

```
> fly -t ci3 cr -r PGPROEE9_6/pgpro
error: Unexpected Response
Status: 500 Internal Server Error
Body:
```

On TSA side:
```
{"timestamp":"1497598698.248210430","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.11.12.1:50342","session":"2","type":"keepalive"}}
{"timestamp":"1497598703.248268843","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.11.12.1:50342","session":"2","type":"keepalive"}}
{"timestamp":"1497598704.582349539","source":"atc","message":"atc.check-resource.failed-to-lookup-created-container-in-garden","log_level":2,"data":{"container":"cc1db4ff-9f59-4a73-459b-82f4f3e74f30","error":"unknown handle: cc1db4ff-9f59-4a73-459b-82f4f3e74f30","session":"1553"}}
{"timestamp":"1497598704.582401752","source":"atc","message":"atc.check-resource.failed-to-initialize-new-container","log_level":2,"data":{"error":"unknown handle: cc1db4ff-9f59-4a73-459b-82f4f3e74f30","session":"1553"}}
```

Also following error exist in logs for all resources:
```
{"timestamp":"1497598736.616182327","source":"atc","message":"atc.syncer.PGPROEE9_6:radar.scan-resource.tick.failed-to-initialize-new-container","log_level":2,"data":{"error":"unknown handle: ce9c7685-c31b-44ab-597c-d61f66ec8593","pipeline-scoped-name":"PGPROEE9_6:resource:mamonsu","session":"17.1.28.5"}}
{"timestamp":"1497598736.617537975","source":"atc","message":"atc.syncer.PGPROEE9_6:radar.scanner-failed","log_level":2,"data":{"error":"unknown handle: ce9c7685-c31b-44ab-597c-d61f66ec8593","member":"PGPROEE9_6:resource:mamonsu","session":"17.1"}}
```

**Comment by kelvich** [comment] 2017-06-16 08:07
Hm, also found some `dial tcp 127.0.0.1:35201: getsockopt: connection refused` messages, rebooted server and now resources works properly.

**Comment by cnelson** [comment] 2017-06-19 17:38
Any chance you have `garden.default_container_grace_time:` set in your manifest?

We did and saw the same issues until we removed it.  [Discussion in slack about it is here.](https://concourseci.slack.com/archives/C07RY25QF/p1495034421311428)

**Comment by gerhard** [comment] 2017-06-20 13:47
Yes, we did. We've removed `garden.default_container_grace_time` & also upgraded to 3.2.1, will close this issue if the problem doesn't come back within a week.

**Comment by chendrix** [comment] 2017-06-27 01:04
@gerhard any update?

**Comment by gerhard** [comment] 2017-06-30 17:14
I've been avoiding Concourse on purpose, it always turns into a time sink when I look at it. Maybe @dumbbell has something to share. Will follow-up next week, thanks for the reminder.

**Comment by JohannesRudolph** [comment] 2017-07-03 15:58
https://github.com/concourse/concourse/issues/1255 seems to be related as well and I see the same issue whenever I restart our docker-compose based concourse deployment. 

Any insights what we can do to fix this? Running 3.2.1 btw.

**Comment by JohannesRudolph** [comment] 2017-07-03 16:03
Some more info, I see that the worker is registered (and to make sure, I pruned old workers too). It even has a container count but doing a container list shows nothing: 

```
iDevBook01:Downloads jr$ fly -t cimain workers
name          containers  platform  tags  team  state    version
8f0c7dcec304  48          linux     none  none  running  1.1    
iDevBook01:Downloads jr$ fly -t cimain containers
handle  worker  pipeline  job  build #  build id  type  name  attempt
iDevBook01:Downloads jr$ 
```

**Comment by andrewedstrom** [comment] 2017-07-14 17:51
Has anyone figured out a series of steps we can use to recreate this issue? We want to look into this but since we aren't experiencing the issue ourselves it's tough for us to debug.

**Comment by gerhard** [comment] 2017-07-14 18:06
I haven't found any `unknown handle` errors in our logs, happy to have this closed.

We are now on 3.3.1

**Comment by pms1969** [comment] 2017-07-17 10:03
I see this a lot.  It happens after a linux worker stalls due to some  problem.  I often have to rebuild the workers and the atc's.  Strangely, the windows workers are much more sturdy.

Haven't been able to figure out exactly what kills the workers, but there are tonnes of containers and gazillions of volumes, and I don't really know how to clean them up???

I'm about to update to 3.3.2.  Hopefully this will fix whatever the problem is.

**Comment by JohannesRudolph** [comment] 2017-07-27 12:50
> Has anyone figured out a series of steps we can use to recreate this issue? We want to look into this but since we aren't experiencing the issue ourselves it's tough for us to debug.

It's actually fairly easy with 3.3.2. We run our concourse via `docker-compose`. Everytime we recreate the worker container, concourse lists the old worker as "stalled" and registers the new, recreated worker und a new id. In any other deployment, this essentially amounts to killing a worker and replacing it with a new instance. 

What we see is that for a few minutes the new worker has no containers, then slowly having a few check containers. During this whole time the concourse ui shows lots of "unknown handle: <GUID>" errors on our resources (and they are in the orange error state). After > 30min concourse appears to "catch up" and resources turn back to green. We sometimes also see "file not found" errors on the resources instead of the "unknown handle".

**Comment by JohannesRudolph** [comment] 2017-07-27 13:12
The `file not found` errors appear to be the same as #1251

**Comment by topherbullock** [comment] 2017-07-31 18:46
I think this is due to haw "stalled" workers are treated in the pool, and that there is potentially an issue with stalled workers being considered when they shouldn't be.

One course of action might be to where this error actually is returned and trace back why it selected the stalled worker in the first place

**Comment by topherbullock** [comment] 2017-08-09 14:09
#1458 captures the gist of my previous comment, closing in favour of that one. Should address these errors, which aren't very descriptive, and shouldn't happen in the first place (since we know the workers aren't in a usable state)

**Closed by topherbullock** 2017-08-09 14:09 UTC
Labels: area: troubleshooting, needs-investigation, type: bug

**Comment by Meshimages** [comment] 2017-08-22 12:12
> What we see is that for a few minutes the new worker has no containers, then slowly having a few check containers. During this whole time the concourse ui shows lots of "unknown handle: " errors on our resources (and they are in the orange error state). After > 30min concourse appears to "catch up" and resources turn back to green. We sometimes also see "file not found" errors on the resources instead of the "unknown handle".

Can confirm this in a docker-compose (using official concourse/concourse repo) environment.

**Comment by chris-aeviator** [comment] 2017-08-22 12:15
> What we see is that for a few minutes the new worker has no containers, then slowly having a few check containers. During this whole time the concourse ui shows lots of "unknown handle: " errors on our resources (and they are in the orange error state). After > 30min concourse appears to "catch up" and resources turn back to green. We sometimes also see "file not found" errors on the resources instead of the "unknown handle".

I can confirm the same behaviour in an  `docker-compose` environment with official `concourse/concourse` repo.

**Comment by william-tran** [comment] 2017-09-18 20:56
I think this issue needs to be re-opened. I'm on concourse 3.4.1 running on k8s via helm chart.  Regardless of how a worker process ended (SIGKILL, SIGTERM, land-worker, retire-worker), when it starts up again it always cleans up its container volumes. TSA (?) sees the worker come back under the same name and expects volumes to be there but they aren't. I see this in the logs at startup

```
{"timestamp":"1505767465.598683357","source":"guardian","message":"guardian.start.clean-up-container.start","log_level":1,"data":{"handle":"5a86c759-daff-4dee-44cc-a87ed154533b","session":"6.10"}}
{"timestamp":"1505767465.598800182","source":"guardian","message":"guardian.start.clean-up-container.destroy.started","log_level":1,"data":{"handle":"5a86c759-daff-4dee-44cc-a87ed154533b","session":"6.10.1"}}
{"timestamp":"1505767465.604939699","source":"guardian","message":"guardian.start.clean-up-container.destroy.state","log_level":1,"data":{"handle":"5a86c759-daff-4dee-44cc-a87ed154533b","session":"6.10.1","state":{"Pid":123,"Status":"created"}}}
```

I have a PR to the chart that works around this issue: https://github.com/kubernetes/charts/pull/2109

**Comment by topherbullock** [comment] 2017-09-20 13:54
The issue isn't really about upgrading to 3.0.1 & 3.1.1 , and the `unknown handle` error is really just a side effect of worker lifecycles and how those volumes are handled. This issue is in the closed state simply because there are 2 more actionable issues which propose real solutions to the observed errors: #755 #1458 . 

Feel free to keep adding situations where these errors occur on this issue or the aforementioned ones; the core team works off Github issues organized in a backlog and the goal here is to consolidate and distill into something actionable.

**Comment by jadekler** [comment] 2017-09-20 23:17
Ran into this today, too, on 3.4.1

**Comment by gerhard** [comment] 2017-10-05 17:17
I'm on 3.5 (running as a binary) and this hit me hard today. This is what I was seeing in the logs every 2 minutes:

```
Oct  5 17:02:12 ci runsvdir-start[3289]: {"timestamp":"1507222932.464753628","source":"atc","message":"atc.syncer.infrastructure:radar.scan-resource.interval-runner.tick.failed-to-lookup-created-container-in-garden","log_level":2,"data":{"container":"fc403126-b5b7-4c8b-5ade-dd7b2180077e","error":"unknown handle: fc403126-b5b7-4c8b-5ade-dd7b2180077e","pipeline-scoped-name":"infrastructure:resource:infrastructure","session":"16.1.36.1.6"}}
Oct  5 17:02:12 ci runsvdir-start[3289]: {"timestamp":"1507222932.464875698","source":"atc","message":"atc.syncer.infrastructure:radar.scan-resource.interval-runner.tick.failed-to-initialize-new-container","log_level":2,"data":{"error":"unknown handle: fc403126-b5b7-4c8b-5ade-dd7b2180077e","pipeline-scoped-name":"infrastructure:resource:infrastructure","session":"16.1.36.1.6"}}
Oct  5 17:02:12 ci runsvdir-start[3289]: {"timestamp":"1507222932.472824335","source":"atc","message":"atc.syncer.infrastructure:radar.scanresources-runner-error","log_level":1,"data":{"error":{"Handle":"fc403126-b5b7-4c8b-5ade-dd7b2180077e"},"session":"16.1"}}
```

Eventually this specific handle gets fixed by this:

```
Oct  5 17:04:42 ci runsvdir-start[3289]: {"timestamp":"1507223082.464618921","source":"guardian","message":"guardian.destroy.start","log_level":1,"data":{"handle":"fc403126-b5b7-4c8b-5ade-dd7b2180077e","session":"369"}}
Oct  5 17:04:42 ci runsvdir-start[3289]: {"timestamp":"1507223082.464885235","source":"guardian","message":"guardian.destroy.finished","log_level":1,"data":{"handle":"fc403126-b5b7-4c8b-5ade-dd7b2180077e","session":"369"}}
Oct  5 17:04:42 ci runsvdir-start[3289]: {"timestamp":"1507223082.464943409","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: fc403126-b5b7-4c8b-5ade-dd7b2180077e","handle":"fc403126-b5b7-4c8b-5ade-dd7b2180077e","session":"3.1.453"}}
```

But I have another resource which never gets destroyed, so it remains in this `unkown handle` state.

Re-creating the pipeline doesn't fix it. I have no stale workers. I'm going to try renaming the resource, see if it fixes the issue.

**Comment by drahnr** [comment] 2017-10-19 08:13
@william-tran I can confirm this behaviour with 3.5.0 and native binary.

**Comment by gerhard** [comment] 2017-10-19 09:19
In my experience, the best strategy of fixing this is to nuke everything and start from scratch. I don't care about the build history, so I just hard kill everything and start from a vanilla OS image. I run everything (worker, web & db) on a single host, so things are very simple. If you have worker hosts, nuking just those might be enough, but I wouldn't know.

**Comment by brandon-bethke-neudesic** [comment] 2017-10-20 20:46
This 'unknown handle' issue on the resource check happens frequently for us. We are using built-in and custom resources and it happens on both. We are running 3.5.0.
It's worth noting that this is happening on a resource that triggers the entire pipeline. So in a nutshell, this issue is preventing our pipelines from running.
Taken from the web ui logs. 
```
{"timestamp":"1508531599.956529617","source":"atc","message":"atc.syncer.mypipeline:radar.scan-resource-type.interval-runner.tick.failed-to-lookup-created-container-in-garden","log_level":2,"data":{"container":"ad
17fd56-5c08-4f9f-405c-e4b9bda57db7","error":"unknown handle: ad17fd56-5c08-4f9f-405c-e4b9bda57db7","pipeline-scoped-name":"mypipeline:resource-type:health-status-file","session":"16.7.41.1.12"}}
"timestamp":"1508531599.956656218","source":"atc","message":"atc.syncer.mypipeline:radar.scan-resource-type.interval-runner.tick.failed-to-initialize-new-container","log_level":2,"data":{"error":"unknown handle: 
ad17fd56-5c08-4f9f-405c-e4b9bda57db7","pipeline-scoped-name":"mypipeline:resource-type:health-status-file","session":"16.7.41.1.12"}}
{"timestamp":"1508531599.957147360","source":"atc","message":"atc.syncer.mypipeline:radar.scanresources-runner-error","log_level":1,"data":{"error":{"Handle":"ad17fd56-5c08-4f9f-405c-e4b9bda57db7"},"session":"16.7
"}}
```

**Comment by brandon-bethke-neudesic** [comment] 2017-10-20 23:45
Using the latest helm chart. I see this error in the pod history.

```
Liveness probe failed: Fatal error detected: {"timestamp":"15
08540130.715145588","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: 50b62307-38e8-4e35-73e2-1e0e52351e1c","handle":"50b62307-38e8-4e35-73e2-1e0e52351e1c","session":
"3.1.59"}}
{"timestamp":"1508540130.735813379","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: a7f70aa9-2e0b-4f87-5288-eb251fcbdc5c","handle":"a7f70aa9-2e0b-4f87-5288-eb251fcb
dc5c","session":"3.1.61"}}
{"timestamp":"1508540130.767119408","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: a47da79e-ffa7-4c08-43a8-92bf1e2c5e76","handle":"a47da79e-ffa7-4c08-43a8-92bf1e2c
5e76","session":"3.1.64"}}
{"timestamp":"1508540130.807168007","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: 99bbce09-12ee-4f6b-73d6-0e44813f1a94","handle":"99bbce09-12ee-4f6b-73d6-0e44813f
1a94","session":"3.1.65"}}
{"timestamp":"1508540130.807623625","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"unknown handle: f162c9ad-ed3f-431e-55ee-d7622d68853e","handle":"f162c9ad-ed3f-431e-55ee-d7622d68
853e","session":"3.1.66"}}
```

**Comment by william-tran** [comment] 2017-10-21 14:13
@brandon-bethke-neudesic since you're using the helm chart, this error will cause the worker to retire and the container to restart; you should be able to see the number of restarts when you kubectl get pods. Retiring and restarting the worker is the only way I've been able to recover the worker. I've found it happens more often when the node hosting the worker hits Max cpu, so you could try bumping up the instance type.

**Comment by EugenMayer** [comment] 2017-11-19 14:14
This issue is related to the broken worker draining in non-bosh environements. I could fix that using https://github.com/concourse/concourse/issues/1457#issuecomment-345519748

**Comment by william-tran** [comment] 2017-12-15 02:38
@brandon-bethke-neudesic I started running into the errors you saw `guardian.api.garden-server.destroy.failed` very frequently on 3.8.0, but it might have also been caused by running multiple concourse-web pods. When you run multiple web pods, I saw in the pods that there were multiple requests to delete the same thing, and the second request would fail and trigger a pod restart. I'm testing things without `unknown handle` as a fatal error, making worker pod schedule on nodes specific to them, and stopped using persistent volumes. I'm load testing our setup and so far so good.

**Comment by francoisruty** [comment] 2018-01-24 15:10
I'm encountering this issuse too.
I use docker-compose to run Concourse, and each time I restart (docker-compose restart), all resource cheks start failing with "unknown handle" errors

**Comment by dolph** [comment] 2018-02-01 16:00
I just ran into this issue on almost every resource in my deployment after rebooting the host with `reboot -n`.

* I'm running concourse with `docker-compose`.
* I do not use any custom resources types. The resources that are failing are `git` and `time`. If my `docker-image` resources were failing, I didn't notice.
* I do not use `garden.default_container_grace_time`.
* I have several dozen resources in 5 pipelines.
* I have 435 volumes currently listed with `fly volumes | wc -l`.

The issue seems to be slowly resolving itself (my docker uptime is about 40 minutes and more than half of my resources are available again.

**Comment by Jarlotee** [comment] 2018-08-08 00:00
This happens every time i restart my worker non-bosh on ubuntu any update on this?

**Comment by romerojunior** [comment] 2018-08-13 13:57
happening with 3.14.1 after restarting concourse-web and concourse-worker services (non-bosh)

**Comment by vorotech** [comment] 2018-09-12 19:17
still happening with 4.0.0 each time after `docker-compose up -> Ctrl+C -> docker-compose up`
docker on windows, I'm using official docker compose file

**Comment by OvermindDL1** [comment] 2018-09-25 03:35
Still happening in 4.2.1, similar stats as listed recently as well, a simple 1 git resource to 1 action pipeline and it happens for a long time.  Restarting the worker (which has an active heardbeat log and `fly -t ... workers` lists as online and all) then clearing the old stale worker gets it working within a few minutes until it just stops for seemingly no reason again...

**Comment by kalfa** [comment] 2018-12-11 15:34
I've experienced the unknown handle problem.

It was cause in my case by me, rebuilding the workers without landing them.

Once the workers built and came up with the same name (a problem in my pipeline), TSA got confused.

Within this scenario, I solved it this way:
- land each worker
- prune each worker
- restart each worker

so that the worker "past handles" are forgotten, and the new worker (even with the same name) can re-register without creating issues, as it were a brand new worker name.

Maybe this helps.
