### ISSUE TITLE
Web UI task duration is -18051 days and unintuitive

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#3978] opened 2019-06-04 16:14 UTC
I was very excited for the task duration shown on the web ui in Concourse 5.1. However, I was pretty surprised the task duration is only visible on hover. I'm fine with the detailed stats revealed on hover (i.e. init etc.) but the total task execution time is something I'd like to see front and center - build performance is crucial after all!

Anyhow, I get weird durations for pretty all the resource operations I checked (just a few because hover is... annoying.).

![Screenshot from 2019-06-04 18-07-05](https://user-images.githubusercontent.com/130103/58895359-02492100-86f4-11e9-8e51-a026ddefa51e.png)

Task steps seem to produce fine results. 

## Version Info

* Concourse version: 5.2.0

**Comment by marco-m** [comment] 2019-06-04 20:22
Looks like a duplicate of #3975 3835 which has already been fixed :-)

**Comment by pivotal-jamie-klassen** [comment] 2019-06-05 00:49
@marco-m yep @mockersf submitted the fix for both get and put steps

**Closed by pivotal-jamie-klassen** 2019-06-05 00:49 UTC
Labels: bug
