### ISSUE TITLE
Autocomplete on search has an invalid dropdown

### ISSUE THREAD

**Issue by pivotal-saman-alvi** [concourse/concourse#3255] opened 2019-02-08 22:14 UTC
## Bug Report
Autocomplete dropdown on main CI page presents a white dropdown (possibly a browser default), which prevents you from seeing the original dropdown on the page. It stops interaction with the original dropdown so you cannot autocomplete `team` or `status` options.

## Steps to Reproduce
1. Type some random text in the search field until the browser saves the search
2. Click the search bar and attempt to search to view the dropdown
3. See that it competes with the original dropdown

## Version Info
You can see this on CI at the moment.

![screen shot 2019-02-08 at 5 03 22 pm](https://user-images.githubusercontent.com/8999128/52508726-916d7e80-2bc3-11e9-99ec-5f98fabc4ce3.png)

**Comment by vito** [comment] 2019-02-13 18:28
Hmm I can't get this to happen.

**Comment by pivotal-jamie-klassen** [comment] 2019-02-13 19:54
@vito I think it may be browser-dependent. In @pivotal-saman-alvi's example I think maybe Chrome is doing something (maybe passively?) about the fact that that particular sample string `asdfsdf` has been entered in that particular input many times and it popping up its own suggestion... I guess the hope here is that there might be some way to tell the browser not to show an autocomplete on certain text inputs? Which is probably not a bug.

**Comment by pivotal-jamie-klassen** [comment] 2019-03-01 17:41
Closing in favour of #3381 which has some better context

**Closed by pivotal-jamie-klassen** 2019-03-01 17:41 UTC
Labels: bug, web-ui
