### ISSUE TITLE
postgres concourse DB utilization stays 99 to 100 percent most of the times.

### ISSUE THREAD

**Issue by sree4062git** [concourse/concourse#5598] opened 2020-05-13 13:57 UTC
## Summary

we are on concourse 5.2.4 version, We have multiple concourse pipelines running as part of our day today operations, we have the postgres SQL DB on AWS RDS. We are seeing the CPU utilization is always reaching 100 percent. We are restarting the concourse DB to temporarily fix the issue, once the restart is done the CPU utilization looks low, however after one or two days of restart the CPU again reaches 99 percent.

I have seen the same issues reported on older versions(3.x and 4.x) and the issues were addressed on later versions. I am unable to find any solutions for 5x version, has anyone observed the issue like this and have any resolution steps?

* Concourse version: 5.2.4
* Browser (if applicable): chrome

**Comment by clarafu** [comment] 2020-05-13 18:16
@sree4062git Hi, I am going to close this issue for now because it feels like it belongs more as a discussion rather than a bug report. For it to be a bug report, we would need clear reproducible steps that can be used to debug exactly what and where the problem is coming from. I would instead suggest that you open up a discussion for your issue through this link https://github.com/concourse/concourse/discussions/new where we can gather more information about what the underlying problem is.

That being said, to answer your question it really depends on what is causing the high load on your database. There are a few database inspection queries that can help you figure out what your database is spending the most time on (for example, the query to find the slowest queries by avg time https://github.com/concourse/concourse/wiki/Schema-Inspection-Queries#show-the-top-n-slowest-queries but maybe modify it to show the slowest queries according to total time). We can discuss further workarounds after we figure out what exactly is causing the high DB cpu for your cluster.

**Closed by clarafu** 2020-05-13 18:16 UTC
Labels: bug
