### ISSUE TITLE
Concourse does not track users triggering a job

### ISSUE THREAD

**Issue by luis-ledezma** [concourse/concourse#3554] opened 2019-03-20 18:16 UTC
Is there any way to track which user manually triggers a job in concourse? History records seems to be poor without this.

**Comment by marco-m** [comment] 2019-03-20 19:46
Hello, this is a duplicate of #194, I suggest closing this issue and following the original.

**Comment by vito** [comment] 2019-03-20 23:46
also a dupe of https://github.com/concourse/concourse/issues/2752 which is more specifically about this

**Closed by vito** 2019-03-20 23:46 UTC
