### ISSUE TITLE
"Login session expired" error with multiple ATCs

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#2425] opened 2018-07-28 14:10 UTC
# Bug Report

After we upgraded to 4.0, we started getting "Login session expired" errors on login. We tracked the error down to https://github.com/coreos/dex/blob/master/server/handlers.go#L215-L224 and then figured out that the atc is using the dex memory store: https://github.com/concourse/skymarshal/blob/master/dexserver/dexserver.go#L73. That seems to lead to login errors when load-balancing across multiple atc instances. We fixed the issue by enabling sticky sessions on our load balancer. This leads to the following:

# Feature Request

If my understanding of the situation is correct, it would be helpful to:
* Optionally configure dex to store session state in postgres
* Or, if there's a reason that wouldn't work, document that a concourse with multiple atc instances need to use sticky sessions

cc @LinuxBozo @sharms

**Comment by xyloman** [comment] 2018-07-28 14:38
We ran into the same issue but have only one ATC running at this time.

**Comment by pivotal-nader-ziada** [comment] 2018-07-30 14:07
Hello @jmcarp and @xyloman 
We have not seen this issue in any of our environments even though we use multiple ATCs, Can you please add the ATC logs to help us investigate the issue further.
Thanks

**Comment by xyloman** [comment] 2018-08-01 01:47
@pivotal-nader-ziada Is there specific logs fragments that would help.  We are using github enterprise auth.  When I get back in the office tomorrow I should be able to log into the concourse cluster and pull some logs after increasing the instance count from 1 to 2 on the ATC.

**Comment by xtremerui** [comment] 2018-08-01 02:07
@xyloman if you search the error in atc log it should bring you to the sections to look for. Logs from atc skymarshal and dex would be helpful.

**Comment by wendorf** [comment] 2018-08-02 20:43
I just ran into this with multiple ATCs (problem wasn't reproducible with a single ATC). I've configured only GitHub auth.

Only (seemingly) relevant log from ATC 1:

```
{"timestamp":"1533242377.697374105","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector \"github\", name=\"me\", email=\"me@example.com\", groups=[\"my-org:my-team\"]","session":"6"}}
```

Only (seemingly) relevant log from ATC 2:

```
{"timestamp":"1533242377.805443287","source":"atc","message":"atc.dex.event","log_level":2,"data":{"fields":{},"message":"Failed to get auth request: not found","session":"6"}}
```

**Comment by sharms** [comment] 2018-08-02 20:45
Not sure this needs logs: how could a in memory session store without a consensus based algorithm work for multiple nodes?

Without persistent sessions I don’t believe that is possible.

**Comment by xtremerui** [comment] 2018-08-03 14:48
@sharms with the logs example @wendorf posted we found similar error logs in our own env. It just happened several times so it was hard to trace it down. We can confirm it is indeed an issue. Thx.

**Comment by xyloman** [comment] 2018-08-09 19:01
@xtremerui  we have seen the same entries in our logs that @wendorf  posted.  We have multiple ATCs working currently but only have one in the external load balancer to ensure that we avoid this issue for users attempting to log into the system.

**Comment by hprotzek** [comment] 2018-08-10 08:02
We are using the helm chart (from @wendorf) and if we are running with 2 web nodes, we see these errors too and can't login.  Neither with local users or github auth. 

Configuring sticky sessions (nginx.ingress.kubernetes.io/affinity: "cookie") in the nginx ingress controller helps only for the local user auth, not for the github auth.

**Comment by sharms** [comment] 2018-08-10 14:20
As @jmcarp mentioned, dex supports a shared session store across nodes, we just need to submit a patch to document and enable it.

**Comment by cirocosta** [comment] 2018-08-10 14:26
Hey,

<br />

FYI, the issue can be reproduced locally by:

- creating a GitHub OAuth application in GitHub (see https://concourse-ci.org/install.html#github-auth-config);
- raising two ATCs (make sure you have them on different ports) passing the GitHub application credentials;
- putting a roundrobin load-balancer in front of the ATCs; then
- trying to login using GitHub auth.

Using a sample `Procfile`, we can have the two ATCs and a DB configured as following:

```Procfile
atc1: ./atc --bind-port=8030 --debug-bind-port=8079 --github-client-id=$GITHUB_ID --github-client-secret=$GITHUB_SECRET --external-url=http://localhost:8080
atc2: ./atc --bind-port=8765 --debug-bind-port=8077 --github-client-id=$GITHUB_ID --github-client-secret=$GITHUB_SECRET --external-url=http://localhost:8080
db: ./db
```

For the load-balancer part, we can have an HAProxy configured with the following:

```cfg
defaults
  mode http

frontend http
  bind *:8080
  default_backend mybackend

backend mybackend
  balance roundrobin
  server atc1 127.0.0.1:8030
  server atc2 127.0.0.1:8765
```

such that on port 8080, HAProxy balances the load between ATC1 (8030) and ATC2 (8765).

Given that the auth flow would start in ATC_X (either 1 or 2), and then finish (github callback) in ATC_Y (the other), we can see the failure.

<br />

thx!

**Comment by jmcarp** [comment] 2018-08-13 22:38
If the client secret needs to be shared across all ATCs, it seems like we should configure it via a flag passed to ATC and set by the orchestrator (BOSH, k8s, etc). WDYT @ddadlani ?

**Comment by jmcarp** [comment] 2018-08-14 04:34
It turned out that setting the client secret via flag instead of generating on start was pretty simple, so I submitted a patch at https://github.com/concourse/skymarshal/pull/5. Want to pull that into your patch for postgres state storage and see if multiple ATCs work as expected @ddadlani ? I can also add postgres storage and test it out myself when I have time.

**Comment by vito** [comment] 2018-08-14 13:41
@jmcarp Ah good catch! Yeah, having that set on start across the ATCs makes sense.

Though I wonder if we can take a shortcut and just derive the client secret from the session signing key, which serves a kinda similar purpose (and also has to be configured across all ATCs). This would just be in interest of minimizing the steps/config needed to get Concourse going for the first time.

Maybe we could just take a hash of the private key? I don't *think* there are any glaring security concerns here, since they're both secrets already and it's not like we'd want to expose the hashed form, either.

**Comment by ddadlani** [comment] 2018-08-14 14:07
@jmcarp we are already working on adding postgres storage. We'll also add in what @vito suggested and test it out. Thanks for the help!

**Comment by ddadlani** [comment] 2018-08-14 21:09
We added the `dex` tables into our database by putting them in a new schema called `dex`, which we added using a migration. We are using a schema to prevent future table name conflicts.

This works locally but breaks in the bosh release, because the bosh release DB is owned by `vcap` but the database user is `atc`. `atc` does not have enough permissions to create a schema in the database. This is also likely to be a problem in other deployment environments. 

To mitigate this for the bosh release, we could submit a PR for the [postgres release](https://github.com/cloudfoundry/postgres-release) to add the ability to create a schema when creating a database. But this issue still requires further consideration.

**Comment by mhuangpivotal** [comment] 2018-08-20 18:02
We pushed our work on a [branch](3141edf35c561878482c717e2b688c02b6b7b771):
- this approach uses [postgres schema](https://www.postgresql.org/docs/9.5/static/ddl-schemas.html) to separate out the dex tables in the atc database
- the migration to add the dex schema only works if the database user has `CREATE` privilege on the atc database. With BOSH, this can be done with a post_start hook
- the client secret is generated by taking the SHA-256 of the private key and is shared by all ATCs

Because of the postgres permission restrictions, we are going to explore using a prefix for dex tables without a separate shema.

**Comment by mhuangpivotal** [comment] 2018-08-21 16:00
We tried a couple of approaches to prefix the dex tables:
- change the table names everywhere. There are 26 queries, each query potentially having multiple table names. This comes with a high maintenance cost, especially if we cannot get the PR merged
- use a postgresql parser to insert prefixes at runtime via custom `sql.DB` implementation. This introduces a new dependency and requires the parser to support the full postgres syntaxes. We played with https://github.com/xwb1989/sqlparser and it errored on a few complex queries we tried.

**Comment by mhuangpivotal** [comment] 2018-08-21 18:57
We decided to store dex tables within `atc` database without additional schema or prefix. While this makes development slightly confusing (dex has a table called `migrations`), this avoids the risk of a breaking change or the need to substantially alter dex.

**Closed** 2018-08-30 14:48 UTC
Labels: accepted, bug, needs-docs, size/medium
