### ISSUE TITLE
Dashboard Feedback

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#1829] opened 2017-11-21 02:05 UTC
Somethings we are looking for feedback on:
- Running Animation
- Colour palette
- Font 
- Readability on a monitor
- Timestamp
- new icons

**Some issue that we are hoping to close with this feature:** 
Colour blind mode #1275
Bug Report: animation seems to be stuck flashing in the background! #1206
Bug report: animation of previously failed pipeline that is building now "flashes" (can possibly cause epilepsy). #1008

**Comment by jama-pivotal** [comment] 2017-11-21 14:12
Just dropping in a few related issues:
https://github.com/concourse/concourse/issues/1806
https://github.com/concourse/concourse/issues/1818

**Comment by Eulerizeit** [comment] 2017-11-21 17:45
It is important that the dashboard use as little resource as possible. The wonderful thing about Dave Goddard's implementation is the fact that it uses hardly any CPU or memory enabling me to keep the CI open on my computer and do other work.

**Comment by srbry** [comment] 2017-11-29 16:22
To plug Dave Goddards work again, he has a feature that is missing from the current `/beta/dashbaord`. His automatically scales to make sure all jobs can show on a single screen. This is very important for a dashboard in my opinion as you dont want to have to scroll around it to be able to see all your jobs.

Another feature that he has thats missing here is scaling on the pipeline name text, rather than just showing `...` it does a pretty good job of reducing the size of the text to show it all if its sensible to do so.

**Comment by srbry** [comment] 2017-11-29 16:24
Also how much can we customise dashboards? I might have 6 pipelines and only care about monitoring 4 of those pipelines, and of those 4 I might only care about "some" of the groups. Something akin to the `CS_GROUPS` in `concourse-summary`

**Comment by Eulerizeit** [comment] 2017-11-29 16:36
Being able to Dashboard a subset is a big deal. +1 to that.

**Comment by flavorjones** [comment] 2017-11-29 18:34
I've +1ed the `CS_GROUPS`-like suggestion above; but I'd like to additionally suggest that the dashboard by default show a `pipeline-grid` for each `group` defined in the Concourse configuration. This would handle the common pattern of using a `group` to compartmentalize a PR pipeline, for example.

**Comment by jama-pivotal** [comment] 2017-11-29 18:42
@srbry I wonder if the search bar would be sufficiently powerful to help you dashboard specific pipelines. Right now it only supports searching by name, and `team:` and `status:` but it might be able to provide some kind of specialized view.

**Comment by christophe-f** [comment] 2017-12-01 14:27
In the new beta dashboard, is there a way to show only the pipelines having a red status?

**Comment by freelock** [comment] 2017-12-01 17:26
+1 on scaling to show all pipelines -- we currently have around 60, and this number is only growing.

Otherwise it's a good start...

**Comment by jama-pivotal** [comment] 2017-12-01 19:09
@christophe-f if you're using 3.6.0 or 3.7.0 you should be able to do some magic search things. Try `status:fail` or `team:foo`

**Comment by christophe-f** [comment] 2017-12-01 19:53
Thanks James

**Comment by elgohr** [comment] 2017-12-03 14:03
I'm already using and loving the Dashboard.
Nevertheless it might be more useful when the running tasks were be blinking, instead of the top bar of the pipeline.

**Comment by airtonix** [comment] 2017-12-07 08:34
- font is hard to read, the old one was heaps better.
- colour palette:
  - current job in progress is red: confused me... is it failing, tried checking which task was failing... nope no jobs failed yet... why is it red? if it's failed, why are other tasks still running?... oh it's different red from other failed red jobs. the old grey was obvious... it meant; outcome has yet to be determined.

- no tooltips : ![image](https://user-images.githubusercontent.com/61225/33705755-66310054-db81-11e7-84ef-670c01385f27.png)

**Comment by Lindsayauchin** [comment] 2017-12-07 19:14
@airtonix thank you for the feedback!
From the screenshot provided you are looking at the beta pipeline view not the dashboard. Please use /beta/dashboard/ to view the dashboard view. 
The pipeline UI is in very early stages of design so stay tuned for more updates on the fonts, color, tooltips, etc.

**Comment by airtonix** [comment] 2017-12-08 04:03
@Lindsayauchin yeah that's actually what I get when i goto `http://concourse.fusion.one/beta/dashboard/`. 

![image](https://user-images.githubusercontent.com/61225/33750581-ceb8d0ae-dc24-11e7-8707-b7fc6ab2d131.png)

**Comment by aashah** [comment] 2017-12-18 18:53
We're finding currently running jobs showing up as red when viewed through the `/beta` page.
![screen shot 2017-12-18 at 10 51 45 am](https://user-images.githubusercontent.com/1176726/34122505-87167002-e3e1-11e7-941b-f146807b4d28.png).

Would you like us to open a new issue to try and get some reproduction steps? Or is this a known issue?

**Comment by aashah** [comment] 2017-12-18 19:01
One feature request would be to allow specifying the search value in the URL. i.e. `https://my.concourse.example.com/beta/dashboard?search=team%3Amy-team`

**Comment by phynias** [comment] 2018-01-04 19:14
did something change in 3.8.0 ? when i go to /beta/dashboard/ it only shows 1 pipeline. it's basically the same page as /beta/

**Comment by Lindsayauchin** [comment] 2018-01-11 17:05
@airtonix are you on version: v3.8.1?

**Comment by phynias** [comment] 2018-01-11 18:29
3.8.0

**Comment by Lindsayauchin** [comment] 2018-01-11 21:40
I think you are in the wrong directory @phynias @airtonix take of the last slash from the url. Try "/beta/dashboard" instead of "/beta/dashboard/" :)

**Comment by phynias** [comment] 2018-01-11 22:38
yes!! thanks!!

**Comment by itsdalmo** [comment] 2018-01-12 12:30
Love:
- The new dashboard. It's really useful.
- The new layout (in the dashboard view).
- The new colour palette (with the exception of the gray/brown background).

Dislike:
- The new pipeline view.
- Mixed feelings about the new font.

I really feel that the new pipeline view is actually much worse than the old. The new view does not look like a pipeline to me, and does not give the same quick overview as the old one. 

I thought you were just adding a dashboard view and doing cosmetic changes, not throwing away the one thing that actually worked in the old dashboard (the pipeline view). This feels like a step backwards to me, and I hope you'll keep the old pipeline around for those of us who prefer it over the new one.

**Comment by phynias** [comment] 2018-01-12 19:49
noticing a weird thing with the dashboard page. the numbers under each projects are not of the last build. for instance i have a build that just finished successfully and yet it shows a check mark and "28d 23h". if i go into the project that time corresponds to the last time the job failed. unless i a misunderstanding what that number means. doesn't it make the most sense to show the last time it was built?

**Comment by bamdadd** [comment] 2018-01-18 11:40
I think it'd be very nice to see what `version` that has been ran on each stage of the pipeline.
For example if we have a dev,qa,prod pipeline, ideally it'd be nice to see something that represents:
`Dev (v100, Green), QA(v99, Green), Prod(v80, Green)` 
This can be optional to be enabled, but its very important to quickly notice what version of the app/service has broken at what stage without the need to look deeper.

**Comment by pn-santos** [comment] 2018-01-19 15:45
I think dashboard is definitely going in the right direction:

**Already Good**
- Seeing current status (running jobs and job status) of all pipelines and jobs in one view
- Filter search is great!
- Running animation is much better!

**Would be Good** (some of these might be simply because it's not done yet...)
- Can't logout/login as another team from the dashboard (the team name doesn't provide a drop down)
- Mousing over the title of a pipeline (that has an ellipsis) should show it's full name
- From a pipeline I see no way to navigate back to dashboard (other than using the back button)
- Some "standard" filters would be nice, like: only running pipelines, only pipelines with failed jobs, recently active pipelines (<30 min ago?)
- When you over over a job, besides the name it would also be nice to see last run time, the duration of the last run, and how long it has been running (if active)

**Not Good**
- Running jobs show up as failed when you view them (red bar)
- The font used is pretty bad... What was wrong with the previous font?
- The current pipeline layout is worse in my opinion (probably still WIP?), resources that trigger builds are indistinguishable from ones that don't, resource are not clickable, and it doesn't fit jobs to screen as well as the previous mechanism (lots of scrolling for pipelines with independent jobs, i.e. jobs that don't use inputs that passed previous jobs)

**Comment by flavorjones** [comment] 2018-02-05 13:43
I'd like to echo some comments buried in the mega-comments above: The font used in 3.8.0 is much harder for me, personally, to read; and I think that it makes it harder to see the pipeline name on the dashboard view from across the room.

**Comment by olle-brkt** [comment] 2018-02-16 21:46
I also like the old font much more than the new one!

**Comment by andrewedstrom** [comment] 2018-03-13 05:10
I would love to see some kind of visual indicator on the dashboard when a pipeline has resources that are in an error state. Errorring resources are orange in the pipeline view but In the dashboard there is no way to tell if a pipeline has failing resources. 

We just realized that one of our pipelines has resources that have been missing for a long time, but we didn't notice because it was showing up as all green in the dashboard.

**Comment by drahnr** [comment] 2018-05-23 08:20
Another nice thing - especially for group display selection - would be and option to toggle visibility of groups 
```
groups:
  name: grp1
  dashboard: yes // default to yes
```

**Comment by Rukenshia** [comment] 2018-06-07 18:09
Isn't the dashboard slowly getting into a state where it would warrant being linked from _somewhere_? I use it quite a lot now but I was unable to find any other way to get to it other than changing the URL in my browser 😄

In the latest concourse version (3.14.0) it looks like the footer is a bit too big though: 
![image](https://user-images.githubusercontent.com/1899599/41117931-b706a938-6a8e-11e8-8831-d7248fbd4737.png)

**Comment by jama-pivotal** [comment] 2018-06-11 21:36
The original intent was to have the base/root URl map to the dashboard, with the addition of the broken resource flag, now might be the time to make the switchover

**Comment by jama-pivotal** [comment] 2018-06-29 19:00
aaand update is that we ARE moving all of this into the root path as per #2282

**Comment by mpicard** [comment] 2018-07-02 19:44
Just wanted to say I tried concourse today and it was awesome! Love the color pallet and minimalist design! I didn't read the entire thread but it's too early for me to comment on the font.

The only feedback I have at the moment is the icons are inconsistent. I see a mixture of Font Awesome 4 and custom SVG icons. Personally, I'm also lazy and often use FA icons but I wouldn't mix the two. I'm not a big fan of the custom ones so maybe use FA for all of them? For example the top bar seems to have custom ones of varying shapes and sizes as well as alignment:

![screenshot_20180702_204124](https://user-images.githubusercontent.com/7460934/42183090-67cd686c-7e38-11e8-941b-670f7d5de600.png)

**Comment by surajpatel0928** [comment] 2018-07-20 02:45
If you have multiple concourse servers is there away to do a dashboard view? I have about 5 servers each with 3-4 pipelines, I would like to only have one view vs 5.

**Comment by mdelillo** [comment] 2018-07-23 15:53
We are seeing orange flags on green pipelines- see screenshot. Resources have at one point been orange but were fixed later on.

![screen shot 2018-07-23 at 11 50 11 am](https://user-images.githubusercontent.com/6590106/43087863-de9223b6-8e6e-11e8-8d02-2eb2075c3b76.png)

**Comment by jama-pivotal** [comment] 2018-08-03 18:34
Its live now in 4.0.0! Closing issue, please feel free to enter new issues as feedback as we keep iterating on our UI!

**Closed by jama-pivotal** 2018-08-03 18:34 UTC
Labels: feedback, web-ui
