### ISSUE TITLE
Concourse --help usage message should go to STDOUT not STDERR

### ISSUE THREAD

**Issue by pcman312** [concourse/concourse#670] opened 2016-09-26 23:44 UTC
When calling `concourse --help` or `concourse web --help` the usage message goes to STDERR, which means that piping it anywhere is more difficult since I have to use 2>&1.

**Comment by vito** [comment] 2016-10-08 17:22
dupe of https://github.com/concourse/fly/issues/89

**Closed by vito** 2016-10-08 17:22 UTC
Labels: unscheduled
