### ISSUE TITLE
Allow a message to be added when pausing a pipeline or resource

### ISSUE THREAD

**Issue by adamwg** [concourse/concourse#2302] opened 2018-06-19 15:58 UTC
# Feature Request

## What challenge are you facing?

When a job or resource in a pipeline is paused there is no way to tell who paused it, when, or why. Thus, it's hard to tell whether it's safe or desirable to unpause it. For example, one developer may pause a "deploy to production" job to allow for extra testing in a staging environment, but without knowing this another developer may unpause, triggering an unwanted production deploy.

## A Modest Proposal

Allow a message to be added when pausing a resource or pipeline. This would allow whomever is pausing to indicate to others why they're pausing it. The UI can then display the note, along with (potentially) who paused and when.

**Comment by marco-m** [comment] 2018-06-19 21:48
Duplicate of #1982.

**Comment by jama-pivotal** [comment] 2018-06-28 15:55
Thanks for the suggestion @adamwg . As @marco-m mentioned, this is a duplicate issue of #1982, and more productively #2025 which has some design proposals on implementing this! I'd encourage you to check out those issues and provide your feedback on those issues as well

That said, I'm going to close this issue in attempts to centralize conversations to the issues mentioned!

**Closed by jama-pivotal** 2018-06-28 15:55 UTC
