### ISSUE TITLE
Pipelines with non-Concourse keys newly rejected

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#1290] opened 2017-06-15 17:20 UTC
In Concourse 3.1.1, the following manifest was parsed and [rendered properly](https://java-experience.ci.springapps.io/teams/strepsirrhini-army/pipelines/chaos-lemur):

```
---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: nebhale/slack-notification-resource

resources:
- name: chaos-lemur
  type: git
  source:
    uri:    https://github.com/strepsirrhini-army/chaos-lemur.git
    branch: master

- name: slack
  type: slack-notification
  source:
    url: ((slack-strepsirrhini-army))

jobs:
- name: unit-test
  public: true
  plan:
  - get: chaos-lemur
    trigger: true
  - task: unit-test
    file: chaos-lemur/ci/unit-test.yml
    on_failure: *slack-failure

- name: deploy
  public: true
  serial: true
  plan:
  - get: chaos-lemur
    trigger: true
    passed:
    - unit-test
  - task: deploy
    file: chaos-lemur/ci/deploy.yml
    params:
      ARTIFACTORY_USERNAME: ((artifactory-username))
      ARTIFACTORY_PASSWORD: ((artifactory-password))
    on_failure: *slack-failure
    on_success: *slack-success

slack-failure: &slack-failure
  put: slack
  params:
    attachments:
    - color: danger
      fallback: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME <FAILURE>"
      text: "<!here> Build has failed"
      title: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME"
      title_link: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

slack-success: &slack-success
  put: slack
  params:
    attachments:
    - color: good
      fallback: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME <SUCCESS>"
      text: "Build has succeeded"
      title: "$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME #$BUILD_NAME"
      title_link: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
```

In 3.2.0 this no longer works, failing with the following error:

```
error: invalid configuration:
unknown/extra keys:
  - slack-failure
  - slack-success
```

It would appear the new implementation validates that there are no keys in pipeline definitions that aren't part of the official declaration.  However, given how YAML anchors work, I think that this should be relaxed and reverted to the pre 3.2.0 behavior.

**Comment by vito** [comment] 2017-06-15 18:58
Yep, looks like we unintentionally changed this. That validation was always the intended behavior but it looks like it got lost in a refactor to having `fly` submit an unmarshalled `atc.Config` rather than the raw payload. So the extra keys would just get dropped client-side and never hit the ATC's server-side validation.

I'll mark this as a bug since it regressed even though technically this was always the desired behavior on our end.

**Comment by vito** [comment] 2017-06-16 14:59
Fixed by permitting specifically *toplevel* extra keys, and keeping the validation for anything nested further down (e.g. under `jobs` and `resources`), as that's where 99% of the risk for typos actually is.

This'll be fixed in 3.2.1 which we hope to ship today.

**Comment by nebhale** [comment] 2017-06-16 15:40
Thanks for the quick turnaround.  Looking forward to it.

**Closed** 2017-06-16 21:21 UTC
Labels: type: bug, workflow: completed

**Comment by nebhale** [comment] 2017-06-16 22:19
3.2.1 looks good.

**Comment by vcardillo** [comment] 2018-03-12 21:33
I just ran into this on 3.6.1:
```
unknown/extra keys:
  - resource_types[1].check_every
```
