### ISSUE TITLE
Bug in baggageclaim ctl script

### ISSUE THREAD

**Issue by henryaj** [concourse/concourse#759] opened 2016-11-09 17:02 UTC
I'm seeing BOSH complain that it couldn't start `baggageclaim`, whose logs say:

```
expected argument for flag `--size-in-megabytes', but got option `-5333'
```

Sure enough, [this line](https://github.com/concourse/concourse/blob/72a866c8fb111437e6a1d7854a60dd0f0aeb5278/jobs/baggageclaim/templates/baggageclaim_ctl.erb#L36) looks to be the culprit: if your ephemeral disk is too small, it evaluates to a negative number which `baggageclaim` chokes on.

Happy to make a PR to address this -- what would an appropriate fix look like?

**Comment by vito** [comment] 2016-12-14 22:12
This is a dupe of https://github.com/concourse/concourse/issues/745 but yes a PR would be much appreciated! Perhaps it could just set it to the size of the disk if the disk is <=10G or whatever the offset is?

**Closed by vito** 2016-12-14 22:12 UTC
Labels: unscheduled
