### ISSUE TITLE
Workers randomly disappear

### ISSUE THREAD

**Issue by aquavitae** [concourse/concourse#562] opened 2016-08-01 08:16 UTC
We have 3 linux workers, and every so often (a couple of times a day) one of them will disappear from /api/v1/workers. When this happens any tasks that were running on them hang and I have to delete and recreate the pipeline to get them to start again.  If I ssh onto the machine I see that the service is still running, but nothing is logged indicating any sort of error.  At the moment the machines are rather under-resourced, so this could easily be related to insufficient memory or processor power. Even if this is the case, I would still expect it to fail gracefully and at least show something in the logs.

**Comment by vito** [comment] 2016-08-01 15:22
I would do some testing around the stability of your network. If a worker's disappearing it's because it's failing to heartbeat, which registers the worker with a TTL of 1 minutes, every 30 seconds, or every 1 second as long as heartbeating is failing.

**Comment by aquavitae** [comment] 2016-08-02 05:48
Ok, I'll look into that. Thanks for the suggestion.

Surely a disappearing worker shouldn't break the pipeline though?  At the moment, once a worker has gone down, even after I've brought it back up any pipelines it was doing seem to be permanently broken at the checking for new versions stage.  I've tried waiting well beyond the 5min container TTL.

**Comment by aquavitae** [comment] 2016-08-02 12:09
Continuously monitoring the logs on the server shows an error relating to too many open files on the worker.  Looks likes when that limit is hit the worker stops responding.

**Comment by vito** [comment] 2016-09-03 00:11
This should be fixed by https://github.com/concourse/concourse/issues/629 - aside from the fd leak issue, which was the root cause. Though that may also be fixed once heartbeating goes away. We'll also [add health checking to workers](https://www.pivotaltracker.com/story/show/129737457) which should increase visibility of this kind of thing - hopefully the health-checking would fail when a fd limit is reached and point you in the right direction for debugging.

**Closed by vito** 2016-09-03 00:11 UTC
Labels: unscheduled
