### ISSUE TITLE
High-density view shows all pipelines as red and running

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#5212] opened 2020-02-20 19:17 UTC
## Bug Report

High density view displays all non-paused pipelines as red and running even if no jobs are red or running.

## Steps to Reproduce

Go to https://hush-house.pivotal.io/ and switch to high density view.

## Expected Results

Pipelines with all green jobs are green on the high density view. Running state is only displayed if a pipeline has a job running.

## Actual Results

All non-paused pipelines are red and running.

## Version Info

* Concourse version: 6.0.0
* Deployment type (BOSH/Docker/binary): Helm
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome, Firefox
* Did this used to work? Yes

**Comment by pivotal-jamie-klassen** [comment] 2020-02-21 17:34
what version of concourse is running on hush-house?
```bash
$ kubectl describe pods -n hush-house | grep 'Image:'
    Image:         concourse/concourse-rc:6.0.0-rc.25
    Image:         concourse/concourse-rc:6.0.0-rc.25
```
when I run the sample docker-compose.yml from docs, replacing `image: concourse/concourse` with `image: concourse/concourse-rc:6.0.0.-rc.25`, I can't seem to reproduce the problem. Maybe there needs to be a certain number of pipelines? This is pretty weird...

**Comment by pivotal-jamie-klassen** [comment] 2020-02-21 17:48
I spoke briefly with @aoldershaw about this this morning and at first we thought this was the HD version of #5107 and would expect it to be resolved by #5118...

**Comment by aoldershaw** [comment] 2020-02-21 17:52
@pivotal-jamie-klassen @taylorsilva the issue happens because all jobs are considered for determining a pipeline's status, rather than just the jobs for the pipeline in question.

It was solved in this commit: https://github.com/concourse/concourse/pull/5118/commits/4758d2c69e4dab0d29a3275a47b2b9797f7645e9

**Comment by pivotal-jamie-klassen** [comment] 2020-02-21 17:54
Ah, so part of the repro conditions is to have at least one failing job in the entire cluster!

**Comment by pivotal-jamie-klassen** [comment] 2020-02-21 18:01
so on 6.0.0-rc.25 this dashboard:
<img width="598" alt="Screen Shot 2020-02-21 at 12 57 04 PM" src="https://user-images.githubusercontent.com/22056320/75058864-d223f700-54a9-11ea-8830-6cabed01505b.png">
shows up like this on HD, reproducing the bug:
<img width="216" alt="Screen Shot 2020-02-21 at 12 57 12 PM" src="https://user-images.githubusercontent.com/22056320/75058875-d9e39b80-54a9-11ea-94dd-e8a604215f18.png">

Switching to the latest RC, the HD view becomes:
<img width="215" alt="Screen Shot 2020-02-21 at 1 00 04 PM" src="https://user-images.githubusercontent.com/22056320/75059046-20d19100-54aa-11ea-842d-514735f628b3.png">

which confirms that the bug is already fixed on master!

**Closed by pivotal-jamie-klassen** 2020-02-21 18:01 UTC
Labels: bug
