### ISSUE TITLE
Custom web application root

### ISSUE THREAD

**Issue by venth** [concourse/concourse#1925] opened 2017-12-29 07:05 UTC
Hi there!

# Feature Request

Please consider to expose concourse ci web ui on a custom application root.

## What challenge are you facing?

Currently in the organization I work in the infrastructure applications are supposed to be exposed at a specific path via k8s ingress. We tried different approaches: using nginx ingress and traefik ingress. Unfortunately none of them allowed us to deal with relative links used in concourse ci ui webpage.

## A Modest Proposal

Perhaps, there could be additional parameter besides external-url, called application-root. The default value of application root would be: `/`

Other solution could be parsing external-url argument and treat the path after host and port as the application root.

**Comment by wanderanimrod** [comment] 2018-03-16 01:01
+1. Is there a way to work around this problem in the meantime?

**Comment by maxfrigge** [comment] 2018-05-01 20:01
I would also like to run concourse under e.g. `http://foo.com/concourse`. There is already a parameter `--external-url` which could be used in the web app to load it's resources. 

I can try to open a PR if someone could point me in the right direction.

**Comment by vito** [comment] 2019-03-12 18:33
Closing as a dupe of https://github.com/concourse/concourse/issues/942

**Closed by vito** 2019-03-12 18:33 UTC
Labels: enhancement
