### ISSUE TITLE
error message for out-of-disk when trying to copy an input?

### ISSUE THREAD

**Issue by larham** [concourse/concourse#513] opened 2016-07-06 16:56 UTC
In a Pivotal private pipeline (I'm happy to provide more info), we have a task which combines all *.tgz files (bosh releases) in a particular directory as an input. Below is a repeatable error message when trying to fly this task.

As a preliminary step (the one indicated with a panic), it gathers all the releases (*.tgz), and if there are too many of these (> 4ish), the concourse error at bottom is the result.

By trial and error, it seems that this error is some kind of disk space effect, because if we clean the release dir beforehand such that there is just one release, we get past this step, and vice-versa, if there are several releases that are all part of the input, we see this panic in a fairly repeatable way.

The issue is that for a newbie like me, the golang panic is unintelligible. Would it be possible to add error messaging to indicate that this error may be a disk space outage?

---------------------------------------------------
fly -t private execute -c task.yml -o bosh-init-deploy-output=/var/folders/rr/s1r8hxx51vg1jb27j2lsn01m0000gn/T/new-deployment-repo.48L38otV -i deployment-repo=<edit> -i sec-eng-ci-repo=<edit> -i create-release-output=<edit>

executing build 85564
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  850k    0  850k    0     0   997k      0 --:--:-- --:--:-- --:--:-- 1016k
100 61440    0 61440    0     0  66251      0 --:--:-- --:--:-- --:--:-- 66278
100  377M    0  377M    0     0  6580k      0 --:--:--  0:00:58 --:--:-- 8681kpanic: unexpected EOF

goroutine 16 [running]:
panic(0x4c9600, 0xc82000e160)
    /var/vcap/data/packages/golang/69f4e820bb43cb872465d0829e4dbadf45bce46d.1-66bfff1ec360c077e1442e2a798ae3d163357dbf/src/runtime/panic.go:464 +0x3e6
github.com/concourse/fly/commands/internal/executehelpers.Download(0xa55170, 0xc82011adc0, 0x7fff5fbff55e, 0x17, 0x7fff5fbff576, 0x4d, 0xc82030cab0, 0x24, 0xc820356280, 0x50, ...)
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/internal/executehelpers/downloads.go:34 +0x5fc
github.com/concourse/fly/commands.(*ExecuteCommand).Execute.func2(0xa55170, 0xc82011adc0, 0x7fff5fbff55e, 0x17, 0x7fff5fbff576, 0x4d, 0xc82030cab0, 0x24, 0xc820356280, 0x50, ...)
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:103 +0x48
created by github.com/concourse/fly/commands.(*ExecuteCommand).Execute
    /var/vcap/packages/fly/src/github.com/concourse/fly/commands/execute.go:107 +0xa26

**Comment by vito** [comment] 2016-07-15 21:46
looks like a dupe of https://github.com/concourse/concourse/issues/513

**Closed by vito** 2016-07-15 21:46 UTC
Labels: unscheduled
