### ISSUE TITLE
fly env replacement puts in quotations 

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#669] opened 2016-09-26 20:18 UTC
When using env variable in yml the replace mechanism adds the values with quotation marks.

For example:

    foo: {{bar}} 

when bar is value - will be processed as `foo: "value"`. This is ok when the env variable is used for complete value in the yml, but if it is used as part of the value - say

    foo: prefix_{{var}}

This will result in a badly as `prefix_"value"` instead what was probably expected `prefix_value`. 

Changing this will probably break a lot of existing setups, but having the option to workaround this will be nice. For example, if the value is already in quotation marks to be expanded without them - say:

    foo: "prefix_{{var}}"

or some other indication that plain value is expected - say: $ in front of the name:

    foo: prefix_{{$var}}

There are many options how this could be solved without backward incompatibility.

**Comment by vito** [comment] 2016-09-26 20:22
dupe of https://github.com/concourse/concourse/issues/360 which led to https://github.com/concourse/concourse/issues/545

**Closed by vito** 2016-09-26 20:22 UTC
