### ISSUE TITLE
testflight failing to create container with memory limit

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#6512] opened 2021-02-04 22:47 UTC
## Summary

The testflight [test](https://github.com/concourse/concourse/blob/368451a95f6d4dcc6e6903e5b83934c47914e898/testflight/container_limits_test.go#L13) for container limits is failing with `containerd` with the following error:

```
find or create container on worker a967c5450087: starting task: new task: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: open /sys/fs/cgroup/memory/garden/a6de8b89-bce8-4fba-58a7-4aff260615ec/memory.memsw.limit_in_bytes: no such file or directory: unknown
```

This error is from `runc` and started showing up after runc v1.0.0-rc-93 (https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc93) began being bundled in the `concourse/dev` image.

## Steps to reproduce

So far this wasn't reproducible using Docker compose.

## Additional context

Failed build - https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/580

## Triaging info

* Runc version: v1.0.0-rc-93 - [Release Notes](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc93)
* Concourse version: circa v7.0.0 - https://github.com/concourse/concourse/commit/368451a95f6d4dcc6e6903e5b83934c47914e898
* Did this used to work? - Yes

**Comment by muntac** [comment] 2021-02-24 18:54
The same test is now failing with the new version of `guardian` likely cause it got packaged with the same `runc` responsible for the issue i.e. `v1.0.0-rc-93`.
https://ci.concourse-ci.org/teams/main/pipelines/release-6.7.x/jobs/testflight/builds/92#L60348c89:770

**Comment by taylorsilva** [comment] 2021-03-04 21:10
We tried reproducing this issue using the `concourse/dev` image that the build failed with
```
concourse/dev@sha256:8fca5cca3995603b641191d15fd00c8cebd7a8f828497101830346f6e3facf22
```
But the tests actually passed when we used the latest code on `master`. We unpinned the guardian and runc release and are letting them run through the pipeline now.

**Comment by muntac** [comment] 2021-03-04 21:51
Testflight [passed](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/611) with both `runc` rc-93 and the version of `guardian` that contains it. Not sure why since there have been many changes since the failure. One guess is underlying GKE VMs may have been updated to use the newer `runc`. Anyway, closing this issue.

**Comment by aoldershaw** [comment] 2021-03-05 20:33
Re-opening as the test suites are failing on Ubuntu-based VMs (but passed on COS)

**Comment by taylorsilva** [comment] 2021-03-08 17:09
CI workers are based on ubuntu where memswap is disabled:
```
cat /boot/config-$(uname -r) | grep MEMCG
CONFIG_MEMCG=y
CONFIG_MEMCG_SWAP=y
# CONFIG_MEMCG_SWAP_ENABLED is not set
```

The tests pass when memswap cgroup is enabled on an OS. Our local docker OS has it enabled so the container limits tests apss.

Some tests to verify the issue is running runc-93 on an OS with the memswap cgroup disabled.

Concourse built with runc-92
Ubuntu OS with memswap cgroup disabled
Result: The test passed... by skipping the tests...

Checked in CI and found the latest testflight build using runc-92 also passed and skipped those tests!
https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/testflight/builds/614#L6045065b:60:78
<img width="742" alt="image" src="https://user-images.githubusercontent.com/4583837/110355239-01e76380-8007-11eb-8247-cb04539c893c.png">

So the real problem is that the error message we used to get changed.

**Closed** 2021-03-08 17:30 UTC
Labels: bug
