### ISSUE TITLE
Some running jobs the yellow lines are flickering painfully

### ISSUE THREAD

**Issue by ctaymor** [concourse/concourse#1677] opened 2017-09-29 17:53 UTC
# Bug Report

I'm seeing one (and only one) of our jobs which is running flicker really really fast. It's somewhat painful to look at, and I know since fast flickers can be dangerous or painful for folks with certain health conditions, could be a real problem. (see gifs below)

Other builds have the normal, slow yellow pulse. Also, teammates looking at our concourse are not seeing the fast flicker.

We're on concourse version 3.0.0. I'm seeing it in Google Chrome version 61.0.3163.91.

I've never seen this before (and we did not update our concourse recently). I'm sorry there aren't clearer reproduction steps, I'm not sure, at this point, how to reproduce it.

Perhaps relevant, refreshing the page does not fix this at all.

![fast_flicker_build_running](https://user-images.githubusercontent.com/4574361/31028826-4f2dc4fe-a504-11e7-8fc7-6bcdab92639d.gif)
![other_builds_are_normal](https://user-images.githubusercontent.com/4574361/31028827-4f2f97f2-a504-11e7-80c9-a48c655de141.gif)

**Comment by ctaymor** [comment] 2017-09-29 17:57
Looks like the gif didn't have enough fps to capture it. Here's a better gif. It doesn't totally capture the flicker, but it does at moments. 
![flicker_with_higher_fps](https://user-images.githubusercontent.com/4574361/31028996-e45da8aa-a504-11e7-9b46-d23d5aeebadf.gif)

**Comment by vito** [comment] 2017-09-29 20:09
Duplicate of #1008.

Side note: we're working on a new pipeline UI that'll "fix" this (by...being entirely different).

**Closed by vito** 2017-09-29 20:09 UTC
