### ISSUE TITLE
slow execution of resources on external workers - optional `inputs` field on resource get and put steps

### ISSUE THREAD

**Issue by ebeer** [concourse/concourse#2401] opened 2018-07-19 21:37 UTC
# Feature Request - optional `inputs` field on resource get and put steps

## What challenge are you facing?

Our concourse runs on GCP. At the end of every job we use a resource tagged with vsphere to release an environment. Currently this means that concourse transfers the contents of every task and resource container in the job from gcp to our vsphere worker just so that this resource can consume a json file. Due to the size of files we work with this can often take over twenty minutes.

Our modest suggestion is to add an optional `inputs` field to resource `get` and `put` steps so that we as pipeline authors can limit what gets transferred for cases like this. @danger-ranger 
* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): bosh
* Infrastructure/IaaS: GCP with Vsphere workers
* Browser (if applicable): chrome
* Did this used to work? not that we know

**Comment by jama-pivotal** [comment] 2018-07-30 00:51
@ebeer you might be interested in reviewing the upcoming changes to the `resources` API in the first RFC: https://github.com/concourse/rfcs/pull/1 or rendered: https://github.com/vito/rfcs/blob/resources-v2/01-resources-v2/proposal.md

**Comment by vito** [comment] 2018-12-05 16:38
Closing as a dupe of https://github.com/concourse/concourse/issues/1202, which hey, we've implemented. It'll be in the next release (5.0).

**Closed by vito** 2018-12-05 16:38 UTC
