### ISSUE TITLE
duplicate key value violates unique constraint "pipeline_build_events_22_build_id_event_id"

### ISSUE THREAD

**Issue by Eeems** [concourse/concourse#7683] opened 2021-10-15 17:29 UTC
## Summary

Since I've upgraded to 7.4.1 I've been having get tasks fail with the following error:
`save image get event: pq: duplicate key value violates unique constraint "pipeline_build_events_22_build_id_event_id"`

## Steps to reproduce

1. Configure pipeline with various concurrent jobs that contain a resource get and will automatically trigger at various times during the day.
2. Trigger various jobs at the same time.
3. Sometimes you will get a duplicate key error.

## Expected results

No duplicate key error.

## Actual results

Duplicate key errors will happen.

## Additional context

Likely this is due to changes in #7641 to move event id incrementing to happen in memory instead of using a Postgres Sequence.

## Triaging info

* Concourse version: 7.4.1
* Did this used to work: This did not happen on 7.4.0

**Comment by Eeems** [comment] 2021-10-16 18:11
For some context on how often it happens, in one of my pipelines it's happening almost every other time a job runs:
![image](https://user-images.githubusercontent.com/1176979/137597833-89cf36b6-1422-4e47-9fae-0b57c0e4310a.png)

This is requiring me to go in and re-run jobs constantly to ensure that the pipeline is actually running to completion.

**Comment by coffee-squirrel** [comment] 2021-10-19 15:42
We're also seeing this using [`concourse-bosh-deployment`@7.4.1](https://github.com/concourse/concourse-bosh-deployment/releases/tag/v7.4.1) (Bionic stemcell `1.10`)-- although the constraint name is `pipeline_build_events_58_build_id_event_id`.

Potentially related, checks are occasionally erroring out with `create resource config: pq: deadlock detected`.

**Comment by qzk** [comment] 2021-10-31 23:27
> We're also seeing this using [`concourse-bosh-deployment`@7.4.1](https://github.com/concourse/concourse-bosh-deployment/releases/tag/v7.4.1) (Bionic stemcell `1.10`)-- although the constraint name is `pipeline_build_events_58_build_id_event_id`, and it's been rare thus far.
> 
> Potentially related, checks are occasionally erroring out with `create resource config: pq: deadlock detected`.

Similarly, after upgrading to 7.4.1, we're experiencing a lot of checks (maybe 90% of them) erroring with: "create resource config: pq: deadlock detected" as well.

**Comment by qzk** [comment] 2021-11-01 05:47
I've upgraded to 7.4.2 from 7.4.1 and the deadlock errors still persist. 
<img width="1292" alt="errors" src="https://user-images.githubusercontent.com/11757158/139626929-a8b4bc3b-cbb9-45dc-bea1-fbd0a769138b.png">
 
<img width="326" alt="deadlock_error" src="https://user-images.githubusercontent.com/11757158/139627052-f3ebf2bc-78b0-4afd-aedf-55f7461a2c52.png">

I've downgraded to 7.2.0 (what we originally had) and the issues went away.

**Comment by Eeems** [comment] 2021-11-01 14:32
I've updated and I'll report back on if it solves the issue for me. I'm expecting that I will also encounter the deadlock issue that @qzk reported.

**Comment by muntac** [comment] 2021-11-01 14:35
Curious if this occurs when upgrading from 7.4.0 or any version that is **not** 7.4.1.

**Comment by qzk** [comment] 2021-11-01 14:45
> I've updated and I'll report back on if it solves the issue for me. I'm expecting that I will also encounter the deadlock issue that @qzk reported.

it looks to be tied to the number of check containers running. it works fine with only a few check builds running but after unpausing probably about 600 pipelines which caused about 4000 check builds to run, the deadlock issues start appearing

**Comment by Eeems** [comment] 2021-11-01 17:18
So far so good. I'll continue running my pipelines for the rest of the day to confirm.

**Comment by clarafu** [comment] 2021-11-01 17:59
I have a suspicion that it might have something to do with this https://github.com/concourse/concourse/blob/b8f9da5b8c00b6112a7a334b3dccdc49962859f9/atc/db/build.go#L1905 because just checking `0` will result in multiple goroutines still finding that the `eventID` is `0` and trying to refresh all together (even after we did `refreshEventId` in `Reload()`). We also don't update the `eventID` here https://github.com/concourse/concourse/blob/b8f9da5b8c00b6112a7a334b3dccdc49962859f9/atc/db/build.go#L1936 or fetch here https://github.com/concourse/concourse/blob/b8f9da5b8c00b6112a7a334b3dccdc49962859f9/atc/db/build.go#L1905 using the `sync/atomic` package 

I'm still trying to reproduce this issue but not having much luck yet :( It would be best if we are able to reproduce this locally so we can properly test against it.

Currently master branch is using https://github.com/concourse/concourse/blob/45621cb6dfd46ad9d75f822fb8b2d083913e7aaf/atc/util/seq_generator.go#L5-L7 to handle the concurrency. We could just switch back to that if we think it does have to do with the `atomic` package. Personally it is my first time using the package and Aidan and I were hoping we could use that instead of the `seq_generator` as a refactor, but maybe the risks are too high for us to use it.

**Comment by clarafu** [comment] 2021-11-02 14:54
@qzk Are you able to get any further information about the panic error you are seeing? In the ATC logs, are there are panic deadlock log error messages that can give us more information on where that is occurring? Thanks!

**Comment by qzk** [comment] 2021-11-02 15:03
i recall when i looked at the logs, i didn't see much information around the log messages besides just: ```{"timestamp":"2021-10-31T18:50:32.479979811Z","level":"info","source":"atc","message":"atc.tracker.notify.run.finish.errored","data":{"build":"check","build_id":1044610934,"error":"create resource config: pq: deadlock detected","pipeline":"edited-out","session":"25.12080.1854.4","team":"edited-out"}}```

**Comment by clarafu** [comment] 2021-11-02 15:20
Oh I think that deadlock is coming from something else. I think it is caused by the fact that we are locking `FOR SHARE` on the select query when we are grabbing out information on the resource config https://github.com/concourse/concourse/blob/4da448db5d95969babb857ffccdd8cd639722018/atc/db/resource_config.go#L208

**Comment by jamesmealing** [comment] 2021-11-03 10:04
We have also just upgraded to v7.4.2 and are seeing a relatively high number of `create resource config: pq: deadlock detected` errors.

**Comment by clarafu** [comment] 2021-11-03 13:58
@jamesmealing Would you be able to give me some information on your deployment/pipelines that you are seeing this error on? Do you know approximately how many pipelines/resources/resource-types you have in your deployment? Also, is the error coming from checks of most of your resources and resource types?

**Comment by jamesmealing** [comment] 2021-11-03 15:38
Yeah, of course. So we have 2 web nodes, 8 workers, and the database is in RDS. The whole environment is deployed in AWS via Terraform. We currently have 361 pipelines. Not sure about resources or resource types - If you can give me an easy way to check those, I'd be happy to. Definitely a variety of resources/resource types that we're seeing the error from, albeit intermittently and, as such, from a minority of all builds, however, this is still very problematic. As such, we will likely roll back to v7.4.0 this evening, so let me know if there are any metrics or logs or anything that you want me to collect before doing so. Thank you. 🙂

**Comment by dlbock** [comment] 2021-11-03 15:44
We are also seeing the same `create resource config: pq: deadlock detected` messages on resources and on tasks.

Our installation: 8 web nodes, 40 workers deployed in GKE via Terraform. The database is in CloudSQL (Postgres 11). We have maybe about ~100 pipelines. The other thing that we're noticing on 7.4.2 is an extreme slowdown of builds. Ones that used to take ~5 mins now take ~ > 30 mins. This change was noticed as soon as we updated from 7.4.0 to 7.4.2 2 days ago. Our container placement strategy is `limit-active-tasks` + `volume-locality`, with the max active tasks set at 10. We're also considering rolling back to 7.4.0 either today or sometime this week because most builds are basically unusable now due to the slow build time.

**Comment by qzk** [comment] 2021-11-03 16:44
for us the deadlock error looked to be coming only from check builds.

the logs are gone on our end (due to downgrading to 7.2.0) but i had a terminal window open where i tailed the log output for about an hour from 7.4.2 before shutting it down. 

greping by session didn't reveal much.

i've tailed the log output from 7.2.0 for about an hour as well, then compared the log message types to find message types that'd appear only in 7.4.2. but not 7.2.0

these are the results. the number is how many times the message type appeared in the 7.4.2 logs after about an hour. note some of the smaller # errors might be due to me shutting down the instances at the end when i began to proceed with the downgrade.
```
1390 atc.tracker.notify.run.errored
1165 atc.tracker.notify.run.finish.errored
 805 atc.tracker.notify.run.build-removed
 759 atc.tracker.notify.run.finish.failed-to-finish-build
 704 atc.tracker.notify.run.resource-rate-limit-exceeded
 238 atc.periodic-metrics.tick.streamed-resource-caches.emit.event
 238 atc.periodic-metrics.tick.get-step-cache-hits.emit.event
  24 atc.tracker.notify.run.get-step.lock-task.acquire.not-acquired-already-held-in-db
  13 atc.collector_checks.tick.check-collector.deleted-check-builds
  11 atc.worker-cache.refreshing
   5 atc.tracker.tick.run.finish.failed-to-finish-build
   5 atc.tracker.tick.run.finish.errored
   5 atc.tracker.tick.run.errored
   5 atc.tracker.tick.run.build-removed
   5 atc.tracker.notify.run.check-step.failed-to-create-container-in-db
```

here are example messages of each type from the 7.4.2 logs:
atc.tracker.notify.run.errored:
```
# the edited out pipelines are diff from each other; missing pipelines don't appear with the deadlock error
{"timestamp":"2021-10-31T19:25:18.642541729Z","level":"info","source":"atc","message":"atc.tracker.notify.run.errored","data":{"build":"check","build_id":1044610236,"error":"update resource config scope: get resource type: pipeline not found","pipeline":"edited-out","session":"25.6741.230","team":"edited-out"}}
...
{"timestamp":"2021-10-31T19:51:23.366935034Z","level":"info","source":"atc","message":"atc.tracker.notify.run.errored","data":{"build":"check","build_id":1044628145,"error":"create resource config: pq: deadlock detected","pipeline":"edited-out","session":"25.8416.2182","team":"edited-out"}}
```

atc.tracker.notify.run.finish.errored:
```
# the edited out pipelines are diff from each other; missing pipelines don't appear with the deadlock error
{"timestamp":"2021-10-31T19:30:46.253928207Z","level":"info","source":"atc","message":"atc.tracker.notify.run.finish.errored","data":{"build":"check","build_id":1044604233,"error":"update resource config scope: get resource type: pipeline not found","pipeline":"edited-out","session":"25.5635.905.2726","team":"edited-out"}}

{"timestamp":"2021-10-31T19:49:56.112805821Z","level":"info","source":"atc","message":"atc.tracker.notify.run.finish.errored","data":{"build":"check","build_id":1044628612,"error":"create resource config: pq: deadlock detected","pipeline":"edited-out","session":"25.8416.2764.4","team":"edited-out}}
```

atc.tracker.notify.run.build-removed:
```
{"timestamp":"2021-10-31T19:33:33.951169538Z","level":"info","source":"atc","message":"atc.tracker.notify.run.build-removed","data":{"build":"check","build_id":1044609998,"pipeline":"edited-out","session":"25.6741.711","team":"edited-out"}}
```

atc.tracker.notify.run.finish.failed-to-finish-build:
```
{"timestamp":"2021-10-31T19:33:33.326651790Z","level":"error","source":"atc","message":"atc.tracker.notify.run.finish.failed-to-finish-build","data":{"build":"check","build_id":1044612391,"error":"sql: no rows in result set","pipeline":"edited-out","session":"25.7040.1074.1665","team":"edited-out"}}
```

atc.tracker.notify.run.resource-rate-limit-exceeded:
```
{"timestamp":"2021-10-31T19:38:49.542648105Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.resource-rate-limit-exceeded","data":{"build":"check","build_id":1044625714,"pipeline":"edited-out","resource":"golden-pipeline","session":"25.8410.1891","team":"edited-out","waiting-for":"487.782144ms"}}
```

atc.periodic-metrics.tick.streamed-resource-caches.emit.event:
```
{"timestamp":"2021-10-31T19:30:52.769702541Z","level":"debug","source":"atc","message":"atc.periodic-metrics.tick.streamed-resource-caches.emit.event","data":{"name":"streamed resource caches","session":"39.815.10.1","value":0}}
```

atc.periodic-metrics.tick.get-step-cache-hits.emit.event:
```
{"timestamp":"2021-10-31T19:26:52.769276215Z","level":"debug","source":"atc","message":"atc.periodic-metrics.tick.get-step-cache-hits.emit.event","data":{"name":"get step cache hits","session":"39.791.9.1","value":0}}
```

atc.tracker.notify.run.get-step.lock-task.acquire.not-acquired-already-held-in-db:
```
{"timestamp":"2021-10-31T19:39:05.072632012Z","level":"debug","source":"atc","message":"atc.tracker.notify.run.get-step.lock-task.acquire.not-acquired-already-held-in-db","data":{"build":"check","build_id":1044626584,"id":[2,-547214718],"lock-name":"edited-out","pipeline":"edited-out","resource":"...-commits","session":"25.8413.3102.5.33.1","step-name":"git-resource","team":"edited-out"}}
```

atc.collector_checks.tick.check-collector.deleted-check-builds:
```
{"timestamp":"2021-10-31T19:53:10.927250521Z","level":"debug","source":"atc","message":"atc.collector_checks.tick.check-collector.deleted-check-builds","data":{"batch":0,"count":1353,"session":"30.826.2"}}
```

atc.worker-cache.refreshing:
```
{"timestamp":"2021-10-31T19:33:13.085930324Z","level":"debug","source":"atc","message":"atc.worker-cache.refreshing","data":{"session":"9"}}
```

atc.tracker.tick.run.finish.failed-to-finish-build:
```
{"timestamp":"2021-10-31T19:38:28.071037870Z","level":"error","source":"atc","message":"atc.tracker.tick.run.finish.failed-to-finish-build","data":{"build":"check","build_id":1044605991,"error":"sql: no rows in result set","pipeline":"edited-out","session":"25.6699.319.2881","team":"edited-out"}}
```

atc.tracker.tick.run.finish.errored:
```
{"timestamp":"2021-10-31T19:38:41.593939914Z","level":"info","source":"atc","message":"atc.tracker.tick.run.finish.errored","data":{"build":"check","build_id":1044606049,"error":"update resource config scope: get resource type: pipeline not found","pipeline":"edited-out","session":"25.6699.389.2977","team":"edited-out"}}
```

atc.tracker.tick.run.errored:
```
{"timestamp":"2021-10-31T19:38:41.590456967Z","level":"info","source":"atc","message":"atc.tracker.tick.run.errored","data":{"build":"check","build_id":1044606049,"error":"update resource config scope: get resource type: pipeline not found","pipeline":"edited-out","session":"25.6699.389","team":"edited-out"}}
```

atc.tracker.tick.run.build-removed:
```
{"timestamp":"2021-10-31T19:38:28.074858296Z","level":"info","source":"atc","message":"atc.tracker.tick.run.build-removed","data":{"build":"check","build_id":1044605991,"pipeline":"edited-out","session":"25.6699.319","team":"edited-out"}}
```


atc.tracker.notify.run.check-step.failed-to-create-container-in-db:
```
{"timestamp":"2021-10-31T19:30:45.848377308Z","level":"error","source":"atc","message":"atc.tracker.notify.run.check-step.failed-to-create-container-in-db","data":{"build":"check","build_id":1044608765,"error":"container owner db.buildStepContainerOwner disappeared","pipeline":"edited-out","session":"25.6708.1333.3","step-name":"...-build-status","team":"edited-out"}}
```

**Comment by dlbock** [comment] 2021-11-03 20:45
I just downgraded to v7.4.0 and already seeing a rapid improvement of build times

**Comment by dumptruckman** [comment] 2021-11-19 01:11
We were experiencing a `create resource config: pq: deadlock detected` error on the `put` step of an instanced pipeline any time the pipeline ran. This of course meant the pipeline would not complete. This happened on version 7.4.1. After reading the discussion here we downgraded to 7.4.0 and the problem went away.

**Comment by qzk** [comment] 2022-01-24 00:32
We just upgraded Concourse from 7.2.0 to 7.4.4 and the aforementioned issue seems to be gone.

**Comment by qzk** [comment] 2022-04-19 17:43
Months later, issue is still gone. I think it should be fine to close this ticket as resolved.

**Closed** 2022-04-19 17:45 UTC
Labels: bug
