### ISSUE TITLE
Dashboard team filter no longer auto-completes when logged out

### ISSUE THREAD

**Issue by mhuangpivotal** [concourse/concourse#3322] opened 2019-02-15 20:07 UTC
## Steps to Reproduce

On the dashboard page, focus on the search box. Select the team option in the dropdown.

## Expected Results

The dropdown should show a list of teams.

## Actual Results

There is no dropdown.

## Version Info

* Concourse version: v5.0.0 (prod)
* Browser (if applicable): Chrome
* Did this used to work? yes

**Comment by vito** [comment] 2019-02-15 20:38
Seems to be working for me:

![screenshot from 2019-02-15 15-38-02](https://user-images.githubusercontent.com/1880/52883073-b750d100-3137-11e9-89a0-9a261491be25.png)

**Comment by pivotal-jamie-klassen** [comment] 2019-02-15 20:51
@vito I can reproduce it while logged out

**Comment by vito** [comment] 2019-02-15 20:53
@pivotal-jamie-klassen ah, same - updating the title

**Comment by vito** [comment] 2019-02-23 22:22
closing in favor of #3353 which is already prioritized

**Closed by vito** 2019-02-23 22:22 UTC
Labels: bug, web-ui
