### ISSUE TITLE
[Docker][4.0.0] Can't login using a reverse-proxy

### ISSUE THREAD

**Issue by loganmzz** [concourse/concourse#2513] opened 2018-08-21 08:06 UTC
# Bug Report

* Concourse version: 4.0.0
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Laptop / Ubuntu 18.04.01 LTS / Docker Engine 18.03.1-ce
* Did this used to work? Yes, before 4.0.0

First, since starting to play with Concourse, I'm still wondering why EXTERNAL_URL is required as any HTTP request contains enough information ...

Using 4.0.0 release, I'm unable to login which results into different behaviour following the configurations as described below:

### EXTERNAL_URL: http://localhost:8080  exposed_port: 8080
All works fine

### EXTERNAL_URL: http://localhost:8080  exposed_port: Docker engine choice (e.g. 32785)
1. From Web UI, I can access the home page.
2. After clicking on login, I got redirected to an URL based on EXTERNAL_URL: http://localhost:8080/sky/issuer/auth?access_type=offline&client_id=skymarshal&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fsky%2Fcallback&response_type=code&scope=openid+profile+email+federated%3Aid+groups&state=eyJyZWRpcmVjdF91cmkiOiIvIiwiZW50cm9weSI6ImExZWU5NjU5Njc0NjhhYzUxNGQ1ZjIxYThjMmU0ZjI3MTk0ZjAxNDk2YjY4NzAzZjg1NjZkMDY4YWY1NWMxMTcifQ%3D%3D
3. Trying to hack URL by replacing port number results in HTTP code 400 (Unregistered redirect_uri ("http://localhost:32785/sky/callback").)

1. From CLI, I can log with password
2. But can't log with token / callback

### EXTERNAL_URL: http://concourse.dev.localhost  exposed_port: Docker engine choice (e.g. 32786)
1. From Web UI, I can access the home page.
2. After clicking on login, I access the login form.
3. After form submission, I got HTTP code 400 without futher details (no response body, no custom HTTP error message.). Digging logs I found the following lines:
```
{"timestamp":"1534836692.714751244","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector \"local\", name=\"\", email=\"admin\", groups=[]","session":"6"}}
{"timestamp":"1534836697.794028282","source":"atc","message":"atc.sky.callback.failed-to-fetch-dex-token","log_level":2,"data":{"error":"Post http://concourse.dev.localhost/sky/issuer/token: dial tcp: lookup concourse.dev.localhost on 8.8.4.4:53: no such host","session":"5.7"}}
```

1. From CLI, I can't log with password
```
logging in to team 'main'

error: oauth2: cannot fetch token: 400 Bad Request
Response:
```
2. Can't also log with token / 

### EXTERNAL_URL: http://concourse.dev.localhost  exposed_port: Docker engine choice (e.g. 32786)
1. From Web UI, I can access the home page.
2. After clicking on login, I access the login form.
3. After form submission, I got HTTP code 400 without futher details (no response body, no custom HTTP error message.). Digging logs I found the following lines:
```
{"timestamp":"1534836692.714751244","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector \"local\", name=\"\", email=\"admin\", groups=[]","session":"6"}}
{"timestamp":"1534836697.794028282","source":"atc","message":"atc.sky.callback.failed-to-fetch-dex-token","log_level":2,"data":{"error":"Post http://concourse.dev.localhost/sky/issuer/token: dial tcp: lookup concourse.dev.localhost on 8.8.4.4:53: no such host","session":"5.7"}}
```

1. From CLI, I can't log with password
```
logging in to team 'main'

error: oauth2: cannot fetch token: 400 Bad Request
Response:
```
2. Can't also log with token / callback

### EXTERNAL_URL: http://concourse.dev.localhost   bind_port: 80   exposed_port: Docker engine choice (e.g. 32788)   container hostname: concourse.dev.localhost
All works fine

## Expected result/behaviour
Concourse should work without providing an external URL. More an instance can be access in many ways (URLs) and Concourse should at least support a list.

The documentation must be improved on following points:
* External URL assumptions & requirements (as it's not specific to Docker deployment)
* Cloud deployment: CaaS (e.g. Docker), PaaS, IaaS

**Comment by vito** [comment] 2018-08-22 14:54
Yeah, we really shouldn't be relying on the external URL internally. We just recently got rid of that dependency from the workers.

I think the problem is just this one line:

https://github.com/concourse/atc/blob/8819682a06f74aa284de084b14955f42919a64cb/atccmd/command.go#L518

If we (or someone, hint hint) were to change that to the bind IP/port (except `127.0.0.1` if it binds to `0.0.0.0`), this should be fixed.

I'll prioritize this highly somewhere!

**Comment by vito** [comment] 2018-08-22 15:11
Woops, actually I'm gonna prioritize https://github.com/concourse/concourse/issues/2463 instead since it's the same thing but with a lot more user activity. Sorry for the noise!

**Closed by vito** 2018-08-22 15:11 UTC
Labels: bug
