### ISSUE TITLE
feature request: ability to automatically pause recurrent failing jobs

### ISSUE THREAD

**Issue by markstokan** [concourse/concourse#303] opened 2016-03-01 00:30 UTC
The Toolsmiths team ran into an issue today where Docker Hub began returning "500 Internal Server Errors" to requests for a docker image in a Task. We run some of our pipelines so often that we were creating containers faster than concourse could tear them down and eventually we hit our 250 container limit on two workers.

We understand that Concourse keeps "failed" containers around for post-mortem purposes but this ended up biting us. We talked about this with Evan and we determined that the most helpful feature in this scenario is automatically pausing the job after a certain number of consecutive failures.

Thanks.

Mark & Topher

**Comment by xoebus** [comment] 2016-03-03 01:13
Sorry but we probably won't be adding this feature because it has a limited use case but starts us down a path of adding lots of complexity compensate for edge cases.

I'm interested in fixing your problem though. If the containers were failing to create because the Docker registry was down then I'm surprised that you were running out of containers. Do you know the type of containers that were being created?

**Comment by markstokan** [comment] 2016-03-03 23:04
From my understanding these were Garden containers, not Docker containers download from Docker Hub.

ex. output of "fly containers" while we were experiencing the issue...
```
dl45o1cl4m8  d16c69f3-a0b7-46e8-a88f-5edadf8b3491  uptime_checker                 toolsmiths-environments-app     1815     631039    get    cron-trigger                  n/a
dl45o1cl4m9  d16c69f3-a0b7-46e8-a88f-5edadf8b3491  uptime_checker                 toolsmiths-environments-app     1815     631039    get    toolsmiths-ci                 n/a
dl45o1cl4mv  d16c69f3-a0b7-46e8-a88f-5edadf8b3491  uptime_checker                 toolsmiths-environments-app     1816     631065    get    cron-trigger                  n/a
dl45o1cl4n0  d16c69f3-a0b7-46e8-a88f-5edadf8b3491  uptime_checker                 toolsmiths-environments-app     1816     631065    get    toolsmiths-ci                 n/a
dl45o1cl4nq  d16c69f3-a0b7-46e8-a88f-5edadf8b3491  uptime_checker                 toolsmiths-environments-app     1817     631105    get    cron-trigger                  n/a
dl43it4qp5v  8dd05389-05ab-4abf-a0d3-0d78000dd9d2  uptime_checker                 toolsmiths-environments-app     1817     631105    get    toolsmiths-ci                 n/a

**Comment by markstokan** [comment] 2016-03-03 23:06
we addressed the situation by adding "serial: true" to our jobs to limit our concurrent builds, so our problem is "fixed" in that sense.

**Comment by vito** [comment] 2016-04-10 18:49
Closing this again; same reason as before. Sounds like whatever the root cause was has gone away as well.

**Closed by vito** 2016-04-10 18:49 UTC
Labels: in-flight

**Comment by fareedy** [comment] 2019-01-20 10:57
Please share more   like that. | <a   href="https://yourjobs.co.za/job-tag/available-jobs/">available   jobs</a>
-- | --
