### ISSUE TITLE
Worker fails very often 

### ISSUE THREAD

**Issue by ahelal** [concourse/concourse#452] opened 2016-05-28 12:46 UTC
Hi i am having issue with v1.3 I tried at least 4 rc currently with  v1.3.0-rc.75 workers fail very often average once  every 1 to 2 hours. Jobs that are currently running keep spinning and never fail till I abort them.

To debug the issue I have one of the workers connect to tsa using localhost, but still the same result. @vito said could be an ARP issue I regularly flushed arp every 30 min did not help. 

```json
{"timestamp":"1464198836.640052557","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"4.1.4"}}
{"timestamp":"1464198856.906386852","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"5.1.4"}}
{"timestamp":"1464244632.934403419","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"wait: remote command exited without exit status or exit signal","session":"3"}}
{"timestamp":"1464244703.374308348","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"2.1.4"}}
{"timestamp":"1464244703.401187897","source":"guardian","message":"guardian.iptables-runner.command.failed","log_level":2,"data":{"argv":["iptables","-w","-L","w--input"],"error":"exit status 1","exit-status":1,"session":"1.1","stderr":"iptables: No chain/target/match by that name.\n","stdout":"","took":"14.891813ms"}}
{"timestamp":"1464244703.546618700","source":"guardian","message":"guardian.destroy.state-failed-skipping-kill","log_level":1,"data":{"error":"runc state: runc start: exit status 1: open /run/runc/42be4a77-3b20-449b-4ad9-d4ca0737d92c/state.json: no such file or directory","handle":"42be4a77-3b20-449b-4ad9-d4ca0737d92c","session":"17"}}
{"timestamp":"1464244703.553925276","source":"guardian","message":"guardian.destroy.state-failed-skipping-kill","log_level":1,"data":{"error":"runc state: runc start: exit status 1: open /run/runc/5297886c-4099-4d10-5329-a6582288ff59/state.json: no such file or directory","handle":"5297886c-4099-4d10-5329-a6582288ff59","session":"18"}}
{"timestamp":"1464244703.560360432","source":"guardian","message":"guardian.destroy.state-failed-skipping-kill","log_level":1,"data":{"error":"runc state: runc start: exit status 1: open /run/runc/d13e6cf6-7836-4992-7910-4ab018a200eb/state.json: no such file or directory","handle":"d13e6cf6-7836-4992-7910-4ab018a200eb","session":"19"}}
{"timestamp":"1464258743.359131098","source":"guardian","message":"guardian.run.exec.execrunner.cleanup-process-json-failed","log_level":2,"data":{"error":"remove /opt/concourseci/worker/depot/caa2480d-30d3-4f52-7159-7ad838145b05/processes/498b947f-af81-4361-6e9d-4302f190606a.pid: no such file or directory","handle":"caa2480d-30d3-4f52-7159-7ad838145b05","id":"caa2480d-30d3-4f52-7159-7ad838145b05","path":"bash","pid":"498b947f-af81-4361-6e9d-4302f190606a","session":"2087.2.2"}}
{"timestamp":"1464269568.809067726","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"wait: remote command exited without exit status or exit signal","session":"3"}}
{"timestamp":"1464269569.036051512","source":"worker","message":"worker.beacon.keepalive.failed","log_level":2,"data":{"error":"EOF","session":"3.1"}}
{"timestamp":"1464269573.812045336","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to connect to TSA:%!(EXTRA *net.OpError=dial tcp 127.0.1.1:2222: getsockopt: connection refused)","session":"3"}}
{"timestamp":"1464269578.813131809","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to connect to TSA:%!(EXTRA *net.OpError=dial tcp 127.0.1.1:2222: getsockopt: connection refused)","session":"3"}}
{"timestamp":"1464269583.814375639","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to connect to TSA:%!(EXTRA *net.OpError=dial tcp 127.0.1.1:2222: getsockopt: connection refused)","session":"3"}}
{"timestamp":"1464269588.815528870","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to connect to TSA:%!(EXTRA *net.OpError=dial tcp 127.0.1.1:2222: getsockopt: connection refused)","session":"3"}}
{"timestamp":"1464269593.816601276","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to connect to TSA:%!(EXTRA *net.OpError=dial tcp 127.0.1.1:2222: getsockopt: connection refused)","session":"3"}}
{"timestamp":"1464287912.879069805","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"3.1.4"}}
{"timestamp":"1464331188.054756403","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"wait: remote command exited without exit status or exit signal","session":"3"}}
{"timestamp":"1464331241.237997532","source":"tsa","message":"tsa.connection.forward-worker.register.failed-to-fetch-containers","log_level":2,"data":{"error":"Get http://api/containers: EOF","session":"2.1.4"}}
```

**Comment by ahelal** [comment] 2016-06-01 18:06
I updated my config to use ```--peer-ip``` instead of defaulting through the tsa. It seems problem is not occurring for 4 hours. Will keep monitoring.

But could that have been the issue ?

**Comment by vito** [comment] 2016-09-03 00:13
I'm gonna close this for now since we're pretty unlikely to find the root cause at this point. It may have been a fd leak or something.

See https://github.com/concourse/concourse/issues/629 which should make this easier to debug in the future, at least.

**Closed by vito** 2016-09-03 00:13 UTC
Labels: unscheduled

**Comment by misham** [comment] 2016-12-20 22:44
Seeing this issue in 2.4.0 with web nodes running behind an ELB.  Specific error:

```
{"timestamp":"1482273780.214950085","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to construct client connection:%!(EXTRA *errors.errorString=ssh: handshake failed: EOF)","session":"3"}}
```

ELB allows HTTP and TCP over 2222 through.  Tested it with telnet over port 2222 and it's working.

I can't find a way to increase log level worker messages to get more details on SSH error.  Is there some undocumented flag?
