### ISSUE TITLE
Serial group with paused job blocks other jobs after upgrading to 2.1.0

### ISSUE THREAD

**Issue by alext** [concourse/concourse#643] opened 2016-09-13 12:41 UTC
We've hit a regression in the behaviour of serial groups with paused jobs when upgrading from 1.5.1 to 2.1.0.

With 1.5.1, if a job in a serial group is paused, and has a build pending, it won't prevent other jobs in the same serial group from running. With 2.1.0, it does prevent other jobs from running.

For example, given the following pipeline:

```yaml
---
resources:
  - name: ticker
    type: time
    source: {interval: 10s}

jobs:
  - name: alpha
    serial_groups: ['foo']
    serial: true
    plan:
      - get: ticker
        trigger: true

  - name: bravo
    serial_groups: ['foo']
    serial: true
    plan:
      - get: ticker
        trigger: true
        passed: ['alpha']

  - name: charlie
    serial_groups: ['foo']
    serial: true
    plan:
      - get: ticker
        trigger: true
        passed: ['bravo']
```

When running on concourse 2.1.0, if the `charlie` job is paused, and has a build pending for it, no more `alpha` builds will proceed. When running on concourse 1.5.1, `alpha` builds will proceed as normal in this situation.

**Comment by vito** [comment] 2016-10-08 17:07
dupe of https://github.com/concourse/concourse/issues/643 - thanks for the repro case though!

**Closed by vito** 2016-10-08 17:07 UTC
Labels: unscheduled

**Comment by alext** [comment] 2016-12-02 16:03
Ummm... This is #643...

I think I found the one you meant - #520.
