### ISSUE TITLE
www.concourse.ci should redirect to the homepage

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#627] opened 2016-09-01 23:48 UTC
I have no idea how many people are like me, but I will instinctively type `www` before a domain name if I know that it only has two parts.

What would it take to configure a CNAME for `www.concourse.ci` to `concourse.ci`?

**Comment by vito** [comment] 2016-10-08 16:58
dupe of https://github.com/concourse/concourse/issues/592

**Closed by vito** 2016-10-08 16:58 UTC
Labels: unscheduled
