### ISSUE TITLE
Don't log "ERROR:  update or delete on table "volumes" violates foreign key constraint" during happy path of GC

### ISSUE THREAD

**Issue by dgodd** [concourse/concourse#1215] opened 2017-05-26 16:28 UTC
# Bug Report

* Concourse version: 3.0.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP (postgresql is GCP postgresql BETA)

We are seeing a lot of log messages on postgresql similar to 

```
E  ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes" 
E  DETAIL:  Key (id, state)=(3716002, created) is still referenced from table "volumes". 
E  STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4)) 
E  ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes" 
E  DETAIL:  Key (id, state)=(3716099, created) is still referenced from table "volumes". 
E  STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4)) 
E  ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes" 
E  DETAIL:  Key (id, state)=(3716100, created) is still referenced from table "volumes". 
E  STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4)) 
E  ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes" 
E  DETAIL:  Key (id, state)=(3716114, created) is still referenced from table "volumes". 
E  STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4)) 
E  ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes" 
E  DETAIL:  Key (id, state)=(3716113, created) is still referenced from table "volumes". 
E  STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4)) 
E  ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes" 
E  DETAIL:  Key (id, state)=(3715531, created) is still referenced from table "volumes". 
E  STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4)) 
```

**Comment by clarafu** [comment] 2017-06-06 14:13
This is actually working as intended, though I guess having postgres log errors in the happy path is a bit noisy. We rely database integrity to prevent garbage collecting a volume that's still in use, by having the child volume reference a compound foreign key of `(parent_id, parent_state = 'created')` to prevent the parent's state from transitioning to `destroying`.

I'll bucket this under "operability" and reframe it as an enhancement as it'd be nice to not have Postgres logging so frantically during the "happy path".

**Comment by ascherbaum-pivotal** [comment] 2017-06-06 20:21
My standard approach to this kind of problems is using a stored procedure (probably written in pl/pgSQL) which accepts the ID which is to delete, and checks the referential integrity before deleting the row.

**Comment by mariash** [comment] 2017-06-13 00:36
@ascherbaum-pivotal is that not going to be racy? to run check before trying to delete?

**Comment by topherbullock** [comment] 2017-10-05 14:13
This may now be resolved by a couple things : 
- the addition of the `failed` state (), which volumes and containers can pass into  when their creation on the worker has failed and they're only representation is a database row.
- Creating containers no longer getting GC'd. There shouldn't be any more cases where a volume is initializing for a Container, and it gets thrown in the trash while the volumes for it are initializing.

Going to look into this more in-depth and check that this is resolved.

**Comment by JohannesRudolph** [comment] 2018-04-09 07:51
I can verify this still happens on 3.10

**Comment by Nopik** [comment] 2018-06-24 20:40
I'm getting this too, on 3.14.1. I can help to diagnose/troubleshoot this, if needed. It is happening few times per minute now on my cluster.

**Comment by keithkroeger** [comment] 2018-10-17 10:50
Any word on how this is going?

**Comment by xulsitatirev** [comment] 2018-12-12 11:23
We have just faced this problem on 4.2.1.

**Comment by billimek** [comment] 2018-12-17 15:53
Seeing the same here running concourse v4.2.1 w/PostgresDB v10.5.  Our DBAs are getting angry as we start to run concourse at scale with persistent PostgresDBs and their logs are getting flooded with errors.  Previously we've been running our concourse instances with an ephemeral postgresDB (via docker-compose) but are transitioning to permanent persistent postgresDBs

From our DBA:

```
I am still noticing this issue in the PostgreSQL QA logs.  Here are number of errors in for this issue as noted in the logs:
 
2018-12-08                          2882
2018-12-09                          2880
2018-12-10                          3069
2018-12-11                          1852
2018-12-12                          3461
2018-12-13                          9268
2018-12-14                          18999
2018-12-15                          20160
2018-12-16                          20160
```

This is with just about 6-8 concourse installations, and we could theoretically scale up to around 600 which will be a very big problem.

**Comment by crstamps2** [comment] 2018-12-17 21:19
I am on one of the teams @billimek talks about that switched to using a more persistent DB instead of the ephemeral one. Correlation might not necessarily be causation here, but ever sense I switched over our DB to the more persistent one, I constantly have a lack of workers, even after checking with such a log as seen below. 

```bash
❯ fly -t <target> cr -r pull-requests/pull-requests
error: check failed with exit status '70':
no workers
```

My pipelines all freeze up at random times, the worker stalls, I clear it with the `prune-worker` command but no luck.

I didn't have this problem until I switched DBs. I am not 100% sure if its related to this issue.

**Comment by topherbullock** [comment] 2019-01-21 21:50
Added this to be triaged in the Runtime backlog. We see this a lot in our logs for our GCP Cloud SQL database for Wings. 

We could make this a procedure run in a transaction which checks for the constraint violation ala @ascherbaum-pivotal 's suggestion.

Another consideration is to try and avoid trying to delete these volumes GC shouldn't consider for deletion in the first place, and it would be a good time to address this related noisy volume GC issue #1780

**Comment by xulsitatirev** [comment] 2019-03-04 10:20
Unfortunately, we have faced this problem with `concourse-3.8.0`.
```
ERROR:  insert or update on table "volumes" violates foreign key constraint "fkey_container_id"
DETAIL:  Key (container_id)=(152252) is not present in table "containers".
STATEMENT:  INSERT INTO volumes (worker_name,parent_id,parent_state,handle,container_id,path,team_id) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id
ERROR:  update or delete on table "resource_configs" violates foreign key constraint "resource_config_check_sessions_resource_config_id_fkey" on table "resource_config_check_sessions"
DETAIL:  Key (id)=(19186) is still referenced from table "resource_config_check_sessions".
STATEMENT:  DELETE FROM resource_configs WHERE id NOT IN (SELECT resource_config_id FROM resource_config_check_sessions UNION SELECT resource_config_id FROM resource_caches)
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(276080, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(276080, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(276313, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(276313, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(276756, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(276756, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))
```

**Comment by prein** [comment] 2019-05-31 14:05
I'm experiencing the same issue on Concourse 5.2.0 installed to Kubernetes with Helm.
Postgres logs full of
```
ERROR:  update or delete on table "volumes" violates foreign key constraint "volumes_parent_id_fkey" on table "volumes"
DETAIL:  Key (id, state)=(101038, created) is still referenced from table "volumes".
STATEMENT:  UPDATE volumes SET state = $1 WHERE (id = $2 AND (state = $3 OR state = $4))

```
Jobs error out with either 
`dial tcp: lookup concourse-05212019-postgresql on 10.96.0.42:53: read udp 10.38.0.4:42714->10.96.0.42:53: i/o timeout`
or
`failed to create volume`

Did anyone come up with a workaround or recovery protocol yet?

**Comment by nader-ziada** [comment] 2019-06-19 00:52
To avoid this error message, we would have to add an additional query on the `volumes` table to filter out these records, this is a concern since this table usually has a huge number of records. 
Still investigating what the most efficient option would be.

**Comment by ddadlani** [comment] 2019-07-15 18:33
It seems that fixing this would require a new database query which is pretty heavy. Moving this back into the backlog so we can revisit it later.

**Comment by skreddy6673** [comment] 2020-06-19 17:26
Seeing this on v5.7.1 Helm Deployment on K8s.

**Closed** 2021-04-21 20:09 UTC
Labels: troubleshooting
