### ISSUE TITLE
Add possibility to link to specific lines in output (web)

### ISSUE THREAD

**Issue by MatthiasWinzeler** [concourse/concourse#1423] opened 2017-07-31 09:01 UTC
Hi guys

We use concourse for all our CD pipelines. Therefore, whenever a deployment fails, we often find ourselves sending links to point co-workers to some build output, i.e:

> hey, do you know why this command fails in https://<concourse-url>/teams/main/pipelines/<pipeline>/jobs/<job>/builds/7?

We use bosh for deployments which creates a lot of build output (generated manifests etc.) which makes it easy to get lost in the longer outputs.

A nice addition to concourse would be to send links to specific lines in the build output, similar to how github allows this [(example)](https://github.com/concourse/concourse/blob/master/.anderson.yml#L4-L6).

Currently, there is no output line number that you reference to so this would need to be created first...

Idea: toggle line numbers if you click on the left side of the build output (I saw this in some text editors) and then automatically create the anchor in the url if you click on a line number.

What do you think?

**Comment by jtarchie** [comment] 2017-07-31 17:33
@MatthiasWinzeler, this maybe harder than it sounds. The log output stored is not static. It is actually the terminal playback, not just the final captured output. Think more [asciinema](https://asciinema.org/) not a text file. I think we'd have to think through this a bit more.

**Comment by vito** [comment] 2017-10-17 13:49
Duplicate of https://github.com/concourse/concourse/issues/361.

**Closed by vito** 2017-10-17 13:49 UTC
Labels: area: web-ui, type: enhancement
