### ISSUE TITLE
Why is the `concourse-release` not using the correct version of the branch?

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5757] opened 2020-06-11 21:57 UTC
I noticed when I created a release pipeline, the versions coming into the `concourse-release` resource was not the version that the release branch was for (ex. my release branch is v6.3.0 but the versions it was producing was v6.2.1)

![Screen Shot 2020-06-11 at 5 58 07 PM](https://user-images.githubusercontent.com/19290703/84443313-593ddc00-ac0d-11ea-8eff-017583f1cf5d.png)

**Comment by jamieklassen** [comment] 2020-06-15 13:25
It looks like when creating a dev release, BOSH strictly bumps the patch version when determining the version for dev releases:

https://github.com/cloudfoundry/bosh-cli/blob/9c1c210c83673a780e3787a91f444541755e6585/releasedir/fs_release_dir.go#L158

which ultimately increments the last segment:

https://github.com/cloudfoundry/bosh-cli/blob/9c1c210c83673a780e3787a91f444541755e6585/vendor/github.com/cppforlife/go-semi-semantic/version/version_segment.go#L69-L88

I can see from the bosh-cli code that the source of the 'latest' dev release version is determined from the filesystem somehow, and my guess is that it looks in the git history for a semver tag.

**Comment by YoussB** [comment] 2020-06-22 19:40
@clarafu, it seems that this is by design in the [resource type](https://github.com/dpb587/bosh-release-resource) that we are using for bosh releases.

- this only affects the version as seen when doing a `get` of the resource type, despite the fact that the resource would be fetching the correct binary.
- the way the resource type is designed is that it fetches the latest final release from the repo's `releases/concourse/index.yml` and then [increments the patch](https://github.com/dpb587/bosh-release-resource/blob/master/boshrelease/release.go#L83).

### Possible solutions:
- Create an issue against the [resource type](https://github.com/dpb587/bosh-release-resource) to be able to choose the proper version bumping when creating an instance of the resource.
- finalize the release early on, although I don't think this is viable as this is the first step of releasing.

**Comment by YoussB** [comment] 2020-06-30 19:15
@clarafu and I took another stab at this and thought that the best way would be if the resource doesn't show the incremented patch version, thus the version won't mislead us while the resource is actually working fine.

we created [this issue](https://github.com/dpb587/bosh-release-resource/issues/10) on the resource type.

will close this for now and wait until the other one is resolved.

**Closed by YoussB** 2020-06-30 19:15 UTC
