### ISSUE TITLE
set_pipeline step does not unarchive pipelines where there is no diff

### ISSUE THREAD

**Issue by PFacheris** [concourse/concourse#6843] opened 2021-04-08 19:18 UTC
## Summary

My team makes use of the set_pipeline step within a "manager" pipeline to set release and PR pipelines based on the result of a templating process. There was recently a case where the release pipeline was accidentally archived and we expected the job that sets it to unarchive it.

The result looked fine:
![image](https://user-images.githubusercontent.com/1783057/114083043-859da580-987c-11eb-9195-1572501d593e.png)

But the target pipeline was still archived, we expected it to not be archived as this would be consistent with the fly behavior.

## Steps to reproduce

Create the following pipeline and manually trigger it to set the booklit pipeline:
manager.yaml
```
resources:
- name: booklit
  type: git
  source: {uri: https://github.com/vito/booklit}
jobs:
- name: reconfigure
  plan:
  - get: booklit
  - set_pipeline: booklit
    file: booklit/ci/pipeline.yml
```

Run:
```
fly archive-pipeline -p booklit
```

Manually trigger the manager pipeline.

## Expected results
I would expect the booklit pipeline to no longer be archived to be consistent with fly.

## Actual results
The booklit pipeline is still archived.

## Triaging info

* Concourse version: 6.7.4
* Browser (if applicable):
* Did this used to work? Not sure, first time trying it.

**Comment by clarafu** [comment] 2021-04-20 19:50
@PFacheris Hm I tried to reproduce this bug but I was unable to with the latest version of concourse (v7.2.0). I'm also not exactly sure where the bug could be either because whenever you archive a pipeline, it should clear out the `config` of your jobs, resources and resource types that were set from that pipeline. In the screenshot it shows that a diff was not found, meaning that the config in the database is the same as the config that we are trying to set. If the pipeline was really archived, it should have seen that the config in the database was empty and show that there is a diff with the pipeline we are trying to set. Would you be able to confirm if the config of the jobs that belong to that archived pipeline are empty in the database? Also, that you are trying to set the correct pipeline within the `set-pipeline` step?

**Comment by taylorsilva** [comment] 2021-06-29 15:42
Closing because there's no reproducible. Please open it again or reply if reproducible steps are provided.

**Closed by taylorsilva** 2021-06-29 15:42 UTC
Labels: bug
