### ISSUE TITLE
Several APIs methods respond with content-type text/plain

### ISSUE THREAD

**Issue by yevster** [concourse/concourse#1692] opened 2017-10-03 16:38 UTC
The GET of the following API methods responds with JSON, but has `Content-Type` header set to `text/plain; charset=utf-8` regardless of the `Accepts` header of the request

`/api/v1/teams/main/pipelines/:pipeline_name/jobs`
`/api/v1/teams/main/pipelines/:pipeline_name/jobs/:job_name/builds`

A PR is forthcoming.

**Comment by vito** [comment] 2017-10-03 17:16
Dupe of #1111 but PRs welcome!

(also note #1122 which we've yet to fill out)

**Closed by vito** 2017-10-03 17:16 UTC
