### ISSUE TITLE
Set up buildroot permissions for non-root access

### ISSUE THREAD

**Issue by geofffranks** [concourse/concourse#493] opened 2016-06-23 20:45 UTC
In https://concourse.ci/running-tasks.html, it mentions that we can use the `USER` rule in our Dockerfile to control what user a task runs as. However, when doing so, that user doesn't have access to write into the build directory.

For my immediate case, it means I cannot run `godep restore` on code that was placed in the build as an input. I also suspect it will mean that i cannot create/write to output directories from this task.

Can concourse be made to change permissions on the build directory to the user specified in the dockerfile?

**Comment by vito** [comment] 2016-10-07 18:12
dupe of https://github.com/concourse/concourse/issues/493

**Closed by vito** 2016-10-07 18:12 UTC
Labels: unscheduled

**Comment by danielkza** [comment] 2016-11-03 17:23
@vito Did you mean to point to another issue? Closing an issue as a duplicate of itself seems funky.

Also, is there any workaround as of now, other than using sudo to chown the build dir?

**Comment by vito** [comment] 2016-11-03 17:26
yep probably meant https://github.com/concourse/concourse/issues/403
