### ISSUE TITLE
Container jobs do not get distributed correctly

### ISSUE THREAD

**Issue by sharms** [concourse/concourse#1586] opened 2017-09-12 22:08 UTC
# Bug Report
![screen shot 2017-09-12 at 6 07 18 pm](https://user-images.githubusercontent.com/95657/30350571-3fbe620c-97e5-11e7-81fb-e7e15b3ca77f.png)
If any single node in the worker cluster reaches 250 jobs, there will be occasional errors with 'max containers reached'.  Running 3.4.1.

To test, we added an additional 2 worker nodes (for a total of 7), and it still occurs:

`fly workers`
```
name        containers  platform  tags  team  state    version
sanitized  103         linux     none  none  running  1.2
sanitized  123         linux     none  none  running  1.2
sanitized  98          linux     none  none  running  1.2
sanitized  104         linux     none  none  running  1.2
sanitized  115         linux     none  none  running  1.2
sanitized  133         linux     none  none  running  1.2
sanitized  250         linux     none  none  running  1.2
```

Interestingly, there appear to be many check jobs (truncated, output is thousands), which led to increasing workers to 7 (at 5 almost all 5 nodes hit 250 over time):
`fly containers`
```
handle                                worker                                pipeline               job                                 build #  build id  type   name                                      attempt
sanitized  sanitized  none                   none                                none     none      check  none                                      n/a
sanitized  sanitized  none                   none                                none     none      check  none                                      n/a
sanitized  sanitized  none                   none                                none     none      check  none                                      n/a
```

**Comment by vito** [comment] 2017-09-18 15:31
Duplicate of #675

**Closed by vito** 2017-09-18 15:31 UTC
