### ISSUE TITLE
Upgrade from 2.7.0 to 3.1.0 causes gradle to execute unit tests in random order on each run

### ISSUE THREAD

**Issue by ishustava** [concourse/concourse#1565] opened 2017-09-05 22:26 UTC
We use concourse to run unit tests that are written in Spring with JUnit. We use `gradle` to execute them from command line. 

### Prior to upgrade
All tests run in the same order for each run of the task.

### After upgrade
Test execution order changes every time the task runs

Our initial investigation has shown that switching `baggage_claim`'s driver to `btrfs` explicitly in our manifest results in tests running in the same order as before the upgrade. So, we think it may be related to the file system, but we are not sure how it affects `gradle` executor.

### Why we think it's a bug?
We like that we now get a free randomizer for our tests, but we don't understand what is causing this behavior. In addition, it results in the pipeline not having an isolated, deterministic, and controlled environment.Because this only exists in the concourse created container, even if we find test pollution, we can't reproduce it locally. This can have severe impact on our ability to deliver stories.

Deployment type: bosh deployed Concourse to GCP
Concourse versions: `2.7.0` to `3.1.0`

**Comment by jtarchie** [comment] 2017-09-06 03:19
`btrfs` probably returns files in a consistent order, where `overlay` doesn't.

You probably don't experience this docker because volume mounts are not using a file system like `overlay`. The best way to reproduce this is having your test runner always do a random seed for test runs. This work locally and on concourse.

I'm closing this as it isn't a bug.

**Closed by jtarchie** 2017-09-06 03:19 UTC

**Comment by vito** [comment] 2017-09-06 03:23
Possibly relevant?:

https://github.com/junit-team/junit4/wiki/test-execution-order
