### ISSUE TITLE
fly -t target builds --since not true

### ISSUE THREAD

**Issue by eltoru** [concourse/concourse#4909] opened 2019-12-17 08:49 UTC
## Bug Report
When running fly -t target builds and use the parameter since to get all builds started since a specifc time, it only works when the since parameter have builds started after the since time. If you set a time erlier than there is any new builds started, fly will give you all builds (later than since time )as response. 

This behavious does not work well. Sometimes you want to pull for new builds to be started by use of fly command. This response behaviour make it not possible. 

## Steps to Reproduce
fly -t thetarget builds --since="$(date +%F" "%T)" 

## Expected Results
fly -t thetarget builds --since="$(date +%F" "%T)"
should always only give you builds started since the time parameter.

## Actual Results
fly -t thetarget builds --since="a valid date newer than any started build"
gives you all builds when no matches in since are found.

## Version Info

* Concourse version: 5.4.1
* Deployment type (BOSH/Docker/binary): Docker composer
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work? Do not know

**Comment by pivotal-jamie-klassen** [comment] 2019-12-17 13:49
This is a duplicate of #4683, which was fixed by #4682 in [v5.7.0](https://github.com/concourse/concourse/releases/tag/v5.7.0#user-content-4683). Please upgrade!

**Closed by pivotal-jamie-klassen** 2019-12-17 13:49 UTC
Labels: bug
