### ISSUE TITLE
Containers leaky as a vegetable

### ISSUE THREAD

**Issue by tiredpixel** [concourse/concourse#1669] opened 2017-09-27 11:43 UTC
Containers are not cleaned up, leading to increasingly more containers running over time, leading to eventual subnet exhaustion (not directly experienced yet in this phase of testing, but it'll clearly happen).

Kubernetes `1.7.0`, Ubuntu `16.04.3 LTS`, non-default kernel `4.10.0-28-generic`.

This is basically a refiling of #1424, but against Concourse `3.5.0`. I'm raising a new ticket since related #1297 and #1413 have been closed and released, yet the problem persists.

```
{"timestamp":"1506512429.404951572","source":"guardian","message":"guardian.destroy.destroy.delete-failed","log_level":2,"data":{"error":"runc create: exit status 1: container init still running\n","handle":"dcea3bf8-93b5-4e42-5c9d-a69db690604e","session":"3613.1"}}
{"timestamp":"1506512429.405071259","source":"guardian","message":"guardian.api.garden-server.destroy.failed","log_level":2,"data":{"error":"runc create: exit status 1: container init still running\n","handle":"dcea3bf8-93b5-4e42-5c9d-a69db690604e","session":"3.1.4513"}}
```

**Comment by topherbullock** [comment] 2017-09-27 13:51
Uh oh, leeks!
![](http://i0.kym-cdn.com/photos/images/newsfeed/000/328/161/576.gif)

Those examples seem like containers which are still in the process of being created being GC'd or at least trying to be GC'd and failing. 3.5.0 fixed a leak related to multiple teams using the same resource config (#1579), but our metrics show that this particular issue is fixed.

I suspect this may be related to the original issue you filed about errors coming from the networking component of Garden (#1640), and we're currently looking into some possible issues around cleaning up container rows in the database which don't map to a successfully initialized container (#1576) so the leak may be related to this. The root cause of the 'failed' (there isn't a failed state, so they appear as 'creating' until they are garbage collected) containers however does seem to be how Garden runs on Kubernetes and your specific kernel version.

**Comment by tiredpixel** [comment] 2017-09-27 15:04
@topherbullock, :D
Thanks for your reply. You explanation makes some sense to me. All the clusters I maintain, both Docker Swarm and Kubernetes, are running as a single `main` team, so I doubt it's related to that. Whilst a failure to clean up rows in the database could well be an issue, I'm not sure it would lead to the issues I was seeing before (which appears to be the same as this scenario), where zombie processes are left on the workers. It's worth noting, however, that I've experienced this leaks on multiple kernel versions—always on Kubernetes clusters, though (my Docker Swarm clusters have other problems, filed separately, but the container garbage collection appears to work fine, on those). I've also experienced this on multiple versions of Kubernetes.

What is to be done? :) Can I be of assistance in providing some extra information? I've already previously debugged it down to runc level (documented in my original ticket). Is there something else I can do?

**Comment by gerhard** [comment] 2017-12-13 10:13
We've just hit this after upgrading from 3.6.0 to 3.8.0. We have 6 workers, all pipelines are stuck:

```sh
$ bosh -d concourse deployment
Using environment 'https://10.0.0.6:25555' as client 'admin'

Name       Release(s)             Stemcell(s)                                     Team(s)  Cloud Config
concourse  datadog-agent/5.8.5.5  bosh-google-kvm-ubuntu-trusty-go_agent/3363.15  -        latest
           garden-runc/1.9.0
           ulimit/0.1.0
           concourse/3.8.0
           postgres/23

$ bosh -d concourse is

Instance                                     Process State  AZ  IPs
db/d02f1a90-7a49-4cbf-8816-55d039b80d76      running        z2  10.0.32.6
web/1d13b97c-f964-4802-beac-ea6483c84385     running        z2  10.0.32.5
web/236cbaf7-3e80-4a1d-93c6-377411faff52     running        z2  10.0.32.4
worker/0a08291c-1f6b-4d14-974e-7ba446c8f24d  running        z2  10.0.32.8
worker/22385291-93e9-4630-8a6a-8265831486f2  running        z2  10.0.32.9
worker/3d3982b3-0adc-4d30-b16a-6c762975bd55  running        z2  10.0.32.11
worker/8a328a4a-7d24-412c-83f4-a026c35b2029  running        z2  10.0.32.10
worker/aae20483-ed0e-41fb-a8db-d9b108d8504b  running        z2  10.0.32.7
worker/ea8e2613-8584-416f-99d8-fe25761fc37e  running        z2  10.0.32.12

$ bosh -d concourse ssh worker -c "ps -efH | grep -c /proc/self/init"

worker/ea8e2613-8584-416f-99d8-fe25761fc37e: stdout | 2
worker/3d3982b3-0adc-4d30-b16a-6c762975bd55: stdout | 2
worker/22385291-93e9-4630-8a6a-8265831486f2: stdout | 2
worker/0a08291c-1f6b-4d14-974e-7ba446c8f24d: stdout | 2
worker/aae20483-ed0e-41fb-a8db-d9b108d8504b: stdout | 5
worker/8a328a4a-7d24-412c-83f4-a026c35b2029: stdout | 12

$ fly -t rmq ws

name                                  containers  platform  tags  team  state    version
0a08291c-c029-432d-83a4-5b28b615a984  250         linux     none  none  running  1.2
22385291-f793-405f-84db-46eb51782947  250         linux     none  none  running  1.2
3d3982b3-2f05-4b6c-802d-426c98b0bf9a  250         linux     none  none  running  1.2
8a328a4a-721e-4014-978d-3dfa83a18254  250         linux     none  none  running  1.2
aae20483-b731-4688-850b-677502f5575b  250         linux     none  none  running  1.2
ea8e2613-3f1c-4d5a-9732-d46077652a9a  250         linux     none  none  running  1.2
```

What can we do?

**Comment by michaelklishin** [comment] 2017-12-21 12:23
This happens to RabbitMQ Concourse deployment every 2-3 days, whenever there's a spike in build activity. What kind of information should we provide to help Concourse maintainers make progress on resolving this?

**Comment by topherbullock** [comment] 2018-07-26 14:13
This issue is old enough, and there's been enough changes to the core runtime's GC that I'm going to close it off. 
I suspect that a couple things will help with containers piling up:

#1959 - Workers now report the resource (container and volume) handles they have when heartbeating, and the ATC marks ones in use, and a sweep phase cleans up any garbage on the worker and in the DB
#1637 - The "Failed" state for Containers; containers which are never initialized on the worker host will be marked in the DB as failed, and we'll GC them from the DB on the next pass

**Closed by topherbullock** 2018-07-26 14:13 UTC
