### ISSUE TITLE
adding time resource trigger blocks dependent pipeline jobs until first version exists

### ISSUE THREAD

**Issue by jamespollard8** [concourse/concourse#4680] opened 2019-10-30 19:06 UTC
## What challenge are you facing?

When I add a time resource (eg Tuesday morning) to auto trigger my pipeline job each week, I am unable to run the pipeline jobs with that time resource as an input because the time resource has "no versions available". (It won't get a version until the time resource is first hit on Tuesday.)

I changed the settings of the time resource to include today to work-around the issue and get the first version populated BUT after changing the settings, it removed the previous versions of this resource so it didn't actually work-around the issue.

(I saw other users report this on the concourse discord. For example, user `snegi` on 1/28/19)

## What would make this better?

Somehow being able to manually populate the initial version of the time resource would be great.

Thanks!
James (from PWS Platform team)

**Comment by clarafu** [comment] 2019-10-30 19:25
Hi James!

It looks like this issue has been previously brought up within the time-resource repo [issue 11](https://github.com/concourse/time-resource/issues/11). This behaviour is entirely dependent on the way the time resource returns back versions from the check. I'm going to close this issue because it seems to be a duplicate of the one I linked, but any thoughts you have on it or even a PR would be welcome for the linked issue!

**Closed by clarafu** 2019-10-30 19:25 UTC
Labels: enhancement

**Comment by jamespollard8** [comment] 2019-10-30 20:41
thanks a bunch!
