### ISSUE TITLE
Concourse 4.2.1 dashboard not showing Pipeline Last Run time

### ISSUE THREAD

**Issue by dhruvdarji1** [concourse/concourse#3875] opened 2019-05-16 15:15 UTC
Can anyone please tell me why Concourse is not showing last run time of the Pipeline on overall Dashboard?

## Bug Report

> (summarize the issue)

Go to Concourse Dashboard and check the bottom part of pipeline which shows the no of days before when pipeline was last run. 

> (please include any pipelines/tasks using https://gist.github.com)

## Expected Results

it should show correct no of days based on when last time that pipeline was run

## Actual Results

it shows the no of days based on when pipeline was build instead [ possibly, not sure ] 

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): BosH
* Infrastructure/IaaS: 
* Browser (if applicable): Chrome
* Did this used to work?

[image](https://user-images.githubusercontent.com/42613405/57865561-bb06f900-77f5-11e9-8bd1-f968cfb08207.png)

**Comment by marco-m** [comment] 2019-05-17 20:38
Hello, closing as a duplicate of #2040.

**Closed by marco-m** 2019-05-17 20:38 UTC
Labels: bug
