### ISSUE TITLE
Intermittently failing to check resources, possibly due to slow nw

### ISSUE THREAD

**Issue by devdavidkarlsson** [concourse/concourse#925] opened 2017-02-15 14:57 UTC
# Bug Report

I get a lot of failures EOF packing, probably due to slow network towards my repo. After a while they usually turn green again. Could it be improved somehow?

<img width="856" alt="screen shot 2017-02-15 at 15 54 29" src="https://cloud.githubusercontent.com/assets/2795016/22979588/39277494-f397-11e6-93d7-d0414ed1fd78.png">

The following can also be handy:

* Concourse version: 2.5.1, 2.6.0, 2.7.0
* Deployment type (Docker): Docker on VirtualBox with NFS mounted OSX folders...

**Comment by devdavidkarlsson** [comment] 2017-03-10 08:49
[09:42:13]: Cloning remote git repo...
Cloning into '/var/folders/ld/9p4vdwbx4pz0swp598x9ywxr0000gn/T/d20170310-34194-gv2y5u'...
remote: Counting objects: 2132, done.
remote: Compressing objects: 100% (684/684), done.
Connection to bitbucket.org closed by remote host.5.00 KiB/s    
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
[09:44:04]: Exit status: 128

**Comment by joharohl** [comment] 2017-05-23 13:21
Just to chime in that I'm seeing the same problems. No issue until a few weeks ago and very intermittent. Also to bitbucket.org.

Running 2.7.3.

Any troubleshooting and/or feedback you need, just let me know.

**Comment by mariash** [comment] 2017-06-06 00:42
@devdavidkarlsson @joharohl how big is your repo? You can try changing git config. See `git_config` in https://github.com/concourse/git-resource#source-configuration. Seems like this error might be thrown if git memory is exceeded. Try changing `packedGitLimit` or `packedGitWindowSize` (https://git-scm.com/docs/git-config#git-config-corepackedGitLimit). See more here https://stackoverflow.com/a/29355320/91588.

**Comment by Rukenshia** [comment] 2017-06-14 16:46
Also a repo on bitbucket.org (though that probably doesn't really matter), I've tried using the suggested options (and the suggested values in there) you mentioned @mariash but that doesn't change anything for me.

**Comment by jtarchie** [comment] 2017-08-30 21:11
I don't think there is anything to fix here.

I'm hesitant to add a retry step because eventually the `check` reruns on its defined interval. These all seem to bitbucket related, has someone reached out to them about the network issues?

**Comment by eembsen** [comment] 2017-09-14 13:26
This morning I started to have problems with a bitbucket repo. All of a sudden I get the following errors in Concourse:

```
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/git-resource-repo-cache'...
fatal: did not receive expected object cc36132b7bfe380f911d4346a2a7e21a5a51b0f6
fatal: index-pack failed
```

Strange this is, I can git clone perfectly on the docker host where concourse is running. So it looks like there is a problem with the git resource.

Cheers,
Erwin

**Comment by jtarchie** [comment] 2017-09-14 13:29
@eembsen, that can be networking issues. The fact that the resource is cloning means that resource is working just fine. The object it is trying to get from repo is having issues. The `fatal` is a git error message.

**Comment by jtarchie** [comment] 2017-09-14 13:30
@eembsen, I am going to ask, again, on this issue. These all seem to bitbucket related, has someone reached out to them about the network issues?

**Comment by eembsen** [comment] 2017-09-14 13:35
Not that I know of. The strange this is that I can clone the repo without problems locally. Also, the pipeline uses two other repositories also on bitbucket and these are cloned just fine.

**Comment by jtarchie** [comment] 2017-09-14 13:50
When it comes to network issues, as mentioned above, doing it locally and on a different box can show different results. The fact that this issue has become solely related to bitbucket and not any other provider, strongly points to a bitbucket issue. All the error messages show that `git` is working _fine_ and reporting an error with the remote server. Please reach out to bitbucket support with the above error message.

**Comment by jtarchie** [comment] 2017-09-14 13:50
I'm going to close this issue. There doesn't appear to be anything wrong with the resource.

**Closed by jtarchie** 2017-09-14 13:50 UTC
Labels: area: resiliency, type: bug, workflow: go-around

**Comment by lindenquan** [comment] 2019-02-25 19:49
For my case, I set  trigger: false
Then the problem is solved

**Comment by lindenquan** [comment] 2019-03-15 15:33
It happens because git clone uses --single-branch parameter.
You can reproduce the error by adding --single-branch in your local environment.
And concourse want to keep that parameter for versioning and caching.
https://github.com/concourse/git-resource/issues/134
