### ISSUE TITLE
Take a look at `create-and-run-new-pipeline` in `monitoring-stats` to see if it's genuinely slower with v6.0

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#5547] opened 2020-05-05 16:48 UTC
The [`create-and-run-new-pipeline` ](https://ci.concourse-ci.org/teams/main/pipelines/monitoring-stats/jobs/create-and-run-new-pipeline/builds/12942) SLI being run against our large scale deployment `hush-house` have been consistently failing. Investigate what is causing the SLI to fail.

As general knowledge of the SLI, it involves a few different steps for it to pass successfully:
1. Set the pipeline
1. Check the resource and save the new version
1. Auto-trigger a new build using that version
1. Run the task successfully

All these steps should finish within 70 seconds because of a timeout configured for the monitoring job.

https://github.com/concourse/oxygen-mask/blob/3ba002998bd924c6fa1818b45429c53110b9f425/monitor.yml#L227-L229

**Comment by pivotal-jamie-klassen** [comment] 2020-05-06 16:55
While broadly considering how to investigate and generate statistical hypotheses around this problem, we ended up talking a lot about tracing. This issue has now been kinda hijacked by an effort to add tracing to the `lidar` package -- maybe it should be renamed appropriately -- and the WIP commit above is a really good start.

The key insight was to add a `span_context` field to the `plan` JSON on a `db.Check`. This allows us to propagate span context between the `Scanner` and the `Checker` using the `propagators` package in `opentelemetry-go`. I learned how to use an approach like this in my work on #5461. This time, instead of using the `ChildOf` relationship type between spans, we have learned to use the `FollowsFrom` relationship type.

Initially we thought there was some bug because we only saw a single span in jaeger. We couldn't see any clear signals that anything was wrong, though. Today we decided to try checking the logs from the jaeger collector, and saw that elasticsearch was reporting some 403s, and continuing the investigation we saw that elasticsearch itself was rejecting write operations because our Docker VM was almost out of disk.

What fun it is to shave a yak! But more seriously, it might be worth having concourse do some logging if the `SpanSyncer` underlying the tracing package starts failing.

After some judicious docker pruning, the results in jaeger are exactly what we hoped!

<img width="995" alt="Screen Shot 2020-05-06 at 12 36 15 PM" src="https://user-images.githubusercontent.com/22056320/81204223-f23a6100-8f96-11ea-826d-fa5be878bf3a.png">

Having observed this small win, we're now interesting in adding another link in the chain of spans, this time between the checker and the scheduler. We had good results with adding a field to the check plan; can we use a resource version as a similar means of propagating span context? The `metadata` field is already JSON in a similar spirit to the check's plan, but there is some delicate logic to be mindful of in cases when a checker run produces a resource version that already exists -- the current implementation does an upsert on the metadata, and we want to be careful not to destroy the span context in such scenarios. It's important that a resource version is associated to the span context that _first_ produced it.

**Comment by clarafu** [comment] 2020-05-07 18:52
Summary of investigation so far

We observed the failing monitoring `create-and-run-new-pipeline` job and we saw that most of the time, it was unable to check for a version. At times that it did find a version, the time it took to find that version was so long that it did not leave enough time for the build to finish before the timeout was reached.

We took a look into why exactly it is slow to check for a version and in order to do that, we must look into the multiple steps it takes to run a check. The steps needed for a version to be produced is:
1. The lidar `scanner` component must run and create a row in the checks table for that resource
1. The lidar `checker` component must run and run that check from the checks table
1. The check step will run on a worker
1. Save the version into the database

Both the `scanner` and `checker` runs on their own intervals, but because we set the pipeline initially, that will send a notification to the `scanner` to tell it to run right away. We observed the `resource_config_id` taking a long time to be set on the resource, which is the responsibility of the `scanner`. As a theory, there is the possibility of the `scanner` component receiving the notification from the setting the pipeline but is unable to run yet because it is waiting for existing scans to complete first. Only one run of the `scanner` can be running at a time, and we block on waiting for all scans to be finished before releasing the lock on the component.

This is all from pure theory and observation, in order to confirm that this is the issue we wanted to add tracing to certain parts of the ATC in order to have proof of where the slowness is coming from. Having a trace starting from the `scanner` starting, running a scan for the resource, the `checker` starting, running a check for the resource and then have the scheduler start and pick up that version for a build would be really useful in getting the exact time it takes to complete each of those tasks.

One thing to note is that after a deploy to `hush-house` with v6.1, the SLI started to pass a lot more frequently. Another interesting thing is that the DB CPU of `hush-house` has also lowered with the deploy. If the theory of the `scanner` being slow is correct, it could be something caused by the slowness of the database before the deploy (the DB CPU was almost maxed). Possibly causing slowness within queries like `TryCreateCheck` that is used by the `scanner`?

**Comment by pivotal-jamie-klassen** [comment] 2020-05-13 20:34
The full truth about this SLI may require #5602, which I intend to tackle before 6.2.0 drops.

**Comment by jchesterpivotal** [comment] 2020-05-15 16:43
A note here is that PostgreSQL [has support for USDT probes](https://www.postgresql.org/docs/current/dynamic-trace.html#DTRACE-PROBE-POINT-TABLE) (ie SystemTap, Dtrace or eBPF). I'm not sure how easily that can be abused to follow a span into the database to better understand the exact behaviour (eg tracing query start / end, transaction start / end etc).

That's the good news. The bad news is that it's not compiled into the server binaries by default. The other bad news is that there's no immediately obvious way to correlate spans with particular probes firing.

**Comment by jamieklassen** [comment] 2020-07-23 14:02
This SLI has been at 100% for a few days now, and typically the whole process is taking more like 30s rather than 70. I'm going to close this for now, assuming that upgrading to 6.4 should resolve an issues that may have arisen in 6.0.

**Closed by jamieklassen** 2020-07-23 14:02 UTC
