### ISSUE TITLE
Can't see what pipeline I'm currently looking at in the UI

### ISSUE THREAD

**Issue by ahume** [concourse/concourse#1207] opened 2017-05-24 13:07 UTC
# Feature Request

## What challenge are you facing?

Sometimes when looking at the UI, it's difficult to understand which pipeline you're looking at. This is particularly true if there are common job names across pipelines. E.g. we use concourse to schedule deployments across multiple environments. Each environment has its own pipeline, but when I'm looking at job `frontend`, the only way of telling if it's stage/prod is by looking at the URL.

## A Modest Proposal

A small title, possibly in the UI header, showing the name of the current pipeline.

**Comment by pn-santos** [comment] 2018-03-01 16:03
Just pointing out that his issue is duplicate of #295

**Comment by pn-santos** [comment] 2018-04-06 09:37
Would it be possible to also have the text in a color other than white? with white it seems too similar to a group name (even though it has the icon before it). I think another color (orange? light grey?) for both text and icon would help differentiate it more from group names (and the icon and text being the same color would establish an implicit association between them other than proximity).

**Comment by jama-pivotal** [comment] 2018-06-29 19:01
Closing because we finally implemented the breadcrumb!

**Closed by jama-pivotal** 2018-06-29 19:01 UTC
Labels: web-ui
