### ISSUE TITLE
Exclude Worker when it's reached Max Containers on DB Counts

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#3367] opened 2019-02-22 15:13 UTC
Currently we let Garden block us from over-creating containers. I spoke with julz on the Garden team and its a known issue that their "block" isn't something to be relied on. They also have no plans to address this issue.

We should look into excluding at capacity workers  by counting the amount of rows in the container table which will guarantee that we don't go over the limit. This will also allow us to mitigate issues like "insufficient subnets in the pool" error when garden makes containers above its limit.

**Comment by kcmannem** [comment] 2019-02-22 15:14
cc : @ddadlani @topherbullock 

I was thinking we just piggy back off of the `Satisfying()` flow to include the limit as well.

**Comment by ddadlani** [comment] 2019-02-22 15:40
@kcmannem is the container limit settable in garden (I believe it is)? In which case we either want one of the two:

1. add an ATC flag to allow users to specify a max containers limit for the workers (#2928)
2. have the workers report their garden max containers limit

I like option 2 because then you could have different max containers for each worker (useful in scenarios where teams add their own super beefy workers for specific use cases) but I don't know how widely used that would be. Would love to get some input from users as well to see if option 2 is worth the extra effort.

**Comment by vito** [comment] 2019-02-23 21:50
@ddadlani I like option 2 best - we've done that in the past for things like `http_proxy` and `https_proxy` - in general it's better to have config come from the workers since different teams might have different preferences for their workers.

Also, quick note: this feels like it might have the same scheduling challenge we discussed where multiple concurrent creates targeting the same worker could end up picking it anyway and sending it over the limit. I don't think that's a huge deal here though since, well, you probably shouldn't be operating that close to your limit in the first place, and the errors could happen eventually anyway. 🤷‍♂️

**Comment by jchesterpivotal** [comment] 2019-03-13 14:38
> We should look into excluding at capacity workers by counting the amount of rows in the container table which will guarantee that we don't go over the limit. 

By default, this is not reliable due to Multi-Version Concurrency Control. By design, PostgreSQL will not reveal changes  to a table made by session A to session B until a transaction has been committed by A. If many jobs launch at once from multiple ATCs you will underestimate actual usage.

There's also the problem that row counting performs badly for the same reason: PostgreSQL can't keep a single integer count of "the rows", because there is no single meaning for "the rows". There are only the rows that a particular session is able to refer to within the boundaries of a particular transaction.

You can [use locks](https://www.postgresql.org/docs/9.6/explicit-locking.html) or [raise the isolation level](https://www.postgresql.org/docs/9.6/transaction-iso.html), but both have performance implications and will need to be considered carefully.

**Comment by ddadlani** [comment] 2019-07-22 18:05
Closing this for now since we will be revisiting this as part of #3695

**Closed by ddadlani** 2019-07-22 18:05 UTC
Labels: wontfix
