### ISSUE TITLE
Fly should only permit uninterpolated source/params

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#1377] opened 2017-07-13 21:04 UTC
After the new vault and params were added to v3.3.0, fly will not error when there are uninterpolated variables in the pipeline config because the interpolation of secrets from a credential manager will only happen when it is needed (during the step or checks). In result, this allows pipeline configs like:

```
jobs:
- name: ((job-name))
  plan:
```
to not error and will set the job name to `((job-name))` if the variable was not given with `--load-from-vars` or `-v`. 

The proposed solution is to have fly only allow uninterpolated `source` or `params` in the pipeline config.

**Comment by bitprophet** [comment] 2017-08-10 21:46
FTR, I think #1426 is a(n arguably more fleshed out) duplicate of this report.

**Closed** 2019-08-15 21:12 UTC
Labels: bug, fly, wontfix
