### ISSUE TITLE
3.1.1 jobs fail with "file not found" after flushing workers

### ISSUE THREAD

**Issue by tredfield** [concourse/concourse#1251] opened 2017-06-05 19:02 UTC
# Bug Report

Running `3.1.1` we see jobs failing with "file not found" errors. We have flushed workers (destroy and recreate the pods in kubernetes) and the errors go away for about a day. They come back sporadically but eventually fail nearly every build. 

Below is an example log entry we see with the error:

`{"timestamp":"1496684115.561470270","source":"atc","message":"atc.syncer.build-develop-ucp-loyalty:radar.scanner-failed","log_level":2,"data":{"error":"file not found","member":"build-develop-ucp-loyalty:resource:pr-svc-transaction-history-service","session":"17.17"}}`

* Concourse version: 3.1.1
* Deployment type (BOSH/Docker/binary): Docker image running on CoreOS Kubernetes in AWS
* Infrastructure/IaaS: AWS 
* Browser (if applicable): Chrome
* Did this used to work? Yes. Previously on 3.0.1 no issue

**Comment by vito** [comment] 2017-06-14 18:54
I'm not confident we'll be able to reproduce this with the information provided. Next time it happens could you look for logs in the worker around the same time?

**Comment by hamid-elaosta** [comment] 2017-06-15 17:01
This seems like the same issue I'm having also and just reported in Slack. My single worker on the same machine breaks, stopping and re-upping so I get a new worker seems to fix my builds temporarily and I can prune the old one.

https://concourseci.slack.com/archives/C07RY25QF/p1497544260712894

**Comment by vmcpherson** [comment] 2017-06-16 09:41
I'm seeing it on Ubuntu 16.04, seems straight forward to reproduce. Setup a docker-compose.yml file as per the documentation (I need a CONCOURSE_GARDEN_DNS_SERVER env. variable), deploy a build which will work, bounce the containers (docker-compose stop, docker-compose-start). Same build fails with 'file not found' error. I see it in 3.2.0 also

**Comment by JGjorgji** [comment] 2017-06-16 12:51
We are having the same issue after reboot.

v3.1.1
Ubuntu 16.04, the official ec2 image

Unlike other commenters builds work completely fine all the time except after rebooting the machine. This is always reproducible.

Worker is on the same host as ATC.

The fix as above seems to be stopping and pruning the worker and then restarting, works fine after that.

Here is an example log message:
`Jun 16 06:00:34 ip-10-10-10-74 concourse[981]: {"timestamp":"1497592834.116587877","source":"atc","message":"atc.syncer.build-and-lint:radar.scan-resource.tick.failed-to-fetch-image","log_level":2,"data":{"error":"file not found","pipeline-scoped-name":"build-and-lint:resource:someresource","session":"17.1.451.5"}}`

**Comment by hamid-elaosta** [comment] 2017-06-16 21:49
I seem to be having two issues here; The first; After I down-up containers; worker IDs change and can no longer be found; that of course breaks jobs; I prune them and carry on with new ones.

The second, is that after some ? the workers stop functioning correctly and my builds go orange. A down-up (and prune) recovers them temporarily from this.

**Comment by bbokorney** [comment] 2017-06-19 19:43
I'm also seeing the `file not found` issue on any kind of step (resource `get`/`put`, task run, etc.). I've collected logs for a few of the workers where the issue was happening, I'll analyze them soon.

* Concourse version: 3.1.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: OpenStack
* Browser (if applicable): Chrome
* Did this used to work? Yes. Previously on 2.7.5, no issue

**Comment by vito** [comment] 2017-06-26 18:40
Has anyone pinned this down to a repeateable set of steps?

**Comment by biels** [comment] 2017-07-04 12:42
Faced the exact same issue, running this pipeline from the tutorial on the official vagrant box:
pipeline.yml
```
---
jobs:
- name: job-hello-world
  public: true
  plan:
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: echo
        args: [hello world]
```

1. Spin up the official vagrant vm
2. Set the mentioned pipeline 
3. Check that job-hello-world finishes successfully when triggered manually
4. Halt vagrant vm
5. Check that job-hello-world exits with error "file not found"

**Comment by doejon** [comment] 2017-07-08 22:45
Same here.
Binaries are installed directly on a ubuntu machine.
Last time 'file not found' occured, I upgraded from version 3.2.1 to 3.3.1, rebooted and everything worked fine.
Rebooting again and same error (file not found) occured.
I then tried to re-install 3.3.1, rebooted and 'file not found' still showed up.
After removing the pipeline and re-adding it, pipeline worked again.
Paused pipelines do not seem to be affected, they worked just fine when unpausing.

**Comment by hamid-elaosta** [comment] 2017-07-10 09:49
Is anyone else running their workers in Docker? The issue that caused this for me was the change in 3.X. If I use docker-compose down, docker-compose pull, docker-compose up for my upgrade; all my workers are "stalled" and have to be pruned in order to create new ones before this issue goes away. It's annoying because I have to manually prune workers every time I cycle them because of their IDs changing.

**Comment by coxcs1** [comment] 2017-07-25 18:25
+1

**Comment by coxcs1** [comment] 2017-07-25 18:25
after every reboot getting a file not found error for docker images..

**Comment by JohannesRudolph** [comment] 2017-07-27 13:12
I have produced a log from my worker at: https://gist.githubusercontent.com/JohannesRudolph/cac520fb4898d62cd21a679bc3837457/raw/c2d61a2687ad64bebb237600a2fbe43ae7fd4aef/log.txt

It has four instance of this error logged: 
`{"timestamp":"1501159130.332514763","source":"guardian","message":"guardian.unable-to-load-aufs","log_level":2,"data":{"error":"exec: \"modprobe\": executable file not found in $PATH"}}`

**Comment by topherbullock** [comment] 2017-08-09 14:10
I'm observing that this issue has become an aggregate of a number of issues, so I've made several issues to split this up and add some clarity:
- non-BOSH workflow for operating workers #1457
- Improve errors when workers are `landing` or `stalled` #1458

Closing this off to investigate worker workflows which wesult in worries.. wee!

**Closed by topherbullock** 2017-08-09 14:10 UTC
Labels: deployment: other, needs-investigation, type: bug

**Comment by akoranne** [comment] 2017-11-18 22:10
I am seeing this issue on Concourse 3.6.0, on Vagrant + virtualBox + Mac

**Comment by martinsbalodis** [comment] 2018-01-22 09:45
I see this error every time worker has been restarted. The worker is running in a docker container based on `concourse/concourse:3.8.0`. This also happened in previous versions. The only fix is to replace the worker container and prune the old one.

**Comment by chris-aeviator** [comment] 2018-02-12 13:51
help - I'm affected by the same problem (on docker)

My only workaround is to destroy the whole docker environment since trying to prune the worker leads to a `forbidden` error, even with a stalled worker

**Comment by denisdbell** [comment] 2018-03-15 15:54
@chris-aeviator I have the same issue and had to remove all containers and restart. Not sure what might be causing this problem

**Comment by VireshDoshi** [comment] 2018-06-08 18:21
I have experienced the same problem. My setup uses a dockerised concourse web and concourse workers. I haven't managed to to recreate the problem but the removal of containers and doing a restart did the trick.

**Comment by eedwards-sk** [comment] 2018-10-26 21:21
I just got this on 4.1.0

**Comment by ergo** [comment] 2019-01-18 12:37
I think this just hit me.

**Comment by vito** [comment] 2019-01-18 15:55
If you think you've run into this please open a new issue with steps to reproduce - this is a fairly generic error message that a lot of Google results may lead to and we haven't heard from the original author in over a year. I'm going to lock this thread.

**Comment by topherbullock** [comment] 2019-01-21 19:56
If folks are running into this on Docker deployments, they may want to look into configuring the workers as "ephemeral" https://github.com/concourse/concourse/blob/master/docker-compose.yml#L44 , so that Concourse won't consider the workers as the same host when they disappear and re-register under the same name.
