### ISSUE TITLE
Tabs not rendered correctly in web console

### ISSUE THREAD

**Issue by kurtmc** [concourse/concourse#6213] opened 2020-10-26 21:58 UTC
## Summary

Many of our pipelines are not rendering indentation correctly in the log output. I think it's due to the tab characters not being rendered correctly. I believe this started happening since v6.6.0

## Steps to reproduce

Setup a pipeline that prints out tab separated characters and see that the tabs are incorrectly rendered when the job has run.
```
---
jobs:
  - name: job
    public: true
    plan:
      - task: simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: ubuntu}
          run:
            path: bash
            args:
              - -c
              - |
                #!/bin/bash
                echo 1	1
                echo 2		2
                echo 3			3
                echo 4				4
                echo 5					5
```

## Expected results
```
1  1
2          2
3                  3
4                          4
5                                  5

```

## Actual results
```
1 1
2 2
3 3
4 4
5 5
```
![DeepinScreenshot_select-area_20201027105646](https://user-images.githubusercontent.com/2661907/97233058-2d7d6480-1843-11eb-9f88-9cafb77e5689.png)

## Triaging info

* Concourse version: 6.6.0
* Browser (if applicable): Firefox
* Did this used to work? Yes

**Comment by jamieklassen** [comment] 2020-10-28 12:37
This is a duplicate of #6149 which was fixed in #6157 and looks like it will be released in v6.8.0 - at our current cadence I'd guess that would drop towards the end of November. Depending on your deployment configuration you might be able to use one of our dev builds, or downgrade to 6.5.1, but I don't see a clean workaround with the code on 6.6.0. I guess, for the time being, those logs that have significant whitespace could be viewed at the console with `fly watch`.

**Closed by jamieklassen** 2020-10-28 12:37 UTC
Labels: bug
