### ISSUE TITLE
When radar checks for a resource using a custom type, it should ensure that custom type has versions

### ISSUE THREAD

**Issue by mariash** [concourse/concourse#1175] opened 2017-05-17 22:22 UTC
Resource type versions are checked every 30s. If resource type just created and build started before these 30s the build will fail to fetch resource, cause there is no version for custom resource type yet.

**Comment by clarafu** [comment] 2017-06-08 13:47
I think this might be a regression, and maybe a nasty one since the build errors as a result. I'm not sure if we want to *always* force-check or only the first time. It might be extra overhead to using custom resource types if we do it all the time.

**Comment by mariash** [comment] 2017-06-14 22:30
yeah, maybe when build is triggered we should run checks only for custom resource types that don't have version.

**Comment by topherbullock** [comment] 2017-09-28 18:21
This happens consistently when a pipeline is configured to use a new custom resource type and the resource using that type tries to check; it fails with the following error :
`"custom resource type '%s' version not found"`

**Comment by jama-pivotal** [comment] 2017-10-02 18:58
This issue is just to cover checking for versions of a custom type ( and the custom type it depends on ... and the one it depends on ... etc ) when running a check for a resource which uses a custom type when there are not yet any versions found for that custom type.

Adding later stories to surface custom resource type versions and provide better visibility, and a story about considering moving this to some kind of queue if it makes sense.

**Comment by topherbullock** [comment] 2017-10-18 14:52
Looks like this needs some tests, please.

**Comment by jmelchio** [comment] 2017-10-18 17:51
Okay, I'll take another look at this.

**Comment by jama-pivotal** [comment] 2017-10-30 18:50
Timebox : 2 days

Validate this new approach:
Current flow is to pass around a slice of current resource types with versions, we should replace this with something which can resolve versions for each resource type 
Here's how this could work:
- when checking for a resource, a resource asks for a resolved version of a resource_type
- a common component is used in any of the checking whether radar,  fly check-resource, or a triggered build is doing the  checking.

Some questions to consider in validating the approach:
- `image_resource`  which depends on a custom type
- can we refactor to a single resource checking interface?
- should this be expressed as a linked list of dependancies, or a recursive check for versions of resources

Outcomes:
- Propose a way to implement a fix for this
- Find some areas for refactoring / cleanup
- write a comment on this issue which outlines what the specific fix looks like, and remove "SPIKE"

**Comment by vito** [comment] 2017-10-31 21:06
Here was our thinking for the injectable resource type checking factory thing:

https://gist.github.com/vito/cecc7004c02d239e1c68dceacb815ade

We later decided against putting the `RefreshResourceTypes()` method on there, since it's so different and not really necessary for the root of the problem.

**Comment by topherbullock** [comment] 2017-10-31 21:07
### UPDATE: 
We found a couple places where we'll need to do recursive checking for versions of custom types to avoid this error occurring:
1. The known case of radar scanning for a resource using a custom resource type for the first time
1. When a build is manually triggered, and there is a resource using a custom resource type for the first time (https://github.com/concourse/atc/blob/master/scheduler/buildstarter.go#L98-L124)
1. When a task is using a custom resource type as its `image_resource`

In case `#1` radar will eventually check, so throwing the error there doesn't necessarily make sense, since it will resolve eventually.

In cases `#2` and `#3`, these are happening in a path where we definitely want to have a version resolved for the (chain of) custom resource types we need.  So we can probably have a general resource type checking interface which can be called out-of-band from radar (maybe radar depends on it), and deals with checking for all the resource types when we definitely need them resolved.

**Comment by topherbullock** [comment] 2017-11-01 15:01
Acceptance Criteria:
- Create a resource using a custom resource type, and a job which uses it
- Un-pause the pipeline using the `fly unpause-pipeline` command
- Trigger a check using the `fly check-resource` command
- There should not be an error about "no versions for custom resource" when checking

**Comment by topherbullock** [comment] 2017-11-09 14:56
For case **#3**, `image_resource_fetcher` will need to use radar's `resource_type_scanner` but that requires a `db.pipeline`, which is a lot of piping to add to something which shouldn't need it.

The fetching of an `image_resource` shouldn't need to care about a pipeline, and should be able to generally fetch for resources and types and not care about the overall pipeline in the database.

Let's tackle this case in a separate issue (#1803), and consider the refactoring suggestions in #1786

**Closed** 2018-06-12 19:18 UTC
Labels: bug
