### ISSUE TITLE
Concourse can't handle passed same as job name

### ISSUE THREAD

**Issue by timlharrison** [concourse/concourse#3575] opened 2019-03-22 20:32 UTC
## Bug Report

Concourse 5.0.0 can't handle a pipeline that contains a job where the "passed" is the same as the job's name.  It seems like it locks up the UI but has no effect on the API/fly CLI.  Additionally, the fly CLI doesn't flag this as a configuration issue.

## Steps to Reproduce

1. Create concourse environment
2. Create pipeline with at least 2 jobs
3. Set job #2 to have a "passed" parameter equal to the name of job #2
4. Push the job into concourse and try to access the main UI landing page https://<concourse_url> and log in

## Expected Results

I expected the fly cli to not allow me to upload the pipeline and if it did, I expect the UI to render the pipelines and execute them with an error.

## Actual Results

The fly CLI let me upload the misconfigured pipeline and then the main UI landing page crashes

## Version Info

* Concourse version: 5.0.0 (and 4.2.3)
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: Windows 10 Docker
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by marco-m** [comment] 2019-03-22 21:05
This is a dup of #2174, which contains references also to a self-loop like this one.

**Comment by vito** [comment] 2019-03-26 15:50
Closing as a dupe of #2174 which is fixed.

**Closed by vito** 2019-03-26 15:50 UTC
Labels: bug, triage
