### ISSUE TITLE
Add external_url to build metadata available to resources

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#257] opened 2016-01-16 20:05 UTC
Resources would often benefit from knowing what the `external_url` is. Two examples include notifications (e.g. slack resource) and auditing (e.g. other resources that want to track where requests came from)

**Comment by robdimsdale** [comment] 2016-01-16 20:27
from slack:

```

vito [12:24 PM] 
not really, just make sure you make `—external-url` a required flag and bosh property

[12:24] 
and update its description; right now i think it just says it’s needed for oauth
```

**Comment by robdimsdale** [comment] 2016-01-16 20:30
Also update the `external_url` for concourse-lite at https://github.com/concourse/concourse-lite/blob/master/templates/concourse_manifest.yml

**Comment by vito** [comment] 2016-01-17 21:06
looks like this is a dupe of https://github.com/concourse/concourse/issues/176 actually

**Closed by vito** 2016-01-17 21:06 UTC
Labels: unscheduled
