### ISSUE TITLE
Bug report: Worker gets stuck due to volumes

### ISSUE THREAD

**Issue by aarondl** [concourse/concourse#737] opened 2016-10-31 22:16 UTC
* Concourse version: 2.3.1
* Deployment type (BOSH/Docker/binary): Binary
* Filesystem Driver: Naive
* Browser (if applicable): N/A

We're seeing an issue where the worker hangs. This can seize up an arbitrary number of workers (we've got 3 and seen it kill as many as 2 when Concourse is busy). They disappear from the output of `fly workers` within seconds of this issue appearing.

We wrote this to help combat the issue, but it's only a workaround, and not a good one at that.
https://github.com/colstrom/concourse-technician

It stops the worker, cleans up any volumes the worker couldn't and then starts the worker again.
Revelant pieces being mostly here:
https://github.com/colstrom/concourse-technician/blob/develop/lib/concourse-technician/volume_reaper.rb

We've managed to get a Go stack trace of a seized up worker. There was also a bunch of tar processes invoked like so: `tar -c .` that didn't seem to be finishing or doing anything at all. Looked a little at debugging this but I thought it would be better if someone familiar with the concourse code looks at this. The system locked up about 5pm on the previous day from when this was captured. The goroutines that are stuck for 1145s are ones that are -very- interesting because they would have been waiting since around the time it locked up.

[concourse-dump.txt](https://github.com/concourse/concourse/files/562975/concourse-dump.txt)

**Comment by aarondl** [comment] 2016-11-01 18:46
I want to leave a note as to how urgent/important this issue is, as well as explain the net effect on the system.

When one of the workers hangs, builds will be queued against it and they will simply never complete (hangs indefinitely). This means that you don't really get notified of this issue at all, you have to notice that your builds have stopped. It seems to be able to die at any step (resource get/puts, build tasks, anything).

The frequency of this issue is about 3-4 times a day with our current usage. This makes it fairly urgent, since it regularily kills the middle/final steps of builds that take hours making all that time waiting wasted.

If there's any more information I can give when the worker is dead that would be more helpful than what I've already added let me know.

**Comment by aarondl** [comment] 2016-11-03 19:20
More info to dump:

2/3 workers had seized doing these things:

```
● concourse-worker.service - concourse-worker
   Loaded: loaded (/etc/systemd/system/concourse-worker.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2016-11-01 19:34:55 UTC; 1 day 23h ago
 Main PID: 19417 (concourse)
    Tasks: 362
   Memory: 9.8G
      CPU: 18h 39min 5.142s
   CGroup: /system.slice/concourse-worker.service
           ├─  912 tar xf -
           ├─ 8977 /concourse/2.4.0/linux/bin/runc events 8750e695-fdb0-49e5-4899-597d73e267d1
           ├─16653 /concourse/2.4.0/linux/bin/runc events a67491ea-081c-475a-4ff4-3c000962657a
           ├─17415 /concourse/2.4.0/linux/bin/runc events f989fba0-6049-4ad7-783a-dace3bcaa5b7
           ├─18278 tar -c .
           ├─19417 concourse worker --work-dir /concourse --tsa-host concourse.from-the.cloud --tsa-public-key /etc/concourse/keys/tsa.pub --tsa-worker-private-key /etc/concourse
           ├─30362 /concourse/2.4.0/linux/bin/runc events 465b0218-f725-4ce4-49ac-4982c99ec474
           ├─a67491ea-081c-475a-4ff4-3c000962657a
           │ └─16648 /proc/self/exe init
           └─8750e695-fdb0-49e5-4899-597d73e267d1
             └─8970 /proc/self/exe init
```

And I thought of some other information that might be quite useful. The pipelines that seem to cause this problem the most often use docker in docker. We use the script common.sh from the Docker Image resource: https://github.com/concourse/docker-image-resource/blob/master/assets/common.sh

The volumes that can't be reaped may be coming from this? Investigating a little more.

**Comment by chendrix** [comment] 2017-05-19 23:59
@vito is this another instance of the btrfs bug? #1045

**Comment by vito** [comment] 2017-05-20 12:14
Could be. A bit hard to tell since I don't think the usual btrfs issue is
recoverable, but maybe it's some variant.

**Comment by chendrix** [comment] 2017-07-05 20:54
As we've moved to `overlay` by default, I'm going to close this unless I see a pressing need to have it reopened or someone can find another current reproduction.

**Closed by chendrix** 2017-07-05 20:54 UTC
Labels: type: bug

**Comment by aarondl** [comment] 2017-07-05 21:27
Fair enough. I don't remember seeing this recently. We have other problems now as I alluded to in my e-mail.
