### ISSUE TITLE
Build output page takes significantly longer to respond in 2.1.0

### ISSUE THREAD

**Issue by oppegard** [concourse/concourse#644] opened 2016-09-13 16:58 UTC
We upgraded from Concourse 1.6.0 to 2.1.0, and the build output page (`/teams/main/pipelines/pipeline-name/jobs/job-name/builds/build-id`) take significantly longer to load. The page finishes loading in roughly the same time as before (based on the Chrome network tab), but then Chrome pegs the CPU at 100% and the page is basically unresponsive for 20 seconds.

Please let me know what further information may help in diagnosing the issue.

**Comment by jtarchie** [comment] 2016-09-13 18:22
We also experienced this issue with the upgrade.

Symptoms:

* expanding tasks taking much longer to load
* one job page crashes the browser tab (happy to share URL)

**Comment by jtarchie** [comment] 2016-09-13 20:45
An example of a running job, which failed.


![out](https://cloud.githubusercontent.com/assets/75184/18490787/bcb40008-79c0-11e6-8f83-03b2ab0e3a89.gif)

**Comment by ahelal** [comment] 2016-09-13 21:08
same issue

**Comment by vito** [comment] 2016-09-13 22:10
I think this may fix it:

https://github.com/concourse/atc/commit/8c778e50cacde9d42262113d06131dc3494c6e48

The silly little duration UI at the top of the page updates every second, and we were misusing `lazy`, so every second the entire build output segment would be recomputed. Or, at least, something is causing Chrome to repaint the entire build output whenever the top bit updates. We'll see if this change fixes it.

**Comment by vito** [comment] 2016-09-13 22:43
Hmm now I'm wondering if this is a Flexbox issue actually. Will investigate more once that change makes it through our pipeline.

**Comment by vito** [comment] 2016-09-13 23:18
Oi. Looks like it is a Flexbox performance issue. If I set `position: fixed` on the header or just the build durations bit the full-page repainting goes away. Hmmmmmmmmmmmm.

**Comment by jtarchie** [comment] 2016-09-13 23:45
@vito Is this chrome specific?

**Comment by vito** [comment] 2016-09-13 23:56
@jtarchie Haven't tried Safari (don't have a Mac on-hand), but Firefox seems to repaint only the duration area, as expected. So yeah it seems like a browser-specific issue.

**Comment by vito** [comment] 2016-09-13 23:59
Confirmed with emperical testing that Firefox is a *lot* faster at viewing completed builds with a live-updating duration (i.e. those started/finished within the past hour).

**Comment by vito** [comment] 2016-09-14 00:52
Pushed a workaround; we'll see how it goes: https://github.com/concourse/atc/commit/b8a06e5a8d16896db3eaf2065318465e671eed12

In the meantime y'all can try either Firefox or Safari. Both seem to paint correctly.

**Comment by vito** [comment] 2016-09-15 17:06
Found out more besides the repainting.

After taking a look at one of our builds even after the repainting fix, it was still quite sluggish, and more interestingly, seemed to behave weirdly. Tasks would pop back open with an active spinner even though the one below them had finished.

Looking in the inspector, I noticed *multiple open event streams*.

Here's what I think happened:

* Our `/events` endpoint sends all events (with SSE type `event`), and then a final terminal event, with type `end`, and closes the connection. The client is expected to see the `end` event and close the `EventSource`, otherwise the browser will continue to reconnect.
* As part of 2.0, we upgraded to Elm 0.17.
* Elm 0.17 involved an internal rearchitecture towards having a centralized event loop, iirc.
* These `EventSource` callbacks were now shoving things onto an independent event loop, whereas previously I presume they would happen roughly in sync with the JavaScript runtime.
* All received events, including the `end` event, were being handled slower than they were being received, leading to a significant delay of handling the `end` event.
* Because the `end` event being received no longer resulted in the `EventSource` being closed (due to this delay in processing events), the browser would reconnect. `EventSource`s are durable things in browsers; they'll continuously try to reconnect until they're told to close client-side. This is where things started to go wrong.
* Normally, when reconnecting, the browser says to reconnect from the `Last-Event-Id`. However, the last event received was `end`, which we don't give an ID, so it would reconnect from the very beginning, thereby snowballing.

Bleh!

The fix is simple: we just shouldn't close the connection on the `/events` endpoint, and let the client decide to close it (or not) once it reaches the `end` event. This has always been a kind of awkward dance anyway.

We should also add an ID to the `end` event, for consistency's sake.

**Comment by vito** [comment] 2016-09-15 21:04
More bleh: it looks like Chrome is generally just awful at rendering that page. Build output appearing will also cause a full page repaint (even outside the output area). Compared to Firefox which only painted the new line.

May have to redo that page using something other than Flexbox and see what we can do to make Chrome happy.

We'll ship 2.2 with the improvements we've made so far. Let us know if they seem to help and if it's still slower than before (I suspect it might be).

**Comment by jtarchie** [comment] 2016-09-15 22:33
Is there any way we can test these changes before then? Happy to point an ATC for testing.

**Comment by vito** [comment] 2016-09-16 01:33
We'll be shipping 2.2 with these changes early tomorrow probably, so you might as well wait. Otherwise you could grab a RC from our pipeline: https://ci.concourse.ci/teams/main/pipelines/main/resources/bosh-rc

**Comment by oppegard** [comment] 2016-09-20 20:17
We upgraded to 2.2.0 and not seeing much improvement 😞

**Comment by vito** [comment] 2016-09-20 20:27
@oppegard For running builds? We're working on improving that at the moment.

**Comment by oppegard** [comment] 2016-09-20 21:29
This is for finished builds (that were run on 2.2.0 in case that matters). The concourse "loading" spinner finishes and renders the gets/tasks/puts, but the page is unresponsive and at 100% CPU usage for 10-12 seconds after that.

**Comment by racktear** [comment] 2016-09-22 13:10
We have a public-facing instance of concourse. You may take a look at:
http://build.tarantool.org/teams/main/pipelines/tarantool-1.7/jobs/build/builds/72

This page opens in under 5 seconds in Safari, and in more than a minute in Chrome. Some people can't open it at all.

What I noticed is that 'events' file is 16 MB and it fails to load. See attached screenshot

<img width="1439" alt="build__72_-_concourse_and_build__72_-_concourse" src="https://cloud.githubusercontent.com/assets/6728841/18749316/648ba808-80e7-11e6-8686-ee69d30833bc.png">

**Closed** 2016-09-23 00:17 UTC
Labels: bug
