### ISSUE TITLE
How to add timestamp for each log line?

### ISSUE THREAD

**Issue by FastNinja** [concourse/concourse#838] opened 2016-12-26 05:44 UTC
Hi there!
Maybe I am blind but I couldn't find how I can enable timestamps for output logs.

## What challenge are you facing?

We need to know how long individual actions are taking while we are doing the build and running tests. Time stamps have been very helpful in the past (see the Jenkins log output below)

![image](https://cloud.githubusercontent.com/assets/13673826/21476251/9268026a-cb8a-11e6-96be-87edcde2e474.png)

## A Modest Proposal

Add ability to enable time stamps for logs

**Comment by keymon** [comment] 2017-01-27 14:36
+1 That would be a great feature to troubleshoot issues. 

You can use a wrapper for the time being: http://kvz.io/blog/2013/07/12/prefix-streaming-stdout-and-stderr-in-golang/

**Comment by petemounce** [comment] 2017-02-16 17:57
Personally, I wouldn't want the timestamp to be a part of the content of the log line, but rather associated with it within the UI. If it's something that CI adds to the build automation output, then if I need to parse, or copy/paste that, it becomes unwieldy fast. It would be great if the worker would enrich the log lines and then have the ability to push them somewhere like ELK as structured data.

**Comment by vito** [comment] 2017-10-17 13:50
Duplicate of #361.

**Closed by vito** 2017-10-17 13:50 UTC
Labels: area: troubleshooting, type: enhancement
