### ISSUE TITLE
Jobs error with ContainerNotFoundError

### ISSUE THREAD

**Issue by mdelillo** [concourse/concourse#247] opened 2015-12-29 14:56 UTC
A few of our jobs have errored with the following message:

```
Backend error: Exit status: 404, message: {"Type":"ContainerNotFoundError","Message":"unknown handle: 7uv7ag0a28j","Handle":"7uv7ag0a28j"}
```

Our deployment of concourse is running on AWS but the jobs are all failing on a worker running in vsphere. These are the logs from garden on the vsphere worker for that container:

```
root@4b738971-0ed1-48bc-93e3-402cb8dc9cb4:/var/vcap/sys/log# grep 7uv7ag0a28l garden/*
garden/garden.stdout.log:{"timestamp":"1451322764.911316395","source":"garden-linux","message":"garden-linux.pool.acquire.creating","log_level":1,"data":{"handle":"7uv7ag0a28l","session":"11.98"}}
garden/garden.stdout.log:{"timestamp":"1451322764.911461353","source":"garden-linux","message":"garden-linux.pool.acquire.subnet-pool.acquire.subnet-selecting","log_level":1,"data":{"allocated-subnets":["10.254.0.0/30"],"handle":"7uv7ag0a28l","session":"11.98.1.1"}}
garden/garden.stdout.log:{"timestamp":"1451322764.911491632","source":"garden-linux","message":"garden-linux.pool.acquire.subnet-pool.acquire.subnet-selected","log_level":1,"data":{"handle":"7uv7ag0a28l","session":"11.98.1.1","subnet":"10.254.0.4/30"}}
garden/garden.stdout.log:{"timestamp":"1451322764.911521673","source":"garden-linux","message":"garden-linux.pool.acquire.subnet-pool.acquire.ip-selecting","log_level":1,"data":{"allocated-ips":null,"handle":"7uv7ag0a28l","session":"11.98.1.1"}}
garden/garden.stdout.log:{"timestamp":"1451322764.911544085","source":"garden-linux","message":"garden-linux.pool.acquire.subnet-pool.acquire.ip-selected","log_level":1,"data":{"handle":"7uv7ag0a28l","ip":"10.254.0.6","session":"11.98.1.1"}}
garden/garden.stdout.log:{"timestamp":"1451322764.911564350","source":"garden-linux","message":"garden-linux.pool.acquire.subnet-pool.acquire.new-allocated","log_level":1,"data":{"allocated-ips":["10.254.0.6"],"handle":"7uv7ag0a28l","session":"11.98.1.1"}}
garden/garden.stdout.log:{"timestamp":"1451322764.911591053","source":"garden-linux","message":"garden-linux.pool.acquire.acquired-pool-resources","log_level":1,"data":{"handle":"7uv7ag0a28l","session":"11.98"}}
garden/garden.stdout.log:{"timestamp":"1451322766.814042568","source":"garden-linux","message":"garden-linux.pool.acquire.created","log_level":1,"data":{"handle":"7uv7ag0a28l","session":"11.98"}}
garden/garden.stdout.log:{"timestamp":"1451322767.248266459","source":"garden-linux","message":"garden-linux.garden-server.get-properties.got-properties","log_level":1,"data":{"handle":"7uv7ag0a28l","session":"13.49215"}}
garden/garden.stdout.log:{"timestamp":"1451322767.400682211","source":"garden-linux","message":"garden-linux.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/9e8bdca8-6fee-4bb0-5a0f-d638cf082547","handle":"7uv7ag0a28l","session":"13.49216","user":""}}
garden/garden.stdout.log:{"timestamp":"1451322770.576896667","source":"garden-linux","message":"garden-linux.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/9e8bdca8-6fee-4bb0-5a0f-d638cf082547/micropcf/.","handle":"7uv7ag0a28l","session":"13.49217","user":""}}
garden/garden.stdout.log:{"timestamp":"1451322770.770728111","source":"garden-linux","message":"garden-linux.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/9e8bdca8-6fee-4bb0-5a0f-d638cf082547/micropcf-ci/.","handle":"7uv7ag0a28l","session":"13.49218","user":""}}
garden/garden.stdout.log:{"timestamp":"1451322770.928391218","source":"garden-linux","message":"garden-linux.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/9e8bdca8-6fee-4bb0-5a0f-d638cf082547/current-base-box-version/.","handle":"7uv7ag0a28l","session":"13.49219","user":""}}
garden/garden.stdout.log:{"timestamp":"1451322771.087344170","source":"garden-linux","message":"garden-linux.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/9e8bdca8-6fee-4bb0-5a0f-d638cf082547/next-base-box-version/.","handle":"7uv7ag0a28l","session":"13.49220","user":""}}
garden/garden.stdout.log:{"timestamp":"1451322771.247172356","source":"garden-linux","message":"garden-linux.garden-server.stream-in.streamed-in","log_level":1,"data":{"destination":"/tmp/build/9e8bdca8-6fee-4bb0-5a0f-d638cf082547/base-box-commit/.","handle":"7uv7ag0a28l","session":"13.49221","user":""}}
garden/garden.stdout.log:{"timestamp":"1451322771.401214838","source":"garden-linux","message":"garden-linux.container.next pid","log_level":1,"data":{"handle":"7uv7ag0a28l","pid":1,"session":"262"}}
garden/garden.stdout.log:{"timestamp":"1451322771.407301426","source":"garden-linux","message":"garden-linux.garden-server.run.spawned","log_level":1,"data":{"handle":"7uv7ag0a28l","id":"1","session":"13.49223","spec":{"Path":"micropcf-ci/tasks/build-images/run.sh","Dir":"/tmp/build/9e8bdca8-6fee-4bb0-5a0f-d638cf082547","User":"root","Limits":{},"TTY":{}}}}
garden/garden.stdout.log:{"timestamp":"1451325767.289963245","source":"garden-linux","message":"garden-linux.garden-server.reaping","log_level":1,"data":{"grace-time":"5m0s","handle":"7uv7ag0a28l","session":"13"}}
garden/garden.stdout.log:{"timestamp":"1451325767.290051937","source":"garden-linux","message":"garden-linux.container.cleanup.done","log_level":1,"data":{"handle":"7uv7ag0a28l","session":"262.8"}}
garden/garden.stdout.log:{"timestamp":"1451325767.290072918","source":"garden-linux","message":"garden-linux.pool.release.releasing","log_level":1,"data":{"id":"7uv7ag0a28l","session":"11.100"}}
garden/garden.stdout.log:{"timestamp":"1451325767.374727011","source":"garden-linux","message":"garden-linux.garden-server.run.exited","log_level":1,"data":{"handle":"7uv7ag0a28l","id":"1","session":"13.49223","status":255}}
garden/garden.stdout.log:{"timestamp":"1451325767.459994793","source":"garden-linux","message":"garden-linux.oven-cleaner.remove.start","log_level":1,"data":{"ID":"7uv7ag0a28l","session":"5.50"}}
garden/garden.stdout.log:{"timestamp":"1451325767.492785931","source":"garden-linux","message":"garden-linux.pool.release.subnet-pool.release.changing-allocated-subnets","log_level":1,"data":{"allocated-subnets":null,"id":"7uv7ag0a28l","session":"11.100.2.1"}}
garden/garden.stdout.log:{"timestamp":"1451325767.492814064","source":"garden-linux","message":"garden-linux.pool.release.released","log_level":1,"data":{"id":"7uv7ag0a28l","session":"11.100"}}
garden/garden.stdout.log:{"timestamp":"1451326424.582373142","source":"garden-linux","message":"garden-linux.garden-server.attach.failed","log_level":2,"data":{"error":"unknown handle: 7uv7ag0a28l","handle":"7uv7ag0a28l","session":"13.49525"}}
garden/garden.stdout.log:{"timestamp":"1451326426.321076632","source":"garden-linux","message":"garden-linux.garden-server.set-grace-time.failed","log_level":2,"data":{"error":"unknown handle: 7uv7ag0a28l","handle":"7uv7ag0a28l","session":"13.49528"}}
```

We initially suspected that the issue was the network between AWS and vsphere, but this looks like a problem with the local processes on the worker.

**Comment by xoebus** [comment] 2015-12-29 17:58
Huh. Looks like Garden cleaned up that container even though we were still using it.

Which version of Garden are you using?

**Comment by mdelillo** [comment] 2015-12-29 18:40
We're using concourse 0.69.0 and garden-linux 0.329.0

**Comment by xoebus** [comment] 2015-12-29 18:47
Cool. Sounds like a bug then - I'll prioritize.

**Comment by williammartin** [comment] 2016-02-22 14:14
The RabbitMQ PCF team is seeing this error now as well. We are also running Concourse on AWS with the workers in vSphere. Any idea what the cause is?

**Comment by jutkko** [comment] 2016-08-25 16:00
@xoebus @vito Hi, what is the progress with this issue? I see a story in your tracker but it's not scheduled. I have the suspicion that the grace time has reached and the container is killed by garden. This is happening a lot in RabbitMQ Tile team's pipeline, especially when the build times are long.

**Comment by chendrix** [comment] 2017-05-23 22:47
I'm closing this as it's been quite a while and I don't think given the new 3.0 we would even have the same surface area of a bug.

If anyone has a compelling reason to re-open it please do, with any new actionable information.

**Closed by chendrix** 2017-05-23 22:47 UTC
Labels: type: bug

**Comment by geofffranks** [comment] 2017-05-26 20:59
FWIW, I ran into this on concourse 3.0.1 today (4 times in the span of an hour). I upgraded from garden 1.1.1 to 1.6.0, and this seems to be resolved, though i also had to recreate all my workers after, as jobs were stuck in a 'pending' state and wouldn't even start. So, not sure if it was the upgrade that resolved `unknown handle`, or the worker recreation, or a combo.

Hope this helps anyone else running into this in the future, like future me.

**Comment by chendrix** [comment] 2017-05-26 21:17
That is a very old garden version but I'm glad to hear it's been resolved!

Thanks!
Chris

**Comment by politician** [comment] 2017-05-31 06:45
I'm getting `unknown handle` errors on the `navi-pipeline` tutorial.

1. Run everything using the Docker Compose method.
2. Work through to the end of the `navi-pipeline` tutoral.
3. Verify that it's printing something every 1 minute.
4. Over in your terminal, hit CTRL-C to gracefully shutdown the containers.
5. Restart with `docker-compose up`
6. Refresh your browser view; observe that "every-1m" resource check is now failed with `unknown handle`
7. Run `docker ps`.  Observe that you have 1 worker container
8. Run `fly workers`. Observe that you have 1 worker.
9. Run `fly containers`.  Observe that you probably have 2, and one of them has the UUID of the `unknown handle`.
10. Run `fly check-resource -r hello-world/every-1m`. Observe that you get an HTTP 500 error response.

As it's my first time trying to play with Concourse CI, I'm not sure what to do now.  I could probably blow away the database.  Maybe `destroy-pipeline` will help.  Not sure if that's going to just leak some underlying resource though.

**Comment by politician** [comment] 2017-05-31 07:15
I'm also running into issues with the non-deterministic boot order reported in #1199, so it's possible that this is just a symptom of that.

**Comment by CalamarBicefalo** [comment] 2017-06-06 09:16
I am running into these issues as well in concourse 3.0.1 with the docker compose setup.

It says `unknown handle: xxxxx-xxxx-xxxx-xxxx-xxxxx` errors, and next time you retry it will stay in pending (guess the worker is dead, although `docker ps` says the container is up and running).

How could I provide more useful insights?

**Comment by sanacl** [comment] 2017-06-06 16:02
I'm using a fresh install with the latest docker containers in a Ubuntu server 16.04.2 and see the same "unknown handle" error. Having a look at the log of the concourse web container I see this error

```
{"timestamp":"1496763249.773200035","source":"atc","message":"atc.create-job-build.trigger-immediately.try-start-next-pending-build.task.failed-to-fetch-image","log_level":2,"data":{"build-id":15,"build-name":"4","error":"file not found","job_name":"job-hello-world","session":"7350.1.1.5"}}
```

As @CalamarBicefalo said removing everything solves the thing, but you can imagine this won't work in a production environment :sweat_smile:

**Comment by chendrix** [comment] 2017-06-06 16:44
@sanacl you are reporting something that isn't the original issue at hand here. If you are seeing a bug, feel free to jump into [slack](https://slack.concourse.ci) or file a new [issue](https://github.com/concourse/concourse/issues/new)

**Comment by CalamarBicefalo** [comment] 2017-06-26 09:10
Thanks @chendrix we will definitely do!
