### ISSUE TITLE
CONCOURSE_ENABLE_P2P_VOLUME_STREAMING=false doesn't disable p2p volume streaming

### ISSUE THREAD

**Issue by kallisti5** [concourse/concourse#8861] opened 2023-12-01 01:26 UTC
## Summary

We added an additional worker to our environment.  Workers are in remote locations spread around the world.
Web node has CONCOURSE_ENABLE_P2P_VOLUME_STREAMING=false defined in the environment.

## Steps to reproduce

CONCOURSE_ENABLE_P2P_VOLUME_STREAMING=false

## Expected results

Volume streaming doesn't happen.

## Actual results

Volume streaming is attempted.  The expectation was a single worker would run through an individual pipeline... however the workers seem to be trading off non-parallel steps which kinda doesn't make sense... it's not going to improve performance.

![streaming](https://github.com/concourse/concourse/assets/100110/adf33b0b-fe86-4591-b07e-46fc98ba2efb)

## Triaging info

* Concourse version: 7.10.0

**Comment by kallisti5** [comment] 2023-12-01 01:28
Pipeline run doing this:
https://ci.haiku-os.org/teams/nightly/pipelines/master-x86_gcc2h/jobs/compile-master-x86_gcc2h/builds/339

Pipeline definitions:
https://github.com/haiku/infrastructure/blob/master/concourse/pipelines/haiku-release.yml

**Comment by marco-m** [comment] 2023-12-05 11:54
Hello,
it seems this is a misunderstanding on how Concourse works.

Concourse always "streams" volumes.
If CONCOURSE_ENABLE_P2P_VOLUME_STREAMING=false (the default, no need to set it), then volume streaming goes through the ATC (Concourse web).
If CONCOURSE_ENABLE_P2P_VOLUME_STREAMING=true, then volume streaming is direct from one worker to another worker (the meaning of "P2P").

What you are looking for is called **placement strategy**. See https://concourse-ci.org/container-placement.html

**Comment by kallisti5** [comment] 2023-12-05 14:25
oh, so there's no "keep pipeline on single worker" placement strategy?   We have 27 pipelines, and once they start on a worker, it would be nice (tm) if they kept on the same worker :smile:

**Comment by taylorsilva** [comment] 2023-12-21 21:38
If you want pipelines to stay on a single worker I'd recommend tagging the workers and ensuring your pipeline uses the tag everywhere: [resources](https://concourse-ci.org/resources.html#schema.resource.tags), and on [steps](https://concourse-ci.org/modifier-and-hook-steps.html).

I'm going to close this since it's not a bug.

**Closed by taylorsilva** 2023-12-21 21:38 UTC
Labels: bug
